### ISSUE TITLE
FIx casing on Cavatica in card title

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1009]
On the Create project card status, this title should be cased `Cavatica` not all caps to be consistent with the rest of the portal 

![Screen Shot 2018-11-30 at 11.36.00 AM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/eb2f9376-718a-493d-817c-ed2cd4d93add)

**Comment by nyanofthemoon** [comment]
@rosibaj Found other instances for this casing issue. Let me know if you would like to address these in different tickets. :)

**Comment by nyanofthemoon** [comment]
@rosibaj Perfect- fixing it everywhere then re-sending!
