### ISSUE TITLE
File Repo Scone Update: Default message and tag wrapping

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1014]
- [ ] Default message when the user hasn't added facets yet (to prevent the table jumping when facets are added). Message: "Use the filter panel on the left to customize your search."
Zeplin mockup: https://zpl.io/bev8YdN

![screen shot 2018-12-04 at 11 11 56 am](https://user-images.githubusercontent.com/18424138/49455616-6f1b4700-f7b5-11e8-9f63-d0dfd69957b6.png)

- [ ] Scone design for tag wrapping.
Save and Share buttons will stick to a small rectangle area at the top right. When query is long, the scone tags will wrap around the save/share buttons:
Short scone: https://zpl.io/awmM18j
Long scone: https://zpl.io/VD4x4Lq

![10c kf-file-repo-long-query](https://user-images.githubusercontent.com/18424138/49456995-0a152080-f7b8-11e8-837b-f545d17a53ef.jpg)

**Comment by kcullion** [comment]
@rosibaj when you have a chance, can you review these mockups?
Also did we have a ticket for that right actions panel or was that closed?

**Comment by rosibaj** [comment]
@kcullion mocks look good - we have a ticket for that: https://github.com/kids-first/kf-portal-ui/issues/814

**Comment by kcullion** [comment]
Ok thanks @rosibaj just updating all of the mocks in zeplin and on these tickets to reflect the most recent version

**Comment by kcullion** [comment]
Closing this ticket as there is a corresponding implementation ticket here: https://github.com/kids-first/kf-portal-ui/issues/986
