### ISSUE TITLE
Aggregate display of multiple participants on one file in the File Repository

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1024]
We are getting new vcf files that are being computed across trios - a grouping of three participants. Arranger is interpreting a field with "multiple" values as the first value in the array with a ...

Example: https://p-qa.kfdrc.org/s/7c
Example: File `GF_YD07R3E5`
![Screen Shot 2018-12-07 at 2.43.10 PM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/d080dd73-f7a4-4e00-86c6-8a4749953f90)

**Expected Behaviour**
When there are multiple values in a field, it should display a *count of how many are there* are.  
When there are multiple of the same value, it should just say that value 

In the example provided:
- the Participant ID field should say 3 
- the Study field should say Orofacial Cleft (they all have the same study)
- For the proband field, if there is more than one value, it should say `Mixed`

**Comment by allisonheath** [comment]
With the upcoming family VCFs, I wonder if the `Proband` column is becoming more meaningless? `Mixed` doesn't seem to be quite the right label? I would say it would likely be more useful to see the family composition of the file, but that would likely get confused with the family composition facet? Thoughts?

Would there be anyway to be able to expand/view the Participant ID field (or any others that might turn into counts) or would you need to download the manifest to get the actual IDs?
