### ISSUE TITLE
Chrome - colors missing on consent bars

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1031]
No consent code bar colors in prod 
![Screen Shot 2018-12-13 at 8.51.17 AM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/e0736875-4996-4ce0-bb60-086e8790a54e)

**Comment by nyanofthemoon** [comment]
@rosibaj @ciaranschutte Issue not apparent on `next` branch. How do you wish to proceed?
