### ISSUE TITLE
Transfer all services to kidsfirstdrc.org

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1037]
As users, we want to be able to log in to the services and use the portal, even when the network policies of the Internet service provider, or the browser, are rather strict.

As developers, we want to use the internal domain name for what is internal only. The public domain name is for everything public-facing.

**Task**: Transfer all the public-facing services under the public-facing domain name. See the list of services to transfer below.

Timeboxed to one day, for now.

## Services to transfer
- ego (qa and prod)
- etl-task-service (qa and prod)
- ego UI (qa and prod)
- persona (qa and prod)
- kf-public-stats-api

## Rationale
Some Internet service providers, or browsers might block our services if they are not under the same domain as the main page.

It's also so that we can manage our security profiles a bit more easily.

We should avoid cross-origin requests if we can. Most browsers block them for security reasons.

Also it is more consistent from application configuration standpoint. We want to know what is production running and what is used for internal or service purpose only. Having different domains, help us be more organized in that regards.

Security blocks are usually related to URLs, or certificates. It seems like our portal is blocked within some offices, which is not handy.

## Technical details
Domain names:
- The internal domain name is kids-first.io
- The public domain name is kidsfirstdrc.org

More details:
- https://github.com/kids-first/kf-public-stats-api-config/blob/master/aws-ecs-service-type-1/infra-scripts/prd.tfvar

**Comment by aalex** [comment]
Probably that much of this has been done within the scope of #1952

**Comment by jberube** [comment]
Validate if this is already done, for both PROD and QA.

**Comment by jberube** [comment]
I will validate that this is done and close this.
