### ISSUE TITLE
Fix bump on login when user already has a token

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1042]
As a user, if I am already logged in, I should not see the login screen briefly before accessing the contents of the Web site.

## Notes
- The user does not need to see the login screen when they have a token. They can just be taken directly inside the portal.
- This might be fixed by the Ego upgrade that should be done.

**Comment by steptek** [comment]
The first attempt when the window shows up is more related to checking if the token is there and roles, and the validity of this token, once done successfully the token is stored on LS, and the user information are loaded on browser session.
Afterward, when you refresh the page or restart a browser window, it goes directly to the Portal board, and the login buttons aren't showed up until you clear the browser cache or the session is been expired.

**Comment by aalex** [comment]
LS stands for local storage (in the comment above)

**Comment by aalex** [comment]
Perhaps we should consider this as a non-issue, since it's by design that there is a temporary state while the check is being done. It seems like it only occurs on the first time, and then doesn't occur anymore once the first check has been done. (and stored in local storage)
