### ISSUE TITLE
Action Panel Removal 

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1043]
- [x] Remove Action panel in portal UI
- [x] Move Cavatica and Download buttons inside the table header (disabled by default).  Once the user selects at least one file, both the Download and Cavatica buttons should be enabled. 
![screen shot 2018-12-19 at 1 05 55 pm](https://user-images.githubusercontent.com/18424138/50238993-db3da380-038e-11e9-9135-fd81ffe16e83.png)
- [x] Tooltip appears on hover of disabled buttons: "Please select files in the table for this action."
Zeplin: https://zpl.io/aBy5lXe
![screen shot 2018-12-19 at 1 11 43 pm](https://user-images.githubusercontent.com/18424138/50239300-d5948d80-038f-11e9-8407-5e071ff01f0e.png)
- [x] Download button has a dropdown with the following options (same functionality as the current download options): ** do NOT change text to proband. keep it as participant. 
Zeplin: https://zpl.io/a754odv
![screen shot 2018-12-19 at 1 44 06 pm](https://user-images.githubusercontent.com/18424138/50241058-7ab16500-0394-11e9-858c-ebdad8a227b6.png)

- [x] Enabled Cavatica button has a new tooltip to help explain what Cavatica is for
Zeplin: https://zpl.io/bAZq8vO
![screen shot 2018-12-19 at 1 51 24 pm](https://user-images.githubusercontent.com/18424138/50241323-307cb380-0395-11e9-88e3-84d9d330b040.png)

NOTE: Ticket Scope was changed to be broken into to parts.  Linked tickets:
- https://github.com/kids-first/kf-portal-ui/issues/1096

**Comment by kcullion** [comment]
Note: this addresses the following ticket: https://github.com/kids-first/kf-portal-ui/issues/483

**Comment by allisonheath** [comment]
Looks good - hopefully this results in more people analyzing/downloading! 

One quick question, when you uncheck the "select all" checkbox, that always clears the selection and resets, right? For example, if you've gone through the path of "select all" -> "select only 20" -> "uncheck select all box", when you recheck it, it takes you back to the "select all" and you would have to "select only 20" again to get back into that state, correct?

**Comment by nyanofthemoon** [comment]
@hlminh2000 @ciaranschutte @rosibaj Created a pull request in overture-stack/arranger to allow custom content to appear within a TableToolBar's header: https://github.com/overture-stack/arranger/pull/476

**Comment by rosibaj** [comment]
@nyanofthemoon Looks like the button heights are not quite small enough and the fonts dont quite match !  Vincent likes things very small. Can you please adjust these to the right height/font as per design? 

https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5c1a8d5adef00c24307b82a4
![screen shot 2019-01-21 at 11 45 20 am](https://user-images.githubusercontent.com/15824252/51489019-1445ab00-1d75-11e9-8ab9-ff92e44a29f0.png)
