### ISSUE TITLE
File Entity Page - Fix timestamp display

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1068]
Times should not display as the long format - date only please!!
![Screen Shot 2019-01-11 at 10.25.27 AM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/f5d3df66-ed81-4fef-af45-20f416732e62)

**Comment by hlminh2000** [comment]
@rosibaj do you see this being something you'd want the ability to configure in admin? I think it's fair this can be addressed in code rather than touching arranger (easier solution I'd say, given @ciaranschutte's recent work on the file ID link)

**Comment by rosibaj** [comment]
@hlminh2000 um, right now no, i don't see the need to display a full time-stamp ever.  We can fix in code!
