### ISSUE TITLE
Create Cohort Builder Page Template

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1070]
-  [x] three sections : categories, queries, summary/chart grid sectoin
- [x] titles on three sections

- [x]  summary section will  work on a 4x grid not 3
- [x]  add navigation between chart and table views 

Zeplin: All data (state when landing on cohort builder): https://zpl.io/boKj4kM
When filtered on a query (Summary title changes to reference current query and the charts update with the applied filters): https://zpl.io/aXwByeM

**Comment by kcullion** [comment]
@ciaranschutte as I mentioned on slack, I simplified the cohort title stats to make it more clear that the results are about "participants". Please make this change to the page template.   Zeplin: https://zpl.io/aXwByeM
![screen shot 2019-01-31 at 4 11 02 pm](https://user-images.githubusercontent.com/18424138/52085771-517b1b80-2573-11e9-86ec-79d4b9ad68f9.png)
