### ISSUE TITLE
Save as Virtual Study: Backend

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1072]
Needs some evaluation of Riff, might need to extend functionality to allow retrieval of different entry types. @joneubank can handle the back-end and @ciaranschutte can help with the UI side :)

- [ ] Riff needs to save the details of the virtual study: 
```
- type 
- study_owner
- name
- description
- queries
     - number
     - active 
     - squon
```
- [x] Persona needs to save the study reference 
- [ ] Riff needs to be able to distinguish between saved queries and saved virtual studies (maybe a type)

**Comment by hlminh2000** [comment]
we are going to move forward with a solution that does not include a modification to riff for now, as the riff feature will take some work ideally addressed by Dusan or Jon on the overture side. This means differentiation between saved queries and virtual studies is done in the browser side.
