### ISSUE TITLE
Participant Table View - Add pagination

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1073]
- [ ] Implement the pagenation from the file repository table

![screen shot 2019-02-20 at 4 15 48 pm](https://user-images.githubusercontent.com/18424138/53124987-cf0ac980-352a-11e9-89e6-54105dca607b.png)

**Comment by rosibaj** [comment]
@jberube I tested this on VR - looks ok to me ( I was not able to break anything!!!) Are you waiting for anything from this ticket or can I close it now?

**Comment by rosibaj** [comment]
I noticed you also fixed those pesky column expansions :)

**Comment by jberube** [comment]
It can be closed.

@hlminh2000 fixed the columns by fixing the version of react-table to 6.8.6, a later version introduced that bug, I just profited from it!
