### ISSUE TITLE
File Entity Page - CSS

### ISSUE THREAD

**Issue by ciaranschutte** [kids-first/kf-portal-ui#1088]
Shading is too dark on the menu and submenu gradients

![image.png](https://images.zenhubusercontent.com/5b58924328d06e60f1c19ac1/62df793f-09c3-41aa-86c7-315170e1d26f)

Design  Link: 
https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5bf7036c8c42803effa62bb0

**Comment by kcullion** [comment]
@rosibaj this looks good to me on VR!
