### ISSUE TITLE
File Entity Page - Loader

### ISSUE THREAD

**Issue by ciaranschutte** [kids-first/kf-portal-ui#1091]
- Add a page loading spinner (should be a common spinner kit already implemented in a few places to reuse), instead of the "loading.." text
- file repo has the correct loader when loading 
![screen shot 2019-01-21 at 11 11 24 am](https://user-images.githubusercontent.com/15824252/51485972-77cbda80-1d6d-11e9-8cdc-c393f00aec9f.png)

**Comment by kcullion** [comment]
This looks good to me!

**Comment by jberube** [comment]
This has been reviewed and the PR has been merged, shall we close it?

**Comment by kcullion** [comment]
Thanks @jberube. @rosibaj I'll close this
