### ISSUE TITLE
Data defaults

### ISSUE THREAD

**Issue by ciaranschutte** [kids-first/kf-portal-ui#1094]
- [x] (1) 
https://kf-vr-portal.netlify.com/file/GF_2Y6SSQAH 
This says -- on proband on participant
https://p-qa.kfdrc.org/s/7q shows the value should be “No” 

- [x] (2)
If a file has no sequecing experiements, then the two sections should not show
https://kf-vr-portal.netlify.com/file/GF_HFM0SR3Q
![image.png](https://images.zenhubusercontent.com/5b58924328d06e60f1c19ac1/1a17b37a-81d6-4a36-b4e7-73c27cdbc84b)

- [ ] (3) check for no data from query

**Comment by rosibaj** [comment]
Data has been updated in QA now - sequencing experiment is no longer a field that we should be using

**Comment by ciaranschutte** [comment]
@rosibaj if would be great if @jberube doesn't mind taking this one

**Comment by jberube** [comment]
This is just the first of the 3 points in this issue, to get the discussion rollin'.

**Comment by rosibaj** [comment]
@jberube 🎉 looks great!  Thanks for the fast fixes!!
