### ISSUE TITLE
Column selector is BELOW the footer when used on last table

### ISSUE THREAD

**Issue by ciaranschutte** [kids-first/kf-portal-ui#1095]
![image.png](https://images.zenhubusercontent.com/5b58924328d06e60f1c19ac1/61e1a8ee-dead-48ea-8ed1-34445018c730)

**Comment by jecos** [comment]
Example :
https://kf-qa.netlify.com/search/file?sqon=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22kf_id%22%2C%22value%22%3A%5B%22GF_GRNAC0DM%22%5D%7D%7D%5D%7D

<img width="1898" alt="Screen Shot 2020-01-10 at 3 26 25 PM" src="https://user-images.githubusercontent.com/1424506/72184082-9b909200-33bd-11ea-9384-b7266fb210e6.png">
