### ISSUE TITLE
Implement "Select All files" logic for File Repository Table

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1096]
- [ ] Tooltip appears on hover of disabled buttons: "Please select files in the table for this action."
Zeplin: https://zpl.io/aBy5lXe
![screen shot 2018-12-19 at 1 11 43 pm](https://user-images.githubusercontent.com/18424138/50239300-d5948d80-038f-11e9-8407-5e071ff01f0e.png)
- [ ] Implement the `Select All` rows as part of Arranger backend
- [ ] When the user checks the "Select All" - the buttons are enabled
Zeplin: https://zpl.io/VDqzrYe
![screen shot 2018-12-19 at 1 31 47 pm](https://user-images.githubusercontent.com/18424138/50240393-ae8b8b00-0392-11e9-8ff1-e94796f4968d.png)
- [ ] When the user checks the "Select All" - The FULL TABLE is selected and the file counts change to the following sentence: "All 30,037 files are selected. Select only the 20 files on this page"
Zeplin: https://zpl.io/VDqzrYe
![screen shot 2018-12-19 at 1 34 35 pm](https://user-images.githubusercontent.com/18424138/50240462-dda1fc80-0392-11e9-88a6-4d824d572edf.png)
- [ ] When the user clicks the "Select only the 20 files on this page" link - ONLY THE CURRENT PAGE FILES are selected and the file counts change to the following sentence: "Only the 20 files on this page are selected. Clear selection". The number is dynamic depending on the table rows the user has selected. ("Clear selection" link resets the page with the disabled action buttons)
Zeplin: https://zpl.io/bAZq8vO
![screen shot 2018-12-19 at 1 39 23 pm](https://user-images.githubusercontent.com/18424138/50240744-9c5e1c80-0393-11e9-8afe-c2b0422c66b2.png)

**Comment by rosibaj** [comment]
Note: this ticket should address https://github.com/kids-first/kf-portal-ui/issues/483

**Comment by vferretti** [comment]
See how gmail handle this problem
![image](https://user-images.githubusercontent.com/1181124/63455092-0bf04400-c41a-11e9-9273-f748d9f5cb51.png)
