### ISSUE TITLE
File Entity Page: Export of Associated Particpant Table is odd

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1103]
![image (2).png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/fc7ee998-3036-4945-8277-c86de870248c)

**Comment by rosibaj** [comment]
Tested - It looks like the participantid column is showing correctly now, but I am still seeing [object][object] on the stud id column 

Example data:
https://kf-vr-portal.netlify.com/file/GF_4VEWCTCR 

Result export:
<img width="690" alt="screen shot 2019-02-04 at 3 44 39 pm" src="https://user-images.githubusercontent.com/15824252/52236062-d1ff8c00-2893-11e9-8d98-6a91286c8429.png">

**Comment by jberube** [comment]
I'll take a look at every column for other possible issues, same solution will work.

**Comment by ciaranschutte** [comment]
@jberube Please see PR comments

**Comment by rosibaj** [comment]
tested on VR - seeing the correct values in the study column now: 
<img width="859" alt="screen shot 2019-02-06 at 10 41 29 am" src="https://user-images.githubusercontent.com/15824252/52353080-da72d680-29fb-11e9-8888-bc82e7646895.png">
