### ISSUE TITLE
Add a 404 Page for when a page is not found 

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1104]
As a user, I expect a page that looks nice when the page I was looking for is not found.

## Acceptance criteria
- Provide a page that provides an error message, and some link to navigate back to the rest of the portal.
- Implement a design as the mockup below. (ask @aalex for the assets)
- Entity pages whose ID are not found should also point there. See the list below.

## File entity pages whose ID are not found
- File page
- Participant page
- Member page

## Mockup
https://projects.invisionapp.com/share/8JMV1FYY675#/screens/308942570_KidsFirst-Portal-404 

![image](https://user-images.githubusercontent.com/293677/57879924-84c47c00-77eb-11e9-8242-2ee7a13066c4.png)

**Comment by denis-crsj** [comment]
Closing issue. Details transferred into the Google Sheet : https://docs.google.com/spreadsheets/d/1U1JQZEBEMTP_07PngrmNh8rzbZICTX87Fe_2fEetAbI/edit#gid=0
