### ISSUE TITLE
File Entity Page: Data table issues

### ISSUE THREAD

**Issue by ciaranschutte** [kids-first/kf-portal-ui#1107]
Issues with z-index on dropdowns 

The column dropdown is showing underneath the footer

![picture1](https://user-images.githubusercontent.com/15824252/52287339-edbc6e00-2937-11e9-95fe-f833686937b0.png)

**Comment by rosibaj** [comment]
Tested - correctly on top now!  Thanks @jberube !
<img width="484" alt="screen shot 2019-02-07 at 10 45 08 am" src="https://user-images.githubusercontent.com/15824252/52423132-79afd080-2ac5-11e9-8c22-65002e398c1b.png">
