### ISSUE TITLE
Query Summary: Survival Plot Card Display

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1108]
**Design**
![screen shot 2019-02-08 at 3 58 42 pm](https://user-images.githubusercontent.com/18424138/52505764-89f5a780-2bba-11e9-9595-ed76c8fa27f3.png)
Zeplin: https://zpl.io/boKj4kM

- [x] the colour used for the plot and the # of participants in the title is #008199
(the chart and the number of participants doesn't link anywhere)
- [x] the graph should function like the example on GDC with the drag to zoom functionality:
https://portal.gdc.cancer.gov/exploration?searchTableTab=genes
- [x] The number of participants in the top bar is the number of participants who have survival data
https://portal.gdc.cancer.gov/exploration?searchTableTab=genes

**Data Specs:** https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/888012823/Cohort+Builder+Technical+Specs#CohortBuilderTechnicalSpecs-SummaryView 

- [x] Import the  package: https://github.com/oncojs/survivalplot 
- [x] Plot the survival curve 

It should accept data in this format: 
```
"donors": [
{
"project_id": "Congenital Diaphragmatic Hernia",
"censored": true,
"time": 6,
"survivalEstimate": 1,
"submitter_id": "PT_FCS416QR",
"id": "2c30dc20-18a8-44f9-ab10-558c1e5634dc"
},
{
"project_id": "Congenital Diaphragmatic Hernia",
"censored": true,
"time": 14,
"survivalEstimate": 1,
"submitter_id": "PT_ARN1D5B8",
"id": "26a12266-c6d8-42f9-bd4e-5093d827ac9a"
},
{
"project_id": "Congenital Diaphragmatic Hernia",
"censored": true,
"time": 16,
"survivalEstimate": .95,
"submitter_id": "PT_TQPMJMDF",
"id": "01240896-3f3f-4bf9-9799-55c87bfacf36"
},
{
"project_id": "Congenital Diaphragmatic Hernia",
"censored": true,
"time": 28,
"survivalEstimate": .82,
"submitter_id": "PT_5HYPY6F9",
"id": "6fa41234-9077-4d05-a295-6820f3bedf5b"
},
{
"project_id": "Congenital Diaphragmatic Hernia",
"censored": true,
"time": 32,
"survivalEstimate": .7,
"submitter_id": "PT_BADD0N51",
"id": "c46971a1-cbac-425d-bac2-f4142c92522e"
},
"project_id": "Congenital Diaphragmatic Hernia",
"censored": true,
"time": 44,
"survivalEstimate": .44,
"submitter_id": "PT_GJYKSGM5",
"id": "c46971a1-cbac-425d-bac2-f4142c92522e"
},
"project_id": "Congenital Diaphragmatic Hernia",
"censored": true,
"time": 62,
"survivalEstimate": .32,
"submitter_id": "PT_1KYPR4ZK",
"id": "c46971a1-cbac-425d-bac2-f4142c92522e"
}]
```

**Comment by nyanofthemoon** [comment]
@rosibaj https://github.com/kids-first/kf-portal-ui/pull/1232

**Comment by rosibaj** [comment]
@nyanofthemoon Thanks for resolving all the build issues!  Looks like its showing up great!

**Comment by rosibaj** [comment]
@nyanofthemoon I can see that its not in the mockup as it looks like we forgot to include the reset instructions after drag to zoom - wondering if it would possible for you to add that reset functionality in so we do not have to reload the page to reset the survival graph?
