### ISSUE TITLE
Query Summary: Phenotype Tree Card

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1109]
- [ ] The HPO ontology is found here 
- [ ] Grey numbers appear when a parcipant _has that exact HPO id_ in the field participant.phenotype.hpo_phenotype_observed
- [ ] the lowest level in a tree area with at least one participant is considered a leaf and the text is color black to indicate this
Zeplin: https://zpl.io/boKj4kM
- [ ] All branches should be collapsible. 

![Screen Shot 2019-01-21 at 2.57.14 PM.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/0bb3578d-3937-43eb-a7f8-6b8cd7cf5699)

**Comment by kcullion** [comment]
Resource from @ciaranschutte : https://github.com/denimar/deni-react-treeview

**Comment by nyanofthemoon** [comment]
@rosibaj do we have the hierarchy (parent->childs) for all of those values?

**Comment by rosibaj** [comment]
@nyanofthemoon we sure do - perhaps we should have a meeting to discuss how to do this!

**Comment by nyanofthemoon** [comment]
@rosibaj Vincent asked me to work on this next. Ready to discuss whenever you are?
