### ISSUE TITLE
Query Summary: Add Studies Card (same functionality)

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1110]
Same as dashboard chart, just remove ability to click the bars. 

Zeplin: https://zpl.io/boKj4kM

![Screen Shot 2019-01-21 at 3.05.12 PM.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/f809b1c7-f97c-4ab4-b29d-86e5a75d278b)

**Comment by nyanofthemoon** [comment]
@rosibaj @hlminh2000 Pull request https://github.com/kids-first/kf-portal-ui/pull/1146

**Comment by rosibaj** [comment]
@hlminh2000 Can we get this merged to the storybook?
