### ISSUE TITLE
Query Summary: File Breakdown Card

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1112]
Zeplin: https://zpl.io/boKj4kM

![screen shot 2019-02-08 at 11 07 50 am](https://user-images.githubusercontent.com/18424138/52490023-cc56be80-2b91-11e9-8fb1-ad5e8d209492.png)
- [x] The card should scroll/fade as per the normal card behaviour. 
- [x] it will also be the first card (switching spots with the overall survival card)
- [x] total at the bottom of the table so the user can quickly link to all files in the file repository.
- [x] The link in the last column should go to the File Repository, leading to the files that that number/aggregation query represents.  For example, if it says < 3 files> then the user would be navigated to the file repository with those 3 files selected.

- This should be the same as other link behaviours in the portal.  For example,  from teh dashboard the user is linked to the file repository. 
> Step 1: Got to dahsbaord and hover over a bar in the studies card. Click the link
> <img width="371" alt="screen shot 2019-02-12 at 5 24 55 pm" src="https://user-images.githubusercontent.com/15824252/52672679-89c41780-2eec-11e9-9764-5d5b534a66d1.png">

> Step 2: 
> The user is navigated to the filere positories showing the files related to the link on the dashboard. <img width="371" alt="screen shot 2019-02-12 at 5 24 55 pm" src="https://user-images.githubusercontent.com/15824252/52672680-8b8ddb00-2eec-11e9-89e6-2e62b80ef029.png">
> Resulting query: https://portal.kidsfirstdrc.org/search/file?sqon=%7B%22op%22:%22and%22,%22content%22:%5B%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22participants.study.short_name%22,%22value%22:%22Pediatric%20Brain%20Tumors:%20CBTTC%22%7D%7D%5D%7Dthe `sqon` for the URL should be something like so (replacing the `value` fields with the right value from each row):

```
{
  "op": "and",
    "content": [
    {
      "op": "in",
      "content": {
        "field": "data_type",
        "value": [
          "Aligned Reads"
        ]
      }
    },
    {
      "op": "in",
      "content": {
        "field": "sequencing_experiments.experiment_strategy",
        "value": [
          "RNA-Seq"
        ]
      }
    }
  ]
}
```

**Comment by nyanofthemoon** [comment]
@rosi I do not have access to atlassian.

**Comment by nyanofthemoon** [comment]
![test.png](https://images.zenhubusercontent.com/5c05950b0a4f964ea1a04049/378e87f8-5d7d-4949-982e-3dd3b330f0e4)

**Comment by rosibaj** [comment]
@nyanofthemoon Today in a stakeholder meeting, they decided to make a small change to this card.  We no longer want to implement the CHECKMARKS, nor do we want to implement the CAVATICA BUTTON.   That means this card should only have the scrollable table with links.  I will work on an updated mockup - Let me know if you have any questions!

**Comment by nyanofthemoon** [comment]
@rosibaj Ok! Vincent just said we should interchange the columns "experimental strategy" and "data type".

**Comment by rosibaj** [comment]
@nyanofthemoon sounds good to me!!

**Comment by kcullion** [comment]
@rosibaj @nyanofthemoon I think these are all the changes for this card. I also kept the total at the bottom of the table so the user can quickly get to all files from this card too.

- it will also be the first card (switching spots with the overall survival card)

I will post to zeplin soon but thought I'd post this as you are working on it...

![screen shot 2019-02-08 at 11 07 50 am](https://user-images.githubusercontent.com/18424138/52490023-cc56be80-2b91-11e9-8fb1-ad5e8d209492.png)

**Comment by nyanofthemoon** [comment]
@kcullion Thank you!

**Comment by nyanofthemoon** [comment]
@rosibaj https://github.com/kids-first/kf-portal-ui/pull/1185

**Comment by hlminh2000** [comment]
@nyanofthemoon the `sqon` for the URL should be something like so (replacing the `value` fields with the right value from each row):
```
{
  "op": "and",
    "content": [
    {
      "op": "in",
      "content": {
        "field": "data_type",
        "value": [
          "Aligned Reads"
        ]
      }
    },
    {
      "op": "in",
      "content": {
        "field": "sequencing_experiments.experiment_strategy",
        "value": [
          "RNA-Seq"
        ]
      }
    }
  ]
}
```

**Comment by nyanofthemoon** [comment]
@hlminh2000 @rosibaj Is there an existing generator function (or a generator function currently in progress) for this which I can re-use?
