### ISSUE TITLE
Query Summary: Age at Diagnosis Card

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1113]
Zeplin: https://zpl.io/boKj4kM

![Screen Shot 2019-01-21 at 3.03.45 PM.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/2cdcf0be-a49a-4b2b-b757-c746bf0417bc)

**Comment by nyanofthemoon** [comment]
@hlminh2000 @ciaranschutte @rosibaj https://github.com/kids-first/kf-portal-ui/pull/1170

**Comment by rosibaj** [comment]
@nyanofthemoon looooooking good! Thank you!!!
