### ISSUE TITLE
Query Summary: Demographics Pies Card

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1114]
[ ] - 4 nivo pies in a grid
[ ] - tooltips (same style as portal current)
[ ] - hover state (same style as portal current)
NOTE: in the mockup we show a donut chart - we want a PIE chart.  It was too much time to change in the mockup :)
https://nivo.rocks/pie/ is the pie chart library

Zeplin: https://zpl.io/boKj4kM

![Screen Shot 2019-01-21 at 3.08.27 PM.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/727c6ab9-e472-43bc-a659-9a70998b3687)

**Comment by nyanofthemoon** [comment]
![demo.png](https://images.zenhubusercontent.com/5c05950b0a4f964ea1a04049/f2b0f0c3-2220-45c0-9f1f-656b91a109fd)

**Comment by nyanofthemoon** [comment]
![222.png](https://images.zenhubusercontent.com/5c05950b0a4f964ea1a04049/479c19b1-51e6-40d0-b000-13460c201362)

**Comment by nyanofthemoon** [comment]
![test.png](https://images.zenhubusercontent.com/5c05950b0a4f964ea1a04049/79158c60-a0a4-4179-a383-0aeb7dbf8d35) last version

**Comment by nyanofthemoon** [comment]
![test.png](https://images.zenhubusercontent.com/5c05950b0a4f964ea1a04049/ad98f45e-af30-4d0e-bcaf-70b640f27385) latest version

**Comment by kcullion** [comment]
Thanks @nyanofthemoon! Some styling feedback:
- [ ] Tooltip - change "members" to "Participants" ("members" refers to the actual portal users)
- [ ] Tooltip -  please use same styles as the tooltip from the donut graph on the dashboard. So text should be left-justified, color: #2b388f
- [ ] pie hover state - please use the same as the donut from the dashboard

**Comment by nyanofthemoon** [comment]
@rosibaj @kcullion I can change to "participoants", but just a note that the Donut from dashboard says "members".

**Comment by kcullion** [comment]
Yeah @nyanofthemoon that graph on the dashboard is about the member interests from the user profile. The pie graphs on the cohort builder is about the group of participants that the user is collecting to study

**Comment by nyanofthemoon** [comment]
@kcullion Oh, that makes sense. I . understand now. :)

**Comment by nyanofthemoon** [comment]
@kcullion @rosibaj @hlminh2000 Pull request for requested changes: https://github.com/kids-first/kf-portal-ui/pull/1145

**Comment by rosibaj** [comment]
@hlminh2000 Can we get this merged to storybook for review today 🙏 ?
