### ISSUE TITLE
Cohort Builder: Saved queries widget with Virtual Studies

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1115]
As a user, I want to see a widget that lists my virtual studies.

## Acceptance criteria
- The "Saved queries" widget will now contain two tabs.
- The first tab will show the saved virtual studies of this user.  (see a in the mockup)
- The second tab will be the existing contents of that widget, which lists their saved file queries. (see b in the mockup)
- The titles of the tabs are "Virtual Studies" and "Files", respectively.
- The card takes the first position among the other cards.
- The links leads to the correct destinations.
- Provide an example saved study to each new user. (work with @aalex when you get there) They are created when the user first logs in. The user can delete them, and they are not created again, once they do.
- When the user has 0 saved virtual study, show the blue message with the invitation to create some. (see c and d in the mockup)
- If the number of saved virtual studies changes, update the number that is shown.
- Clicking on a delete button deletes the saved virtual study.
- Show the number of cohorts for each given Virtual Study. Update it if it changes. (at page load time)
- Show the description for each virtual study.

## Mockups
![image](https://user-images.githubusercontent.com/293677/57876771-29db5680-77e4-11e9-9320-6c7a28fc5faf.png)

## Details
We will provide an example Virtual Study for the user to start from. It should contain a set of two common queries, plus one that combines the first two. Each user will have a copy of an example study, and they can do anything they can usually do with a saved study. (for example, edit it, or delete it)

## Technical notes
- This might be complex to implement, since we might need to save some of the info shown in the widget into Persona.
- The SQON is built so that it always come from the participant.

**Comment by rosibaj** [comment]
@aalex  Yes, each user would have a default example saved study to start.  Like saved queries they can only access it or delete it.

Re: `That sounds like another story to me, though` --> I usually let the developer decide if that is possible in the scope of one ticket.

**Comment by nyanofthemoon** [comment]
@aalex Who is on this one?
