### ISSUE TITLE
Filters: Boolean Filters UI

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1118]
We need to add the Boolean filter UI components into the cohort builder category bar:

 https://zpl.io/bPXZQjl

![Screen Shot 2019-01-21 at 3.13.33 PM.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/c3caa277-7d51-40d1-a5fb-db2c1289d0da)

**Comment by hlminh2000** [comment]
There are a couple issues with the current implementation, but it's a big enough chunk of work done so I think we can close this with some followups :)

**Comment by rosibaj** [comment]
@hlminh2000 Sounds good - I made a ticket for the follow-ups: https://github.com/kids-first/kf-portal-ui/issues/1274

Can you put a brief summary of details there?

**Comment by hlminh2000** [comment]
Sure! thank you for the ticket! :)
