### ISSUE TITLE
Query Summary: Data Fetching for Summary Area

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1119]
- [ ] set the page up to fetch the data
- [x] global SQON object for the page
- [ ] fetcher that receives the sqon and makes requests
- [ ] the query can be different (as needed) for different components (charts)

**Comment by ciaranschutte** [comment]
Feb 5th: Query component for individual pieces still has to be done.

**Comment by rosibaj** [comment]
thanks @ciaranschutte I will make a ticket for next sprint for that
