### ISSUE TITLE
Refine the log in / sign up process (add images, rename and delete buttons...)

### ISSUE THREAD

**Issue by phuongmy** [kids-first/kf-portal-ui#115]
We reviewed the wireframes with Vincent.

Please apply the following changes:
1. Add kid image to the log-in / sign-up page:
1.a. Log-in: https://invis.io/MQFHWABDK9Y#/281037369_01b-KF-Data-Portal-Login
1.b Join: https://invis.io/MQFHWABDK9Y#/275376886_10-KF-Signup-V1-Step1

2. Remove the pink button "Join / Login / Logout" at the top right corner

3. In step 2 of the wizard, rename "Save" to "Next"
https://invis.io/MQFHWABDK9Y#/275376887_11-KF-Signup-V1-Step2

4. In step 3 of the wizard, rename "Finish" to "Save"
https://invis.io/MQFHWABDK9Y#/275376888_12a-KF-Signup-V1-Step3-Researcher

5. Update the user flow to indicate the user he has to accept the T&C:
Instead of having the button "Save" greyed out, you can make it active. However if the user has not selected the checkbox "I accept...", it should show an error message in red to tell the user to accept the T&C.

6. Remove the header from the sign-up / login pages
<img width="1432" alt="screen shot 2018-03-07 at 3 20 17 pm" src="https://user-images.githubusercontent.com/8812383/37116110-3c8b2942-221b-11e8-9b2f-caae8b028fc0.png">

**Comment by hlminh2000** [comment]
completed item 5, see https://github.com/kids-first/kf-portal-ui/pull/229

**Comment by hlminh2000** [comment]
Completed and merged the last item so closing
