### ISSUE TITLE
Style Most Frequent Diagnosis Card

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1153]
Some feedback:
- [x] the last number is being cut off on the x-axis
- [x]  please change the cursor from "pointer" to the default arrow - for the hover state of the bars (this version of this graph is not clickable yet)
- [x] Can you spread out the graph height-wise to use more of the card height (leaving approx. 15px padding inside the card)

**Comment by nyanofthemoon** [comment]
@rosibaj https://github.com/kids-first/kf-portal-ui/pull/1177

**Comment by rosibaj** [comment]
@nyanofthemoon hmm... it seems like now there are some un-intended consequences! 
![image](https://user-images.githubusercontent.com/15824252/52440461-2dc45200-2aec-11e9-9ee0-ade52fbbb28d.png)

Can we get this fixed?

**Comment by nyanofthemoon** [comment]
...this is is per the merge conflicts from working on the same page...

**Comment by rosibaj** [comment]
@nyanofthemoon I see what you mean now :) You are right! For now, we can close this one and then do some more feedbacks later after all of the final adjustments.

**Comment by nyanofthemoon** [comment]
@rosibaj *hugs*
