### ISSUE TITLE
Query Summary: Data Fetching for Age at Diagnosis Card

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1162]
Data Specs: 

https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/888012823/Cohort+Builder+Technical+Specs#CohortBuilderTechnicalSpecs-SummaryView

**Comment by ciaranschutte** [comment]
https://github.com/kids-first/kf-portal-ui/issues/1186
