### ISSUE TITLE
Profile page broken in firefox.

### ISSUE THREAD

**Issue by andricDu** [kids-first/kf-portal-ui#117]
Missing icons and main bar is too short.
<img width="1218" alt="screen shot 2018-03-07 at 3 19 47 pm" src="https://user-images.githubusercontent.com/6350043/37116083-1bf3af4c-221b-11e8-8508-d6af9f3e6e0a.png">

**Comment by rosibaj** [comment]
Resolved with recent bug fixes on other tickets
