### ISSUE TITLE
Dead link on file entity page

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1171]
![image](https://user-images.githubusercontent.com/15824252/52350135-e491d680-29f5-11e9-9e93-e5fe6327f649.png)

**Comment by jberube** [comment]
`Study` in the file properties

**Comment by rosibaj** [comment]
@jberube sorry for the confusion there - i totally attached the wrong screen shot 🤦‍♂️ - ive updated it!

**Comment by rosibaj** [comment]
Tested - link is correct now.
