### ISSUE TITLE
Header click not working

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1179]
- seems like click in the header is not working

![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/f6dcc97e-7381-4cc8-8782-ff271808ee65)

**Comment by kcullion** [comment]
@jberube the share should look like/function the same as the share in the file repo (when the user starts to filter the table)

**Comment by ciaranschutte** [comment]
@jberube It's from negative z-index https://github.com/kids-first/kf-portal-ui/pull/1148

**Comment by jberube** [comment]
@ciaranschutte Yeah, that makes sense. I did remove the `z-index: -1` since, though, so this might be already fixed. I'll validate that.
