### ISSUE TITLE
Table actions: columns dropdown button usability

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1180]
Clicking on the columns button should open and close the dropdown. Currently it opens it but doesn't close it. 
(see file repository table for correct functionality)
![Screen Shot 2019-02-07 at 10.58.18 AM.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/bab02408-8276-4506-8413-6362fee1bd5e)

**Comment by jberube** [comment]
Fixed as part of #1193

**Comment by rosibaj** [comment]
Tested on VR - this issue is resolved with some other commits.  I can close the columns dropdown by clicking on columns.
