### ISSUE TITLE
File-entity: Button style consistency

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1181]
- [ ] Can make the font-weight for the buttons 500 to keep it consistent with the other buttons. I think Zeplin is giving the value of 600 - but it may render the font differently.

- [ ] Can you also use a consistent font-size of 12px

![screen shot 2019-02-07 at 11 29 38 am](https://user-images.githubusercontent.com/18424138/52426332-c72f3c00-2acb-11e9-8b49-0f1f86f5d97b.png)

**Comment by aalex** [comment]
In the file entity page: https://portal.kidsfirstdrc.org/file/GF_CVK895RR

They must be 12px with 500 weight.

In this screenshot, the![screenshot_2019-04-05_16-23-31_button_text_weight_different.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/7c814316-8157-487a-8ab6-0f6ffc6e667b) ones at the bottom look like they have the right weight.

**Comment by aalex** [comment]
LGTM
