### ISSUE TITLE
Query Builder: UI Styling and Behaviour

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1192]
- [x] Query numbering should start at 1 and not 0

Different states for the queries: 
- [x] Regular query is selected.  Zeplin: https://zpl.io/aMKZQxd
![screen shot 2019-02-22 at 8 23 04 am](https://user-images.githubusercontent.com/18424138/53245270-43ed1900-367b-11e9-9500-9ae7008341e5.png)

- [x] If the user duplicates query 1, for example, that query becomes the next query highlighted at the bottom and is the active query. Zeplin: https://zpl.io/bWgwv7k
![04 kf-cohortbuilder-query-duplicate](https://user-images.githubusercontent.com/18424138/53247269-e65bcb00-3680-11e9-885e-40be78a615d2.jpg)

- [x] If the user adds a new query - that query becomes the next query at the bottom and is active (green). The query does not have enabled actions until the user starts adding filters (so they can't add multiple blank queries). The row also has a disabled checkbox because the user can't combine another query with an empty one.
Zeplin: https://zpl.io/2ZjG4OL
![screen shot 2019-02-22 at 9 07 56 am](https://user-images.githubusercontent.com/18424138/53247613-cc6eb800-3681-11e9-970e-d14ef3aba2a8.png)

- [x] Query hover state: when the user hovers over a query, the background is darkened and the actions appear. Zeplin: https://zpl.io/bJ9lzdK
![screen shot 2019-02-22 at 8 42 03 am](https://user-images.githubusercontent.com/18424138/53246124-c4147e00-367d-11e9-8939-4a89e0440dd8.png)

**Comment by hlminh2000** [comment]
addressed in PR #1252

**Comment by rosibaj** [comment]
@hlminh2000 LOOKING GREAT!   Only one note: 

- [ ] 1:  not sure what exact logic was used, but i can still select empty queries to combine if they are in the MIDDLE of the query.  I can also duplicate an empty query from the middle. - @kcullion do you agree this shouldn't be allowed?

<img width="1639" alt="screen shot 2019-02-28 at 5 54 08 pm" src="https://user-images.githubusercontent.com/15824252/53604220-df055780-3b81-11e9-96ef-ebb0b9d77f4f.png">
<img width="1633" alt="screen shot 2019-02-28 at 5 56 14 pm" src="https://user-images.githubusercontent.com/15824252/53604336-2986d400-3b82-11e9-88b0-0a21f7f771fc.png">

**Comment by kcullion** [comment]
@rosibaj and @hlminh2000 regarding 1 - I think we should avoid allowing users to have empty queries within the list. And blank queries should not be duplicated or combined (those actions should be disabled when appropriate)
