### ISSUE TITLE
Card Styling: Remove Participants from Study Card

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1196]
- [x] Remove the `Participants (xxx)` from the title of the Study Breakdown Card
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/d956aa98-faf9-40ea-a813-86e183a4ea35)

**Comment by ciaranschutte** [comment]
@rosibaj @hlminh2000 this is complete
