### ISSUE TITLE
Checkboxes on Table no longer work 

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1197]
The checkboxes on the tables no longer work. They can no longer be checked correctly

- select all works
- selecting individual checkboxes does not work ! The box "responds" - it pushes in - but no check mark appears when you click with the mouse.  The e counts update to zero
- no console or network errors occur

Video of the Bug: https://www.screencast.com/t/mB3AzyIu

**Comment by ciaranschutte** [comment]
selectedTableRows is updating correctly

**Comment by hlminh2000** [comment]
Problem identified to be coming all the way from `react-table`, which handles selection event with `select-${idField}` rather than just `idField`. It was a breaking change from that dependency without notice so no way we could have caught that.

**Comment by nyanofthemoon** [comment]
@hlminh2000 @rosibaj We are currently using the datatable component which is using react-table. Is there anything we need to update on our end?

**Comment by hlminh2000** [comment]
@nyanofthemoon since it's a dependency issue, we'll try to fix this at the base component level. There will likely be no need for change in consuming components, but I'll update if there is anything  :)
