### ISSUE TITLE
Query Builder:  Reduce Padding on Category Dropdown options

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1201]
Reduce the top and bottom padding on the category bar filters (so that more fit on the screen at once under clinical)

Zeplin: https://zpl.io/awWvAeJ

![screen shot 2019-02-21 at 2 46 25 pm](https://user-images.githubusercontent.com/18424138/53197099-7c431780-35e7-11e9-9a2d-62a6494f80ce.png)

**Comment by kcullion** [comment]
@jaouad-benassila can you just change the padding on these menu div from 
padding: 5px 10px 5px 23px;
to
padding:8px 20px;

thanks!

**Comment by jaouad-benassila** [comment]
ok @kcullion , I will change it
Thanks.

**Comment by jaouad-benassila** [comment]
@kcullion it is done

**Comment by kcullion** [comment]
Looks great, thanks @jaouad-benassila !
