### ISSUE TITLE
Add new email opt in list to portal registration

### ISSUE THREAD

**Issue by baileyckelly** [kids-first/kf-portal-ui#1204]
As a user, I need to be able to register to a mailing list so that I can get notified by email when new datasets are made available on the portal.

We need to add a new email mailing list to the portal registration for Dataset updates. 

The KF team uses MailChimp as their subscription service. Here are the development docs to send an email to a list. https://developer.mailchimp.com/documentation/mailchimp/guides/manage-subscribers-with-the-mailchimp-api/
The list ID is: 9e9aad8b8e

Some related former issues are #307, #321 and #453, as well as https://github.com/kids-first/kf-persona/pull/1

**Comment by tatianapatton** [comment]
blurb: 
The Gabriella Miller Kids First Data Resource Center is constantly improving the availability and quality of new datasets added to the Data Resource Portal. Sign up below to opt-in to receive updates and announcements when new datasets are available in the Portal.

List ID: 
9e9aad8b8e

**Comment by aalex** [comment]
Here is a screenshot of the basic info tab in the joining assistant. We need to add a checkbox to it. It can be last on the list.

 ![screenshot_2019-02-14_17-10-05](https://user-images.githubusercontent.com/293677/52820947-70050a80-307b-11e9-92e6-b50bed198106.png)

**Comment by hlminh2000** [comment]
@rosibaj @baileyckelly , just to confirm, is this integration with existing mailchimp account where the previous integration was made, just with a different list ID? Or are we looking at a new mailchimp account all together? :) this will be of interest for @jaouad-benassila

**Comment by rosibaj** [comment]
@hlminh2000 same mail-chimp, new list id

**Comment by baileyckelly** [comment]
Thanks @rosibaj !
