### ISSUE TITLE
Query Summary & Table: No cohort results returned

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1212]
When a user makes a query that returns no participants, the cards and tables will fade and a message appears centered on top "There are 0 participants for this cohort."

Zeplin:
Summary: https://zpl.io/anp69Ql
Table: https://zpl.io/2p40B9o

![screen shot 2019-02-15 at 1 50 42 pm](https://user-images.githubusercontent.com/18424138/52881378-625e8c00-3132-11e9-8ef6-c2ac028d3b73.png)

![screen shot 2019-02-15 at 1 50 32 pm](https://user-images.githubusercontent.com/18424138/52881393-70aca800-3132-11e9-9b03-bc1e944dc214.png)

**Comment by hlminh2000** [comment]
probably using this query would work best:
```
query ($sqon: JSON) {
  participant {
    hits(filters: $sqon) {
      total
    }
  }
}
```

**Comment by rosibaj** [comment]
@ciaranschutte I think the Summary view of this looks fine, but i have a question about the table view.  It looks like in the table, there is actually data being returned formthe "0" query.  Any way this could show an empty table instead?

<img width="1675" alt="screen shot 2019-02-28 at 6 08 00 pm" src="https://user-images.githubusercontent.com/15824252/53604935-e7f72880-3b83-11e9-8e02-e5456e49bf77.png">

**Comment by rosibaj** [comment]
Note:  moved feedback to a ticket for another sprint #1270
