### ISSUE TITLE
Query Summary: Pie chart "missing" data bug

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1218]
- [ ] Tooltip: can you make this appear on 2 lines instead of 3? So the number of participants and the word "participants" should appear on one line
- [x] There's a slice of the pie that shows 42 participants for a "missing" data value. Please remove this.
 
![screen shot 2019-02-20 at 9 42 58 am](https://user-images.githubusercontent.com/18424138/53101425-b46b2d00-34f7-11e9-9003-2e62c56d7363.png)
![screen shot 2019-02-20 at 9 43 04 am](https://user-images.githubusercontent.com/18424138/53101426-b46b2d00-34f7-11e9-8066-a72696d1a49c.png)
![screen shot 2019-02-20 at 9 43 09 am](https://user-images.githubusercontent.com/18424138/53101427-b46b2d00-34f7-11e9-9861-cfd3b360008c.png)

**Comment by rosibaj** [comment]
Call the slice "No Data" instead of removing it

**Comment by rosibaj** [comment]
tested - correctly showing `No Data` instead of `_missing` now.
