### ISSUE TITLE
Selection of Table Rows with "Remove from Cohort"

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1221]
- [x] when user hasn't selected any participants, the action buttons are disabled: Zeplin: https://zpl.io/VQKZGQA
![screen shot 2019-02-13 at 11 23 44 am](https://user-images.githubusercontent.com/18424138/52726788-db6ab180-2f81-11e9-94b0-1e9f462aca30.png)

- [x] when the user selects some participants, the action buttons are enabled: Zeplin: https://zpl.io/agPwLWM

![Screen Shot 2019-01-21 at 3.19.53 PM.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/de7fb225-d944-4359-bff8-718f7de158f2)

- [x] Action that should be included is `Remove from Cohort`, `clear selection`
- [x] from @hlminh2000: if all selected, `Remove from Cohort` should be disabled

**Comment by jberube** [comment]
What is the behavior of the checkbox in the header?

I would guess "Select All", but is it all rows in the current page, or all rows of the cohort - including those we didn't fetched yet?

**Comment by rosibaj** [comment]
@jberube Yes, it was intended to be select all (as kim an i initially planned an infinite scroll there).  @kcullion should we adapt this page/design to the select method that we designed for the file repo table as well>

**Comment by kcullion** [comment]
Yes @jberube and @rosibaj the select all proposal for the file repo is here: https://github.com/kids-first/kf-portal-ui/issues/1096
If we are making it like the file repo table, it should be consistent with that.  Although, it hasn't been implemented in the file repo yet - do we want to prioritize this differently? Or can it be done in arranger so that it can apply to both tables in some way all at once?

**Comment by jberube** [comment]
Why would someone would select all? Not selecting any is pretty much the same, no?

**Comment by kcullion** [comment]
@jberube it would be to perform an action on the full list of participants - like push the files of all participants to cavatica. Users were getting confused and didn't realize that selecting none meant selecting all. Currently in the file repo - that header checkbox only selects the files on that page

**Comment by jberube** [comment]
Ok. But what if a user checks "Select All", and then tries to un-check a row?

**Comment by kcullion** [comment]
Great question! We were mimicking what happens in gmail except flipped - we felt that in kids first, users would likely want to select all more often then just selecting the first 20 files in the table, say. 

I will discuss with @rosibaj. but my first instinct is, say the cohort table has 80 participants (20 per page):
1. User checks "select all" in table, all 80 participants are selected (across 4 table "pages")
2. Top of table says "80 Participants are selected. _Select only the 20 Participants on this page_ "
3. User unselects first participant in the list, that row becomes unselected and the 79 other rows are selected across the table pages.
4. Top of table says "79 Participants are selected. _Select only the 20 Participants on this page_ "

**Comment by kcullion** [comment]
Or we can do like gmail...
1. User checks the "select all" checkbox in the header, the first 20 participants are selected.
2. top of table says "20 Participants on this page are selected. _Select all 80 participants in cohort_”
3. user unselects the first participant in the list, that row becomes unselected and the 19 other rows remain selected on this page
4. Top of table does not say anything, or could just say "19 participants are selected"

**Comment by rosibaj** [comment]
@kcullion @jberube This behaviour looks good to me! In reference to your earlier question, yes this could be a part of arranger that is extendable to the file repo.

**Comment by jberube** [comment]
Second version is more doable.

The problem I have with the first one is that I have no way of knowing the ids of the selected rows from other pages, other than to query them all from the server, page by page. For a cohort that have a few 1000s of rows, that can be really heavy on both the server and the client.

**Comment by rosibaj** [comment]
@jberube Makes sense - Let's go with Second version, but first lets also connect with @hlminh2000 during standup - Maybe we could use the `set` feature for the all participants selection if its not performant enough to query all of the ids.

**Comment by kcullion** [comment]
@jberube Let me know if changes to the mockup are needed here.

@rosibaj wondering if some actions should work like they currently do as well? So if the user doesn't select any rows and clicks the analyze in Cavatica button, it still pushes all the participant files. (the remove participant button shouldn't work like this though - they would have to select the participants to remove)

But they can also do that by following the steps in version 2

**Comment by jberube** [comment]
I don't see a way to open the current cohort in the file repository, is that part of another ticket? I know that Vincent though it was the main utility of the cohort builder.

**Comment by rosibaj** [comment]
@jberube If you click the link on the # of files in the cohort summary, that should take you to the file repository.

**Comment by kcullion** [comment]
@jberube the user can click on the total number of files to open the cohort in the file repo
<img width="533" alt="screen shot 2019-03-01 at 2 14 17 pm" src="https://user-images.githubusercontent.com/18424138/53660647-5bed0b80-3c2c-11e9-889a-1b072f8eef59.png">

**Comment by kcullion** [comment]
@rosibaj jinx! haha

**Comment by jberube** [comment]
Since the sprint is ending, I propose we move this ticket to "Review" and create a new ticket for what is remaining, which is:
- "Analyze in Cavatica" button
- "Download" button

**Comment by rosibaj** [comment]
@jberube great suggestion - made a ticket for next sprint here: https://github.com/kids-first/kf-portal-ui/issues/1299

**Comment by jberube** [comment]
@rosibaj @hlminh2000 What is still blocking the merge of this issue?

**Comment by hlminh2000** [comment]
@rosibaj so I've merged the PR associated with this. You will notice that the participant number and the content of the table looks wrong (the set content is applied as an inclusion rather than exclusion), this is a back-end issue, so should be addressed separately. 
Additional UI work on this should ignore this inconveniently wrong behaviour for now if possible.
