### ISSUE TITLE
Link to File Repo as a Participant Set

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1223]
- [ ] translate the participants links to file repository into the 
![Screen Shot 2019-02-20 at 11.58.00 AM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/d224b837-5561-4908-bca2-9f706055e814)
- [ ] pass it as a set of the participants id to the file repository; no need to carry the SQON filters

**Comment by ciaranschutte** [comment]
@rosibaj hooking up the data in this ticket too.

**Comment by ciaranschutte** [comment]
@rosibaj further work needed to make sure the File Repo link is working correctly
Detailed in PR: https://github.com/kids-first/kf-portal-ui/pull/1267

**Comment by hlminh2000** [comment]
Basically the numbers in the file repo doesn't seem to match up with what is shown in cohort-builder before the redirect. From code review, the cohort-builder seems to be working correctly, so this will require some investigations.

**Comment by rosibaj** [comment]
thanks @hlminh2000 @ciaranschutte - I am going to leave this in preview while i do some data investigations!
