### ISSUE TITLE
Filters: Category Bar UI fixes

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1225]
- [x] Please make the entire button the hotspot, not just the label.
![screen shot 2019-02-15 at 10 47 18 am](https://user-images.githubusercontent.com/18424138/53115020-18e7b580-3513-11e9-8e7d-39e7e96d1222.png)

- [x] Fix the layout of the icon and label within the button so the icons are all similar sizes, within the same fixed-height container (so that all of the labels start at the same point). Also make sure the padding on the top and bottom of the buttons are equal.
![screen shot 2019-02-15 at 10 51 10 am](https://user-images.githubusercontent.com/18424138/53115034-22711d80-3513-11e9-8dc0-43704661c3fa.png)

- [x] Implement the hover/active states for the buttons and dropdowns.

- Hover for main menu button - just background-color changes to #f4f5f8
- Active state for menu button - the button has the same grey background in a) but also a subtle drop-shadow to make it protrude slightly from the interface
- Hover state for filter type - background-color changes to #f4f5f8

![screen shot 2019-02-15 at 11 03 16 am](https://user-images.githubusercontent.com/18424138/53115099-53e9e900-3513-11e9-96a4-6a0c4b553ec0.png)

**Comment by rosibaj** [comment]
@ciaranschutte looks great! Thank you!!
