### ISSUE TITLE
Summary Area should refresh from the global SQON

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1227]
When the active query is run:
- [x] The table should update
- [x] The header text should update with the correct numbers
- [ ] All charts should update

**Comment by rosibaj** [comment]
Just assigning everyone to this ticket - i think the table is covered now (thanks @jberube)  and the headers (thanks @ciaranschutte!!)

i think the only outstanding one that is still in progress is the file_breakdown query which @ciaranschutte is working on.  Is that right?

**Comment by ciaranschutte** [comment]
@rosibaj Survival chart still only has mock data
