### ISSUE TITLE
Fix Header Z-Index

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1235]
- Resources and profile dropdowns are behind the cohort category bar
- they should be on top

![Screen Shot 2019-02-21 at 2.53.40 PM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/b0e3aba5-2a60-49fc-8d0d-5d939cff15a1)![Screen Shot 2019-02-21 at 2.53.14 PM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/ca862c7a-bfb3-4e38-816a-dbc61418ee7a)

**Comment by hlminh2000** [comment]
I believe this is a duplicate of https://github.com/kids-first/kf-portal-ui/issues/1230 ? :)

**Comment by rosibaj** [comment]
@hlminh2000 yeah i found the same thing - closed!
