### ISSUE TITLE
Query Builder: Deleting query actually deletes any duplicate queries

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1236]
*Steps to Reproduce*
- Make a query #0
- Duplicate query #0 and see query #1 being generated.  Make a change to query #1 so that it is different from #0
- Delete query #0 
- BUG: when i try and delete query #0, query #1 does not get set to the active state
Video of bug: https://drive.google.com/file/d/1Bh3OKiaOouAj_R1hgzTxz3I5PXXjvfrR/view

**Comment by hlminh2000** [comment]
Great catch @rosibaj! looks like the real bug is that the selection state is not updated after the deletion :)

**Comment by rosibaj** [comment]
updated in other bug tickets
