### ISSUE TITLE
User Profile design review

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#124]
- [x] When I click on the User link in the top header, the dropdown opens outside of the browser width so I get a horizontal scrollbar (and I can't see the full labels). Please reposition it so it's within the viewing screen.
- [x] Community Profile: CHOP added "Organization" as an option for the community profile, please add this to "Edit basic information" form under "last name: 
- [x] User type dropdown in user Basic edit screen: please make this larger like the mockups (and add a colon after the word Role like the other form field labels):
![screen shot 2018-04-17 at 4 16 25 pm](https://user-images.githubusercontent.com/18424138/38894262-bc15057a-425a-11e8-8390-d24961c72834.png)

- [x] Contact information looks squished, can you set the line-height of this area to { line-height:28px;}
- [x] Please reorder the contact information like the mockup so the Job Title/Role is a bit larger font-size (18px)
https://invis.io/MQFHWABDK9Y#/276423115_21-KF-Researcher-Profile-Filled
- [x] Can you add more space in between the Background information div and the research interests box?  {margin-left:5em;} (right now it's set to 1em)
![screen shot 2018-04-17 at 4 20 13 pm](https://user-images.githubusercontent.com/18424138/38894432-39c66ca2-425b-11e8-94a7-ef1c8dc01fc0.png)

- [x] can you add a bit of space between the edit pencil and the "EDIT" label (margin-right: 5px;)
![screen shot 2018-04-17 at 4 20 34 pm](https://user-images.githubusercontent.com/18424138/38894450-46a35c78-425b-11e8-9095-d3640ae1ddd5.png)

- [x] Teal buttons - can you fix the styling of these so they look more consistent with the design ("Save" "Connect" "My Website" "Google Scholar"). There's a couple Save styles happening:
![screen shot 2018-04-17 at 4 22 21 pm](https://user-images.githubusercontent.com/18424138/38894558-8d6638ec-425b-11e8-8a9b-a9d661ac0afa.png)
![screen shot 2018-04-17 at 4 22 26 pm](https://user-images.githubusercontent.com/18424138/38894562-8f5f069c-425b-11e8-87c8-81d7eeff2888.png)

- [x] can you increase the white space between the bio and the story approx: {margin-top:25px;}
- [x] can you increase the overall body copy line-height as well (line-height: 28px;}
- [x] can you increase the spacing in between the interests + website url + google scholar ID (margin-top:20px;)
![screen shot 2018-04-17 at 4 23 57 pm](https://user-images.githubusercontent.com/18424138/38894618-c13d0cea-425b-11e8-86b2-7648b254bf72.png)

- [x] Can you increase the padding inside the Research interest box: {padding: 0 30px 30px 30px;}
- [x] Can you match the styling of the subnavigation bar to the one that I mocked up for the website (it's working much better here and CHOP likes it):
![screen shot 2018-04-17 at 4 25 46 pm](https://user-images.githubusercontent.com/18424138/38894883-875c8432-425c-11e8-9026-e6bd563e5762.png)

- [x] When I edit the bio/story - the area that holds the cancel and save buttons should match the modal area that holds these buttons. Please use consistent styling for the buttons too with these modal buttons
![screen shot 2018-04-17 at 4 30 09 pm](https://user-images.githubusercontent.com/18424138/38894918-9c8f000a-425c-11e8-8ffd-13400f819558.png)

**Comment by rosibaj** [comment]
@hlminh2000 This looks amazing!! Thank you!
