### ISSUE TITLE
Filters: Show selected items first

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1240]
Sort the values by selected values then add a 2nd sort by number of participants.

## Acceptance criteria
- Sort the values by selected values
- then add a 2nd sort by number of participants.

## Details
In other words: 

When the user has checked off values in the filters - the next time they open this filter, those selected values should be at the top of that checkbox value list.

When they uncheck them, they stay where they are in that view. But when the user reopens the filter, that unselected value is back in it’s correct alphabetic place in the list.  

![screen shot 2019-02-25 at 10 43 33 am](https://user-images.githubusercontent.com/18424138/53349217-a3049500-38ea-11e9-9128-68877cc7ae87.png)

**Comment by nyanofthemoon** [comment]
**NOTE**: @jberube I will be deploying the kf-arranger/components dependency with @claudia1296 this morning. Not yet visible in QA.
