### ISSUE TITLE
Filters: Filter name order should be alphabetical

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1242]
Please make the filter list alphabetical:
![screen shot 2019-02-25 at 10 48 55 am](https://user-images.githubusercontent.com/18424138/53349837-f88d7180-38eb-11e9-8981-d40c6c94744a.png)

**Comment by kcullion** [comment]
@rosibaj did we also mean to alphabetize the quick filters here?
![Screen Shot 2019-03-12 at 9 35 08 AM](https://user-images.githubusercontent.com/18424138/54204252-37a1f200-44aa-11e9-8b3b-c52f44e2c09e.png)

**Comment by rosibaj** [comment]
@kcullion Yes, there is also an issue right now that the display names need to be corrected, but Arranger admin is not letting me do that.  @hlminh2000 will look at fixing that bug - in the meantime i have ordered the fields such that `once we fix the display names in arranger they will be in alphabetical order` in PR #1324 (attached)

**Comment by rosibaj** [comment]
@kcullion Yes, there is also an issue right now that the display names need to be corrected, but Arranger admin is not letting me do that.  @hlminh2000 will look at fixing that bug - in the meantime i have ordered the fields such that `once we fix the display names in arranger they will be in alphabetical order` in PR 1324 (attached)
