### ISSUE TITLE
Member page: Make my profile non-searchable (private profile)

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1247]
As a user, i want to allow or disallow the appearance of my profile in the searches that other users might do on the portal.

## Acceptance criteria
- If the user chooses to remain invisible to others by using the global search, they must not appear in global search results.
- If someone goes to the URL of their profile, and their profile is private, there should be an error page.
- It's off by default.

## Mockups
**Privacy Settings**
SMALL CHANGES
- [ ] Rename the "Settings" page label to "Settings & Privacy" to be more clear where to find important privacy settings
![screen shot 2019-02-14 at 1 20 39 pm](https://user-images.githubusercontent.com/18424138/52808226-5e136f80-305b-11e9-84d4-7a4edd873da5.png)
- [ ] Rename the heading for the email section to "Account Login", as this is more the subheading for the email address and not the entire page.

![screen shot 2019-02-14 at 1 29 01 pm](https://user-images.githubusercontent.com/18424138/52808738-949dba00-305c-11e9-8fb5-b5e98b569682.png)

**Comment by nyanofthemoon** [comment]
https://portal.kidsfirstdrc.org/user/**2b0747ab-216e-439c-ac2e-fb92f984b8aa**#aboutMe
