### ISSUE TITLE
Query Builder: blank query

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1255]
- [x] For a blank query, please include the instructions “Use the filters above to build a query”
![screen shot 2019-02-27 at 9 38 11 am](https://user-images.githubusercontent.com/18424138/53497991-6b752480-3a73-11e9-9d46-4532930604b5.png)

- [x] If there is just one row/query and the user tries to delete it (clear the fields) - keep that blank row and revert back to the instruction sentence
![screen shot 2019-03-04 at 11 31 31 am](https://user-images.githubusercontent.com/18424138/53747363-166d5000-3e71-11e9-8b08-972414b81023.png)

- [x] When the user "Clear all" queries - that blank row with the instructions should be on screen (right now it deletes all the rows).
![screen shot 2019-03-04 at 11 48 26 am](https://user-images.githubusercontent.com/18424138/53748507-72d16f00-3e73-11e9-8b86-85dbd19834db.png)

**Comment by rosibaj** [comment]
@hlminh2000 looks great! thank you!

**Comment by kcullion** [comment]
@rosibaj @hlminh2000 I just think the delete icon and clear all button should be using the disabled style when the user has just one blank query. So they can't try to delete in this case...
![Screen Shot 2019-03-12 at 9 42 31 AM](https://user-images.githubusercontent.com/18424138/54204766-4ccb5080-44ab-11e9-85fc-6ff1a2dc9a7c.png)

**Comment by rosibaj** [comment]
@kcullion Can you make a new ticket for this feedback?  I think it should sit in backlog until we can get to the end of the sprint!

**Comment by kcullion** [comment]
Okay thanks @rosibaj  - just made it here: https://github.com/kids-first/kf-portal-ui/issues/1322
