### ISSUE TITLE
Store Queries in localstorage if Cohort is not saved

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1263]
- store the sqons in localstorage so that the user can navigate thru the portal ( or leave) and come back to the same queries if they have not saved them 
- use `SQONProvider` component to check first local

**Comment by rosibaj** [comment]
@hlminh2000 thanks for the fast fix!  It's already more amazing 🎉 (cc @kcullion queries will stay on reload and navigation now!)

**Comment by kcullion** [comment]
@rosibaj @hlminh2000 I just saw..so great!!!
