### ISSUE TITLE
Small UI fixes for 0 results fade-out on summary section

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1270]
Summary view of this looks fine, but:
- [ ] Change the `0` in the message to `no`
- [ ] Can we fix
<img width="842" alt="screen shot 2019-02-28 at 6 12 50 pm" src="https://user-images.githubusercontent.com/15824252/53605156-9733ff80-3b84-11e9-9282-723d804a99d9.png">
 the Z-index?

**Comment by jaouad-benassila** [comment]
![popup](https://user-images.githubusercontent.com/47750690/53912352-cb953900-4026-11e9-80ba-8d4b5961b065.png)

By testing in firefox, I found this UI bug in message pop-up if there are 0 participant for summary section.
By the way, I will fix it.

**Comment by rosibaj** [comment]
@jaouad-benassila nice catch!! sounds good!
