### ISSUE TITLE
Clear all changes which cohort is currently selected

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1286]
When you click “clear all” the currently selected query gets change to Q1.

 This is a video of the current behaviour:
https://drive.google.com/file/d/15pqlCwu2Po6ZYCGWb1Mg1eYx2F83TfX1/view

## What should happen instead
The active query should not change when you click clear all.

**Comment by nyanofthemoon** [comment]
Not a quick win because the component is re-rendered due to props being changed and passed down by the parent components.

src/components/CohortBuilder/index.js

![debug.png](https://images.zenhubusercontent.com/5c05950b0a4f964ea1a04049/168df57b-b8ad-4f56-8751-29bd05e75beb)

**Comment by jberube** [comment]
See `src/AdvancedSqonBuilder/index.js:250` for what cause the `activeIndex` to be reset to `0` too soon.

Will need more sophisticated eventing or state management to fix properly.
