### ISSUE TITLE
Member page: View someone's member's page

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1287]
As a user, I want to be able to view the profile of another user, if their profile is searchable. (public)

Other logged in Kids First members can find my profile when doing a global search and will see a read-only version of it.

Let's do a 1-day investigation spike, and we will re-evaluate after.

## Acceptance criterias
- One can only see users whose profiles are public. See #1247 
- Similar to the profile page when one edits it, but without the editing options. (read-only profile)
- One must be logged in in order to see someone's profile.

## Mockups
Zeplin: https://zpl.io/2EBxvLY

![06b kidsfirst-public-profile-notes](https://user-images.githubusercontent.com/18424138/53818715-82fe5280-3f36-11e9-84a2-fb7dcba2c59c.jpg)

**Comment by nyanofthemoon** [comment]
https://portal.kidsfirstdrc.org/user/2b0747ab-216e-439c-ac2e-fb92f984b8aa#aboutMe
Insert you favorite hash in the url...
