### ISSUE TITLE
Rephrase user interest selection

### ISSUE THREAD

**Issue by Fgerthoffert** [kids-first/kf-portal-ui#130]
<img width="244" alt="screen shot 2018-03-08 at 4 12 09 pm" src="https://user-images.githubusercontent.com/5667028/37176840-8b7da8c4-22eb-11e8-892a-ff76d074f011.png">

@phuongmy can you confirm the wording ? "I am interested in" for example.

**Comment by phuongmy** [comment]
Was fixed in https://github.com/kids-first/kf-portal-ui/issues/178
We replaced by "Role"
