### ISSUE TITLE
Table View: no participants for this cohort message

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1302]
There's a "No rows found" message coming from arranger within the table view.
Please remove this so other message is visible

![Screen Shot 2019-03-12 at 10 57 41 AM](https://user-images.githubusercontent.com/18424138/54211435-ae91b780-44b7-11e9-81d8-0a81a9f47f62.png)

**Comment by rosibaj** [comment]
@jaouad-benassila tested this as well.  Looks great!! Thank you so much!
![Screen Shot 2019-03-19 at 4 30 33 PM](https://user-images.githubusercontent.com/15824252/54639671-554ff800-4a64-11e9-9cda-4d8cf41344c2.png)
