### ISSUE TITLE
Summary Table: Add Download button

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1304]
@rosibaj to add details

- [x] Add "Download" button (similar to file repo).  DO NOT include the File Manifest. 

This button is very similar to the download button in the file repository.  In terms of function, the reports should be the exact same when downloaded.  In the file repository, there may be some logic translating files to participant ids, but in terms of the page we only need to send the participant id that are in the table or selected into the reports. 

![image](https://user-images.githubusercontent.com/15824252/53966230-c71d5e80-40c0-11e9-8cfe-831dbbaf4c45.png)

**Comment by rosibaj** [comment]
tested - noticed a difference in the reports from the file repository to the cohort builder: 
![image](https://user-images.githubusercontent.com/15824252/54846568-8de51100-4cb2-11e9-9c02-9818da436fa6.png)

@jaouad-benassila Can you please make the columns in the cohort builder page clinical report exactly the same as the clinical report in the file repository:

From the original [specs](https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/383156225/Download+Clinical+and+Biospecimen+data#DownloadClinicalandBiospecimendata-a.Clinicaldataoftheparticipants), these columns should be: 
```<participant.kf_id> |<participant.external_id> | <participant.father_id> | <participant.mother_KF_id>| <participant.family_id> |<participant.family.external_id> | <participant.is_proband> | <list of relationships with other participants except father and mother>|<participant.study.name> | <participant.gender> | <participant.race> | <participant.ethnicity> | <participant.hpo_phenotypes_observed> | <participant.hpo_phenotypes_not_observed> | <participant.diagnoses.diagnosis>| <participant.diagnoses.follow with DIAGNOSIS FIELDS below>

age_at_event_days
diagnosis_category
icd_id_diagnosis
mondo_id_diagnosis
ncit_id_diagnosis
source_text_diagnosis
source_text_tumor_location
spatial_scriptor
uberon_id_tumor_location```

**Comment by rosibaj** [comment]
@jaouad-benassila  Thanks for the updates! The clinical reports look _much_ better now!!! As far as i can tell, the SQON is correctly translating the Participant # and the participant _ family number into the reports now.

**Comment by rosibaj** [comment]
Found a another bug documented in #1434
