### ISSUE TITLE
Study Card Data bucket cannot render null values in is_proband field

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1318]
After a data check, the `Participant` index DOES have 250 records and IS aliased correctly. 
![Screen Shot 2019-03-11 at 1.26.00 PM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/72d0e78a-4a37-4a9e-b6cf-0e191c558929)

Upon further investigation:
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/828e1fce-0922-4bf9-b9ab-4849183bda9c)

*Implemented Solution* 
- I will replace Family Members with Other Participants for studies card and Most Frequent Diagnoses card.
- If the field proband return null, I will count it in the total of the Other Participants category.

**Comment by hlminh2000** [comment]
this solution looks good to me. @ciaranschutte so aside from `"true"` and `"false"` for `is_proband`, we can add a new query to aggregate against `"__missing__"`

**Comment by jaouad-benassila** [comment]
As discussed with Vincent:

- I will replace Family Members with Other Participants for studies card and Most Frequent Diagnoses card.
- If the field proband return null, I will count it in the total of the Other Participants category.

**Comment by hlminh2000** [comment]
If `is_proband` is `null`, they could still be probands, we just don't know, right?
Grouping them into the `false` value can be misleading imo. @rosibaj any thoughts on this?

**Comment by rosibaj** [comment]
@hlminh2000 its kind-of an issue with how the data is structured - they _could_ be but we can't tell for sure any way. Thats why Vincent wants to group everything NOT TRUE as `other`

**Comment by rosibaj** [comment]
@jaouad-benassila Tested and this looks to be working fine, but one small edit needs to be made; The next in the tooltip needs to be changed from `Family Members` as well. 
![image](https://user-images.githubusercontent.com/15824252/54842699-fdee9980-4ca8-11e9-92aa-aed77b0c9908.png)

**Comment by jaouad-benassila** [comment]
Fix tooltip text:
![tooltip](https://user-images.githubusercontent.com/47750690/54844506-77888680-4cad-11e9-90f5-646bbc657667.png)

**Comment by rosibaj** [comment]
tested - Tooltip shows correct text now. thank you @jaouad-benassila
