### ISSUE TITLE
Query Summary: Available Data card - alpha order by data type

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1323]
Please order the available data card alphabetically by data type
![Screen Shot 2019-03-12 at 10 18 02 AM](https://user-images.githubusercontent.com/18424138/54207635-e2b5aa00-44b0-11e9-85d9-6428f35ad497.png)

**Comment by rosibaj** [comment]
tested - looks great.  Thank you @jaouad-benassila !!!
