### ISSUE TITLE
Filters: Continuous - greater than, less than behaviour & between data issue

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1328]
- [x] the greater than and less than items need to be switched. For example, the “From” should be the input that is activated for the "greater than" and "greater than or equal to" and the "To" should be activated for the "less than" or "less than or equal to"

- [x] Don’t get rid of the To or From depending on the dropdown item picked, just keep it available and disable it. Find style in Zeplin: https://zpl.io/adpvmQl
![Screen Shot 2019-03-12 at 3 24 43 PM](https://user-images.githubusercontent.com/18424138/54230266-7486dc80-44dc-11e9-8bd9-3c0cc8ba5d36.png)

- [x] 1) Doing a query of `Outcome Age at Events` > 1 seems to work ok - i do it and can get these results: 
![image](https://user-images.githubusercontent.com/15824252/54220345-932ea880-44c7-11e9-9a7b-fc9b542690fb.png)

2) Some issues with "between" behaviour: 
Doing a query of between does not seem to work.  If I select the same field, `Outcome Age at Events` between 1, 10000 (which should work and have results according to the previous screenshot) I get 0 results.
![image](https://user-images.githubusercontent.com/15824252/54220341-90cc4e80-44c7-11e9-94a7-44c0b058e60e.png)

**Expected results:**  
Between should not result in 0 participants

**Comment by kcullion** [comment]
@hlminh2000 Some related bugs:
1. My value isn't applied to the query value area if I try anything except "Between"
![Screen Shot 2019-03-25 at 2 51 03 PM](https://user-images.githubusercontent.com/18424138/54946145-d4827780-4f0d-11e9-94dc-a85140bf707e.png)
2. Not remembered within the dropdown either:
![Screen Shot 2019-03-25 at 2 54 31 PM](https://user-images.githubusercontent.com/18424138/54946203-f11eaf80-4f0d-11e9-91aa-f7dd6605af9d.png)
3. If I set the "Age at diagnosis" between 0 and 10, then I go to the query dropdown to change to just "Greater than" - it assumes I want greater than 10 instead of 0 and applies 10 to both To and From options. I also can't edit that value and change 10 to 15, for instance
![Screen Shot 2019-03-25 at 2 55 35 PM](https://user-images.githubusercontent.com/18424138/54946318-37740e80-4f0e-11e9-8b96-be8c625d917a.png)
![Screen Shot 2019-03-25 at 2 55 45 PM](https://user-images.githubusercontent.com/18424138/54946319-37740e80-4f0e-11e9-88ce-cf1c84d6b79c.png)

**Comment by hlminh2000** [comment]
updated, thanks @kcullion for the test!

**Comment by rosibaj** [comment]
@kcullion This looks good to me- I think Minh caught all of your test cases.  I would like your eyes on this again but its functioning well for me now!

**Comment by kcullion** [comment]
@rosibaj @hlminh2000 this looks good to me...just made a new ticket for that operator label: https://github.com/kids-first/kf-portal-ui/issues/1461

Well done, I'll close this!
