### ISSUE TITLE
Continuous Filters: No inputs

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1339]
The user should not be able to apply a continuous filters if they haven't filled out the input fields. Currently if I leave them blank, they are applied to the query area and actually filter the results.
![Screen Shot 2019-03-18 at 10 41 56 AM](https://user-images.githubusercontent.com/18424138/54538464-ac71a200-496a-11e9-8b22-d0b43490a407.png)

**Comment by rosibaj** [comment]
Will be fixed as part of #1438
