### ISSUE TITLE
Continuous Filters: Clear isn't working

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1341]
The clear link should clear the input text fields.

![Screen Shot 2019-03-18 at 10 59 54 AM](https://user-images.githubusercontent.com/18424138/54540351-3f600b80-496e-11e9-82fd-0fe6a536f5d3.png)

EXPECTED BEHAVIOUR: 
When you click clear, all active text boxes are made `blank` (not `0`)

**Comment by aalex** [comment]
Is there a PR for this issue?

**Comment by jaouad-benassila** [comment]
https://github.com/overture-stack/arranger/pull/507
