### ISSUE TITLE
Continuous Filter: Dropdown order

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1342]
As a user, I expect the ordering options to be well ordered.

## Acceptance criteria
- In the cohort builder, in the continuous (range) filters, change the order of the items in the dropdown. (see in the Order section)
- Between should still be the default

## Order
We will order them from the "smallest" to "biggest":

- less than
- less than or equal to
- between (default)
- greater than or equal to
- greater than

## Screenshot
Here is how it is currently:
![Screen Shot 2019-03-18 at 11 16 35 AM](https://user-images.githubusercontent.com/18424138/54540970-4fc4b600-496f-11e9-9cf6-4d27f07deab4.png)

**Comment by aalex** [comment]
I would recommend putting them in this order: (from smallest to biggest)

- less than or equal to
- less than
- between (default)
- greater than or equal to
- greater than
