### ISSUE TITLE
Boolean Filters: Data Bug for "Affected status"

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1343]
The Affected status should not be coming in at Yes: 0, No:0

![Screen Shot 2019-03-18 at 11 43 08 AM](https://user-images.githubusercontent.com/18424138/54542915-037b7500-4973-11e9-918c-04cf3e288402.png)

**Comment by hlminh2000** [comment]
this should be resolved by #1274

**Comment by kcullion** [comment]
@hlminh2000 so the zero values will be resolved with that ticket?

**Comment by hlminh2000** [comment]
actually, this looks like a data issue from Elasticsearch, ignore my earlier comment :)
@rosibaj no participant document have `affected_status` value, are we looking for another field? If no data is available, maybe we can take this field out?

**Comment by rosibaj** [comment]
Investigating data issue: 
1) Checking QA Aliases: 
`GET participant_centric_sd_46sk55a3_re_47z5mp6a/participant_centric/PT_0281CC60`
--> document found, but `affected_status` not present in document

`GET file_centric_sd_46sk55a3_re_47z5mp6a/file_centric/GF_04FPXEYX`
--> document found and `affected_status` IS found correctly attached to participant in the index? 

2) Checking the latest `participant_centric` ES mapping, the field IS present in the mapping
https://github.com/kids-first/kf-es-model/blob/master/es-model-latest/participant_centric.mapping.json#L8 

The data issue is that there is a mismatch in the data fields in-between the centric documents, which could only have happened in the ETL process.  

To continue to diagnose, I will:
1) Rerun the study in the ETL and 
2) see if the data mis-match issue persists

**Comment by joneubank** [comment]
Found a code reason why this field is missing in the participant_centric index. I will link the commit and PR to this ticket when I deploy today.

**Comment by rosibaj** [comment]
Related to: https://github.com/kids-first/kf-portal-etl/issues/63

**Comment by rosibaj** [comment]
Tested on latest ETL run (March 25, 2019)

The Affected Status is now populating on the participant index correctly! 

![Screen Shot 2019-03-25 at 5 48 00 PM](https://user-images.githubusercontent.com/15824252/54956354-26cf9280-4f26-11e9-83f3-bdd55ecc37f6.png)

**Comment by kcullion** [comment]
@rosibaj the file repo all filters says 605 participants with affected status. Is that just a file vs participant index thing?

**Comment by rosibaj** [comment]
@kcullion (recording for posterity here) - No, the participant count in the file repository is not working due to a separate bug introduced in #1376
