### ISSUE TITLE
Wheel keeps spining after the user has downloaded a file

### ISSUE THREAD

**Issue by phuongmy** [kids-first/kf-portal-ui#135]
Select a file and click on download manifest action for participant.
After the file is downloaded, the wheel keeps spinning.
Jeffrey mentioned because the API is not on the same domain as the ui.
Can we fix it for the demo? 

<img width="1438" alt="screen shot 2018-03-09 at 10 43 27 am" src="https://user-images.githubusercontent.com/8812383/37216241-58a0a7d8-2388-11e8-9318-d54fa9e574d9.png">

**Comment by andricDu** [comment]
We need to reverse proxy arranger

**Comment by andricDu** [comment]
@Jephuff can you confirm that a reverse proxy would fix this.
```
beta.kids-first.io/api/ -> arranger.kfdrc.org
```

**Comment by Jephuff** [comment]
yep, should work. 
I can actually probably do that with netlify unless there are objections? @andricDu

**Comment by phuongmy** [comment]
It's working, thanks!
