### ISSUE TITLE
Search all filter: style fixes

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1354]
- [x] Can you make the search fields responsive, but with a min width like it is now (~230px) so on larger screens it fills the block space consistently
![Screen Shot 2019-03-20 at 9 44 59 AM](https://user-images.githubusercontent.com/18424138/54688978-0bfbb900-4af5-11e9-9706-a2cf7ca3f464.png)

- [x] Clicking off the search dropdown should close it like the behaviour of the other category dropdowns

- [x] I think the items in the dropdown need more separation as it's a bit hard to see that the field names go with the values because of the spacing.  If we move the field name a bit closer to the value list and add a light border (border 1px #cacbcf) that separates the field groupings, this will help.
![Screen Shot 2019-03-20 at 10 34 42 AM](https://user-images.githubusercontent.com/18424138/54692865-0f467300-4afc-11e9-8dc1-1d1397607656.png)

- [ ] nice-to-have: can we match the search textfield with the style in the file repo and dashboard forms? But I do like the size of the font used in the cohort builder better - it stands out more.
![Screen Shot 2019-03-20 at 11 04 06 AM](https://user-images.githubusercontent.com/18424138/54695362-30a95e00-4b00-11e9-8033-3e47a79144b4.png)
![Screen Shot 2019-03-20 at 11 08 10 AM](https://user-images.githubusercontent.com/18424138/54695532-83831580-4b00-11e9-9d79-406f29d375f8.png)

- [x] Can you make the full label and checkbox clickable, not just the checkbox. Makes it easier to select.
![Screen Shot 2019-03-20 at 12 09 48 PM](https://user-images.githubusercontent.com/18424138/54700277-132cc200-4b09-11e9-8907-a7b343f68010.png)

**Comment by jberube** [comment]
@ciaranschutte Already made a branch for it, first item is fixed.
`fix/1354-search-all-style-fixes`

**Comment by kcullion** [comment]
great thanks @jberube - you guys are way ahead of me :)

**Comment by ciaranschutte** [comment]
@kcullion @rosibaj what is this point? "can we match the search textfield with the style in the file repo and dashboard forms? But I do like the size of the font used in the cohort builder better - it stands out more." 

Make icons smaller?

**Comment by hlminh2000** [comment]
re: the input, there's a `FilterInput` component available from `src/uikit/Input.js`

**Comment by kcullion** [comment]
@ciaranschutte I think we can leave it.  It's just the textfield border doesn't match the rest of the textfields across the portal. this one looks like it's a 2px stroke and the others look like it's a 1px stroke with an inner shadow?

**Comment by kcullion** [comment]
@rosibaj this one looks good to me!
