### ISSUE TITLE
Summary table: more padding in between file icon and link

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1358]
Please add 5px between the file icon and the file link
![Screen Shot 2019-03-20 at 11 24 48 AM](https://user-images.githubusercontent.com/18424138/54696756-c940dd80-4b02-11e9-95de-26a0960f9dc6.png)

**Comment by rosibaj** [comment]
tested: 
![image](https://user-images.githubusercontent.com/15824252/54948327-b9fecd00-4f12-11e9-8ac6-40c6a13120c0.png) 

looks great!
