### ISSUE TITLE
Summary Table: select all checkbox

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1359]
When a user clicks the select all checkbox in the header of the table, then clears that selection, the checkbox in the header of the table should clear too. Currently it’s selected and the user would have to unselect and select, in order to select all again.

Select all: 
![Screen Shot 2019-03-20 at 11 29 26 AM](https://user-images.githubusercontent.com/18424138/54697689-5f293800-4b04-11e9-8dc6-0d03eed6121f.png)

Clear selection:
![Screen Shot 2019-03-20 at 11 35 50 AM](https://user-images.githubusercontent.com/18424138/54697697-63edec00-4b04-11e9-97f7-8a3d65a24da9.png)

**Comment by rosibaj** [comment]
tested - the checkbox correctly clears when the clear link is clicked now.
