### ISSUE TITLE
File links to file repo - label in query is not clear

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1360]
when the user clicks a file link from the cohort builder and is taken to the file repository, the query that is filtered has an odd label, they haven't really "uploaded" a list with this action:
![Screen Shot 2019-03-20 at 11 43 11 AM](https://user-images.githubusercontent.com/18424138/54698401-a19f4480-4b05-11e9-979d-060472d14650.png)

**Please change it to:**

**Participant IDs from  "Explore Data Cohort"**

@rosibaj have any better ideas?

**Comment by rosibaj** [comment]
@hlminh2000 A question for you - Is this something we can control coming from the File Repository, or is this text set?
