### ISSUE TITLE
Summary Table: Sort from table header isn't working

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1361]
When clicking a column header of the table it looks like the column would sort ascending and descending (see the border appear) but it doesn't appear to be working.

Please use the file repo table as a guide for the functionality and the style (should be blue instead of dark grey).

File Repo
![Screen Shot 2019-03-20 at 11 52 34 AM](https://user-images.githubusercontent.com/18424138/54699199-f7282100-4b06-11e9-9d53-4b8a260b89ee.png)

Cohort builder
![Screen Shot 2019-03-20 at 11 52 45 AM](https://user-images.githubusercontent.com/18424138/54699218-01e2b600-4b07-11e9-8db0-59da862e6ea0.png)

**Comment by bonbon12** [comment]
Hi, can i give this a go?
