### ISSUE TITLE
Summary Table: Export button not downloading full table

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1362]
The export button for the table should download the full table. Currently it is only downloading the participants on the first page of the table.
![Screen Shot 2019-03-20 at 12 00 49 PM](https://user-images.githubusercontent.com/18424138/54699662-d2807900-4b07-11e9-9cef-894d055f52ab.png)

**Comment by rosibaj** [comment]
@kcullion this is not a bug - this is how the table export works. I will mark this an `enhancement`

**Comment by rosibaj** [comment]
duplicate of #1456
