### ISSUE TITLE
Category Menu: Dropdown values is overflowing the screen

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1364]
The dropdown values are going off the browser screen into the abyss of my computer

![Screen Shot 2019-03-20 at 12 45 56 PM](https://user-images.githubusercontent.com/18424138/54702909-2c843d00-4b0e-11e9-8fb4-7be71651381b.png)

**Comment by vferretti** [comment]
can we left align it ?

**Comment by kcullion** [comment]
@vferretti yes it would be good to align the right edge of the dropdown with the right edge of the menu item.  Is that what you mean?
