### ISSUE TITLE
Adjust survival chart to days

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1366]
- [x] Change the timelines to `days` for all text & values

**Comment by joneubank** [comment]
https://github.com/kids-first/kf-portal-ui/pull/1404

**Comment by rosibaj** [comment]
@joneubank where is the refresh button placed? i can't find it

**Comment by joneubank** [comment]
Days text is fixed. This just needs the zoom-out/refresh functionality added to chart. I am unassigning and placing in the queue to focus on the file repo page as priority.

Don't worry little ticket, we won't forget about you.

**Comment by aalex** [comment]
I've rephrased this one so that we avoid having duplicates. See #1467 for the part that used to say "When you zoom in on the survival chart, you cannot zoom out.  Add the "refresh" button back in to the chart"
