### ISSUE TITLE
Add missing fields to the Search All feature

### ISSUE THREAD

**Issue by jberube** [kids-first/kf-portal-ui#1368]
**EDIT**

The remaining missing fields are the numeric fields (age), as we cannot do aggregations on them.

```
    // Clinical
    // 'diagnoses.age_at_event_days',
    // 'outcome.age_at_event_days',
    // 'phenotype.age_at_event_days',

    // Biospecimen
    // 'biospecimens.age_at_event_days',
```

Adding one of those fields would return that error:

```
"Cannot query field "buckets" on type "NumericAggregations"."
```

An alternative way of fetching results should be used on them, using `interval`, e.g. : `src/components/CohortBuilder/Summary/AgeDiagChart.js`.

---

Some fields where causing the query to return  an error like `"Invalid pivot field "outcome", not a nested field"`, where `outcome` is the first part of the field path.

In the case where an error of that type occurs, the SearchAll control is not functional, and is not rendered by design, so beside the missing control, it is transparent to the user (the rest of the application works fine).

I'm not 100% sure that the any of the `biospecimen` fields caused errors, I might just have stopped adding field at some point since that was very time consuming.

Here is the list of the fields not included in the search, with the error messages I got.

*Legend*
`*   "Invalid pivot field "outcome", not a nested field"`. 
`**  "Cannot query field "outcome__is_disease_related" on type "participantAggregations". Did you mean ...`
`?` I don't remember what the error was, or might have forgotten that field.

```
clinical: [
  * 'diagnoses.age_at_event_days',
  * 'outcome.age_at_event_days',
  * 'phenotype.age_at_event_days',
  * 'phenotype.ancestral_hpo_ids',
  ** 'family.family_compositions.shared_phenotype_ids',
  * 'phenotype.hpo_phenotype_observed_text',
  * 'outcome.vital_status',
],
biospecimen: [
  ? 'biospecimens.age_at_event_days',
  ? 'biospecimens.analyte_type',
  ? 'biospecimens.composition',
  ? 'biospecimens.method_of_sample_procurement',
  ? 'biospecimens.ncit_id_anatomical_site',
  ? 'biospecimens.ncit_id_tissue_type',
  ? 'biospecimens.source_text_tumor_descriptor',
],
availableData: [
  ? 'files.sequencing_experiemtn.experiment_strategy',
  ? 'family.family_compositions.available_data_types',
],
```

**Comment by jberube** [comment]
NOTE: Adding those fields will impact the feature performance. Some more tweaking might be necessary afterward.

**Comment by jberube** [comment]
Added all the missing fields but the four age fields.
I edited the description accordingly.

**Comment by jberube** [comment]
Moved the "age related" fields to another ticket that can be tackled separately. #1459

**Comment by kcullion** [comment]
This looks good to me @rosibaj ! well done @jberube
