### ISSUE TITLE
Sharing Virtual Study: Social media text changes

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1374]
Please change the text that is default posted to social media when sharing a virtual study.

So Kids First File Repo Query should be 
Kids First Virtual Study

![Screen Shot 2019-03-21 at 11 31 29 AM](https://user-images.githubusercontent.com/18424138/54764423-26ee2c00-4bce-11e9-98a9-b3c736559615.png)
![Screen Shot 2019-03-21 at 11 33 33 AM](https://user-images.githubusercontent.com/18424138/54764424-26ee2c00-4bce-11e9-83df-66f33cb7d798.png)
![Screen Shot 2019-03-21 at 11 33 53 AM](https://user-images.githubusercontent.com/18424138/54764425-2786c280-4bce-11e9-913c-698cf2c0e0bb.png)

**Comment by rosibaj** [comment]
@hlminh2000 im not sure if we can distinguish between VS and File Repo - is this the case, or should we prep a blurb that fits all pages?

**Comment by kcullion** [comment]
Yes if we want a general blurb @rosibaj then maybe something more descriptive like: 

Kids First Data Resource Portal: sharing data to enable researchers, clinicians, and patients to collaborate and accelerate pediatric cancer and structural birth defects research"

**Comment by hlminh2000** [comment]
yes we can :)

**Comment by rosibaj** [comment]
Text has been updated: 

![Screen Shot 2019-03-26 at 11 23 40 AM](https://user-images.githubusercontent.com/15824252/55009875-a5294480-4fb9-11e9-9efb-de50f59e9c6b.png)
