### ISSUE TITLE
Summary Charts: Age at Diagnosis data bug

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1375]
I should be seeing data on the chart for some queries I've been making like:
Query:
![Screen Shot 2019-03-21 at 12 30 59 PM](https://user-images.githubusercontent.com/18424138/54768285-3cb31f80-4bd5-11e9-92a8-9e6b9cb97a05.png)
Corresponding chart:
![Screen Shot 2019-03-21 at 12 31 02 PM](https://user-images.githubusercontent.com/18424138/54768288-3d4bb600-4bd5-11e9-8e5b-0d78fd3aa0ce.png)

And for this query:
![Screen Shot 2019-03-21 at 12 32 07 PM](https://user-images.githubusercontent.com/18424138/54768350-5d7b7500-4bd5-11e9-9497-792cd75187d6.png)
Should the chart just be showing the participants where were diagnosed between 0 and 10 instead of (my query only actually has 8 participants):
![Screen Shot 2019-03-21 at 12 32 51 PM](https://user-images.githubusercontent.com/18424138/54768402-771cbc80-4bd5-11e9-885c-509b30b50e88.png)

Another example: 
For this query, it returns 24 participants:
![Screen Shot 2019-03-21 at 1 08 30 PM](https://user-images.githubusercontent.com/18424138/54770874-82beb200-4bda-11e9-9f2c-23958c5fd8ce.png)

Should the age at diagnosis graph just be plotting 24 participants here? It shows more participants here
![Screen Shot 2019-03-21 at 1 08 26 PM](https://user-images.githubusercontent.com/18424138/54770920-9702af00-4bda-11e9-8f26-7b28203a8ea9.png)

**Comment by hlminh2000** [comment]
issues with applying filter on `diagnoses.age_at_event_days` is addressed in https://github.com/kids-first/kf-portal-ui/issues/1418. Other issues remain to be investigated

**Comment by kcullion** [comment]
As per discussion with @hlminh2000  and @rosibaj - another case was found when filtering by Age at diagnosis. For example, filtering ages 2-5 years should not have any newborns in the graph (the participants don't have multiple diagnoses within the table)

**Comment by rosibaj** [comment]
Analysis:  
It seems that diagnoses are not being sorted into the correct historgram bucket
![image](https://user-images.githubusercontent.com/15824252/55029753-41b30d00-4fe1-11e9-97fe-1772e429c624.png)

Using this Study: https://kf-vr-portal.netlify.com/virtualStudies?id=ai with the filter for Diagnosis between the years of 2 and 5 in the TARGET study, there _should_ be 1 bar on the histogram but there are 2.  

Looking into the buckets, it looks like the correct day ranges are not being applied to the Age At Diagnosis histogram buckets: 
![Screen Shot 2019-03-26 at 4 10 36 PM](https://user-images.githubusercontent.com/15824252/55029967-b6864700-4fe1-11e9-84bd-cfa6b2157916.png)

**Comment by rosibaj** [comment]
Tested - The buckets are not correctly sorting the data.  Related features will be implemented in #1454
