### ISSUE TITLE
Summary Table: Remove from cohort is backwards

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1377]
Removing participants is backwards - the way the query and the table react. 

**QUERY BEHAVIOUR ISSUE:** 
- When a user selects participants to remove from the cohort, those ids should be removed from the table and be the reference within the query. 
- Currently it removes all other participants from the table.  For example:

![image](https://user-images.githubusercontent.com/15824252/54940653-90897580-4f01-11e9-91bc-33ace3276985.png)
![image](https://user-images.githubusercontent.com/15824252/54940749-bb73c980-4f01-11e9-9f05-9fd77b079f96.png)

**Comment by rosibaj** [comment]
tested - the counts are no longer backwards and the set is properly removed.  UI enhancements moved to #1431
