### ISSUE TITLE
Cohort builder: "and not" operator between queries

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1394]
As I user, I want to be able to search participants with criteria that I combine with the "and not" operator, so that I can exclude a set of participants with some criteria of my choice.

## Acceptance criteria
- In the cohort builder, in the "Combine queries" section, there should be a "and not" button.
- Clicking on it, with some queries selected creates a new query that combines the two queries with the "and not" operator in-between.
- Selecting the newly created query applies a search that combines the first query, minus the set of results in the second query.
- We currently don't mix operators, so the order of precedence will simply be: compute them from left to right.

## Mockups
When the user has not selected two queries, disabled the combinor button as it currently is: 
![image](https://user-images.githubusercontent.com/293677/57724723-7c3c3c00-7659-11e9-8841-234ba118a213.png)

Selecting two queries enables the combinor buttons:
![image](https://user-images.githubusercontent.com/293677/57724756-8e1ddf00-7659-11e9-914a-833dd0c7ccb0.png)

When the user clicks it, it creates a new query with the two selected queries combined with the "and not" operator:
![image](https://user-images.githubusercontent.com/293677/57724846-b0176180-7659-11e9-9595-be6d6bcd6d90.png)

When the user clicks on that combinor operator, there is a drop down menu with all the combinations:
![image](https://user-images.githubusercontent.com/293677/57724886-c7eee580-7659-11e9-8c17-693abbc628b9.png)

Of course, the user can now change a "and", or and "or" combiner into a "and not", and the other way around.

## Technical details
- To change the UI, edit the Advanced SQON Builder in Arranger components.

**Comment by aalex** [comment]
See also #1625

**Comment by nyanofthemoon** [comment]
https://arranger.readthedocs.io/en/latest/src/sqon.html

**Comment by aalex** [comment]
Both "not" and "and not" operators exist in SQON. (see link above) Will we use "and not"?
