### ISSUE TITLE
Query summary:  add tooltip

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1409]
It is actually very hard to read any query.

## Acceptance criterias
- Show a tooltip with the details about a query when you mouse over it.

## Details

- [ ] Also to help with the query preview, add a tooltip that allows the user to see the full query filter on hover before interacting with it. The query values selected should be shown as a pipe-delimited list in the tooltip. Example:
![Screen Shot 2019-03-25 at 10 05 17 AM](https://user-images.githubusercontent.com/18424138/54926358-8ad26680-4ee6-11e9-9f35-d626e35bdd12.png)

**Comment by aalex** [comment]
@aalex Need specs of the contents v/s how to view.

**Comment by jberube** [comment]
@aalex  What is the state of this state?

**Comment by nyanofthemoon** [comment]
@jaouad-benassila PR link pretty please?

**Comment by jaouad-benassila** [comment]
code review is done by Minh and PR is:
https://github.com/overture-stack/arranger/pull/513
