### ISSUE TITLE
Feedback menu overlaps with the social icons

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1410]
The feedback menu overlaps with the social icons.

When I browse on the Kids First DRP, there is a chat popup at the bottom-right of the page. There are also some social icons, there. (Facebook, Twitter, etc.) I should be able to see both, and click on both, but the feedback menu (the chat popup) overlaps with the social icons.

![screenshot_2019-03-22_17-37-49_feedback_overlaps_social_icons.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/b2100a27-518e-47a4-8594-39a75b803e2d)

(on Google Chrome 73.0 for Ubuntu GNU/Linux 18.04)

**Comment by rosibaj** [comment]
@bdolly @allisonheath Can you please inform Alex when we willk be removing usersnap?  If we remove usersnap then we will not need to action on this bug.
