### ISSUE TITLE
Style the Load Virtual Study Dropdown + change title

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1413]
Make the load virtual study button look like a button and update the virtual study title when you load one.

## Details
We want the "Load virtual study" to look like a button. When the user clicks it, it will show a dropdown menu that lists the saved virtual studies for this user. When the user 

## Acceptance criterias
- [x] Change the title that says "Explore Data" to "Virtual Study"
- [x] Style the Load dropdown more like the mockup so it’s larger and stands out more.
- [x] Make it look like a button.
- [x] Show its dropdown contents when the user clicks it.
- [x] Move that button to the right if the page - near the "Save as" button.
- [x] When the user chooses a Virtual study, load it.
- [x] When the user chooses a Virtual study, show a title with the virtual study name. (instead of the "Explore Data" in the mockup below)
- [x] The "Virtual Study" title will be grey when no study is loaded, and will change to blue with the title of the study when one is loaded.

## Mockup Link for Style
Zeplin: https://zpl.io/29OLvwp

Changes compared to this mockup: Note that:
- The "Virtual Study" title will either be invisible, or show the name of the loaded study.
- The "Load virtual study" button/menu will be aligned to the right, not the left.

## Wireframe

![IMG_20190410_121008.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/9aff8a86-1c65-4f78-962e-d49b81f150e2)

![screenshot_2019-04-09_16-07-25_load_a_VS.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/19b58e84-f28a-432e-a41b-833bedbe4188)

**Comment by nyanofthemoon** [comment]
@aalex PR https://github.com/kids-first/kf-portal-ui/pull/1573

**Comment by aalex** [comment]
Some details could be improved, but overall this looks good to me! (LGTM) I'll spend a bit more time on the QA for this, and potentially create some more backlog items, but overall, it seems much better than before! Good work!
