### ISSUE TITLE
Load Virtual Study: Clear link

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1414]
- [ ] A clear link appears beside the "Load a Virtual Study" dropdown to allow the user to start a new workspace (i.e. link to the blank cohort builder)
![Screen Shot 2019-03-25 at 1 38 55 PM](https://user-images.githubusercontent.com/18424138/54941496-5caf4f80-4f03-11e9-9e5b-1cba37f8a77b.png)

Zeplin: https://zpl.io/am5oqY6

**Comment by rosibaj** [comment]
Will be completed by #1335
