### ISSUE TITLE
Summary Charts: Data Availability table padding

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1423]
For the Data Availability table, instead of applying a negative margin to the cells, can we just change the padding from 
padding:10px; to
padding: 5px 10px

See the first row in this example to see how the new padding would look:
![Screen Shot 2019-03-25 at 2 38 56 PM](https://user-images.githubusercontent.com/18424138/54945404-114d6f00-4f0c-11e9-8498-3693fa131e61.png)

**Comment by jaouad-benassila** [comment]
I did the fix and I sent a PR to Minh

**Comment by rosibaj** [comment]
@kcullion  and I tested - Padding is looking better!
