### ISSUE TITLE
Update text on DCF integrations area 

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1425]
- [x] Add a text blurb below the `Data Repository Integrations` heading:

Text for integration area: 
> The Kids First DRC provides the ability to integrate across different data repositories for pediatric research. By connecting to each integration (powered by [Gen3](url)), you will immediately have the ability to analyze the data available from these repositories in Cavatica through this portal. Please remember that it is your responsibility to follow any data use limitations with controlled access data.

- [ ] Update text for KF integration: 
> Access all released Kids First controlled access data by connecting your account using your NIH login credentials.`

- [ ] Update text for DCF integration: 
>Access select NCI controlled access data by connecting your account using your NIH login credentials.`

**Comment by aalex** [comment]
We will do this in another issue:

 - [ ] Update DCF logo to white version - @rosibaj has the SVG for this

**Comment by aalex** [comment]
LGTM
