### ISSUE TITLE
BETA tag: for Explore Data menu item and title

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1439]
- [ ] Please  add a <sup>BETA</sup>  (superscript with html) with font-size:9px; to the Explore Data menu item.

So it should look like this:
Menu item off: 
![Screen Shot 2019-03-26 at 11 07 38 AM](https://user-images.githubusercontent.com/18424138/55008484-714d1f80-4fb7-11e9-80d6-7d76ed1d8840.png)

Menu item on:
![Screen Shot 2019-03-26 at 11 07 41 AM](https://user-images.githubusercontent.com/18424138/55008485-714d1f80-4fb7-11e9-8476-f5100501e5f9.png)

- [ ] Please  also add a <sup>BETA</sup>  (superscript with html) with font-size:13px; beside the Explore Data title.
Like:
![Screen Shot 2019-03-27 at 9 38 48 AM](https://user-images.githubusercontent.com/18424138/55080259-3fe65980-5074-11e9-9def-3860007d3c92.png)

**Comment by vferretti** [comment]
Need also this tag next to the cohort builder page's title

**Comment by kcullion** [comment]
thanks @vferretti I've added this to the description above
