### ISSUE TITLE
Participants table: select all but one

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1453]
As a user, I want to be able to select all but one item.

## Acceptance criteria
- The select all behaviour must be the same in the file repository as in the participant table.
- One must be able to select all, and then uncheck one selected item.

## Screenshots

![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/464288c4-145b-4531-a4b9-d2a088aa4f2d)

**Comment by jberube** [comment]
That was by design, since all pages are selected, to avoid confusion.

What would we do with the "Select all" checkbox if one is unselected?

**Comment by rosibaj** [comment]
@jberube Re discussions here (#1221) the behaviour _should_ be like this, but it was not implemented fully. 

Right now, it is very weird that there is a checkbox that looks like I can click it, but it cannot be clicked. 

As a user, I would like to select all, then remove just a few.  This is what I am thinking the expected behaviour should be: 
1. User checks the "select all" checkbox in the header, and all participants are selected
![Screen Shot 2019-03-27 at 10 39 10 AM](https://user-images.githubusercontent.com/15824252/55085168-935ca580-507c-11e9-86f6-3f2554c82a89.png)
2.  User un-checks the first check box
![image](https://user-images.githubusercontent.com/15824252/55085353-e171a900-507c-11e9-9dbb-fffe2a075f5a.png)

@vferretti @kcullion Let's discuss on slack!

**Comment by kcullion** [comment]
See gmail for an example of this - I thought we were going to try and mimic that

**Comment by rosibaj** [comment]
Decision with @vferretti  - Remove for AACR for now.  

@aalex For future, we should address both the file repo and cohort builder row selector  in the same manner.  

Ticket Reference #1096

**Comment by aalex** [comment]
@jberube is this a dupe?

**Comment by jberube** [comment]
@aalex No, my bad. The title needs to be changed. See the rest of the conversation and referenced issues for more details.

Probably need more investigation.

**Comment by aalex** [comment]
Question: In the cohort builder, we have removed the "Select all" button. Should we do the same in the file repo?
