### ISSUE TITLE
Age at Diagnosis Chart: only include the diagnoses filtered by the query terms

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1454]
## Acceptance criteria
- The "Age at Diagnosis" chart in the cohort builder should include only the diagnoses that remain after applying the search criteria in the active query.

## How to reproduce
1) add a query of age at diagnosis between 75 and 100 days.
 ![Screen Shot 2019-03-26 at 6.15.43 PM.png ](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/9e39c86f-1898-4971-9381-e82a0f8d3b2f)

2) Look at the age at diagnosis chart
![Screen Shot 2019-03-26 at 6.16.04 PM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/5b597374-bbfa-4b7c-b6e3-3e2c2027b543)

It looks funny that there is a participant in the category of 1-5 years, when the query filter is applied for age at diagnosis between 75 and 100 days.  However, what is happening here is that the participant has MULTIPLE diagnosis, in which one fits the criteria and one does not. 
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/e7d11c54-3f85-427a-a55f-1cbc5c05aaec)

**EXPECTED BEHAVIOUR:**
Only the diagnoses that apply to the query should be show in the Age at Diagnosis

**Comment by aalex** [comment]
Moving this issue aside, as discussed.
