### ISSUE TITLE
Summary Area: No data state for Summary Cards

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1455]
- [ ] Add the "No Data" state to cohort Builder summary cards (mockup below) for when a card has no data to render

![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/1c0fbcf9-b2d9-4d5d-98b2-2537e147abca)

See the mockup in zeplin: https://zpl.io/2G9P7mE

![Screen Shot 2019-03-27 at 9 25 20 AM](https://user-images.githubusercontent.com/18424138/55079329-5095d000-5072-11e9-9e6b-7f270c6f417e.png)

**Comment by denis-crsj** [comment]
Closing issue. Details transferred into Google Sheet : https://docs.google.com/spreadsheets/d/1U1JQZEBEMTP_07PngrmNh8rzbZICTX87Fe_2fEetAbI/edit#gid=0

**Comment by denis-crsj** [comment]
Moving to the Icebox
