### ISSUE TITLE
Query Area: Continuous filters: Add the operator into the query pill so it reads well

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1461]
Add the actual operator text that is selected to the query preview pill.
![Screen Shot 2019-03-27 at 11 43 18 AM](https://user-images.githubusercontent.com/18424138/55090991-7036f380-5086-11e9-9c94-1ca6e6f3a7d6.png)

Expected behaviour: 
If the user selects "greater than" the query will say:
![Screen Shot 2019-03-27 at 11 49 30 AM](https://user-images.githubusercontent.com/18424138/55090974-657c5e80-5086-11e9-8957-ffafd6b3a9e5.png)

Note; it works for "in between" 
![Screen Shot 2019-03-27 at 11 58 44 AM](https://user-images.githubusercontent.com/18424138/55091694-b3459680-5087-11e9-9b5d-b15c98f2b95e.png)

**Comment by rosibaj** [comment]
Tested - looks great @hlminh2000!  Operator is now appearing for all continuous operands in the variable pill!
