### ISSUE TITLE
Replace "d" with "day" in all "Age at event" type fields in the variable component

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#1462]
![Screenshot from 2019-03-27 13-23-23.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/4068e1df-f440-4cc9-864e-132d190103f7)

**Comment by jberube** [comment]
Will be done as part of #1464

**Comment by jberube** [comment]
PR: https://github.com/overture-stack/arranger/pull/506
