### ISSUE TITLE
Age type field: Do not convert values 

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#1464]
When i put in values, THEN change the unit, the numbers convert

Age values in the query  should not be converted when user changes age units. 

![image](https://user-images.githubusercontent.com/15824252/55164760-a174f980-5142-11e9-9f2c-c4ddee449d51.png)

**EXPECTED BEHAVIOUR:**
When the unit is changed, the originally types numbers do not change.

**Comment by jberube** [comment]
PR: https://github.com/overture-stack/arranger/pull/506
