### ISSUE TITLE
Cohort Builder: Make pie charts clickable in order to add a query term to the active query

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#1465]
As a user, I want to be able to click on a dashboard pie chart widget in order to add a new query in the cohort builder.

## Details
Like charts in the ICGC Advanced Search https://dcc.icgc.org/search 
When you click on them, a new term is added to the query and the entire page is refreshed.

## Acceptance criterias
- The four pie charts should be clickable (see the list below)
- Each of these clickable diagram should point to the cohort builder, with the right SQON query.
- the cursor must turn into a pointing hand when we mouse over it.

## List of the pie charts
- [ ] The "gender" pie chart should have its genders clickable
- [ ] the "Race" pie chart should have its races clickable
- [ ] the "Ethnicity" pie chart should have its ethnicities clickable
- [ ] the "Family composition" pie chart should have its compositions clickable

## Screenshot![screenshot_2019-04-02_14-19-59_dashboards_widgets.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/fbc48a91-96b6-4fd8-9ad0-d0d86283bb4d)

**Comment by aalex** [comment]
We want to think about which pie charts we are going to add.

**Comment by vferretti** [comment]
do the same for the two available data charts

**Comment by aalex** [comment]
(QA) LGTM.
