### ISSUE TITLE
Survival chart: reset zoom

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#1467]
As a user, when I zoom in on the survival chart, I cannot zoom out back to the original scale. I want to be able to click on a "Reset zoom" button in order to zoom back out in the chart 

## Acceptance criteria
- Add a "Reset zoom" button above the survival analysis chart. 
- The button should look like in the mockup above.
- The button should be located at the top-right of the widget, like in the screenshot below.
- When you mouse over it, change its background color to turquoise blue.
- Disable it unless you are zoomed. (initially, we are not zoomed in)
- Clicking on the "Reset zoom" button should reset the zoom.

## Mockup of the button itself
![image](https://user-images.githubusercontent.com/293677/56768888-9206c180-677d-11e9-8af4-00e1316f8845.png)

## Screenshot for its location
![image](https://user-images.githubusercontent.com/293677/56769157-5ddfd080-677e-11e9-85f0-cb0fb0786142.png)

## See also
See https://icgc.org/Z9B for correct display on another site.

## Zeplin
There is another reset button for Kids First is in this Zeplin mockup.  https://zpl.io/adpm38E (in order to copy its CSS)

## Technical details
- You can use a similar as the "Edit" in the "My Profile" section.

![image](https://user-images.githubusercontent.com/293677/58194841-9519a280-7c94-11e9-88a0-2fd091d6506e.png)

**Comment by rosibaj** [comment]
@vferretti this is a duplicate ticket

**Comment by jaouad-benassila** [comment]
- Change color for selected area from black color to `#edf8ff`
- Add text `Drag to zoom ` to top-right of the chart.
- Hide text when chart is zoomed, reproduce the same behavior that we see in [https://icgc.org/Z9B](url)

**Comment by aalex** [comment]
(QA) LGTM

![image](https://user-images.githubusercontent.com/293677/59457188-f3462b00-8de5-11e9-9591-aff7547ce695.png)

**Comment by aalex** [comment]
> * Change color for selected area from black color to `#edf8ff`
> * Add text `Drag to zoom ` to top-right of the chart.
> * Hide text when chart is zoomed, reproduce the same behavior that we see in [https://icgc.org/Z9B](url)

@jaouad-benassila Should we create a new ticket with those requirements in?

**Comment by jaouad-benassila** [comment]
those requirements were asked to me by Vincent and I added them to this component(chart) I mean the code is already implemented
