### ISSUE TITLE
Disable download actions for family if there is no family

### ISSUE THREAD

**Issue by phuongmy** [kids-first/kf-portal-ui#147]
When you perform a file search and there is 0 Families, please disable the following actions:
- Download Manifest (Participant and Family)
- Download Clinical (Family)

This action also applies to when you build a query and no additional family members are found (even though the query has families) 

On the disabled button, please add a tooltip "No additional data found" to indicate to user why the action is not available

Strategy >> calculate as a user initiated action when the download button is clicked.   The dropdown will load for a second and then show available options

**Comment by hlminh2000** [comment]
I was thinking we could split this issue into two, one for the Download Manifest (Participant and Family) and one for Download Clinical (Family). I held back from implementing the second one as there were words about some big interaction change :P. The first is addressed by https://github.com/kids-first/kf-portal-ui/pull/322 already so I'd like to move that to QC
