### ISSUE TITLE
Do not allow _missing_ value in search all 

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1470]
Some fields are showing `_missing_ as a value. 

We should not include the `_missing_` values in the search all
 
![image](https://user-images.githubusercontent.com/15824252/55104726-58b93400-50a1-11e9-963e-3c3214af38dd.png)

**Comment by denis-crsj** [comment]
Closing issue. Details transferred into Google Sheet : https://docs.google.com/spreadsheets/d/1U1JQZEBEMTP_07PngrmNh8rzbZICTX87Fe_2fEetAbI/edit#gid=0
