### ISSUE TITLE
Firefox is reverse sorting the Cohort Builder diagnosis card

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1471]
The age at diagnosis chart should be sorted descending, but in firefox only  it is sorting ascending 

Its working on the dashboard correctly as a reference. 

![image](https://user-images.githubusercontent.com/15824252/55105070-09bfce80-50a2-11e9-86ab-30bfed55dc90.png)

**Comment by aalex** [comment]
Confirmed, with: 
- Google Chrome Version 73.0.3683.75 (Official Build) (64-bit) on Ubuntu 18.04
- Firefox 66.0.1 (64-bit) on Ubuntu 18.04

**Comment by vferretti** [comment]
The Age at Diagnosis chart is also reversed.

**Comment by aalex** [comment]
Many charts are reversed:

![image](https://user-images.githubusercontent.com/293677/60604233-35c7ab80-9d85-11e9-8478-5bf6ec76f8ff.png)

**Comment by aalex** [comment]
(QA) It is fixed for the "Age at Diagnosis" and "Most Frequent Diagnoses (Mondo)" charts, but not for the "Available Data" chart.

![image](https://user-images.githubusercontent.com/293677/60686485-fda09580-9e76-11e9-8399-0d6ea1801465.png)

**Comment by aalex** [comment]
I've created another backlog item for the first chart - that was not part of this item. We can then consider this one done.

See #1886 for the other chart whose order we could change.
