### ISSUE TITLE
Main menu dropdown - Search + link to open dropdown = dropdown broken

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1473]
How to reproduce (this happens for any filter link from search): 
1. Search "dia".... in all filters
![Screen Shot 2019-03-27 at 3 42 29 PM](https://user-images.githubusercontent.com/18424138/55107141-f5320500-50a6-11e9-933d-902b9a36eb2f.png)
2. click on "Diagnosis" field name to open filter within menu
![Screen Shot 2019-03-27 at 3 43 09 PM](https://user-images.githubusercontent.com/18424138/55107176-0844d500-50a7-11e9-93a6-263e76796378.png)
3. Click cancel or back button from that clinical dropdown
4 The clinical menu item is still active and when I click on it it doesn't open and close the dropdown anymore
![Screen Shot 2019-03-27 at 3 44 04 PM](https://user-images.githubusercontent.com/18424138/55107241-34f8ec80-50a7-11e9-8eff-eb05a626f57b.png)

**Comment by aalex** [comment]
Confirmed on : 
- Google Chrome Version 73.0.3683.75 (Official Build) (64-bit) on Ubuntu 18.04

Doesn't happen on:
- Firefox 66.0.1 (64-bit) on Ubuntu 18.04

**Comment by kcullion** [comment]
@aalex I was seeing it happen on Firefox too

**Comment by rosibaj** [comment]
Tested on QA - the category button is correctly responding to the Cancel button now
