### ISSUE TITLE
Facet search in category bar should be case insensitive

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1474]
Facet search in category bar is NOT case in-sensitive 

- look at this field 
![image](https://user-images.githubusercontent.com/15824252/55107192-0ed34c80-50a7-11e9-93ef-3c34c4fb7939.png)

- search `solid` with a lowercase s.  There are no results 
![image](https://user-images.githubusercontent.com/15824252/55107207-1a267800-50a7-11e9-8f1a-349d7279a553.png)

**EXPECTED BEHAVIOUR** 
The search is case-insentsitive.  `solid` should match `Solid` in this search. 

NOTE: The search all and the search facet in the file repository are both case insensitive.  this is only happening in the category bar search

**Comment by nyanofthemoon** [comment]
@aalex   Issue is inside of overture-stack/arranger TermFilterUI component where we use a case sensitive array search method ```).filter(({ key }) => key.includes(s.state.searchString));```
we could probably change that to something similar to
```).filter(({ key }) => key.search(new RegExp(s.state.searchString, "i"));```

**Comment by nyanofthemoon** [comment]
@aalex @jberube @jaouad-benassila Pull request here: https://github.com/overture-stack/arranger/pull/510

We will need to update the @arranger/components version in package.json inside of the kf-portal-ui repository in order to see the changes

**Comment by vferretti** [comment]
LGTM
