### ISSUE TITLE
wrap text within cells (multiple lines)

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#1483]
![Screenshot from 2019-03-28 08-48-56.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/f22d11b9-7ba0-410a-94f5-abf6d38eda72)

Example: if the contents of the diagnosis cell is "subependymal giant cell astrocytoma", if the column is too narrow to show it all, instead of clipping the contents or added ellipsis ("..."), it should split the text in two or more lines.

**Comment by aalex** [comment]
I don't see the updated changes in the staging environment, yet.

**Comment by jaouad-benassila** [comment]
before we need to merge to next branch
