### ISSUE TITLE
Table: Selected Row Color

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1485]
- [ ] when selected, the row background colour should be light blue: #edf9fe (this can be a general style - so part of arranger)

<img width="897" alt="Screen Shot 2019-03-22 at 3 17 29 PM" src="https://user-images.githubusercontent.com/18424138/54847830-da7e1b80-4cb5-11e9-9cac-f785b51d6a17.png">

**Comment by aalex** [comment]
LGTM
