### ISSUE TITLE
Between operator not working with mulltiple age_at_diagnosis objects

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1488]
There are results that appear bogus when using the "between" operator:

For example:

![image](https://user-images.githubusercontent.com/15824252/55171150-3a5d4200-514e-11e9-85fb-68d473b1d736.png)

It seems that it returns any rows that contains "at lest one value greater than _min_, and at least one value smaller than _max_", instead of "at least one value that is both greater than _min_, and smaller than _max_" (edited)

**Comment by hlminh2000** [comment]
purely arranger back-end stuff. Fixed and updated for KF :)
