### ISSUE TITLE
Dashboard Study Cards cannot render null values in is_proband field

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1503]
Similar to #1318, the study card on the dashboard is not responsing 

![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/beab9c9f-b7c7-4a92-829c-4639723e11dc)

**EXPECTED BEHAVIOUR** 
- Family Members with Other Participants for studies card and Most Frequent Diagnoses card.
- If the field proband return null, I will count it in the total of the Other Participants category.
- tooltips should also be updated to match the "Other"

**Comment by jaouad-benassila** [comment]
Data displayed in horizontal bar of dashboard is retrieved from back-end by calling this URL:
https://public-stats-api.kids-first.io/v1/feb_05_2019/studies 
which return  a json:
{"studies":[{"id":"SD_PREASA7S","name":"Congenital Heart Defects","probands":716,"familyMembers":1432},{"id":"SD_9PYZAHHE","name":"Orofacial Cleft: European Ancestry","probands":404,"familyMembers":817},{"id":"SD_YGVA0E1C","name":"Ewing Sarcoma: Genetic Risk","probands":470,"familyMembers":698},{"id":"SD_BHJXBDQK","name":"Pediatric Brain Tumors: CBTTC","probands":990,"familyMembers":0},{"id":"SD_DZTB5HRR","name":"Syndromic Cranial Dysinnervation","probands":256,"familyMembers":593},{"id":"SD_46SK55A3","name":"Congenital Diaphragmatic Hernia","probands":194,"familyMembers":393},{"id":"SD_RM8AFW0R","name":"Adolescent Idiopathic Scoliosis","probands":67,"familyMembers":196},{"id":"SD_6FPYJQBR","name":"Disorders of Sex Development","probands":0,"familyMembers":0}]}
back-end should take care of participants in the is_proband field who have no value and return right data.
Problem is in the back-end

**Comment by hlminh2000** [comment]
great, thank you for the investigation @jaouad-benassila! I can take this
