### ISSUE TITLE
Token Refresh causes tokens to clear

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1511]
Token connections disappear.  Every time i use the portal i have to reconnect my tokens. 

Steps to reproduce
1: connect both dcf anf gen 3
2: wait 1/2 and hour for token to refresh
3: you will see these errors:

![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/a1c20098-9775-491b-b667-cf1a0c98882a)

`https://key-manager-qa.kidsfirstdrc.org/refresh?fence=gen3`

```
{exception: "ClassCastException",…}
error: "com.nimbusds.oauth2.sdk.TokenErrorResponse cannot be cast to com.nimbusds.oauth2.sdk.AccessTokenResponse"
exception: "ClassCastException"
stack: "com.nimbusds.oauth2.sdk.TokenResponse.toSuccessResponse: 45↵io.kidsfirst.fence.RefreshTokens.refreshTokens: 89↵io.kidsfirst.fence.RefreshTokens.processEvent: 45↵io.kidsfirst.keys.core.LambdaRequestHandler.handleRequest: 26↵sun.reflect.NativeMethodAccessorImpl.invoke0: -2↵sun.reflect.NativeMethodAccessorImpl.invoke: 62↵sun.reflect.DelegatingMethodAccessorImpl.invoke: 43↵java.lang.reflect.Method.invoke: 498↵lambdainternal.EventHandlerLoader$PojoMethodRequestHandler.handleRequest: 259↵lambdainternal.EventHandlerLoader$PojoHandlerAsStreamHandler.handleRequest: 178↵lambdainternal.EventHandlerLoader$2.call: 888↵lambdainternal.AWSLambda.startRuntime: 293↵lambdainternal.AWSLambda.<clinit>: 64↵java.lang.Class.forName0: -2↵java.lang.Class.forName: 348↵lambdainternal.LambdaRTEntry.main: 114↵"
```

**Comment by joneubank** [comment]
24 Hours after applying fix, refresh still functioning as expected. Not logging out. Reccommend closing unless your testing finds a contrary case.

**Comment by rosibaj** [comment]
@joneubank im still testing - i _thought_ i saw a not refresh but im waiting again to be sure

**Comment by rosibaj** [comment]
tested - tokens refreshed over a few hours open, and after login the next day
