### ISSUE TITLE
Resources Menu is underneath columns selector on File Repository:

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1520]
Resources Menu is underneath columns selector on File Repository:

<img width="682" alt="Screen Shot 2019-03-29 at 10 10 40 PM" src="https://user-images.githubusercontent.com/15824252/55269982-f19daa00-526f-11e9-84ac-d0f9f1ddc2d3.png">

**Comment by nyanofthemoon** [comment]
@aalex Seems already fixed on dev branch. Moving to QA.

**Comment by aalex** [comment]
Fixed as part of #1865 - Closing this one as a duplicate.
