### ISSUE TITLE
Wrong number of participant for a query?

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1522]
There appears to be an issue with the two filters here: 

![image](https://user-images.githubusercontent.com/15824252/55270054-b64fab00-5270-11e9-8e9b-12ec299562bc.png)

When i select the filter Tissue Type `is all of` Tumor, Normal, the participant, file, and file breakdown cards don't quite make sense/match. 

![image](https://user-images.githubusercontent.com/15824252/55270096-53aadf00-5271-11e9-9a4b-b7b998177dd7.png)

@aalex, I think you will want to discuss this with Vincent to make sure of the behaviour.  It will need a backend strategy to make sure the queries cross-filter correctly between the file_centric and participant-centric indices

**Comment by aalex** [comment]
I think this issue has been resolved, and this item is now a duplicate. I must verify this.
