### ISSUE TITLE
Inconsistent number of files

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#1526]
Look at https://portal.kidsfirstdrc.org/explore?id=1wf
Available data file card reports 0 files while the summary above reports more than 4000
![file.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/7aca40bc-3ac8-4ef6-9030-cf404ca478a7)

**Comment by jberube** [comment]
As I understand it at the moment, it is _strange_ but _expected_ (voluntary might be a better word).

The number of files in the header of the results is the total number of files for the 277 participants combined, who have at least one file with the data type gVCF. Those 4665 files are not all gVCF. That's one thing.

Another is that those 277 participants have both a file of data type gVCF and an Experiment Strategy of the correct value, but not necessarily a combination of both that are related.

To this point I am uncertain of what the incoherence is, though I see that there is surely an incoherence! I'm not sure of what the result should have been, or which result is the one that is not good.

**Comment by jberube** [comment]
@nyanofthemoon I'd really could use your opinion on that one.

**Comment by jberube** [comment]
That query might be more suited:
![image](https://user-images.githubusercontent.com/373603/55743737-17117d00-5a01-11e9-9515-2499333a608b.png)

**Comment by jberube** [comment]
After conversation with @vferretti, the card is going to be replaced. New card TBD.

**Comment by vferretti** [comment]
If we removed temporarily the column Experimental Strategy, would it solve the issue?

**Comment by jberube** [comment]
That would not be a quick fix. Removing the column is, but the data would
remain inconsistent.

I would rather do a new card with the breakdown of data types for the
current cohort than trying to modify the existing one.

**Comment by vferretti** [comment]
@jberube would it be easier if we returned the number of PARTICIPANTS per data type and per experimental strategy (separately) rather than the number of files. 
The entire page is about number of participants.

**Comment by jberube** [comment]
I think it make more sense and might be easier.

**Comment by vferretti** [comment]
ok, I'll give you more spec by the end of the day

**Comment by jberube** [comment]
I see that the table now displays results with "No Data" Experimental Strategy, which is new.

Have they fixed a bug in the ETL that could have fixed that?

**Comment by aalex** [comment]
Implementing #1591 will make this one obsolete.
