### ISSUE TITLE
Changing the value of a logical operator changes all the others in a query

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#1527]
Changing one logical operator changes all of them.

## How to reproduce
Create a query with multiple terms and with the logical operator "AND" between them.
Change the first AND by an OR
You can see that all the other AND have been switched to OR. 

## Expected behavior
Only the one that the user changes should change

## Acceptance criterias
- At this point, the operators will be calculated from left to right.

## Technical notes
- We might need to investigate how it is implemented in SQON. The logic might be different at some different places.

**Comment by aalex** [comment]
Note: implementing parentheses will help to make this feature more useful. (combining AND and OR operators)

**Comment by vferretti** [comment]
No parentheses for now. Just make sure that only one operator is changed at the time. Parentheses will be eventually a new feature to implement

**Comment by nyanofthemoon** [comment]
@aalex @vferretti Do we care about the order of operations defined in PEMDAS?

**Comment by aalex** [comment]
I would say that yes - AND over OR.

**Comment by aalex** [comment]
@nyanofthemoon @hlminh2000  Can we do a simple change to SQON so that AND has a precedence on OR, so that mixing up these operators in a query would work?

**Comment by nyanofthemoon** [comment]
@aalex Currently not supporting "multiple" operations within the same query- we can address this issue once we refactor the SQON Builder~
