### ISSUE TITLE
Save a virtual study: both save and save as

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1533]
As a user, I want to be able to do save a virtual study as a new one.

## Acceptance criterias
- [x] Each user can only save their own studies. (that will need to be done in the backend using the UUID of the user)
- [x] Disable buttons when it's not our's: delete, share, save. ("save as" is possible, though) Check the ownership in the frontend. (it will also be checked in the backend)
- [x] "Save as" must be as the right of "Save"
- [x] Use the fa-save icon (font awesome "save")
- [x] Save: will update in the existing virtual study if it's mine.
- [x] When you click Save, keep the current behaviour.
- [x] If it already exists, clicking "Save" will update the current study with the current state of the queries. Updating its title won't be possible, for now.
- [x] Use the tooltip text listed below.
- [ ] when there are unsaved changes, should a star (*) and "You have unsaved changes" like in the mockup below.
- [x] disable the save button if no changes have been made.

## Tooltip text
- Save - Saves the current virtual study if it exists, or a new one if not.
- Save as - Saves the current virtual study as a new one.

## Wireframe
Version with the buttons:
![save_as_button](https://user-images.githubusercontent.com/293677/56687935-63b5b300-66a5-11e9-8d7e-843715ceb61f.png)

## Mockup
![image](https://user-images.githubusercontent.com/293677/57714292-34f68100-7642-11e9-8be5-4fb3ef23c292.png)

**Comment by vferretti** [comment]
Each supported action (Save, Edit, etc) requires more precise specifications

**Comment by aalex** [comment]
@jberube Do we already have the endpoints for delete and save as?

**Comment by jberube** [comment]
Not as far as I know. I'll check.

**Comment by jberube** [comment]
Virtual Studies are stored in the Persona API. I don't see a reason for having backend changes, because everything is done in the front-end... which might not be a good idea. We might want to have some more robust architecture, but that may be another subject.

What does "Closing" a virtual study do?

I also need to know the behavior of "edit" and "delete", since we're working shared data, here.

**Comment by jecos** [comment]
Riff has been modified. A pull request is opened in overstack repo https://github.com/overture-stack/riff/pull/21

**Comment by aalex** [comment]
(QA) LGTM, except some bugs that should be verified, and then probably triaged.
