### ISSUE TITLE
Pushing a file to Cavatica doesn't work

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1534]
# Update Model/ETL/Push to Cavatica with `Cavatica_ID`

The "Push to Cavatica" is not working for the DCF repository. The reason is as follows:
```
In order to resolve target files in `"dataset": "sevenbridges/target"` you need to use GDC UUID
```

In the original specifications provided, there was a miscommunication about the correct id to use.  Currently, we are using the `file.latest_did` with the Cavatica id resolver endpoint, which is resulting in no ids being passed to Cavatica. 

For reference on the original specs provided by Cavatica, you can see these slack conversations, and the other tickets linked in this Epic. 

https://kidsfirst-team.slack.com/archives/CESP7UTDX/p1547650977012400?thread_ts=1547646636.009500&cid=CESP7UTDX
https://kidsfirst-team.slack.com/archives/CESP7UTDX/p1549373971052900

As a `quick-fox-solution` Allisons team has updated the `latest_did` on DCF files so that this push works for now (https://github.com/kids-first/kf-study-imports/issues/517) . This is not a permanent solution.  As a permanent solution to this issue, I am proposing abstracting the cavatica id to a new field in the model with the business logic calculated by the ETL. 

Doing this would involve this work: 

- [ ] Add a new field to the data model called `cavatica_id` 
- [ ] The ETL should populate this field with the correct id to pass to cavatica. 
-- For files from the `gen3` repository, this field should be a copy of `latest_did` field 
-- For file from the `dcf` repository, this field should be the value that is stored in `gdc_uuid`.  This field does not exist in the model today, but we will be asking @allisonheath to add it.
- [ ] Refactor the front-end UI to pass the new `cavatica_id` field instead of `latest_did` when formatting the Cavatica URL resolver endpoint

**Comment by fiendish** [comment]
> Allisons team has updated the latest_did on DCF files so that this push works for now

We updated the external_id field from the full url to just the uid. It sounds like that may not work for you though.

**Comment by rosibaj** [comment]
@fiendish that is correct for the fix you did to external id.  For future fields, we will need to parse that external id that is provided now.

**Comment by rosibaj** [comment]
thanks @fiendish for the heads up.

**Comment by jecos** [comment]
ETL override field latest_did with externalId if the repository is DCF
