### ISSUE TITLE
Improve performances: implement a central state manager and its debugging tools

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1537]
As a user, I want a faster Web site.

As a developer, a central state manager would make my work easier and faster to do. I will have more fun developing.

## Acceptance criterias
- Implement a central state manager.
- Implement its degugging tools suite.

## Technical details
(copy-pasted from #1555 ) The idea is to put that data directly in the props from react-redux's mapStateToProps function.

**Comment by bdolly** [comment]
👏, I'm 💯 behind this effort. 

@aalex let me know if there's anyway I can contribute

**Comment by aalex** [comment]
Done as part of #1533
