### ISSUE TITLE
UI touch-up before demo

### ISSUE THREAD

**Issue by phuongmy** [kids-first/kf-portal-ui#154]
- [x] 1: In File Repo, please rename to "Actions" instead of "File Actions" and remove the "?"
- [x] 2: In User profile - Integrations, make the buttons "Connect" the same size
- [x] 3: Once My dashboard with view my saved sets is completed and merged, change user workflow so that when the user logs in (not for the first time, he's a known user with an existing account) then he's redirected to the dashboard, not the File Repository
- [x] 4: Allison wants us to change the sentence in the Gen3 connection setting. See her proposal 
let's go with ```Access controlled data by connecting your NIH Login and dbGaP authorized access to the Kids First Data Catalog powered by Gen3. ```

<img width="1195" alt="screen shot 2018-03-09 at 4 08 41 pm" src="https://user-images.githubusercontent.com/8812383/37230859-d5d00bb2-23b6-11e8-92ea-2bfb5db80a4c.png">
<img width="1224" alt="screen shot 2018-03-09 at 4 09 06 pm" src="https://user-images.githubusercontent.com/8812383/37230893-fb060940-23b6-11e8-9909-d5eddf5169af.png">
![Uploading Screen Shot 2018-03-09 at 4.09.06 PM.png…]()

**Comment by cy** [comment]
for redirect to dash https://github.com/kids-first/kf-portal-ui/pull/195
