### ISSUE TITLE
Improve performance and security: modernize the build system

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1540]
As a user, I want a faster Web site.

As a user, I want a more secure Web site, that is less likely to be attacked by crackers.

As a developer, I want to develop with some libraries that are up-to-date.

## Acceptance criterias
- Move from the create-react-app boilerplate version 1 to 2
- Upgrade the stack of dependencies (NPM modules)
- Upgrade from Webpack 2 to the latest version
- Create more tickets once enough effort has been done

## Technical notes
It should decrease the memory use on the client side.

It will help developers to view the stack of function calls in a cleaner way.

We will be able to identify some security issues with npm audit.

**Comment by bdolly** [comment]
👏, I'm 💯 behind this effort. 

@aalex let me know if there's anyway I can contribute

**Comment by aalex** [comment]
LGTM
