### ISSUE TITLE
Improve development: Implement unit tests

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1542]
As a developer, I need unit tests so that I can see if my code works as expected.

1-day spike to investigate, and then we will evaluate again.

## Acceptance criteria
- [x] Implement a unit testing system.
- [ ] Create unit tests for most of the code base.
- [ ] Document and report what has not been covered.

## Technical notes
- We could consider removing Storybook, the development environment for UI components.

**Comment by bdolly** [comment]
👏, I'm behind this effort. 

@aalex let me know if there's anyway I can contribute

**Comment by jberube** [comment]
EDIT: added check boxes to the _Acceptance criteria_ to indicate what is already done.
