### ISSUE TITLE
Cohort builder: add more fields

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1547]
Some fields are missing in the cohort builder. We need to add them.

List of their titles:
- Phenotype (source text)
- Diagnosis (source text)

## Acceptance criteria
- Add the two filters listed above in the cohort builder.
- Put the fields in aphabetical order of the text of the label.

## Technical details
The ElasticSearch fields are:
- Phenotype (source text) `phenotype.source_text_phenotype`  (within the `clinical` category)
- Diagnosis (source text) `diagnoses.source_text_diagnosis` (within the `clinical` category)

**Comment by allisonheath** [comment]
We want to still include all of the "Source Text" fields for now - these are important for those with familiarity of the studies to be able to use. From the File Repository these are the fields:
- Diagnosis (Source Text)
- Tumor Location (Source Text)
- Anatomical Site (Source Text)
- Tissue Type (Source Text)
- Tumor Descriptor (Source Text)
- Phenotype (Source Text)

**Comment by rosibaj** [comment]
Four of these fields are already included. The only two not included are:
- Phenotype (Source Text)
- Diagnosis (Source Text)

@vferretti requested that the (Source Text) be removed from the display names of these fields.  That can be added back easily in the arranger admin by @aalex if required. 
![image](https://user-images.githubusercontent.com/15824252/56614188-74532400-65e6-11e9-9164-9bc4c716b678.png)

**Comment by aalex** [comment]
(QA)

It seems like the changes done are not exactly what we need. Here is what fix:

- Rename the filter "Source Text Diagnosis" to "Diagnosis (Source Text)"
- Rename the filter "Phenotype Source Text Phenotype" to "Phenotype (Source Text)"

![image](https://user-images.githubusercontent.com/293677/57101070-7310ae00-6cee-11e9-8429-95875162ed88.png)
