### ISSUE TITLE
Select All should select only filtered values

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#1551]
Open the Diagnosis men,  type "glio" and Apply filter.

in the query, you can see that all the diagnoses were selected and not only the "glio" ones.
![select.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/1307a990-265a-43dc-bb57-cb8b4fe29958)

**Comment by jberube** [comment]
https://github.com/overture-stack/arranger/pull/512

**Comment by vferretti** [comment]
LGTM

**Comment by aalex** [comment]
LGTM
