### ISSUE TITLE
Query terms added from the search filter box should be added as a last operand (their order is wrong)

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#1552]
As a user, I want the terms in the query to be in the order I've added them.

## Acceptance criteria
- Each newly created filter / search term must be added at the end of the query, including those created via the search box.

## Details
create the following using the menu. 
![query.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/e63dbbe5-b903-4847-9fbe-f7b28610faa6)

Type "vent" in the search filter box and select "ventricular septal defect (disease)"

The query term is added in second position rather than at the end. 

![query2.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/e7ebe3aa-8c45-4f15-823b-a429b82f44f8)

**Comment by aalex** [comment]
It seems like diagnosis always goes second? To be confirmed.

**Comment by nyanofthemoon** [comment]
@aalex The logic for "placing" new sqons is different between category filters (placed at the end) and the "Search all filters" (placed based on the order of that specific filter type).

Do we wish to rewrite this logic? Might take a while...

![why.png](https://images.zenhubusercontent.com/5c05950b0a4f964ea1a04049/d0449f6b-f735-458a-b101-645d12880902)

**Comment by vferretti** [comment]
New criteria should be always added to the end of the active query regardless of the method used

**Comment by aalex** [comment]
@nyanofthemoon If I understand well, we should make sure that the "Search all filters" places them at the end, yes.
