### ISSUE TITLE
Front-end central cache for queries resolvers and friends

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1555]
As a developer, I need a way to store the state of my application and control it. See below for a list of benefits.

# Intent
That feature is intended to palliate to some characteristics of the current architecture:
- difficulty in sharing data between the application components / features
- lots of queries sent by visual components, a lot of the time for the exact same data (or a subset of it)
- difficulty in communicating in between components (eventing / messaging)

# Benefits
This feature will allow:
- reuse of data across different components
  - bonus : simultaneous update of most components, rather than having each one having to wait for it's query to resolve, resulting in slightly more pleasant experience
- central caching, further reducing the queries as well as the memory footprint. Some expiration mechanism should be considered on this cache.

# Limitations
Some components have their very own queries and logic. To avoid having to rewrite a part of them, we should provide a wrapper to "feed" them their data in the same way that the `QueriesResolver` does it, so the change is transparent from the point of view of the component.

Some components nest queries. When a nested query needs the value of a parent query, the usefulness of this feature falls short. We should replace the top-most query, but only that one. We can address thos components with patterns such as "sagas" if it is worth it.

# Technical details
One proposed solution is to add `redux` to the mix in the most standard way.

Most components use one or more queries, each made from gql query, a sqon, optional variables and optional transforms. Past the QueriesResolver (or other mean of doing the request), the data is just a pojo. The idea is to put that data directly in the props from `react-redux`'s `mapStateToProps` function. The query should be run separately, only when need be.

Another solution is to avoid using redux to store those info. Use the same cache for all instances of query resolver components. Also store the query before sending it instead of when we get the result. (quick win) (the query is the key and the value are the results)

Let's do the second option.

**Comment by jberube** [comment]
Changes made by Minh render this task obsolete, as it already complies with the second option discussed earlier.
