### ISSUE TITLE
Refactor a centralized and consistent SQON Builder

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1556]
As a developer, I need a centralized and consistent way to build and manipulate SQON search queries accross the application.

## Acceptance criterias
- Be able to build a SQON query.
- Be able to modify it.

## Technical details
Builder to allow managing queries in a consistent way
  - allow manipulating queries easily and in a consistent way.
  - ability to add the OR operator

**Comment by aalex** [comment]
@jberube Please update with any relevant information.

**Comment by nyanofthemoon** [comment]
The process for "building" SQONs on the front-end are dissimilar between different pages and located in different repositories. However, code for building queries itself is already existent. It is my opinion that it is too early / not enough knowledge to properly refactor this part of the app at this point in time.
