### ISSUE TITLE
File type filter: Replace __missing__ by "No Data"

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1558]
In the cohort builder, in the "Available Data Types" search filter, if we select "No Data", the filter shows "_ _ missing _ _", but it should be "No Data".

![screenshot_2019-04-09_14-57-20_check_no_data](https://user-images.githubusercontent.com/293677/55827321-e94b3780-5ad7-11e9-873e-847d1a9089a6.png)
![screenshot_2019-04-09_14-57-50__missing__](https://user-images.githubusercontent.com/293677/55827322-e94b3780-5ad7-11e9-9062-e874fdd02fbe.png)

**Comment by aalex** [comment]
@nyanofthemoon We should remove this item from next week's release?

**Comment by aalex** [comment]
Duplicate of #1561

**Comment by aalex** [comment]
@jecos Can you confirm that the files with no data have null as value for that field? Or is it an empty array? In any of thoses cases, it means it's on Arranger's side that we need to fix it.

**Comment by jecos** [comment]
It's an empty array.
