### ISSUE TITLE
In theory, we should not have files without a data type

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1561]
In prod, in the cohort builder if we search for participants who have files with no data type, there are 2376 participants who match that criteria, but there should probably be none, according to the data in the CHOP DB. There might a mismatch in the ETL, or in the UI.

## Acceptance criteria
- [ ] identify the problem
- [ ] report it

![screenshot_2019-04-09_14-57-20_check_no_data](https://user-images.githubusercontent.com/293677/55828183-d5083a00-5ad9-11e9-8ebb-c30c4809048d.png)
![screenshot_2019-04-09_15-08-55_2067_files_without_data_type](https://user-images.githubusercontent.com/293677/55828185-d5083a00-5ad9-11e9-9836-b67487987410.png)

**Comment by aalex** [comment]
@vferretti Is this description accurate?

**Comment by vferretti** [comment]
@joneubank do you think it is an ETL problem?

**Comment by jberube** [comment]
Could this be related to #1526 ?

**Comment by jecos** [comment]
For information,there is exactly 2345 missing data types, that match exactly the 2345 participants. So something generate a missing data type for each participant.

**Comment by rosibaj** [comment]
@aalex @jecos @vferretti 

I did an analysis on this: 

1) I looked up this query in the cohort builder.  I see that there is "No Data" in the Available Data Types.  
2) I looked up the document on the prod Kibana of one of the participants that matched this using this ES search: 
```GET participant_centric/participant_centric/_search
{
  "query": {
    "term" : { "_id" : "PT_MZ7CWED4" } 
  }
}
```

As a result from that, i can see in the index document that this is the field confifuration for `available_data_types`: 

```          
available_data_types": [],
```

From this, it is clear that the ETL is NOT populating the available data types field. 
3) Looking at this participant, it looks like they have a total of 1 file object, with the `data_type = Aligned Reads`.  This participant _should_ have this populated:
```          
available_data_types": ["Aligned Reads"],
```

4) Looking at the pattern of these participants with _missing_, it looks like records with `participant.family.family_composition = proband-only` have this issue.  

[ ] Verify that the records with `proband-only` are the issues.  @rosibaj does not know how to do nested queries on ES, so needs some help validating this assumption. 
[ ] Check that the ETL is assigning Available Data Types for these types of records if this is the issue.
[ ] Re-run ETL on studies to correct data issue

**Comment by jecos** [comment]
@rosibaj I have also found some "No Data" with 1 file for trio :

![Screenshot from 2019-04-15 12-02-15](https://user-images.githubusercontent.com/1424506/56147525-78dc6480-5f76-11e9-83b8-e3a10029c222.png)

But the pull request should also fixed theses cases.

**Comment by vferretti** [comment]
LGTM
