### ISSUE TITLE
Cohort builder: delete a virtual study

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1563]
As a user, I want to be able to delete a virtual study so that my workspace is not cluttered.

## Acceptance criterias
- [x] Add a "Delete" button. (we decided that it's going to be a button, for now, not a menu)
- [x] Clicking that Delete button shows a confirm dialog and deletes the last loaded virtual study if the user confirms.
- [x] The confirm dialog contains the items details below. The deletion happens only if the user clicks the "Yes, {...}" button.

## Contents of the confirm dialog
- title: Do you really want to delete your virtual study "{name}"?
- text: Deleting a virtual study is permanent. Do you really want to delete it?
- buttons: 
  - YES, delete this virtual study
  - CANCEL

The "CANCEL" button is primary, and the other is secondary.

Replace {name} by the title of the virtual study to be deleted.

## Technical details
Virtual Studies are saved in Riff and a list of them is kept in Persona for the user. So to delete a saved study two operations need to be taken:

- Front end calls riff to delete
- Front end calls persona to update the saved studies field. You need to send the WHOLE LIST of studies with the deleted one removed.

**Comment by nyanofthemoon** [comment]
@aalex Possibly already implemented in RIFF here:
**https://github.com/overture-stack/riff/blob/develop/src/main/java/bio/overture/riff/controller/RiffController.java**

**Comment by nyanofthemoon** [comment]
https://github.com/kids-first/kf-portal-ui/pull/1573

**Comment by aalex** [comment]
Good work!

**Comment by aalex** [comment]
The QA observations for the upcoming release is in the wiki. https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/952696833/QA+for+release+KF+2019-Q2+A

I think we can close this issue and open other items as needed.
