### ISSUE TITLE
Some values in the exported tables are duplicate

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1565]
When I export a table, some fields have multiple values, and that is fine, but for some rows, the values are identical. This can also be fine if, some values are different in one of the items in another field in the same row. The problem is that it seems like some rows have multiple-value fields for which all their values are duplicate, and none has some different values.

**Comment by joneubank** [comment]
Virtual Studies are saved in Riff and a list of them is kept in Persona for the user.

So to delete a saved study two operations need to be taken: 
* Front end calls riff to delete
* Front end calls persona to update the saved studies field. You need to send the WHOLE LIST of studies with the deleted one removed.

**Comment by joneubank** [comment]
All of the endpoints for those operations already exist. All development for this should be contained to the ui.

**Comment by aalex** [comment]
Thank @joneubank - I've renamed this story, so your comments no longer match the contents of the issue, but they were quite relevant and useful when they were made.

**Comment by aalex** [comment]
I'll update this issue with some sample data. It might not be a bug, but I think it probably is one.
