### ISSUE TITLE
Table: Show "+ N more" when there are multiple values in a cell

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#1570]
There are cases where a file has multiple types or a participant has multiple diagnoses. This creates problems in the way we display rows in both the file and participant tables respectively.

- when there are multiple values in a cell, do the following
     - [ ] if there is more than one distinct value, display the first one, with a plus sign
     - [ ] No need for tooltips
     - [ ] If one clicks on the plus (+) sign, unfold and show the full contents of the cell.
     - [ ] Show bullet points in front of each element when there is more than one.

## List of potentially problematic fields

File table:
- [ ] Participant ID
- [ ] Study Name
- [ ] Proband
- [ ] Family ID
- [ ] Participant External ID
- [ ] Aliquot External ID
- [ ] Sample External ID
- [ ] Biospecimen ID
- [ ] Tissue Type (Source Text)
- [ ] Diagnosis (Source Text)
- [ ] Study ID

Participant Table:
- [ ] Diagnosis Category
- [ ] Diagnosis
- [ ] Age at Diagnosis (days)

## Screenshot of those lists
File Table
![problemFields.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/7ed04a85-4a01-426e-9aa8-3e70ce4df3fe)

Participant table
![participan.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/af1926d0-952a-4b09-96eb-2988d60ecf2d)

**Comment by aalex** [comment]
I've split the changes to the format of the exported tables into another issue.

**Comment by aalex** [comment]
@jaouad-benassila We should move this one to "In Progress", I think, since you are progressing on it.

**Comment by nyanofthemoon** [comment]
@jaouad Ok for your pull request https://github.com/kids-first/kf-portal-ui/pull/1577 - please just fix the merge conflicts before you squash and merge! :smile:
