### ISSUE TITLE
Tables: Disable sorting on multiple-value columns in the participants table

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1572]
There are cases where a file has multiple types or a participant has multiple diagnoses. This creates problems in the way we sort rows in both the file and participant tables.

It seems like it has been decided that we remove the sorting feature on those columns.

## Acceptance criterias
- [ ] Remove sorting on the columns listed above.

## List of potentially problematic fields

Participant Table:
- [ ] Diagnosis Category
- [ ] Diagnosis
- [ ] Age at Diagnosis (days)

(the file table columns were moved to another issue)

## See also
- #1571 
- #1570

**Comment by aalex** [comment]
@jberube Do you think the best way to solve the sorting issues on multiple-value fields is to remove the feature altogether? It seems like this is what @vferretti decided yesterday. It must probably be easy to remove such a feature, isn't it? (and probably easy to do that in a single commit, so that rolling it back is easy, if the stakeholders change their minds later)

**Comment by jberube** [comment]
Yes, it's easy.

It's in the configuration object of the columns. The first and last columns
are not sortable, they are good examples.

**Comment by jberube** [comment]
I'm confused: why should we remove the sorting of _any_ of the columns in the File Repo Table?

All those fields should only have on e possible value, right?

**Comment by vferretti** [comment]
you can have multiple participants per file and then you will multiple values in one cell

**Comment by aalex** [comment]
LGTM for the participant table.

For the files table, they seem to be still sortable.

**Comment by aalex** [comment]
The changes to the files table have been moved to another issue.
