### ISSUE TITLE
Show only one item when they are all the same

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1575]
There are cases where a file has multiple types or a participant has multiple diagnoses. This creates problems in the way we display rows in both the file and participant tables respectively.

## Steps to reproduce
In the participant table, some fields have the same value more than once, for example "Cancer Cancer Cancer" - maybe the participant has been diagnosed three times with the same disease.

Instead, we would like to see that value only once: "Cancer".

If not all values are different, no change is required. We will still show them all.

## Acceptance criterias
- [ ] if this value is unique, display it only once

## See also
- #1570

**Comment by jberube** [comment]
This was done this way to ensure that data related to the same diagnosis are aligned.
E.g. One participant can have 2 diagnoses of the same diagnosis category, and then a third one of a different category.
```
Cat1   Diag1   <- related
Cat1   Diag2   <- related
Cat2   Diag3   <- related
```
That fix creates that issue:

```
Cat1   Diag1   <- related
Cat2   Diag2   <- unrelated
----   Diag3   <- orphan 
```

**Comment by aalex** [comment]
If two are the same, but only one is different, show them all. (important)

Show only one item **only if** all of them are the same. (and show only one item in the first position)

**Comment by aalex** [comment]
Is this still blocked?

**Comment by nyanofthemoon** [comment]
@jaouad-benassila Ok for your pull request https://github.com/kids-first/kf-portal-ui/pull/1577 - please just fix the merge conflicts before you squash and merge!
