### ISSUE TITLE
Range (continuous) filters: should not need to click beside the number boxes in order to apply it

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1576]
In the range filters, one should not need to click outside of the text fields in order to enable the Apply button.

## To reproduce (method 1)
- In https://kf-qa-portal.netlify.com/explore
- create a range filter, (so-called continuous filter) such as the age at sample acquisition
- fill in the from number box
- fill in the to number box

We should be able to click on the Apply button.

Instead, we must click outside of the number box in order to enable it. Users should be able to click the apply button as soon as both number fields are filled up.

See #1438

![continuous_68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563353531343765396563333933356331363636303636362f63393037636336322d373833652d343632372d386432332d613835633131323735356334.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/f7fe4df9-d9de-49a1-832a-eea42d7c4d1e)

## To repreoduce (method 2)
Here is another (?) way to reproduce it:

- Fill in a number in the From number field
- Fill in a number in the To number field
- Click outside
- Click on the Years radio button

The button should be activated, but is not.

**Comment by nyanofthemoon** [comment]
@aalex https://github.com/kids-first/kf-portal-ui/pull/1592

**Comment by aalex** [comment]
LGTM
