### ISSUE TITLE
Save/delete a virtual study: minor changes

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1580]
We can now delete a saved virtual study. Here is a list of small changes that have been identified during Q&A.

## Acceptance criterias

- [x] When no study exists, or when there is only one but you are already in it, make open button disabled
- [x] When no study exists, make new button disabled
- [x] Rename "clone" to "save as"
- [x] In the save dialog, deactivate save button if the name field is empty.
- [x] Every button in the save section should have a tooltip. See the list below.

- [x] The text for the delete confirm dialog must match the one detailed below.
- [x] When you delete a VS, clear all queries
- [x] When you create a new VS, clear all queries
- [x] When you are in no VS, New must be disabled
- [x] Move the Share button at the right of the delete button
- [x] Change the "Virtual Study" title for "Explore Data" in blue
- [x] Change the title "{study name}" for "Virtual Study: {study name}" in blue
- [x] "Save as", "Share" and "Delete" must be disabled if no study is open.

## List of tooltips
For each of the buttons, their tooltip text:
  - [x] New: Create a new virtual study
  - [x] Open: Open a saved virtual study
  - [x] Save: Save as a new virtual study
  - [x] Save as: Save as a new virtual study
  - [x] Share: Share this virtual study
  - [x] Delete: Delete this virtual study

# The text for the delete confirm dialog
Delete a virtual study

Are you sure you want to delete "{name}"?

This action cannot be undone.

Cancel

Delete

**Comment by nyanofthemoon** [comment]
https://github.com/kids-first/kf-portal-ui/pull/1583
