### ISSUE TITLE
Empty data in the file repository table create groups of commas that look like a mistake

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1586]
If a cell in the file repository table contains a list of empty values, it shows as a group of commas. Instead, we should not display anything.

## Screenshot
![empty-commas-in-participants-table.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/556c0c38-b3e0-46d0-b8a9-bef5e9ff581c)

**Comment by Velythyl** [comment]
Would it be a good idea to implement my sanitize function as we discussed @nyanofthemoon ?
