### ISSUE TITLE
Cohort builder - Replace summary line to include # of families

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#1588]
Currently the summary line looks like this :
![suum.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/84ea0207-ef73-404f-aa87-23d9424075a9)

Replace this by something more similar to the File Browser's summary; 
![summary.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/2a7a1557-ca2b-470d-ab8c-268869cac567)

Font color should be blue as it is now. Font size should be the same as it is now. Add the link to the number of files

**Comment by aalex** [comment]
QA: The feature seems to be implemented, but the new text is not aligned with the older ones.

![image](https://user-images.githubusercontent.com/293677/56769573-959b4800-677f-11e9-9e8c-f43d97c5f710.png)

Nonetheless, I suggest that we consider this feature as done, and create a bug report. The alignment is not correct either in the file repository.

LGTM.
