### ISSUE TITLE
Invalid Usersnap API key error

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1595]
When we click on the chat bot at the bottom-right of the page, there is an error message.

## Screenshot
![usersnap.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/50504f6b-9a14-448a-8ae0-80c9e35f0372)

## Technical details
Our API key for Usersnap is probably not valid.

**Comment by bdolly** [comment]
This is addressed in PR #1496 as we are deprecating the use of UserSnap in the portal in favor of using some of the better features with HotJar

**Comment by aalex** [comment]
@bdolly Should we do some work regarding changing the support chat window in order to use the new Hot Jar system? (let's link the two issues, anyways)

**Comment by jberube** [comment]
That should not happen after the v2.0.0 release
