### ISSUE TITLE
Disable sorting on columns in the files table that have multiple values

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1599]
In the files table, there are cases where a file has multiple types. This creates problems in the way we sort rows in both the file and participant tables.

Let's remove the sorting feature on those columns.

## Acceptance criterias
- [ ] Remove sorting on the columns listed above.

## List of potentially problematic fields

File table:
- [ ] Participant ID
- [ ] Study Name
- [ ] Proband
- [ ] Family ID
- [ ] Participant External ID
- [ ] Aliquot External ID
- [ ] Sample External ID
- [ ] Biospecimen ID
- [ ] Tissue Type (Source Text)
- [ ] Diagnosis (Source Text)
- [ ] Study ID

## See also
- #1572 (it has been done in the participants table)
- #1571 
- #1570

**Comment by nyanofthemoon** [comment]
@aalex I think we did this one already, no?
