### ISSUE TITLE
Blank page when I delete a virtual study

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1602]
When I delete a saved virtual study and then click new, of when I simply delete a virtual study, there is sometimes a blank page. (which might be the symptom of a front-end crash)

It seems not consistent and hard to reproduce.

**Comment by aalex** [comment]
I've been trying to reproduce it, but couldn't for now. I will try harder.

**Comment by jberube** [comment]
I've found a way to reproduce.

- Load a virtual study
- Press "Delete"
  - On the confirmation modal, quickly press on the "Delete" button multiple times
- 🔥

**Comment by jberube** [comment]
There are similar problems with other actions (load, save, delete).

A good cleanup and defining error boundaries will fix it.

**Comment by aalex** [comment]
@jberube LGTM
