### ISSUE TITLE
Migrate Netlify at Ste-Justine

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1605]
As developers, we need to administer our netlify instances for the staging and dev environments.

(the prod netlify is managed by CHOP)

## Acceptance criterias
- Investigate what needs to be done
- Maybe simply recuperate the netlify account of OICR.
- Probably create a Google Auth account (?)
- Choose a domain name, if needed.
- Buy the domain name, if needed.
- Deploy netlify for QA
- Deploy netlify for dev

**Comment by nyanofthemoon** [comment]
@aalex Removing "dev" from the list, as discussed this morning.

**Comment by nyanofthemoon** [comment]
@aalex Ready for PO Review. (should probably be closed because QA is up - if code on QA "does not work", it does not affect this ticket)

**Comment by aalex** [comment]
Good work!
