### ISSUE TITLE
Prune unused branches

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1617]
In kf-portal-ui, we want the Git repository to be free of unused branches.

## Acceptance criteria
- Make a list of Git branches candidate for deletion
- Make it approved by the PO
- Remove them.

**Comment by denis-crsj** [comment]
Closing issue. Details transferred into Google Sheet : https://docs.google.com/spreadsheets/d/1U1JQZEBEMTP_07PngrmNh8rzbZICTX87Fe_2fEetAbI/edit#gid=0
