### ISSUE TITLE
Provide a default page for https://ego.kids-first.io

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1619]
- Go to https://ego.kids-first.io/
- We should see something useful - like a page with some info about what this is.
- Instead, there is an error message.

## Contents of the error page

> Whitelabel Error Page
> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> 
> Thu Apr 18 16:10:23 UTC 2019
> There was an unexpected error (type=Not Found, status=404).
> No message available

## Screenshot
![screenshot_2019-04-18_12-11-56_ego_error_page.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/f5bee2ee-3816-4c21-8d92-2f86849a2ca3)

**Comment by steptek** [comment]
this message is normal
when you try to get access on / on ego as you do not provide any path neither any authentication info
so the / root context gives you that default error page

**Comment by aalex** [comment]
Question: is it relevant at all to provide a default page, since this is an endpoint.
