### ISSUE TITLE
Blank page when loading the cohort builder page

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1621]
Some users experiement a crash in the front-end application when they load the cohort builder's page.

## Notes

- The user loads the page: https://portal.kidsfirstdrc.org/explore
- A white page crash occurs

**Comment by aalex** [comment]
> react-dom.production.min.js:198 TypeError: Cannot read property 'content' of undefined
>     at Object.children (Results.js:226)
>     at t.value (QueriesResolver.js:88)
>     at Rn (react-dom.production.min.js:173)
>     at Mn (react-dom.production.min.js:172)
>     at Fn (react-dom.production.min.js:180)
>     at wr (react-dom.production.min.js:232)
>     at xr (react-dom.production.min.js:233)
>     at Ur (react-dom.production.min.js:249)
>     at zr (react-dom.production.min.js:248)
>     at Dr (react-dom.production.min.js:245)
> tr @ react-dom.production.min.js:198
> n.callback @ react-dom.production.min.js:210
> Jn @ react-dom.production.min.js:193
> Zn @ react-dom.production.min.js:193
> vr @ react-dom.production.min.js:217
> br @ react-dom.production.min.js:220
> (anonymous) @ react-dom.production.min.js:250
> t.unstable_runWithPriority @ scheduler.production.min.js:18
> Hr @ react-dom.production.min.js:250
> Ur @ react-dom.production.min.js:249
> zr @ react-dom.production.min.js:248
> Dr @ react-dom.production.min.js:245
> Cr @ react-dom.production.min.js:243
> enqueueSetState @ react-dom.production.min.js:130
> a.setState @ react.production.min.js:13
> (anonymous) @ QueriesResolver.js:58
> r @ runtime.js:62
> (anonymous) @ runtime.js:296
> e.(anonymous function) @ runtime.js:114
> r @ main.c22cf919.js:28834
> (anonymous) @ main.c22cf919.js:28834
> Promise.then (async)
> r @ main.c22cf919.js:28834
> (anonymous) @ main.c22cf919.js:28834
> (anonymous) @ main.c22cf919.js:28834
> value @ QueriesResolver.js:34
> vr @ react-dom.production.min.js:216
> br @ react-dom.production.min.js:220
> (anonymous) @ react-dom.production.min.js:250
> t.unstable_runWithPriority @ scheduler.production.min.js:18
> Hr @ react-dom.production.min.js:250
> Ur @ react-dom.production.min.js:249
> zr @ react-dom.production.min.js:248
> Dr @ react-dom.production.min.js:245
> Cr @ react-dom.production.min.js:243
> enqueueSetState @ react-dom.production.min.js:130
> a.setState @ react.production.min.js:13
> _setState @ index.js:82
> (anonymous) @ VirtualStudyListProvider.js:23
> Promise.then (async)
> (anonymous) @ VirtualStudyListProvider.js:22
> Jn @ react-dom.production.min.js:193
> Zn @ react-dom.production.min.js:193
> vr @ react-dom.production.min.js:216
> br @ react-dom.production.min.js:220
> (anonymous) @ react-dom.production.min.js:250
> t.unstable_runWithPriority @ scheduler.production.min.js:18
> Hr @ react-dom.production.min.js:250
> Ur @ react-dom.production.min.js:249
> zr @ react-dom.production.min.js:248
> Dr @ react-dom.production.min.js:245
> Cr @ react-dom.production.min.js:243
> enqueueForceUpdate @ react-dom.production.min.js:131
> a.forceUpdate @ react.production.min.js:13
> (anonymous) @ inject.js:61
> value @ inject.js:60
> (anonymous) @ provide.js:132
> value @ provide.js:131
> (anonymous) @ provide.js:132
> value @ provide.js:131
> (anonymous) @ provide.js:132
> value @ provide.js:131
> (anonymous) @ provide.js:153
> value @ provide.js:152
> value @ state.js:143
> r @ effects.js:10
> Promise.then (async)
> e.(anonymous function) @ effects.js:26
> (anonymous) @ Login.js:71
> r @ runtime.js:62
> (anonymous) @ runtime.js:296
> e.(anonymous function) @ runtime.js:114
> r @ main.c22cf919.js:35273
> (anonymous) @ main.c22cf919.js:35273
> Promise.then (async)
> r @ main.c22cf919.js:35273
> (anonymous) @ main.c22cf919.js:35273
> Promise.then (async)
> r @ main.c22cf919.js:35273
> (anonymous) @ main.c22cf919.js:35273
> (anonymous) @ main.c22cf919.js:35273
> (anonymous) @ Login.js:54
> (anonymous) @ provideLoggedInUser.js:54
> r @ effects.js:8
> Promise.then (async)
> e.(anonymous function) @ effects.js:26
> value @ provide.js:66
> vr @ react-dom.production.min.js:216
> br @ react-dom.production.min.js:220
> (anonymous) @ react-dom.production.min.js:250
> t.unstable_runWithPriority @ scheduler.production.min.js:18
> Hr @ react-dom.production.min.js:250
> Ur @ react-dom.production.min.js:249
> zr @ react-dom.production.min.js:248
> Dr @ react-dom.production.min.js:245
> Cr @ react-dom.production.min.js:243
> enqueueSetState @ react-dom.production.min.js:130
> a.setState @ react.production.min.js:13
> n @ I18n.js:135
> t @ I18n.js:147
> (anonymous) @ EventEmitter.js:46
> e.emit @ EventEmitter.js:45
> (anonymous) @ i18next.js:155
> r @ i18next.js:260
> (anonymous) @ i18next.js:275
> (anonymous) @ BackendConnector.js:132
> t.loaded @ BackendConnector.js:121
> (anonymous) @ BackendConnector.js:269
> (anonymous) @ BackendConnector.js:162
> (anonymous) @ index.js:93
> u.onreadystatechange @ ajax.js:69
> XMLHttpRequest.send (async)
> o @ ajax.js:71
> value @ index.js:82
> value @ index.js:75
> t.read @ BackendConnector.js:155
> t.loadOne @ BackendConnector.js:265
> (anonymous) @ BackendConnector.js:211
> t.load @ BackendConnector.js:210
> (anonymous) @ i18next.js:208
> t.load @ CacheConnector.js:40
> t.loadResources @ i18next.js:207
> t.loadNamespaces @ i18next.js:341
> value @ I18n.js:133
> value @ I18n.js:73
> vr @ react-dom.production.min.js:216
> br @ react-dom.production.min.js:220
> (anonymous) @ react-dom.production.min.js:250
> t.unstable_runWithPriority @ scheduler.production.min.js:18
> Hr @ react-dom.production.min.js:250
> Ur @ react-dom.production.min.js:249
> zr @ react-dom.production.min.js:248
> Dr @ react-dom.production.min.js:245
> Cr @ react-dom.production.min.js:243
> Kr @ react-dom.production.min.js:253
> $r @ react-dom.production.min.js:253
> eo.render @ react-dom.production.min.js:261
> (anonymous) @ react-dom.production.min.js:264
> Gr @ react-dom.production.min.js:251
> ro @ react-dom.production.min.js:264
> render @ react-dom.production.min.js:266
> v @ index.js:20
> (anonymous) @ index.js:26
> t @ bootstrap 78b241d759af33ac273e:49
> (anonymous) @ main.c22cf919.js:96530
> t @ bootstrap 78b241d759af33ac273e:49
> (anonymous) @ bootstrap 78b241d759af33ac273e:144
> (anonymous) @ bootstrap 78b241d759af33ac273e:144
> Show 36 more frames

**Comment by jberube** [comment]
Many actions or state can cause this pas to crash:

- clicking quickly on the "Save" button of the "Save as" confirmation dialog
  - can reslult in a crash, can save the study multiple times
- clicking quickly on the "Delete" button of the "Delete Study" confirmation dialog
  - can reslult in a crash
- entering an url `/explore?id=X`, where `X` is not a valid id for a study
  - can reslult in a crash
  - might need another cause, too
- ending up with a study in the local storage that has been deleted
  - less sure about that last one as I could not reproduce easily

**Comment by aalex** [comment]
(QA) LGTM. Closing.
