### ISSUE TITLE
Cohort builder: "Combine queries" card (Venn diagram)

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#1625]
As a user, I want to be able to combine queries in the cohort builder by doing set operations in a Venn diagram, so that it's easier to do than with mathematical operators.

## Acceptance criteria
- Create a new card that takes the first position. Put the last card that was there in a new row, if needed.
- Create a Venn diagram with three (3) circles.
- Each circle has a dropdown menu with which we can choose which query it's associated with. (see the details of the menus below)
- Follow the details of the menus and set logic as listed below.
- When the user clicks on a section in the diagram, highlight it. (or unhighlight it)
- When the user clicks the "Create query" button create a new query combining 2 of the sets, and potentially another query combining the one you've just created with another one. Follow the details of the combination as listed below. Clear the selection in the diagram.
- In each circle show how many participants there are in that set. Update it when the set changes. 

## Mockups
![image](https://user-images.githubusercontent.com/293677/57877485-f994b780-77e5-11e9-9874-ff210c423a3b.png)

## Details of the menus and set logic
- Choosing a query updates how many participants are in each section of the diagram.
- Each dropdown menu lists all queries currently in the query area, plus the ∅ symbol for an empty set.
- The user can choose different or similar values for any dropdown.
- When the user first lands in the page, populate it with the last three query numbers. (or the empty set if there is none)
- When a new query is created, replace the first empty set with its number, or replace the lowest set number with it.
- When a query is deleted, remove it from the diagram, and replace it with the highest number that is not currently in the diagram, or with an empty set if all the queries are already in there.
- When the user mouse overs a clickable section in the diagram, highlight (in blue in the mockup) the section.

## Details of the combinations
![image](https://user-images.githubusercontent.com/293677/57556374-db8e0980-7344-11e9-8db3-a5afe1dc6c7e.png)
Given the diagram above:

- D: what is in A minus what is either in B or C
- E: what is in B minus what is either in A or C
- F: what is in C minus what is either in A or B
- G: what is in both A and C minus what is in B
- H: what is in both A and B minus what is in C
- I: what is in both B and C minus what is in A
- J: what is in A, B and C

Here are the possible combinations, in mathematical notation: 
- ( S1 ∩ S2 ∩ S3 )
- ( S1 ∩ S2 ) − ( S3 )
- ( S1 ∩ S3 ) − ( S2 )
- ( S2 ∩ S3 ) − ( S1 )
- ( S1 ) − ( S2 ∪ S3 )
- ( S2 ) − ( S1 ∪ S3 )
- ( S3 ) − ( S1 ∪ S2 )

## See also
For inspiration, see: https://dcc.icgc.org/analysis/view/set/a3f0e354-2bcb-4306-a452-13d14794e93d

Click on one section of more in the diagram, and then click on the total number for the combined sets to see the results.

![image](https://user-images.githubusercontent.com/293677/57656211-c6fc7c00-75a5-11e9-9312-dd2ac4aaac95.png)

## Technical discussion
- In order to create a query such as ( S1 ∩ S2 ) − ( S3 ), it's possible to combine two queries with an intersection, (and) and then create another query by combining the one that was first created withthe other one, using the "and not" operator.

**Comment by nyanofthemoon** [comment]
Idea? https://github.com/benfred/venn.js

**Comment by aalex** [comment]
Question: should we put this into a draggable tray or another tab, since the cards are used to show statistics about the results, not to alter the queries?

**Comment by aalex** [comment]
Question: I think we should keep the "or", "and" and "and not" combinors separately as well. It might work better that way for some users.

**Comment by nyanofthemoon** [comment]
https://arranger.readthedocs.io/en/latest/src/sqon.html

**Comment by denis-crsj** [comment]
Closing issue for now. Details transferred to the Google Sheet file : https://docs.google.com/spreadsheets/d/1U1JQZEBEMTP_07PngrmNh8rzbZICTX87Fe_2fEetAbI/edit#gid=0
