### ISSUE TITLE
"Is Not" queries are badly displayed in the query section of the cohort builder

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#1633]
In the queries section of the cohort builder, it says "is", whereas it should be "is not", when you create a "is not" query.

## How to reproduce
- Create the following query, "Study IS NOT Congenital Heart Defects"
- In the query summary, it is written "Study Is Congen..."
- It says "is", but should say "is not"

![image](https://user-images.githubusercontent.com/293677/56606882-33064880-65d5-11e9-8fbf-17aa7c99b965.png)

![image](https://user-images.githubusercontent.com/293677/56606923-529d7100-65d5-11e9-85e1-96197834394b.png)

**Comment by aalex** [comment]
(in QA) It seems like it is not fixed.

![image.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/0b9a9366-f88a-4b06-913d-bf2610b314ab)

![image.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/0dd1c42e-36c3-44eb-9118-e3800e0cb58d)

**Comment by aalex** [comment]
@jaouad-benassila It seems like there was no PR associated with the issue. (and it ended up in QA and got closed, nevertheless)

**Comment by aalex** [comment]
It works when there are two items checked, but not when there is only one.

**Comment by aalex** [comment]
Closed, and then the changes asked for in QA are moved to #1714
