### ISSUE TITLE
Update the UI in the file repository for new ontological field format

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1635]
The format of the Ontological Fields has been changed. We should update the UI in the file repository accordingly.

See https://github.com/kids-first/kf-portal-etl/issues/66

## Acceptance criterias
- There are 5 labels to change (see in the Details section)
- Change them in:
  - use the Arranger admin UI to change it in the database
  - Arranger for the cohort builder
  - participant table: headers of the table
- There is a field not to use anymore. 

### Diagnosis and Biospecimens
- Rename "Mondo ID Diagnosis" to "Diagnosis (Mondo)"
- Rename "NCit ID Diagnosis" to "Diagnosis (NCit)"
- Rename "NCit ID Tissue type" to "Tissue type (NCit)"
- Rename "NCit ID Anatomical Site" to "Anatomical Site (NCit)"
- Rename "HPO ids" to "Shared Phenotype (HPO)"

Note: We need to decide what we do with the Diagnosis Field @jecos : Please comment.

### Phenotypes
- Rename "Observed Phenotype" to "Observed Phenotype (HPO)"
- Rename "Not Observed Phenotype" to "Not Observed Phenotype (HPO)"
- Remove fields **HPO phenotype not observed** and **HPO phenotype Observed** - in the file repository only

Note: Values are already in the right format i.e. term (ID)

See issue #1636 for the same changes in the cohort builder.

**Comment by nyanofthemoon** [comment]
In kf-portal-ui
- family.family_compositions.family_members.phenotype.hpo_phenotype_observed_text
- phenotype.hpo_phenotype_observed_text
