### ISSUE TITLE
Update UI for the new ontological field format

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1636]
The format of the Ontological Fields has been changed. We should update the UI in the cohort buider accordingly.

See https://github.com/kids-first/kf-portal-etl/issues/66

## Acceptance criteria
- There are labels to change (see in the Details section)
- Change them in Arranger for the cohort builder (see the details below)
- There is a field not to use anymore. 

## Labels to change in the cohort builder (via a commit into arranger front-end components)
- [ ] Rename "Tissue type (NCIT ID)" to "Tissue type (NCIT)" `participants.biospecimens.ncit_id_tissue_type`
    - [x] Done in QA
    - [x] Verified in QA
    - [x] Done in prod
    - [x] Verified in prod
- [ ] Rename "Anatomical Site (NCIT ID)" to "Anatomical Site (NCIT)" `participants.biospecimens.ncit_id_anatomical_site`
    - [x] Done in QA
    - [x] Verified in QA
    - [x] Done in prod
    - [x] Verified in prod
- [ ] Rename "Family Shared Phenotype" to "Family Shared Phenotype (HPO)" `phenotype.shared_hpo_ids`
    - [x] Done in QA
    - [x] Verified in QA
    - [x] Done in prod
    - [x] Verified in prod
- [ ] Rename "Anatomical Site" to "Anatomical Site (Source Text)" `participants.biospecimens.ncit_id_anatomical_site`
    - [x] Done in QA
    - [x] Verified in QA
    - [x] Done in prod
    - [x] Verified in prod
- [ ] Rename "Tissue Type" to "Tissue Type (Source Text)" 
    - [x] Done in QA
    - [x] Verified in QA
    - [x] Done in prod
    - [x] Verified in prod

## Field to change in the cohort builder
- [x] Replace "Phenotype" by "Observed Phenotype (HPO)" `phenotype.hpo_phenotype_observed`
- [x] Remove "Diagnosis" Field `diagnoses.diagnosis`
- [x] Add field "Not Observed Phenotype (HPO)" `phenotype.hpo_phenotype_not_observed`
- [x] Add "Diagnosis (Mondo)" `diagnoses.mondo_id_diagnosis`
- [x] Add "Diagnosis (NCIT)" `diagnoses.ncit_id_diagnosis`

## In the file repository (via arranger admin ui)
- [x] Rename the "Mondo ID Diagnosis" filter to "Diagnosis (Mondo)"
    - [x] Done in QA
    - [x] Verified in QA
    - [x] Done in prod
    - [x] Verified in prod
- [x] Rename "NCit ID Diagnosis" to "Diagnosis (NCIT)"
    - [x] Done in QA
    - [x] Verified in QA
    - [x] Done in prod
    - [x] Verified in prod
- [x] Rename "NCit ID Tissue type" to "Tissue type (NCIT)" (in the file repo, via Arranger admin UI)
    - [x] Done in QA
    - [x] Verified in QA
    - [x] Done in prod
    - [x] Verified in prod
- [x] Rename "NCit ID Anatomical Site" to "Anatomical Site (NCIT)"
    - [x] Done in QA
    - [x] Verified in QA
    - [x] Done in prod
    - [x] Verified in prod
- [x] Rename "Shared HPO ids" to "Family Shared Phenotype (HPO)"
    - [x] Done in QA
    - [x] Verified in QA
    - [x] Done in prod
    - [x] Verified in prod
- [ ] Remove "Diagnosis" Field `participants.diagnoses.diagnosis`
    - [x] Done in QA
    - [x] Verified in QA
    - [x] Done in prod
    - [x] Verified in prod
- [x] Rename "Observed Phenotype" to "Observed Phenotype (HPO)"
    - [x] Done in QA
    - [x] Verified in QA
    - [x] Done in prod
    - [x] Verified in prod
- [x] Rename "Not Observed Phenotype" to "Not Observed Phenotype (HPO)"
    - [x] Done in QA
    - [x] Verified in QA
    - [x] Done in prod
    - [x] Verified in prod
- [ ] Remove field "Observed Phenotype" `phenotype.hpo_phenotype_observed_text`
    - [x] Done in QA
    - [x] Verified in QA
    - [x] Done in prod
    - [x] Verified in prod

**Comment by aalex** [comment]
@jecos Question: is this spec ok?

**Comment by aalex** [comment]
Some fields names: 

- family.family_compositions.family_members.phenotype.hpo_phenotype_observed_text
- phenotype.hpo_phenotype_observed_text

**Comment by jberube** [comment]
Fields  `participants.phenotype.hpo_phenotype_observed_text` and  `participants.diagnoses.diagnosis` are used in the application.

`participants.diagnoses.diagnosis` in:
- Cohort Builder
  - a column of the Participants Table
  - `Download` button
- `src/components/CohortBuilder/Summary/DiagnosesChart.js` (Most Frequent Diagnoses)

Dashboard
- `TopDiagnosesChart` (Most Frequent Diagnoses)

`participants.phenotype.hpo_phenotype_observed_text` in:
- Sidebar
- File Repository
- File Entity Page

**Comment by aalex** [comment]
More fields names:

```
family.family_compositions.shared_hpo_ids
participants.diagnoses.mondo_id_diagnosis
participants.diagnoses.ncit_id_diagnosis
participants.biospecimens.ncit_id_tissue_type
participants.biospecimens.ncit_id_anatomical_site
participants.family.family_compositions.family_members.phenotype.shared_hpo_ids
participants.phenotype.hpo_phenotype_observed
participants.family.family_compositions.family_members.phenotype.hpo_phenotype_not_observed
```

**Comment by aalex** [comment]
We should now use the project "2019_05_15_good" in the QA environment.

**Comment by aalex** [comment]
Same in prod: we should now use the project "2019_05_15_good".

**Comment by aalex** [comment]
See #1754 - we must also update one of the charts.

**Comment by aalex** [comment]
Still TODO: in the file : aggspanel or the Arranger admin UI:

- remove participants.family.family_compositions.family_members.phenotype.hpo_phenotype_observed_text
- remove participants.diagnoses.diagnosis
- remove participants.phenotype.hpo_phenotype_observed_text

**Comment by aalex** [comment]
![image](https://user-images.githubusercontent.com/293677/57955825-e0af0380-78c4-11e9-9003-4803eed31737.png)

(QA) LGTM

The new project is :
REACT_APP_PROJECT_ID=2019_05_17_v3
