### ISSUE TITLE
Advanced filters feedback - simplify the name of the field

### ISSUE THREAD

**Issue by phuongmy** [kids-first/kf-portal-ui#164]
Don’t display the entire path of a field in both:
- the Add filter window and 
- in the query string. 

Just display the last term + first direct parent. 
E.g. in the  figure below, we should simply display “Family Data Available data types” only. 
<img width="618" alt="screen shot 2018-03-11 at 11 28 42 am" src="https://user-images.githubusercontent.com/8812383/37255199-6866b8ae-251f-11e8-82ad-49a82f4d3f7b.png">

**Comment by alex-wilmer** [comment]
https://github.com/overture-stack/arranger/issues/254

**Comment by phuongmy** [comment]
We're now using Display name. Ok to close.
