### ISSUE TITLE
Save a virtual study: Check the permissions in Riff and Persona

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1644]
I need to be able to delete and update only my own studies.

## Acceptance criteria
- The short URL and the SQON is in Riff. Check the ownership in the backend of Riff. The user UUID should be stored there and in the token.
- The title is stored in Persona. (it uses Ego middleware) We need to make sure the delete is only allowed if it's mine. (updating a title is not implemented)

**Comment by steptek** [comment]
- Le Check des permissions de presense d'un user est faite au niveau Riff sur les endpoint save...
- Persona via le ego-midleware check les access rules definis dans le token de l'utilisateur et verify si y a pas un "deny".

**Comment by aalex** [comment]
This means that we can consider this issue as invalid and close it?

**Comment by steptek** [comment]
QA and close if Riff validates the checking.

**Comment by aalex** [comment]
We need to know what are the QA procedures for this item.
Also, is there a PR?
