### ISSUE TITLE
White screen in Cohort-Builder, part 2

### ISSUE THREAD

**Issue by jberube** [kids-first/kf-portal-ui#1646]
This one is unrelated to the previous white screen issue.

When doing some manipulations on the index of the query, or switching the query by creating a new one, loading one or deleting one, the sqon might end-up being corrupted temporarily (`undefined` content), causing a crash.

Using a default empty sqon (`{ op: "and", content: [] }`) temporarily should solve the issue.

**Comment by aalex** [comment]
LGTM
