### ISSUE TITLE
Fork: ego

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1654]
As developers, we need to manage the releases of our micro-services so that we can choose which features and bug fixes are included in each of them.

This task is about forking a specific service: 

See the issue for the epic for the list of acceptance criteria.

**Comment by nyanofthemoon** [comment]
@aalex Need to discuss with @alubneuski how we can change Vault variables.

**Comment by nyanofthemoon** [comment]
Related PRs: https://github.com/kids-first/aws-jenkins-seed-job/pull/111

**Comment by nyanofthemoon** [comment]
@aalex We need to create a Facebook App ID as well in order to create an app for OAuth!
