### ISSUE TITLE
Fork: ego-ui

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1655]
As developers, we need to manage the releases of our micro-services so that we can choose which features and bug fixes are included in each of them.

This task is about forking a specific service: ego-ui

See the issue for the epic for the list of acceptance criteria.

**Comment by nyanofthemoon** [comment]
@jberube Don't see any dependencies in https://github.com/kids-first/ego-ui/blob/master/package.json .... might as well close this one.
