### ISSUE TITLE
Fork: riff

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1656]
As developers, we need to manage the releases of our micro-services so that we can choose which features and bug fixes are included in each of them.

This task is about forking a specific service: riff

See the issue for the epic for the list of acceptance criteria.

**Comment by nyanofthemoon** [comment]
@aalex @jecos Task is in closed. Are all of the following acceptance criterias met?
![review](https://user-images.githubusercontent.com/3919995/57153403-37d0b680-6da4-11e9-9ba0-ff62f39ca37e.png)
