### ISSUE TITLE
Fork: persona

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1657]
As developers, we need to manage the releases of our micro-services so that we can choose which features and bug fixes are included in each of them.

This task is about forking a specific service: persona

See the issue for the epic for the list of acceptance criteria.

**Comment by nyanofthemoon** [comment]
@aalex @steptek Task is in review. Are all of the following acceptance criterias met?
![review](https://user-images.githubusercontent.com/3919995/57153355-1374da00-6da4-11e9-81d0-a11702f9d629.png)
