### ISSUE TITLE
Cohort builder: filter often provide a count of participant that is off by one

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1673]
Counts are occasionally off by 1 between what the filters say and what the total # of participants are.

## How to reproduce
Example Query: https://portal.kidsfirstdrc.org/explore?id=297

![image](https://user-images.githubusercontent.com/293677/57099338-393da880-6cea-11e9-9d15-4028dc39dee2.png)

See that the number of participants near the "All Data" title is different from one of the filter's.

**Comment by jberube** [comment]
Not an issue.

Using the query above, change "any of" to "all of" on the tissue types.

There are 27 participants that have "all of" Tumor, Normal, 29 that have "any of" Tumor, Normal.

That 27 that have Tumor, Normal, 1 that has ony Tumor, 1 that has only Normal.

**Comment by aalex** [comment]
This matches what has been explained and observed on the Slack team. We can therefore close this issue: you are right. Thank you.
