### ISSUE TITLE
Limit the width of text values of filters

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1680]
In the cohort builder, for filters that have many text values and the user needs to choose one, very long text values in some filters can lead to a menu/widget that is too wide.

## Acceptance criteria
- The current maximum width of the lines is reasonable.
- Use up to three lines for an item. (make them multi-line)
- Use ellipsis (the unicode character ...) when it's longer than that.
- A tooltip shows the whole value.

## Screenshot
Here is how it looks in the menu:
![image](https://user-images.githubusercontent.com/293677/60982064-72575200-a305-11e9-80cb-2ab2f5d763d4.png)

Here is how it looks in the query area:
![image](https://user-images.githubusercontent.com/293677/60984968-9a957f80-a30a-11e9-9d9c-e0aad94c2db9.png)

Here is how it's done in another widget:
![image](https://user-images.githubusercontent.com/293677/60984933-8baecd00-a30a-11e9-9c56-56607b66c131.png)

## Technical discussion
- We did a fix that limits the width of the menu/widget by putting ellipsis for values that are too long.
- Instead, we want to be able to see multiple lines for long text.

**Comment by aalex** [comment]
Question: We should plan a better fix for this.

**Comment by jberube** [comment]
Could be cleaner.

**Comment by vferretti** [comment]
Put the value on multiple lines like the boxes in the query section do.
