### ISSUE TITLE
Change the link of studies and participants clickable diagrams in the dashboard to point to the cohort buider

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1685]
As users, we want to be able to click on diagrams and they send us to the cohort builder with the right query.

## Acceptance criteria
- Change the links in the clickable the "Studies" & "Participants" diagram widget so that they point to the cohort builder. (see screenshot)
- Make sure the SQON is valid and matches what has been clicked.

## Screenshots
Here is **what to make clickable:**
![image.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/6ba4dfd8-d315-49f8-93b2-9da78682daf7)

**Comment by aalex** [comment]
We will need to parse the url and generate a SQON query, probably.
Pass the result and generate a valid SQON.

**Comment by aalex** [comment]
It seems like we will need to change https://github.com/kids-first/kf-public-stats-api/blob/master/src/routes/diagnosesCategories.ts so that it returns different data.

**Comment by aalex** [comment]
(QA) LGTM.
Thank you!

**Comment by vferretti** [comment]
Links don't work for me

**Comment by aalex** [comment]
See line 113 in chart.js

**Comment by nyanofthemoon** [comment]
@aalex `operator: MERGE_OPERATOR_STRATEGIES.KEEP_OPERATOR,` ?

**Comment by aalex** [comment]
(QA) LGTM
