### ISSUE TITLE
Query area: show number of participants for a query

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1688]
Users need to know how many participants.

Users should see the actions they can do on a query all the time. (delete, duplicate)

Time boxed to one day.

## Acceptance criteria
- Show how many participants a query leads to.
- Show the participant icon. ( @aalex has the SVG file)
- When a query is mouse overed or active, show the trashcan and the duplicate icon, just like we already do.
- Update the number of participants with the actual result for each query.
- When a query changes, update its number of participants.
- When a dependant query changes, update its dependee as well.

## Mockups
![image](https://user-images.githubusercontent.com/293677/57407310-d8faab00-71b0-11e9-9d0a-b2c87b67f723.png)

Icône à utiliser pour les participants:
[icon-participants.zip](https://github.com/kids-first/kf-portal-ui/files/3242532/icon-participants.zip)

## Technical details
- Some ES queries will probably need to be done!

**Comment by aalex** [comment]
Can we do that that with a single query in ES?

**Comment by jberube** [comment]
> Can we do that that with a single query in ES?

No.

That said, the rest of the feature is feasible in a day. I've done everything by the aesthetics in half the timebox.

**Comment by aalex** [comment]
(QA) Good work!

**Comment by aalex** [comment]
![image](https://user-images.githubusercontent.com/293677/59459234-48843b80-8dea-11e9-9bb0-a59167df28ab.png)
