### ISSUE TITLE
Remove field phenotype.ancestral_hpo_ids

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1695]
It seems like the field phenotype.ancestral_hpo_ids is unused. We can then remove it.

## Acceptance criteria
- Remove field phenotype.ancestral_hpo_ids
  - From filters in the Cohort-Builder
  - From the File Repository

## Screenshot
![image](https://user-images.githubusercontent.com/293677/58730678-d1e34900-83ba-11e9-8047-397a2b59c3ee.png)

## Technical details
- Remove it from the file repo (first) - with arranger admin UI - in the schema
- Remove the ES field
- Remove it from the front-end (cohort builder + file browser?)

This field is buggy. It should do a tree of phenotypes. It is still used in the file repo.

**Comment by jberube** [comment]
En effet, il faut en enlever les occurences dans `src/components/CohortBuilder/Categories/index.js`

**Comment by aalex** [comment]
(QA) LGTM
![image](https://user-images.githubusercontent.com/293677/58811250-73ea7780-85ed-11e9-826d-198f949b0895.png)
