### ISSUE TITLE
Deploy the remaining services

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1711]
As developers, we need to deploy our own versions of the microservices in our ecosystem.

## Acceptance criteria
- Deploy Ste-Justine's fork of:
  - [x] kf-arranger
  - [x] ego
  - [ ] ego-ui
  - [x] rollcall
  - [x] riff 
  - [x] persona
  - [x] kf-publis-stats-api

**Comment by nyanofthemoon** [comment]
@aalex Haven't found "where" `ego-ui` is. Will prolly ask OICR.

**Comment by aalex** [comment]
They are all deployed in QA, expect ego-ui.

Most are not in prod, yet. (persona is)
