### ISSUE TITLE
Standardize build and deployment: Riff

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1713]
As developers, we need to standardize the build and deployment procedures of all our microservices.

## Acceptance criteria
- Standardize the build and deployment procedures of Riff

**Comment by nyanofthemoon** [comment]
- create release / tag in Github
- https://jenkins.kids-first.io/job/kids-first-kf-persona
  -- Click on "Scan Multibranch Pipeline Now"
  -- The tag will appear under the "Tags" tab
- select the tag
  -- Click on "Build Now"

**Comment by nyanofthemoon** [comment]
Jenkins file for both `develop` and `master` branches points to the `riff_api` function found in
https://github.com/kids-first/aws-infra-jenkins-shared-libraries/blob/master/vars/riff_api.groovy

We + CHOP would like to process to be standardized in the same fashion as shown in this Jenkinsfile for the `public-stats-api` project:
https://github.com/kids-first/kf-public-stats-api/blob/master/Jenkinsfile
