### ISSUE TITLE
Navigation Issues

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#172]
1. Clicking the KF Logo:

Currently, the user is navigated to the login screen.  If you are already logged in, the sign-in wizard flashes for a second then redirects to the file repository.

> Correct behaviour: When you click on the KF logo, you should be navigated to the Kids First Website

**Comment by hlminh2000** [comment]
The second point of this issue is already addressed. For the first point, we don't have a website yet, so we'll have to wait. Let's move to backlog? :)

**Comment by rosibaj** [comment]
@hlminh2000 yes, we can move to backlog!  Thanks for noticing - this was set-up as an older ticket.

**Comment by rosibaj** [comment]
closing as we have a duplicate ticket about this
