### ISSUE TITLE
Saved queries: show the description of each virtual study

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1722]
As a user, I want to see a widget that lists my virtual studies.

(this user story is part of an epic - see below)

## Acceptance criteria
- Show the description for each virtual study.
- This text must reflect the actual description for each virtual study and be kept up-to-date.
- Limit to 60 characters. Use an ellipsis if its more than that.
- Imitate a "pre" tag - in which multiple white spaces are shown as such. (imitate the behaviour of the description in the cohort builder page, for that)
- Add a tooltip that show the full description of the virtual study when you mouse over it.
- Use the same grey text font and style as the other tab. (not in bold)

## Mockups
![image](https://user-images.githubusercontent.com/293677/57876868-69a23e00-77e4-11e9-8f64-f689d0ac6e83.png)

## Technical discussion
- It should be implemented better than in the file repository. In the file repository, it's calculated once and then stored. Here, we want to dynamically query it each time the page is loaded.

**Comment by aalex** [comment]
(QA) The PR attached to this item has been closed, but the branch has not been merged. The feature is therefore not implemented in the dev/QA environment. Someone should then continue the work in that branch (or in a new branch) and then open a new PR.

**Comment by jberube** [comment]
I am on it at the moment, thanks.

**Comment by aalex** [comment]
The PR https://github.com/kids-first/kf-portal-ui/pull/1861 had been linked to this item, but then got closed without being merged.

**Comment by aalex** [comment]
(QA) LGTM

![image](https://user-images.githubusercontent.com/293677/60686335-165c7b80-9e76-11e9-88af-9e21fa497937.png)

**Comment by aalex** [comment]
(QA) Changes requested:
- Display the description of the virtual study on more than one line, if needed. 
- Increase the maximum length of the description to 140 characters.
- Make sure there is no text under the "Delete" button. (the trashcan)

**Comment by aalex** [comment]
(QA) LGTM

![image](https://user-images.githubusercontent.com/293677/60919658-53ed4a00-a264-11e9-8752-8cf8d620561e.png)
