### ISSUE TITLE
Dynamically update the data version

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1737]
As a user, I need to know which data version I am viewing.

## Acceptance criteria
- Dynamically update the data version.
- Show it at the bottom of the page.

## Screenshots
![image.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/f9d93fcc-5f10-453e-939a-0e6467e5f3af)

## Technical discussion
- It seems like the endpoint already exists: http://kf-release-coord.kids-first.io/releases?state=published&limit=1
it gives the latest release with the version number and other info.
- Ticket #706 also need this version number.
- Store the info in Redux.

**Comment by nyanofthemoon** [comment]
@aalex This appears to have been done already. Moving to QA.
Uses endpoint defined in env. var REACT_APP_DATA_VERSION_API and falls back to env var REACT_APP_DATA_VERSION_FALLBACK static value.

**Comment by aalex** [comment]
The QA has it properly set:
![image](https://user-images.githubusercontent.com/293677/60979522-ddeaf080-a300-11e9-9979-4df12f329d26.png)

In prod, it shows the fallback, which is "2.0":
![image](https://user-images.githubusercontent.com/293677/60979578-f3f8b100-a300-11e9-83cf-dd176d427672.png)

We should then make sure the value in prod is properly set.

**Comment by aalex** [comment]
It was not set in prod. I just set it up with the proper value. It will be effective on the next deployment to prod.
