### ISSUE TITLE
Selecting any files via the checkbox causes the top aggregation to fail

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#174]
When a file is selected via checkbox in the File Repository, the summary aggregations fail

![Screen Shot 2018-03-12 at 11.27.19 AM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/e52efedc-dde1-417b-97e8-2e80c1d11628)

Correct Behaviour:  
- When you select a a file the summary counts should **not** be affected 
- There should be an indication on the right panel that the actions being affected by the selected files.  this is out of scope for this ticket, but will be handled by: https://github.com/kids-first/kf-portal-ui/issues/175

**Comment by phuongmy** [comment]
Decision from Vincent to update the counts when selecting files.
Ok to close ticket.
