### ISSUE TITLE
Clickable chart: Studies

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1740]
As a user, I want to be able to click on a chart in order to add a new query in the cohort builder.

This item is about: the "Studies" card.

## Acceptance criteria
- See the epic this item is attached to for details.
- Each of these clickable diagram should point to the cohort builder, with the right SQON query.
- The cursor must turn into a pointing hand when we mouse over it.

## Screenshot
![image](https://user-images.githubusercontent.com/293677/57793984-a0a71f80-7710-11e9-9df1-17e464d3c377.png)

**Comment by aalex** [comment]
(QA) LGTM

**Comment by aalex** [comment]
One question:

When we click on the pink or green area in a bar in this chart, shouldn't the query also filter proband-only, or non-proband-only?

![image](https://user-images.githubusercontent.com/293677/58270434-d0c97080-7d57-11e9-8024-980f484e2e84.png)

(I do prefer the behaviour that is effective right now, though - only applying the study filter)

**Comment by jaouad-benassila** [comment]
we can't because the sqon is for built from different names displayed on the left the chart not from proband or not proband

**Comment by aalex** [comment]
Also, the stakeholders prefer if the proband / non-proband is not taken into account in the click. LGTM
