### ISSUE TITLE
Clickable charts: Most Frequent Diagnoses

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1741]
As a user, I want to be able to click on a chart in order to add a new query in the cohort builder.

This item is about: the "Most Frequent Diagnoses" card.

## Acceptance criteria
- See the epic this item is attached to for details.
- This clickable diagram should point to the cohort builder, with the right SQON query.
- The cursor must turn into a pointing hand when we mouse over it.

## Screenshot
![image](https://user-images.githubusercontent.com/293677/57794091-d9df8f80-7710-11e9-8be3-863ca0ab3e78.png)

**Comment by jberube** [comment]
Je suggère de changer le scope de la story pour inclure le "Studies" chart aussi. C'est la même composante.

**Comment by jaouad-benassila** [comment]
je pense que le problème est au niveau des donnés qu'on récupére de la chart et on les passe au sqon

**Comment by aalex** [comment]
(QA) LGTM
