### ISSUE TITLE
Backend for the "and not" operator between queries

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1751]
As I user, I want to be able to search participants with criteria that I combine with the "and not" operator, so that I can exclude a set of participants with some criteria of my choice.

One-day timebox.

## Acceptance criteria
- Make sure the UI can combine queries with an "and not" operator.

## Technical details
- `A - B`: results in all elements in A, minus all elements in B.
- See if it's the NOT_IN_OP operator or the NOT_OP operator that is to be used.
- Make sure the Arranger middleware creates the proper ES queries.
- Validate that it's possible to do it with ES.

**Comment by aalex** [comment]
It looks like it's in Arranger - server side: https://github.com/kids-first/arranger/blob/master/modules/middleware/src/constants.js#L9

**Comment by Velythyl** [comment]
"Dumb" way to see this, but the buildQuery.js file only includes wrappers for NOT_OP - meaning, only NOT_OP, AND_OP and OR_OP are implemented, I think.

From what I can tell, we need to use OR_OP.

![image](https://user-images.githubusercontent.com/31974070/59716701-81565300-91e4-11e9-98b9-5dbbfd36c8a0.png)

**Comment by Velythyl** [comment]
How can we test this? I tried pasting 

```
{"op":"and","content":[{"op":"in","content":{"field":"participants.family.family_compositions.composition","value":["duo+"]}},{"op":"not","content":{"field":"participants.is_proband","value":["false"]}}]}
```

at the end of `https://kf-qa.netlify.com/search/file?sqon=`, but it just crashed the page. I assume there's a layer transcribing the URL that fails?

**Comment by Velythyl** [comment]
How can we test it? I assume we have to change the Component for https://kf-qa.netlify.com/explore ?
