### ISSUE TITLE
Most frequent diagnosis chart: Use Diagnosis (Mondo)

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1754]
As a user, I prefer the Diagnosis (Mondo) rather than the old filed Diagnosis.

## Acceptance criteria
- The Most frequent diagnosis card in the cohort builder must use the field for the Diagnosis (Mongo), instead of Diagnosis.

![image.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/172930e5-54a7-41e2-b679-06d61f74799f)

## Technial details
- We have changed which field we use for diagnosis. 
- Instead of using `diagnoses.diagnosis`, we should now use `diagnoses.mondo_id_diagnosis`.

**Comment by aalex** [comment]
Untested attempt: [1754-use-diagnosis-mondo-in-diagnosis-chart.diff.txt](https://github.com/kids-first/kf-portal-ui/files/3193183/1754-use-diagnosis-mondo-in-diagnosis-chart.diff.txt)

**Comment by nyanofthemoon** [comment]
@aalex Ok for the chart on the cohort builder page, but the chart on the dashboard uses `participants.diagnoses.source_text_diagnosis`

**Comment by aalex** [comment]
(QA) LGTM
