### ISSUE TITLE
Cohort builder: Change ontological fields in the columns of the participants table

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1758]
As a user, I want the ontological fields to use the Mondo and NCIT ID.

## Acceptance criteria
- The participants table must provide the "Diagnosis (Mondo)" column, instead of "Diagnosis".
- When we export the contents of the table, it should export that column.

## Screenshot
![image](https://user-images.githubusercontent.com/293677/58121657-edd63600-7bd5-11e9-9222-cb1b375f6741.png)

**Comment by nyanofthemoon** [comment]
Need to change another repository as well since they Dashboard (and possibly other things) are using the diagnosis field from it...
<img width="1187" alt="kfpsa" src="https://user-images.githubusercontent.com/3919995/58121748-1bbb7a80-7bd6-11e9-96c0-a39b07f2245b.png">
