### ISSUE TITLE
Saved queries:  example virtual studies

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1764]
As a user, I want to see example virtual study in the "Saved Queries" dashboard widget.

## Acceptance criteria
- Provide three example queries. (Ask @aalex for those queries)
- For consistency, it's ok if it's implemented in the same way as it currently for the saved file repo queries - even though it would be safer if it was done in the backend.

## Technical discussion
- There are file repo example queries - they are created from the front-end in Riff.

**Comment by nyanofthemoon** [comment]
Code that currently creates "example queries" is done **on the front-end side** by calling the Riff API.
 
<img width="187" alt="cat" src="https://user-images.githubusercontent.com/3919995/58191954-ac08c680-7c8d-11e9-88c1-bf690f745131.png">

<img width="1076" alt="kf-portal-ui" src="https://user-images.githubusercontent.com/3919995/58191846-69df8500-7c8d-11e9-981f-5a73a8e2720a.png">
