### ISSUE TITLE
Login with ORCID: front-end

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1771]
As a user, I want to be able to log in with ORCID.

## Acceptance criteria
- Add a new item in the login with:
  - Display the ID logo (see file: https://ndownloader.figshare.com/files/8439047 )
  - The text is "Log in with ORCID"
- log in with ORCID.
- No window popping: redirect to the ORCID web site, and then when the user is done logging in to ORCID, they will be redirected back to the Kids First URL given. (/orcid)
- Create a new route /orcid in the UI portal.
- In the settings, show "Connected with ORCID", and link to https://orcid.org

## Error messages

- [x] Error message for 'email.not.verified' - "You must make sure that your email address has been verified by the ORCID Web site." - And then a line break, and this: "See the documentation on the ORCID Web site" with a link to https://support.orcid.org/hc/en-us/articles/360006894294-How-to-verify-your-email-address 
 
- [x] Error message for 'email.empty' - "You should change the visibility setting of your email address so that it's available publicly."  - And then a line break, and this: "See the documentation on the ORCID Web site" with a link to https://support.orcid.org/hc/en-us/articles/360006894294-How-to-verify-your-email-address 

## Dev Todo

- [x] display loader during redirection
- [x] error display for 'email.not.verified'
- [x] error display for 'email.empty'
- [x] error display for network error with Ego
- [x] skin the Orcid login button
- [x] bug: going through `/join` when logging out

## Mockups
![image](https://user-images.githubusercontent.com/293677/58345602-c033fb80-7e26-11e9-81f7-60094dcdf70e.png)

In case of error:

![image](https://user-images.githubusercontent.com/293677/59860631-491e5400-934d-11e9-9f8b-61a9d0ff562e.png)

![image](https://user-images.githubusercontent.com/293677/59860754-81be2d80-934d-11e9-97f5-d2e90443ec97.png)

While waiting:

![image](https://user-images.githubusercontent.com/293677/59860695-65ba8c00-934d-11e9-93b2-95dae9c6c221.png)

In the settings, show:

![image](https://user-images.githubusercontent.com/293677/59864476-d913cc00-9354-11e9-9b2f-1714844a45b2.png)

## Technical details
- There are JavaScript libraries for ORCID clients and we should probably use one. Here is one: https://github.com/ORCID/orcid-js
- There are a list of clients here: http://members.orcid.org/api/resources/code-examples
- The simplest is to redirect to ORCID in the same (target) window instead of popping a new window.

----

### Documentation

https://members.orcid.org/api/resources

https://api.sandbox.orcid.org/v2.0/

### 1: Prerequisites

Create an account on https://orcid.org/signin using an email created with https://www.mailinator.com/

### 2: Redirection to Orcid

Clicking of the `Login with Orcid` button redirects the user to Orcid's authorization page:

Url template: `https://sandbox.orcid.org/oauth/authorize?client_id=...&response_type=...&scope=...&redirect_uri=...`

```
client_id=APP-QUZGHG4BSBZ2J6GL
response_type=code
scope=/read-limited
redirect_uri=https://kf-qa.netlify.com/orcid
```

https://sandbox.orcid.org/oauth/authorize?client_id=APP-QUZGHG4BSBZ2J6GL&response_type=code&scope=/authenticate&redirect_uri=https://kf-qa.netlify.com/orcid

### 3: Orcid login process

The user completes his login - or not.

#### Success

If he completes, he will be redirected to the uri given in `redirect_uri`, with the code included in the url, i.e.:

`https://kf-qa.netlify.com/orcid?code=...`

That page should display a UI showing that the login request is being processed.

#### Failure

The user did not completed his login. He will be redirected to the uri given in `redirect_uri`... TBD

Display the same error as the FB and Google auth does.

### 4: Get the JWT Token from Ego

In an "ajax" call, the client sends the `code` obtained in step 3 above to Ego to obtain the JWT token.

Url : `{EGO_URL}/oauth/orcid/token`

Header: `code: {code}`

Ego may return a success, or two errors:

`email.empty` The email address of the user may not be shared.

`email.not.verified` The email address of the user has not been verified on Orcid, yet.

In both of the cases above, we won't get the address. See _Obtaining the email address_ below.

### 5: decode the token

Process as with Google and FB login to decode and store the JWT token.

### Security 

The `APP_SECRET` is the only piece of sensible information, and it should not in the UI source code, nor be in an URL, header or body of a request at any time from the USER's perspective. Only the Ego should be able to access it.

### Obtaining the email address

There is still some uncertainty as to how the user's email address will be obtained, both for costs and user experience constraints.

~~It might be necessary to find an alternate way to obtain the email address, and reduce the `scope` of the request to `/authenticate`.~~

We decided to use the `/authenticate` scope. We'll ask the user to make his email address public.

See the https://members.orcid.org/api/oauth/orcid-scopes

**Comment by aalex** [comment]
We could remove the "Log in" and "Sign in" text next to each logo.

**Comment by aalex** [comment]
We must wait for the client application. (sandbox) Some changes in Ego are being reviewed.

**Comment by jberube** [comment]
> We could remove the "Log in" and "Sign in" text next to each logo.

I suggest that we stick to the guidelines of each provider:
https://developers.google.com/identity/branding-guidelines
https://developers.facebook.com/docs/facebook-login/userexperience

**Comment by jberube** [comment]
@aalex can you provide the error messages for the `email.empty` and `email.not.verified` error cases please?

**Comment by jberube** [comment]
Two interesting help topics for error messages:

`email.not.verified`
https://support.orcid.org/hc/en-us/articles/360006894294-How-to-verify-your-email-address

`email.empty`
https://support.orcid.org/hc/en-us/articles/360006897614-Visibility-settings

**Comment by jberube** [comment]
As discussed this morning, I added a killswitch to the feature.

Not setting the environment variable `REACT_APP_ORCID_AUTH_APP_ID` will hide the login button.

**Comment by aalex** [comment]
(QA) I've create some ORCID sandbox users, and then tried to log in, but then there is this error message. The error seems to come from Ego.

![image](https://user-images.githubusercontent.com/293677/60537516-b7accb80-9cd6-11e9-87d7-6784a11097ed.png)

See #1862 for the details.

**Comment by vferretti** [comment]
in the QA login page the button is Log in with ORCID ID. It should be Log in with ORCID
