### ISSUE TITLE
Saving a shared virtual study that is not mine as a new one doesn't work

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1794]
As I user, I want to be able to save a virtual study that has been shared with me as a new one that is mine.

## How to reproduce
- As a user, save a virtual study. Click "Share" in order to get its URL.
- As another user, open the URL of the saved virtual study.
- Clicks "Save as". A dialog should pop.
- It should create a new virtual study that belongs to the user who clicked "Save as". Instead, it doesn't create such a study.

## Screenshot
![image.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/5366b533-0d73-4589-8848-0a2e934fef58)

**Comment by jberube** [comment]
Cannot reproduce.

**Comment by aalex** [comment]
It seems like this issue is no longer valid. It has been fixed, part of some fixes/changes that were done.
Thank you!
