### ISSUE TITLE
Save dialog: pressing enter should close that dialog

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1795]
As a user, I want to be able to close the Save (a virtual study) dialog by pressing Enter or Escape.

## Acceptance criteria
- Pressing Enter should be equivalent to pressing the "Save" button, in the "Save as/save" a virtual study dialog.
- Pressing Escape should cancel.

## Screenshot
![image.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/6d6d5fb7-f584-4f84-92ea-16c317e8132e)

## Technical details
- Changing that will affect all dialogs in the application.

**Comment by aalex** [comment]
(QA) LGTM.
Thank you!

**Comment by vferretti** [comment]
but how can I  have two lines in the description? Also when the cursor is in the description field and we press enter, it looks like it creates a new line and then close

**Comment by aalex** [comment]
That's correct. We should probably remove that feature, then.

One way that could work is the following:

Shift-Enter wouldn't close the dialog, but would create a `<br/>` carriage return.

But then, most users don't know about this Shift-Enter character. (it's standard in many systems)

We should then remove this "Close when Return is pressed" feature: it will be simpler.

**Comment by aalex** [comment]
Closing again, since I've opened a separate issue to track the removal of this feature.
