### ISSUE TITLE
Clicking on a chart crashes the application when the virtual study contains a reference

### ISSUE THREAD

**Issue by jberube** [kids-first/kf-portal-ui#1801]
Create a study with a reference:

![image](https://user-images.githubusercontent.com/373603/58717374-1958dd80-8399-11e9-9f8f-bb79b1b75c18.png)

Then click on any clickable graph:

![image](https://user-images.githubusercontent.com/373603/58717186-a485a380-8398-11e9-9f07-26ab25b9fa76.png)

**Comment by aalex** [comment]
(QA) LGTM. It also works, now.
