### ISSUE TITLE
Change the link of Frequent diagnoses clickable diagrams in the dashboard to point to the cohort buider

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1807]
As users, we want to be able to click on diagrams and they send us to the cohort builder with the right query.

## Acceptance criteria 
 - Change the links in the "Most Frequent Diagnoses" diagram widget so that they point to the cohort builder (see screenshot)
- The diagnosis chart must use the new Diagnosis (Mondo) field.
- Rename its title to "Most Frequent Diagnoses (Mondo)"

## Screenshot
![image.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/6ba4dfd8-d315-49f8-93b2-9da78682daf7)

## Technical details
- We must change the backend (kf-public-stats-api - NodeJS TypeScript) so that it returns the contents of the Diagnosis (Mondo) instead of what it returns now.
- Deploying locally seems to be troublesome: it doesn't communicate with Ego, aparently. 
- We might change it and deploy to QA env.
- See also #1685

**Comment by nyanofthemoon** [comment]
@aalex Appears already done in dev branch. Moving to QA.
