### ISSUE TITLE
Some file entity pages crash the application

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1823]
This page crashes the application:
https://portal.kidsfirstdrc.org/file/GF_MHKCDHT5

Instead, we should either see the file page, or an error page - file not found.

**Comment by jberube** [comment]
The server does not returns the data of the file.

The display of the error could be better.

Maybe we could do a nice display that is usable in both the Participant Entity page and the File Entity page?

**Comment by Velythyl** [comment]
Also, some don't have a participant and since the accessors aren't using lodash it crashes too https://portal.kidsfirstdrc.org/file/GF_YXDSEMQ9

**Comment by denis-crsj** [comment]
Closing issue. Details transferred into Google Sheet : https://docs.google.com/spreadsheets/d/1U1JQZEBEMTP_07PngrmNh8rzbZICTX87Fe_2fEetAbI/edit#gid=0
