### ISSUE TITLE
Participant entity page: show number of files per biospecimen

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1828]
In the participant entity page, I want to know how many files per biospecimen there are, with a link that point to the file repository.

## Acceptance criteria
- Clicking on a number of files should lead to the file repository, with the appropriate filter applied.

## Mockup
![image.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/c972c455-d08b-48a6-af77-79e640b30963)

## Technical details
- See #961

**Comment by Velythyl** [comment]
The number of Files requires a second Query. 

We're not sure if said query is even possible, as it requires either asking the files their related biospecimen or asking the biospecimens their related files. ES is not good for joins and relations of the sort.

**Comment by aalex** [comment]
@Velythyl I think this will be done as part of #961, in the end?

**Comment by jberube** [comment]
No.

**Comment by denis-crsj** [comment]
Closing issue. Details transferred into Google Sheet : https://docs.google.com/spreadsheets/d/1U1JQZEBEMTP_07PngrmNh8rzbZICTX87Fe_2fEetAbI/edit#gid=0
