### ISSUE TITLE
Participant Entity page: Links to these pages from elsewhere in the portal

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1829]
As a user, I want to be able to click on a participant ID in order to land on their participant page.

## Acceptance criteria
- Each place listed above should have a link whenever a participant ID is mentioned.

## Locations of the links
- In the file repository: the column "Participants ID"
- In the cohort builder: the column "Participant ID"
- In the file entity page.

## Screenshots
In the file repository:
![image](https://user-images.githubusercontent.com/293677/59379399-7901a200-8d24-11e9-9dd1-07a37d3f1ce8.png)

In the cohort builder:
![image](https://user-images.githubusercontent.com/293677/59379487-bcf4a700-8d24-11e9-87da-14ca8b6c6712.png)

## Notes
- Implement this feature last, so that it's done only once the participant pages are ready to be shown.

**Comment by claudia1296** [comment]
@aalex Je n'ai pas la colonne participant ID

**Comment by aalex** [comment]
(QA) LGTM

![image](https://user-images.githubusercontent.com/293677/61904850-b2b5f300-aef5-11e9-8100-ccf09ee652af.png)

![image](https://user-images.githubusercontent.com/293677/61904872-c06b7880-aef5-11e9-87d9-cae0dfcef889.png)

![image](https://user-images.githubusercontent.com/293677/61904912-d8db9300-aef5-11e9-8513-0c57c8e66712.png)

That is:
- file repo
- cohort builder
- file entity
