### ISSUE TITLE
Cohort builder: missing border on the last row of the query area (when zoomed)

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1855]
There is a missing border under the last row of the query area in the cohort builder, in prod.

## Screenshot
![image.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/7c9ab72b-27c4-4d37-aaad-bf7ff06bb651)

## How to reproduce
- Perhaps create three (3) queries or more.
- Every row in the query area looks similar (reagrding its borders) except the last one.

## Technical details
- It seems to happen only when we zoom with the browser.
- Also make sure to test how it looks with Firefox

**Comment by aalex** [comment]
I haven't been able to reproduce it. I saw it on Vincent's computer.
We both use Chrome and Ubuntu 18.04.

I use Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)
I also tried Chromium 75.0.3770.90
and Firefox 67.0.4

![image](https://user-images.githubusercontent.com/293677/60135816-8da45800-9770-11e9-89e7-d4c510a6c312.png)

**Comment by rosibaj** [comment]
I am able to reproduce it:  
![image](https://user-images.githubusercontent.com/15824252/60180964-2974a900-97ef-11e9-8671-f964495586ee.png)

It happens when the zoom on my browser is less than 100% 
Chrome Version 75.0.3770.100 (Official Build) (64-bit)
Mac OS

**Comment by jberube** [comment]
@rosibaj Thanks for finding the cause! 👍

**Comment by jberube** [comment]
Setting the height of `.actionButtonsContainer` to 40px instead of 100% fixes it.

**Comment by jberube** [comment]
...but it breaks if the query goes on two lines.
