### ISSUE TITLE
Fixes to the participant page

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1856]
As a user, I want to be able to view a page showing a participant's information.

Here is a list of changes that have been requested. 

## Acceptance criteria
- Remove the "Diagnosis" column in the "Diagnoses" table.
- Remove pagination in tables - always show all rows
- Align left the tabs of the biospecimen table.
- Remove the grey area behind the biospecimen table
- Remove the line on the left of the tabs
- Align the title "Available Data" and "Sequencing Data" and the rest of that section
- Do not put a "Family" section, if there is no family info to show.
- Align the main tabs to the left.

## Screenshots
Remove the "Diagnosis" column in the "Diagnoses" table.
![image](https://user-images.githubusercontent.com/293677/60215521-c1958100-9835-11e9-995a-9fae47878066.png)

Remove pagination in tables - always show all rows
![image](https://user-images.githubusercontent.com/293677/60215456-a7f43980-9835-11e9-8392-335dcfc7b5f6.png)

Align left the tabs of the biospecimen table.
![image](https://user-images.githubusercontent.com/293677/60215246-36b48680-9835-11e9-8e9b-5e1d4674338d.png)

Remove the grey area behind the biospecimen table
![image](https://user-images.githubusercontent.com/293677/60215299-5481eb80-9835-11e9-81bb-afd80801a289.png)

Remove the line on the left of the tabs
![image](https://user-images.githubusercontent.com/293677/60215561-dbcf5f00-9835-11e9-9e71-c44707e02342.png)

"Sequencing Data" and "Other data types" are 2 sub-sections of the main "Available Data" section.
1) make subsection titles smaller than the main section title
2) remove vertical space between Available Data and Sequencing Data titles
3) remove dashed line between the two sub-sections
![image](https://user-images.githubusercontent.com/293677/60215583-f1dd1f80-9835-11e9-8d5e-df35a36165d8.png)

Do not put a "Family" section, if there is no family info to show.
![image](https://user-images.githubusercontent.com/293677/60215605-002b3b80-9836-11e9-9ffe-6e7a867fdf05.png)

- Align the main tabs to the left.
![image](https://user-images.githubusercontent.com/293677/60215831-8ba4cc80-9836-11e9-8137-4fae33c1fe5b.png)

**Comment by jaouad-benassila** [comment]
List of tasks that have been done:
1. Remove the "Diagnosis" column in the "Diagnoses" table.
2. Align left the tabs of the biospecimen table.
3. Remove the grey area behind the biospecimen table
4. Remove the line on the left of the tabs
5. Align the title "Available Data" and "Sequencing Data" and the rest of that section
6. Do not put a "Family" section, if there is no family info to show.

**Comment by Velythyl** [comment]
I just removed the pagination. Working on aligning the tabs

**Comment by aalex** [comment]
(QA) LGTM, so far.

**Comment by aalex** [comment]
We can also remove the "Other Data Types" section, if there is nothing to show in it.

![image](https://user-images.githubusercontent.com/293677/60686575-92a38e80-9e77-11e9-85b7-0ef82d7c9fea.png)
