### ISSUE TITLE
Saved queries: See how long ago it has been saved

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1858]
As a user, I want to be able to see how long ago I've updated, or saved, a virtual study.

## Acceptance criteria
- Show the text "Saved N UNIT ago." under the title of each saved virtual study, in the "Saved queries" widget. (N is the number, UNIT is either "minutes", "hours, "days" or "years")
- Convert to the biggest unit. (details below)
- If it's less than a minute ago, show "Saved less than a minute ago"

## Details of the units
- If it's equal or greater than 60 minutes: use hours;
- but if it's equal or greater than 24 hours, use days;
- but if it's equal or greater than 365 days, use years

## Mockup 
![image](https://user-images.githubusercontent.com/293677/60210536-141d7000-982b-11e9-81de-2e71f626d128.png)

## Technical details
- You can see the how it's done for the saved queries of the file repository.

**Comment by vferretti** [comment]
![image](https://user-images.githubusercontent.com/1181124/62377262-72b3c900-b510-11e9-9d18-850c66cdea8d.png)

here is how it is done for saved file queries. Replicate same behavior and display
