### ISSUE TITLE
(QA) Failure to log in with ORCID

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1862]
As a user, I want to be able to log in via ORCID.

## But report
In the QA environment, it seems like there is an error message that happens when ORCID redirects our browser back to the portal. See the screenshot below.

## Screenshot
![image.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/60cfcb4b-de37-4a6b-8b48-87cbe15e6ed2)

## Technical details
It might be on Ego's side, since there are error messages that indicate an I/O error.

**Comment by aalex** [comment]
It seems to be an IO error, perhaps due to difficulties reaching the ORCID servers.

**Comment by jberube** [comment]
```
{
  "timestamp": "2019-07-02T21:04:11.099+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "I/O error on POST request for \"https://sandbox.orcid.org/oauth/token\": Connection reset; nested exception is java.net.SocketException: Connection reset",
  "path": "/oauth/orcid/token"
}
```
