### ISSUE TITLE
Cohort builder: Make the description of the virtual study bigger

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1867]
Make the description bigger.

## Acceptance criteria
Make the text of the description of the current virtual study 16.66% bigger.

## Screenshot
![image.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/fd7e7bfd-5918-4a40-b9e7-95a523df19d8)

## Technical details
Make the text of the description of the current virtual study 14px instead of 12px.

**Comment by jberube** [comment]
Made in the scope of #1866

**Comment by aalex** [comment]
(QA) LGTM

![image](https://user-images.githubusercontent.com/293677/60686077-d0eb7e80-9e74-11e9-8347-b26704c5db61.png)
