### ISSUE TITLE
Active tab in Cohort Builder is lost

### ISSUE THREAD

**Issue by jberube** [kids-first/kf-portal-ui#1869]
## Issue

The current active tab in Cohort Builder is lost when :
- Loading a study
- Pressing "New"
- Deleting a study

## Technical details

The value `activeView` in the `cohortBuilder` reducer is written over when an action that resets the state is made (any of the above + logout).

Move that value in another reducer that is made to handle UI related values.

**Comment by aalex** [comment]
(QA) LGTM

Thank you!
