### ISSUE TITLE
Long query parameters overlaps the count of participants

### ISSUE THREAD

**Issue by jberube** [kids-first/kf-portal-ui#1872]
In the cohort builder, in the query area, when the queries are long, they might overlap with the count of participants.

Instead, we would like them to never overlap.

## Screenshot
![image](https://user-images.githubusercontent.com/373603/60600998-4bd26d80-9d7f-11e9-9873-c151556594f7.png)

**Comment by jberube** [comment]
https://github.com/kids-first/arranger/pull/5

**Comment by aalex** [comment]
(QA) It seems like the fix no longer works, or has never worked. Perhaps a regression occured? (in the version of Arranger we use, perhaps?)

**Comment by aalex** [comment]
(QA) LGTM

There are edge cases in which they might overlap, but I find that it still looks good when it does.

![image](https://user-images.githubusercontent.com/293677/60917135-3b7a3100-a25e-11e9-960a-e7aa48d1f373.png)
