### ISSUE TITLE
Available Data card: the title on the left of the chart overlaps on Firefox

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1876]
In the "Available Data" card, in the cohort builder, the title on the left of the chart overlaps with the contents of the chart, in Firefox.

Instead, we should make sure there is a small (1-3 px) margin between them, and that they don't overlap.

## Screenshot
![image](https://user-images.githubusercontent.com/293677/60613081-26059280-9d98-11e9-855c-8e5862539601.png)

## Technical details
- See also #1875

**Comment by jberube** [comment]
Fixed by #1898
