### ISSUE TITLE
The ETL crashes in the QA environment

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1878]
The ETL crashes in the QA environment.

## Technical details
We need to run the ETL in the QA environment, so that we can rename the studies, and then test the database migration script. (we need to run the ETL so that the studies have their new names)

**Comment by jecos** [comment]
This is the output log from the last run : 
` java.lang.IllegalStateException: Impossible to fetch data from https://kf-api-dataservice-qa.kidsfirstdrc.org/sequencing-experiment-genomic-files?after=1548012778.613719&study_id=SD_YGVA0E1C&limit=100&visible=true, got statusCode = 502 and body = <html>
INFO   | jvm 1    | 2019/06/28 19:44:21 | <head><title>502 Bad Gateway</title></head>`

Loks like etl got too much 502 bad gateway responses from dataservice

**Comment by aalex** [comment]
We often - but not always - get 502 bad gateway errors when we do REST calls to the data service. Sometimes it works. There might be a proxy service that didn't get a response from the data service.

**Comment by jecos** [comment]
it works now
