### ISSUE TITLE
Member page: Search and filter members

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1887]
As a user, I want to be able to search among the members of the portal.

## Acceptance criteria
- Provide a text field for the search.
- Display the results in the table.
- For the text search, search within the fields listed below.
- Provide a list of clickable research interests to be searched for.
- Provide a list of clickable profile types to be searched for.

## Fields to consider for the text search
- concatenated firstName and lastName
- institution
- state

## Fields to consider for other search types
- profile type (role)
- research interests

## Fields not to consider for the search
- firstName
- lastName
- jobTitle
- city

## Mockup
TBD

## Technical details
- The contents of the `role` field can be: ` ["research", "community", "health", "patient"]` - display the same value as in the member page.

**Comment by jberube** [comment]
Merge with #1881
