### ISSUE TITLE
Styling simplification for the reset zoom button

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1895]
As a user, I want to be able to reset the zoom of the overall survival chart. I also want the user interface to be rather simple and lean.

## Acceptance criteria
- In the "Overall Survival" chart in the cohort builder, change the "Reset zoom" button so that it has no border, and no text. Make its icon bigger. (see mockup)
- Add the tooltip text "Reset zoom" when one mouses over it.

## Mockup
![image.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/31f7c9b8-b8b5-42d3-834b-81d75f4a9ef4)

# See also
- See #1467

**Comment by aalex** [comment]
LGTM, but:

Now, when we are already in the default zoomed out view, the button is still enabled, and we can click on it. (and the tooltip appears) It seems to me like the behaviour changed.

This is in QA:
![image](https://user-images.githubusercontent.com/293677/60918616-c27cd880-a261-11e9-9b0a-9d4ecfc0014c.png)

This is in prod: 
![image](https://user-images.githubusercontent.com/293677/60918709-fc4ddf00-a261-11e9-973b-fb87621588dd.png)

**Comment by nyanofthemoon** [comment]
@aalex Ok, so when it is disabled: no click and no tooltip.

**Comment by aalex** [comment]
(QA) LGTM

Thank you!

![image](https://user-images.githubusercontent.com/293677/60923042-0d035280-a26c-11e9-9d32-4c3f294a92ae.png)
