### ISSUE TITLE
Age at diagnosis chart: use a comma for ranges

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1903]
As a researcher, I want to see the age range shown in a scientific notation.

## Acceptance criteria
- Use ", " as a separator between the "from" and "to" values under each column of the chart.
- Use a closing parenthesis (")") for open interval, that does not include its endpoint.

## Example
Show: `[0, 5)` and `[5, 10)`

Instead of `[0 - 5[` and `[5 - 10[`

## Screenshot
![image](https://user-images.githubusercontent.com/293677/60746597-87229700-9f4d-11e9-9fa9-7bd12a92c01c.png)

**Comment by baileyckelly** [comment]
Is there an ETA in this? We need this fixed for the July meetings.

**Comment by aalex** [comment]
@baileyckelly It should be released in production this week. (probably tomorrow - Tuesday)

**Comment by aalex** [comment]
(QA) LGTM

![image](https://user-images.githubusercontent.com/293677/60914510-a7a56680-a257-11e9-9e64-71cc8325c80f.png)
