### ISSUE TITLE
Download Manifest (Participant and Family) UI Updates

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#192]
- [x] 1: Please update the summary counts as described in the new design, also the information for family members (see screenshot below in expected section) --> note: it shows the number of family members for each data type
- [x] 2: the data types should be displayed in the inactive state (grey) until checked, then they should move to active state ( blue)
- [x] 3: the user should be able to click the whole row, not only the checkbox to select data type he wants 
- [x] 4: the count of files displayed in the family member section should exclude the files that are already listed in the File summary

**Current:**
<img width="833" alt="screen shot 2018-03-15 at 2 50 11 pm" src="https://user-images.githubusercontent.com/8812383/37484920-5c87f20c-2860-11e8-8403-923cea7e3ae7.png">

**Expected: *
<img width="618" alt="screen shot 2018-03-15 at 2 51 44 pm" src="https://user-images.githubusercontent.com/8812383/37484940-6926e824-2860-11e8-8c82-9fd58d1ef6b2.png">

https://invis.io/MQFHWABDK9Y#/280440053_01d-KF-Smart-Filters-Family-Files-Manifest-Overlay

**Comment by hlminh2000** [comment]
Closing as the merge has addressed all points mentioned

**Comment by rosibaj** [comment]
@hlminh2000 I just took a closer look here, and the first point (about the summary counts) is actually not done.  If you look at the design, the summary stats on this modal are actually different!  WE can put this is another ticket if you prefer though - lmk.
