### ISSUE TITLE
Cohort builder: The line height of the description of the virtual study is too high

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1921]
As a user, I want to saved queries and give them a title and a description.

## Bug report
For multi-line descriptions, there is a wide space between each line. Instead, we want the line height to be one-line high. Two new lines in a row should end up in creating a space, though. (think like a pre tag)

To summarize:
- each line takes the height of one line
- empty lines are still shown
- empty lines at the end of a description are trimmed

## Screenshot
![image.png](https://images.zenhubusercontent.com/5c55147e9ec3935c16660666/6b0b0369-ddd0-4831-8566-3ee1bf4b5194)

## Examples
These examples should be rendered like they are rendered here, but with a regular font.

```
This is a multi-line description.
This is a multi-line description.
```

```
This is a description with an empty line in the middle.

This is a description with an empty line in the middle.
```

**Comment by aalex** [comment]
(QA) 
![image](https://user-images.githubusercontent.com/293677/60922675-44253400-a26b-11e9-80d6-f02f0625c1e3.png)

**Comment by aalex** [comment]
My description in the screenshot above is:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce convallis iaculis leo vitae laoreet. Nullam non ex quis enim eleifend laoreet. Nullam tempus ligula quam, sed dictum ligula scelerisque tincidunt. Sed eget volutpat orci, dapibus dignissim enim. Maecenas sit amet ante ac nibh maximus lob
```

**Comment by nyanofthemoon** [comment]
Needs moar details.

**Comment by aalex** [comment]
This is the current state of the description in QA:

![image](https://user-images.githubusercontent.com/293677/60984174-3de59500-a309-11e9-9873-a0356e18c5b2.png)

We no longer see the whole description. Instead:

- we want to see the whole description.
- what we initially wanted is simply to avoid having a big line height.
- Wrapping the lines would be best.

## Screenshot
![image](https://user-images.githubusercontent.com/293677/60984289-784f3200-a309-11e9-9b38-a3e32f2c8ccd.png)

**Comment by aalex** [comment]
How it's done in the dashboard widget for my "saved queries" is ok:

![image](https://user-images.githubusercontent.com/293677/60984596-f8759780-a309-11e9-9104-6d3e66f4096e.png)

**Comment by aalex** [comment]
See #1937 for more changes. 

The rest is good. Thank you!
