### ISSUE TITLE
Fix the name of the SNOMED fields in the file repository

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1948]
We need to fix the name of the SNOMED fileds in the file repository.

## Acceptance criteria
- Rename "Snomed Phenotype Not Observed" to "Not Observed Phenotype (SNOMED)"
- Rename "Snomed Phenotype Observed" to "Observed Phenotype (SNOMED)"
- Rename "Participants:Family:Family Compositions:Family Members:Phenotype:Snomed Phenotype Not Observed" to "Shared Not Observed Phenotype (SNOMED)" :question: 
- Rename "Participants:Family:Family Compositions:Family Members:Phenotype:Snomed Phenotype Observed" to "Shared Observed Phenotype (SNOMED)" :question: 
- See the field names below.

## Fields
In file-centric:
- participants.phenotype.snomed_phenotype_not_observed
- participants.phenotype.snomed_phenotype_observed
- participants.family.family_compositions.family_members.phenotype.snomed_phenotype_not_observed
- participants.family.family_compositions.family_members.phenotype.snomed_phenotype_observed

## Technical details
- Renaming the fields should involve changes in the Arranger admin UI, and maybe some changes in the code for the UI as well.
- See #1805 

## Questions
- Are the field names correct?
- Should we add those fields in the cohort builder as well?

**Comment by vferretti** [comment]
won't fix
