### ISSUE TITLE
Participant page: add PedcBioPortal link

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1950]
Participants of the CBTTC study need a link to their page on PedcBioPortal.

## Acceptance criteria
- Add a field in the summary table for the participants part of the CBTTC study. (use if kf_id to identify the study) - Only the participants from that study must have this field.
- The name of the field is: "PedcBioPortal"
- The contents text is their participant ID. (PT_XXXXXX)
- That text will be a link to the PedcBioPortal (see the URL below) with their participant ID in the URL.

## URL
The URLs for PedcBioPortal are:
```
If Study ID = SD_BHJXBDQK, then
https://pedcbioportal.kidsfirstdrc.org/patient?studyId=pbta_cbttc&caseId=<pt_id>
If Study ID = SD_M3DBXD12, then
https://pedcbioportal.kidsfirstdrc.org/patient?studyId=pbta_pnoc003&caseId=<pt_id>
```

**Comment by aalex** [comment]
So far, it seems like the link will be `https://pedcbioportal.kidsfirstdrc.org/patient?studyId=phgg_cbttc&caseId=<pt_id>` - to be confirmed.

**Comment by claudia1296** [comment]
@aalex Je ne comprend pas peux-tu venir me voir ?

**Comment by vferretti** [comment]
The URLs for PedC are:

If Study ID = SD_BHJXBDQK, then
`https://pedcbioportal.kidsfirstdrc.org/patient?studyId=pbta_cbttc&caseId=<pt_id>`
If Study ID = SD_M3DBXD12, then
`https://pedcbioportal.kidsfirstdrc.org/patient?studyId=pbta_pnoc003&caseId=<pt_id>`

**Comment by aalex** [comment]
(QA) URL to view a page that should have the link: https://kf-qa.netlify.com/participant/PT_00G007DM#summary

(right now, there are errors with those pages, though)

**Comment by aalex** [comment]
(QA) LGTM

![image](https://user-images.githubusercontent.com/293677/61904547-096efd00-aef5-11e9-9667-b18d4f04373c.png)

**Comment by aalex** [comment]
(QA) PNOC also has it:

![image](https://user-images.githubusercontent.com/293677/61905228-9c5c6700-aef6-11e9-9c31-b4057d1aec91.png)

**Comment by aalex** [comment]
(QA) Those for the other studies don't have it, as expected.

![image](https://user-images.githubusercontent.com/293677/61905339-d7f73100-aef6-11e9-959e-dfd23a2434f0.png)
