### ISSUE TITLE
Member page: invites members to make their profile public.

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1954]
As a user, I need to know that there is a new option to make my profile public, so that I can make it public, if I want.

Let's create a one-time dismissable banner that invites people to make their profile public.

## Acceptance criteria
- In the dashboard, show a banner with the text and link detailed below ( only when user's profile is private).
- Users can click the close ('x') button to dismiss the banner.
- Once dismissed, it doesn't appear again ever.

## Text and link
- Text: "Make your profile public so that other members can view it!" - The text of the link is "Make your profile public".
- Link: /profile

## Mockup
![image](https://user-images.githubusercontent.com/293677/61405229-427cf100-a8a7-11e9-8de9-e26deb3422af.png)

**Comment by evans-g-crsj** [comment]
Reminder: add a switch in the member page to toggle from "isPublic" to "isPrivate" and vice versa.

**Comment by jecos** [comment]
When I set my profile to public, The banner is still displayed until i refreshed the browser @evans-g-crsj
