### ISSUE TITLE
Null dates are rendered as an invalid date

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1960]
As a user, if a date is unkown, I want to see no data, instead of invalid data.

## Steps to reproduce
- Go to https://portal.kidsfirstdrc.org/file/GF_2EAKX5WW
- The date shown for the field "Experiment Date" is "1969-12-31", but should be "--".

Note that there are other locations where this can occur. :question: 

## Screenshot
![image](https://user-images.githubusercontent.com/293677/61744534-8b302080-ad65-11e9-8e72-940c76e0c1e2.png)

## Technical details
- The date for that file is null in the data service.
- Null dates are rendered as UNIX epoch minus one day.
- It should be fixed in the UI.

**Comment by aalex** [comment]
Question: Where else can it occur, in the portal?

**Comment by jecos** [comment]
Check with @nyanofthemoon this is a UI issue

**Comment by nyanofthemoon** [comment]
`experiment_date: pickData(se, 'experiment_date', d => format(d, 'YYYY-MM-DD')),` should check if date is null to not report epoch -1 as 1969-xx-dd using `import { format } from 'date-fns';`. Put an empty string if `experiment_date` is null rather than evaluate null as a date value.

**Comment by aalex** [comment]
(QA) Trying to view the file entity page, but there is an error.

![image](https://user-images.githubusercontent.com/293677/61826325-31e0f380-ae30-11e9-91da-6e9e8b8ee229.png)

**Comment by aalex** [comment]
(QA) LGTM

![image](https://user-images.githubusercontent.com/293677/61888999-a8363200-aed2-11e9-9144-13a896eae65d.png)
