### ISSUE TITLE
Fixes to the Family Table in the Participant page

### ISSUE THREAD

**Issue by Velythyl** [kids-first/kf-portal-ui#1969]
See https://github.com/kids-first/kf-portal-ui/issues/964

This fix is to take the new Family mapping as input (since the ETL was changed for the families).

This new family input allows to stop querying all family members every time we try to load the table. Now, everything is inside the family members aggregation.

Also, the join we use to create the rows was improved by going for a more concise functionnal style.

https://kf-qa.netlify.com/participant/PT_6FEYZN0H#clinical

https://kf-qa.netlify.com/participant/PT_5AAEG153#clinical

**Comment by aalex** [comment]
(QA) LGTM

![image](https://user-images.githubusercontent.com/293677/61905879-25c06900-aef8-11e9-9bbd-2355addd3a62.png)
