### ISSUE TITLE
Fixes to the participant page

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1981]
More changes have been requested in QA for the participant page.

## Acceptance criteria
- Remove loading message in the clinical tab
- Sequencing data table: Make links more visible
- remove scrollbar under the two biospecimen tables
- Make all links are purple (90278e)

## Screenshots
![image](https://user-images.githubusercontent.com/293677/61968304-adb07c80-afa5-11e9-9dbb-f07d1afbcf99.png)

![image](https://user-images.githubusercontent.com/293677/61968329-c15be300-afa5-11e9-8c4e-2c33f701d8fe.png)

**Comment by vferretti** [comment]
mettre sur une ligne la colonne 1 du dernier tableau
