### ISSUE TITLE
UI for Login

### ISSUE THREAD

**Issue by cy** [kids-first/kf-portal-ui#20]
UI for login as different Personas; takes token from Ego and persists/retrieves profile from Persona

**Comment by phuongmy** [comment]
Specifications to create user account: https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/215613462/Log+in+and+create+account
Specification to fill-in user profile: https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/385744922/User+Profile
