### ISSUE TITLE
Rename study "Consortium: Pediatric Brain Tumors - CBTTC" to "Pediatric Brain Tumor Atlas: CBTTC"

### ISSUE THREAD

**Issue by jberube** [kids-first/kf-portal-ui#2003]
During the deployment of 2.7.0, the study `Consortium: Pediatric Brain Tumors - CBTTC` should have been renamed to `Pediatric Brain Tumor Atlas: CBTTC` in saved virtual studies and urls in riff, but it wasn't.

**Comment by jecos** [comment]
Done
