### ISSUE TITLE
Cohort Builder: Hyperlink to Mondo not built in some cases 

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#2033]
For some reasons, the hyperlink to Mondo is not built in some cases. 
Select study Kids First: Congenital Heart Defects in the CB and parse the list of returned participants

![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/74394315-b20b-4e49-9d76-fbc21953ca79)

**Comment by jberube** [comment]
Duplicate of #2020
