### ISSUE TITLE
Participant clinical table(s) have no loader displaying when server's slow

### ISSUE THREAD

**Issue by evans-g-crsj** [kids-first/kf-portal-ui#2074]
As a user when I go the the view displaying clinical data (url : https://kf-qa.netlify.com/participant/Participan_ID#clinical or explore data -> tableview -> click on a participant -> go to clinical tab ), I want to see a loader for each table while it's respective data is fetching.

Current problem, when the server is slow and there are multiple tables what happens is that sometimes I see a table and a moment later I see other tables popping out but nothing indicated me that those table were to show up. 

In parallel, this component should be Refactored because the code seems too convoluted. Idea : split the component in two components (smart && dump component) and use redux thunk for api calls and so on...

**Comment by denis-crsj** [comment]
Closing issue. Details transferred into Google Sheet : https://docs.google.com/spreadsheets/d/1U1JQZEBEMTP_07PngrmNh8rzbZICTX87Fe_2fEetAbI/edit#gid=0
