### ISSUE TITLE
File Repository: Facet with no value is displayed

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#2077]
Go to https://p.kfdrc.org/s/3ct
and look at the Observed Phenotype facet on the left. There is no value and then it should not be displayed at all. 

![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/12a3743a-2ac9-44c9-ae33-836139c3763d)

**Comment by jberube** [comment]
Seems to have the same root cause as #2089 .

**Comment by jberube** [comment]
It has been decided that we will make a UI fix.

We will add a message like "There is no data for this cohort." in the filter (message to be confirmed).

This will also solve #2089 .

**Comment by jberube** [comment]
Here is an example:

![image](https://user-images.githubusercontent.com/373603/67697604-34973b80-f97f-11e9-87d9-d5acfbcbeefd.png)

**Comment by jberube** [comment]
Here is  what it looks like in the File Repository's facets:

![image](https://user-images.githubusercontent.com/373603/67708857-47b40680-f993-11e9-99dd-0d223c74af8f.png)
