### ISSUE TITLE
Analyze in Cavatica after opening entity page directly does not work

### ISSUE THREAD

**Issue by jecos** [kids-first/kf-portal-ui#2088]
**Scenario 1 (works fine) :** Go to the file repository, open a file then click on Analyze in Cavatica => it works

<img width="1126" alt="works" src="https://user-images.githubusercontent.com/1424506/65627563-a0137500-df9d-11e9-9414-6d1a97ba4f24.png">

**Scenario 2 :**  Open directly the file entity page  (ex.:https://portal.kidsfirstdrc.org/file/GF_26JGDSZ8) in a new tab, click in Analyze in cavatica => FAIL

<img width="1240" alt="failed" src="https://user-images.githubusercontent.com/1424506/65627539-9558e000-df9d-11e9-9429-8ae5c2de1b3c.png">

Technical detials : The reason is that there is no state managed in file entity page.

**Comment by jberube** [comment]
@evans-g-crsj is this in QA, yet?
