### ISSUE TITLE
Participant page: Do not repeat diagnoses and phenotypes that are not shared with other family members in the family table

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#2091]
see https://portal.kidsfirstdrc.org/participant/PT_N35R1FCW#clinical

the family table. Doesn't make sense to repeat all these diagnoses and phenotypes if they are not shared. 
We should only show shared items in this table.

**Comment by vferretti** [comment]
Rename this table with Shared Diagnoses and Phenotypes with Family members

**Comment by evans-g-crsj** [comment]
After discussion, 

rename the table with : Participant's phenotypes/diagnoses shared with other family's members

the rules to show dx en phenotypes rows are :  1) participant column must not be empty 2) at least one family member must share the same value.
