### ISSUE TITLE
use css vs inline style (at least in member pages)

### ISSUE THREAD

**Issue by evans-g-crsj** [kids-first/kf-portal-ui#2153]
As a dev, I want to use css vs inline styles when styling my components in order to make better code reuse and possibly improve performance (even though is it's probably negligible).

For example : <div style={{ paddingRight: 120 }}> =>  <div className="myCss">.

where: ideally, in all the application but let's focus on the member page section first.

**Comment by adipaul1981** [comment]
Member page was redone. This task is not applicable now.
