### ISSUE TITLE
Login with ORCID: error messaging

### ISSUE THREAD

**Issue by chris-s-friedman** [kids-first/kf-portal-ui#2182]
We received a support request for someone having an issue setting up an account with orcid - They got the error that they did not have their email shared with trusted parties. On the orcid account settings site, it isn't really clear what a user has to change. Our error message says `share your email address either with "Trusted Parties" or "Everyone".`  but that s`hare your email address with ...` language isn't on the account settings page in orcid. I sent them this screenshot. 

![Untitled](https://user-images.githubusercontent.com/17438916/70454365-51dc2100-1a78-11ea-86e7-c612981fb048.png)

I'm thinking that it may be helpful to update the language in our error message to make it more clear what a user has to change in their orcid settings.

**Comment by jecos** [comment]
@chris-s-friedman  we can easily change the wording. Do you have a suggestion?

This is the entire message we display in this case : 
<img width="779" alt="Screen Shot 2020-01-08 at 1 37 31 PM" src="https://user-images.githubusercontent.com/1424506/72005680-2fc2f380-321c-11ea-820f-e851249b1186.png">

As you can see, we already mention to update the email sharing preference.

**Comment by chris-s-friedman** [comment]
@bdolly probably has some thoughts on this.

**Comment by denis-crsj** [comment]
Closing issue. Details transferred into the Google Sheet : https://docs.google.com/spreadsheets/d/1U1JQZEBEMTP_07PngrmNh8rzbZICTX87Fe_2fEetAbI/edit#gid=0
