### ISSUE TITLE
Prevent user from downloading reports simultaneously

### ISSUE THREAD

**Issue by jecos** [kids-first/kf-portal-ui#2202]
How to reproduce
- User click on download clinical reports 
- Message "Please wait while we generating your report" is displayed
- User can still click on download clinical reports 
- Message "Please wait while we generating your report" is displayed twice and two reports are fenerating simulteneously
![Screen Shot 2020-01-02 at 9.47.36 AM.png](https://images.zenhubusercontent.com/5cab6ac920cddd7cf9ba5b40/6c48c325-f2ed-4dda-b8e5-cb4b4c7a2bce)

# Bugs
- Sequences of actions: the following filters are selected (study = "neuroblastoma", diagnostic category="cancer"):
![rapport](https://user-images.githubusercontent.com/12585875/85779381-88664a00-b6f1-11ea-9e1e-5ab9ba160dd8.png)

1. The download of the report of the participants (participants only) should give that those with a category of diagnosis = cancer, which is not the case (some participants do not have a diagnosis for example)

![rapport](https://user-images.githubusercontent.com/12585875/85780743-f0696000-b6f2-11ea-8c15-f1a2a0809a66.png)

2. In the Phenotypes tab, participants without phenotypes should not be displayed
![rapport](https://user-images.githubusercontent.com/12585875/85781103-56ee7e00-b6f3-11ea-8b25-029836441cca.png)

**Comment by evans-g-crsj** [comment]
all reports (cohort builder & file repository) are the same.

**Comment by Emma-Drieux** [comment]
@evans-g-crsj j'ai mis deux remarques sur Bugd, j'en rajouterai si j'en vois d'autres

**Comment by evans-g-crsj** [comment]
@Emma-Drieux what you reported is valid, but it's another issue. I suggest we create a new ticket for this.

**Comment by evans-g-crsj** [comment]
Should be better. Some rows repeat themselves but that s another issue we should take care of later on.

**Comment by Emma-Drieux** [comment]
The first bug is resolved. The second which concern the phenotypes will be reported in another story
