### ISSUE TITLE
Public page: Find me on - Add value as text instead of static label

### ISSUE THREAD

**Issue by jecos** [kids-first/kf-portal-ui#2235]
On public page > About me > Contact Information > Find me on

Instead of displaying 
Website 
Twitter
Github
...

Display corresponding values. For instance :
www.mysite.com
@jecos 
jecos

![Screen Shot 2020-01-10 at 2.39.22 PM.png](https://images.zenhubusercontent.com/5cab6ac920cddd7cf9ba5b40/44c7204f-7136-48df-ac7a-553a5030dd42)

**Comment by denis-crsj** [comment]
Transferred into the Gooogle Sheet : https://docs.google.com/spreadsheets/d/1U1JQZEBEMTP_07PngrmNh8rzbZICTX87Fe_2fEetAbI/edit#gid=0
