### ISSUE TITLE
Handle error messages on data portal coming back from Cavatica copy

### ISSUE THREAD

**Issue by phuongmy** [kids-first/kf-portal-ui#226]
Please handle the blabla :)

We should display on the data portal error messages coming back from Cavatica.

Example:
The user wants to copy files to Cavatica (has everything set up in the portal for it) but he has not connected GEN3 on his Cavatica account. In this scenario the copy will fail. We should indicate it to the user and tell him what to do.

Need help from @kcullion  on the error messages design?

**Comment by kcullion** [comment]
@phuongmy @joneubank yes I was hoping to design the messages in a consistent way. Jon, would you be able to send me some screenshots of the different types of messages?
