### ISSUE TITLE
Profile Page: Settings: arbitrary use of color 

### ISSUE THREAD

**Issue by bdolly** [kids-first/kf-portal-ui#2265]
![Screen Shot 2020-01-21 at 10 47 47 AM](https://user-images.githubusercontent.com/1334131/72820124-6f3a0880-3c3c-11ea-8a04-9aff63e5d1cb.png)
The red color for this button is not present in any of the other Kids First properties and is thus inconsistent with existing branding elements. It is recommended to use `#d82030` as this value is used in the Kids First website

**Comment by evans-g-crsj** [comment]
Good point.
