### ISSUE TITLE
File repository : styling issue in Browse All modal

### ISSUE THREAD

**Issue by jecos** [kids-first/kf-portal-ui#2267]
@jecos commented on [Tue Jan 21 2020](https://github.com/kids-first/kf-api-search-members/issues/20)

See attached file :
![Screen Shot 2020-01-21 at 11.20.55 AM.png](https://images.zenhubusercontent.com/5cab6ac920cddd7cf9ba5b40/2d88b2c7-5e9c-4406-8d88-41e5ef6ccd56)

**Comment by evans-g-crsj** [comment]
It's most probably broken because of the big refactor that was made for the build process. We will not investigate further since that UI will change.
