### ISSUE TITLE
User Settings design review

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#227]
- [x] Zeplin has a slightly new layout for the settings page where the headlines are above the items - this would be better on smaller screens
<img width="1620" alt="screen shot 2018-03-14 at 12 55 28 pm" src="https://user-images.githubusercontent.com/18424138/37418775-64c61f70-2789-11e8-930b-2fdf4c1f7e0e.png">

- [x] The connect, edit, delete buttons should match the same button style throughout the portal and profile
- [x] This section was renamed to just "Settings" within the left sidebar (see mockup)
- [x] The links within the table should be the standard brand purple: #a42c90 with hover state #c03299

- [x] please update CAVATICA modal styling:
![screen shot 2018-04-17 at 4 41 59 pm](https://user-images.githubusercontent.com/18424138/38895541-569adcfc-425e-11e8-8bc2-8c97e4d07f9f.png)

- [x] please update GEN3 modal styling:
  
![screen shot 2018-04-17 at 4 46 50 pm](https://user-images.githubusercontent.com/18424138/38895801-085c0cd6-425f-11e8-9913-6a4e0e714079.png)

**Comment by rosibaj** [comment]
@hlminh2000 also forgot to say the new headers look great!!!

**Comment by hlminh2000** [comment]
touched up! :D Thank you for the review @rosibaj :)
