### ISSUE TITLE
Support UI tag system

### ISSUE THREAD

**Issue by phuongmy** [kids-first/kf-portal-ui#228]
In the user profile page, a user should be able to add research interests.
We want this to be a free text field so KF users will populate their own database of interests.

Please provide UI support for a tag system. Users should be able to add tags to their user profile:

- by selecting amongst the existing tags
- by creating a new tag if it does not exist

Design:
1- Research interests displayed on the user profile: https://invis.io/MQFHWABDK9Y#/276423115_21-KF-Researcher-Profile-Filled
2- Create a new research interest: https://invis.io/MQFHWABDK9Y#/280722992_20d-KF-Researcher-Profile-Edit-Interests-Autofill

Note: the backend support was completed by https://github.com/kids-first/kf-portal-ui/issues/81

**Comment by rosibaj** [comment]
@jgnieuwhof good news!  When i add a tag on one profile, it no longer shows up as a new interest on other profiles 👍. 

A couple issues more issues remain still:
1) Autocomplete is not working correctly. When a user types, 
- they should see all terms that could possible match the types interest (whether it is at the beginning, middle or end of the tag) 
- the word that autocomplete is  matches should be highlighted
![screen shot 2018-05-28 at 10 55 36 am](https://user-images.githubusercontent.com/15824252/40620146-c18bd620-6265-11e8-8583-3b87fbdab136.png)

Currently, it will only match the EXACT term.  For example, BOTH of these screenshots should suggest "hello" as an interest.
<img width="532" alt="screen shot 2018-05-28 at 10 43 35 am" src="https://user-images.githubusercontent.com/15824252/40619681-fee25898-6263-11e8-91db-2e0bb4af982a.png">
<img width="494" alt="screen shot 2018-05-28 at 10 43 30 am" src="https://user-images.githubusercontent.com/15824252/40619682-feef94f4-6263-11e8-8917-39780b944a48.png">

**Comment by jgnieuwhof** [comment]
@rosibaj - the highlighting issue is totally addressable, will do. re: the partial match issue, I don't _think_ mongodb provides partial match full-text search out of the box. I'll look into it a little more, but the partial match requirement may need to be part of a larger conversation regarding persona.

**Comment by rosibaj** [comment]
@jgnieuwhof This looks great for now!   Maybe we can summarize your concerns with the matching solution that you put in place when you are back so that later we can fix that if needed?
