### ISSUE TITLE
Improve code style

### ISSUE THREAD

**Issue by evans-g-crsj** [kids-first/kf-portal-ui#2300]
The source code is not really consistent with regard to code style. For example, sometimes that kind of spacing is used **{a:b}** vs **{ a:b }** or l**et a = 'I will never change'** vs **const a = 'I will never change'**.

A more heterogeneous code style would enforce better consistency.

Improve code style in the source code by adding rules to eslint (or any other tool(s) that could improve our code style).

**Comment by francisl** [comment]
@evans-g-crsj I updated eslint to be a little closer to airbnb, plus I added auto formatting with prettier. So that kind of inconsistencies will by automaticaly addressed.

If we need to make the rules sticker, I think we should open another issues. Aggree?
