### ISSUE TITLE
Should we use a logging framework in persona and/or portal-ui?

### ISSUE THREAD

**Issue by evans-g-crsj** [kids-first/kf-portal-ui#2306]
At this point in time, no logging framework is used in persona or portal-ui.

We should discuss and analyse if adding such a framework would be a benefit. For instance, we could add logging when debugging or avoid logging messages to the end-user in production or add tags for better filtering in aws cloud watch (for persona).

Take a decision if it'd be worth it.

**Comment by denis-crsj** [comment]
Closing issue. Details transferred into the Google Sheet : https://docs.google.com/spreadsheets/d/1U1JQZEBEMTP_07PngrmNh8rzbZICTX87Fe_2fEetAbI/edit#gid=0
