### ISSUE TITLE
Scroll bar appears unnecessarily when little content is showing in 'Saved Queries' card in the dashboard 

### ISSUE THREAD

**Issue by evans-g-crsj** [kids-first/kf-portal-ui#2322]
In the Dashboard, cards have a fixed height. Sometimes their content elements use up more space than the fixed height. When it happens a scroll bar mus appear.

The 'Saved Queries' card shows a scroll bar even when the content elements fit in the available space.

Remove the scroll bar when not needed.

Note: its seems that this problem appears only on some browsers. This version of chrome makes the bug appears (Version 80.0.3987.116 (Official Build) (64-bit))![screenshotOverFlowSavedQueries.png](https://images.zenhubusercontent.com/5d6419eca4c8f41d47fc9940/50f709d0-7810-48a9-ad58-e38e18b671e0)

**Comment by denis-crsj** [comment]
Closing issue. Details transferred into the Google Sheet : https://docs.google.com/spreadsheets/d/1U1JQZEBEMTP_07PngrmNh8rzbZICTX87Fe_2fEetAbI/edit#gid=0
