### ISSUE TITLE
Improve behaviour for 'Search Files by Participant ID' filter (File Repository)

### ISSUE THREAD

**Issue by evans-g-crsj** [kids-first/kf-portal-ui#2332]
Filtering can be used in the file repository to search for particular file(s). Many facets exist in the side menu for that. The **Search Files by Participant ID** lists all files related to a participant given its ID.

![screenshotSearchFilesByParticipantIDExample.png](https://images.zenhubusercontent.com/5d6419eca4c8f41d47fc9940/66970a98-f6ae-4a1d-b599-b0376f3922d4)

The list of IDs displayed to the user is meaningless to him/her.

Instead, the facet should be conceptually and visually more meaningful. For that, the search results and the behaviour after clicking a selection should be changed.

In order to achieve that, these changes need to be made: 

1. when the user types-in a query in the input all matching participants are shown (instead of related files).
2. When a selection is made only the file(s) related to the participant are displayed
3. The query header should display : **Participant ID: <id_of_the_selection>**
![screenshotExampleSearchPartId.png](https://images.zenhubusercontent.com/5d6419eca4c8f41d47fc9940/8e3b6ab8-8364-411f-9eb4-bd92faf253ec)

Note: the behaviour should be similar to the one resulting from the view results of the 'UPLOAD YOUR LIST OF IDS' modal.
![screenshotBehaviour.png](https://images.zenhubusercontent.com/5d6419eca4c8f41d47fc9940/ba06efc4-6c3c-431f-969c-16c73718798a)

### Sub-tasks
- [x] participant filter
- [x] biospecimen filter
- [x] file filter

**Comment by evans-g-crsj** [comment]
Contrary to before, no suggestion is shown. The user must know what id he/she wants to use to filter.

For the participant filter the following ids can be used: kfId or externalId;
For biospecimen: kfId, external sample id or external aliquot id;
For file: external, filename or kfid

![screenshotExample](https://user-images.githubusercontent.com/54366437/84675411-3572e280-aefa-11ea-9281-4acf4aab737a.png)

![screenshotFileFilter](https://user-images.githubusercontent.com/54366437/84675416-360b7900-aefa-11ea-925b-5502fce50da0.png)

![screenshotClinicalFilters](https://user-images.githubusercontent.com/54366437/84675417-36a40f80-aefa-11ea-9fe6-2dacdc7da527.png)

**Comment by denis-crsj** [comment]
Tested successfully. Moving the task to Done
