### ISSUE TITLE
fix(cohort builder): category menu has incorrect behaviour

### ISSUE THREAD

**Issue by evans-g-crsj** [kids-first/kf-portal-ui#2367]
It is possible in the explore page to build a query. Various menus are used to do that.

The category-type-menu is broken on Firefox (reproduced on version 74.0 (64-bit)). It must be corrected since it can confuse the user.

1) on Linux AND MacOS, go on the explore page, then select a category menu and check a few boxes so that the apply button appears green.

![screenshotCategoryMenu1.png](https://images.zenhubusercontent.com/5d6419eca4c8f41d47fc9940/cc679874-dd22-4423-bd8a-534d19356515)

Then, change the option (e.g. "any of" -> "all of"). You will notice that the apply button becomes disabled unless a checkbox is selected or re-selected.

![screenshotCategory2.png](https://images.zenhubusercontent.com/5d6419eca4c8f41d47fc9940/35b89926-1ed5-4a4c-b016-b54aa9827d46)

It should stay green if the logic allows it.

On macOS ( reproduced on Mojave 10.14.6 ) another problem showed up. As reported in a conversion on Slack:

> When I tried to change the "any of" to "all of" in the cohort builder in Firefox, I can't actually select it, the menu appears for a split second and then disappears 

> basically, the menu when I click the blue arrows doesn't stay dropped down, so I can't select "all of"

The steps to reproduce are pretty the much the same as the ones explained in the first issue. 

The menu must not disappears when the option is changed.

### Sub-tasks
- [x] Apply button must not be disabled when there are checkboxes and the select menu changes
- [x] (MacOS) menu must not disappear

**Comment by denis-crsj** [comment]
Tested on Firefox version 77.0.1 (64-bit) and on MacOS 10.15.5
