### ISSUE TITLE
Variant DB - Clinvar annotation (Phase I)

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#2369]
Our Clinvar Data Source will be https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/clinvar.vcf.gz
See parent directory for Readme.txt and others. 

This VCF file contents only annotations on SNV variants which will be sufficient for now. 

We aim to
  - Import this file into parquet files and create a clinvar table
  - Join this table with the Variant table based on variant definition and location
  - Add, as a first step, the clinvar ID and clinvar clinical significance field to the Variant table

The clinical significance field is populated using 2 fields from the vcf file: CLNSIG, CLNSIGCONF. Result is a list of terms for a given variant. 

Rule:
1 )  if CLNSIG == “Conflicting_interpretations_of_pathogenicity” 
Split terms from field CLINSIGCONF
Remove (n) from each term

Example:  for variant ID = 210112 we have 
CLNSIGCONF=Benign(1),Likely_benign(2),Uncertain_significance(1). The expected list of clinical significance  will be {Benign, Likely_benign, Uncertain_significance}

2) if CLNSIG != “Conflicting_interpretations_of_pathogenicity” 
Then split values from this field to populate our variable

**Comment by Emma-Drieux** [comment]
LGTM
