### ISSUE TITLE
Variant DB: Import gnomAD v3

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#2372]
-Load gnomAD v3 into parquet files
- Join with the Variant table to add the following fields for the global (ALL) population only: AC, AF, AN and # of Homozygote.
For both Exomes and Genomes

**Comment by Emma-Drieux** [comment]
@jecos sur zepplin, je ne vois que la table des genomes pour la v3 et pas celle des exomes comme c'est le cas pour la v2.1.1, tu vas l'importer plus tard?

**Comment by jecos** [comment]
@Emma-Drieux maybe I'm wrong but there is not exome version in gnomad v3

**Comment by Emma-Drieux** [comment]
yes correct!

**Comment by Emma-Drieux** [comment]
LGTM!
