### ISSUE TITLE
Feature (CohortBuilder, Dashboard): sunburst for phenotypes ontology

### ISSUE THREAD

**Issue by evans-g-crsj** [kids-first/kf-portal-ui#2383]
The portal allows users to view all kind of data. A new feature is on its way that will allow the visualization of a given ontology. Various tools exist to help visualize the ontology graph.

An interesting tool is a sunburst (radial treemap).

Add a sunburst to the dashboard that will give users a visualization tool.

(details are to come...the first step is to add a sunburst and experience with it)

**Comment by luclemo** [comment]
@evans-g-crsj keep your 👀 on #2384 ... design specs coming!

**Comment by francisl** [comment]
reference https://github.com/kids-first/kf-portal-ui/issues/2384
