### ISSUE TITLE
implement summary data (bring existing implementation from kf into arranger)

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#239]
- [ ] Add summary counts at top
- [ ] Allow stat states to be handled at by the portals
https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5ab11a5d7df492f91899d2c1

**Comment by hlminh2000** [comment]
A consideration is that different portals will have different sets of stats to show. It may make sense to have this simply as a slot in the AFV for different portals to feed in their own data or component and handle stat updates accordingly.

**Comment by jgnieuwhof** [comment]
I think we'd be able to move stats into arranger, and just allow the parent app to specify which stats to show and which icons to associate with it, as it seems like a common feature that many of the portals could use
