### ISSUE TITLE
Variant DB : Manage security roles of analytics clusters

### ISSUE THREAD

**Issue by jecos** [kids-first/kf-portal-ui#2414]
Analytics cluster launched by kf-api-variant-cluster should be have specific permissions for some AWS resources.  

- S3 : 
  - Parquet files for occurences table : 
Occurences parquet files are partitioned by study and by consent codes. kf-api-variant-cluster first need to know which studies / consent codes the user have access. kf-api-variant-cluster receive as an input the gen3 token. Then it should request gen3 API to fetch this information.

![archi_variant_dwh-Security](https://user-images.githubusercontent.com/1424506/79457929-05bd6200-7fbf-11ea-955a-e8a3bb98ba46.png)

  - S3 repostiory notebook :
Each user have its own notebook repository on s3.

- Glue
Clusters should have permissions to read all tables from variant_live schemas. 

### Out of scope
We will not be managing the "Open access" case for now. If a user does have open access to a study but does not have a consent code for that study, he will not have access to it in the Variant Warehouse.

### Sub-Tasks
- [ ] Sub-task ...

### Testing Strategy

**Comment by denis-crsj** [comment]
@jecos As mentioned during the planning poker, let's list the different sub-tasks involved in this story and see if it could be split in multiple stories

**Comment by denis-crsj** [comment]
@adipaul1981 I updated the description with an "Out of scope" section as requested.
