### ISSUE TITLE
Variant DB : Create 1 or 2 Notebook examples

### ISSUE THREAD

**Issue by jecos** [kids-first/kf-portal-ui#2419]
Create and provide 1 or 2 useful notebook examples.

**Comment by denis-crsj** [comment]
To split in 2 different cards

**Comment by denis-crsj** [comment]
@jecos If I remember correctly, you mentioned the other day that David Higgins was working on this and since it is not blocking the following task : #2543 , I will close the task but I'll keep it in the board in Notion for the Release 1 so we still no it's one of the item that needs to be completed
