### ISSUE TITLE
Ontology browser : Add Any Of / All Of / Not in the modal

### ISSUE THREAD

**Issue by jecos** [kids-first/kf-portal-ui#2437]
User should have the possibility to select the kind of filter to apply directly from the modal.

### Testing Strategy
Anybody with access to Bastion and the QA environment

**Comment by denis-crsj** [comment]
@lucas Ne reste qu'à ajouter le lien vers la maquette

**Comment by denis-crsj** [comment]
@luclemo Est-ce que la petite modif visuelle avait été effectué pour cette tâche en fin de compte ? Si oui, serait-ce possible d'ajouter le lien de la maquette dans la description de la carte ?

**Comment by luclemo** [comment]
@denis-crsj non, désolé j'ai été totalement pris avec clin. En fait je ne suis pas certain que ça demande une maquette. On cherche à ajouter la même fonctionnalité du var interpreter de clin. 

Voici un capture d'écran:


![image](https://user-images.githubusercontent.com/1451515/85417069-35e42c80-b53d-11ea-9dac-fe0b4fb4a4b7.png)

En gros on veut un bouton avec une option dropdown qui offre:

- `Any of` -- défaut (_union_ dans clin)
- `All of` (_intersection_ dans clin)
- `Not` (_exclusion_ dans clin)

On pourra regarder pour les choix d'icônes au besoin, mais je pense que ces détails avec cette capture pourrait suffire pour commencer l'intégration?

**Comment by denis-crsj** [comment]
Looks good !
