### ISSUE TITLE
Ontology browser : click on filter should open the ontology browser

### ISSUE THREAD

**Issue by jecos** [kids-first/kf-portal-ui#2438]
As a user, I add a filter with Ontologie browser (Observed HPO Phenotypes for instance)

The filter is added into the cohort builder. 

If I click on this filter :
![Screen Shot 2020-04-20 at 11.10.34 AM.png](https://images.zenhubusercontent.com/5cab6ac920cddd7cf9ba5b40/b9235f33-7288-4697-8ae5-a3201bd90419)

Then I should open the ontologie broser in place of the clacssic filter dropdown

**Comment by vferretti** [comment]
I would keep this classic filter but add a link at the top to the browser from the filter menu
