### ISSUE TITLE
2 small wizard ui fixes

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#245]
- Title should be 'Join Kids First Data Resource Portal' not 'Join Kids First'
- The consent checkbox is selected by default in the active, blue state.  This should be in the inactive grey until a user selects the check box
- Can you make the weight of the title not as bold (medium) and make sure it isn't getting cut off at the top:
![screen shot 2018-03-23 at 11 11 43 am](https://user-images.githubusercontent.com/18424138/37837311-49180fb4-2e8b-11e8-9d81-4fac27ca254b.png)

**Comment by jgnieuwhof** [comment]
@rosibaj - I've addressed the first two issues, however was unable to reproduce the third issue, the checkbox appears to default to false. It is persistent, so if you make it to this page and have previously accepted terms it will reload to that state, could that have been what happened here?

**Comment by rosibaj** [comment]
@jgnieuwhof . The instructions were a bit unclear - the issue is that the selected state is styled even when the checkbox is not checked.   i just tried in incognito mode and this is what I see: 
<img width="965" alt="screen shot 2018-05-07 at 3 00 27 pm" src="https://user-images.githubusercontent.com/15824252/39719527-80b30934-5207-11e8-853d-1e0c75911ea4.png">

it should be like the other modal selection states:
(unselected)
<img width="1037" alt="screen shot 2018-05-07 at 3 01 38 pm" src="https://user-images.githubusercontent.com/15824252/39719569-9b0ea7d4-5207-11e8-8ad1-90dfc2aa1753.png">

(selected) 
<img width="1050" alt="screen shot 2018-05-07 at 3 01 45 pm" src="https://user-images.githubusercontent.com/15824252/39719568-9afc6998-5207-11e8-8fd9-f9c48fcf2236.png">

**Comment by jgnieuwhof** [comment]
@rosibaj - thank you! this is helpful
