### ISSUE TITLE
Bug(Survival Chart): sometimes it fails to load data

### ISSUE THREAD

**Issue by evans-g-crsj** [kids-first/kf-portal-ui#2462]
How to reproduce : filter query with -> biospeciment -> consentType -> HMB...an errror is thown (network console). 

Note: other filters induce this error as well.

![screenshotSurvival.png](https://images.zenhubusercontent.com/5d6419eca4c8f41d47fc9940/b7489072-b3a6-4e53-b5d3-c47104dd3299)

**Comment by vferretti** [comment]
See also #1455

**Comment by denis-crsj** [comment]
Moving to the icebox for now.
