### ISSUE TITLE
Perf(Elastic Search): remove unused saveSets

### ISSUE THREAD

**Issue by evans-g-crsj** [kids-first/kf-portal-ui#2489]
In the cohort builder, every time the file link is clicked a saveSet with no name is created. Often, it contains multiple ids (thousands) and other data.

It clutters elastic search with a lot of data and can have a serious impact.

Remove useless saveSets (that contain no tag/name). Ideally, automatically but manually could be sufficient for now.

**IMPORTANT**
If a set has been shared, what happens if it's deleted ? Make sure to take into consideration that people can share sets. If we deleted a set, we risk of making their shared links obsolete.

**Comment by evans-g-crsj** [comment]
Note: warning. save sets can be shared

cohortbuilder -> make a query -> view files to land in the file repo

![screenshot_save_sets_actions](https://user-images.githubusercontent.com/54366437/91599726-bad03580-e934-11ea-92ee-a2ac43bca118.png)

**Comment by denis-crsj** [comment]
Transferring to the Icebox for now
