### ISSUE TITLE
Participant Entity page: split the phenotype table in two tables

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#2508]
In the participant entity page, split the phenotype table in two: One for observed phenotypes and one for not observed phenotypes. see an example of current page: https://portal.kidsfirstdrc.org/participant/PT_6TJ0G4CG#clinical

- Create two tabs, one for each table
- leave the column 'Interpretation' as is

![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/c4b75b84-aa8e-400b-8e96-28d281e5bec6)

### Defects
- [x] When there is no either observed or not observed hpo terms, remove corresponding tabs. When there is neither observed and not observed HPO, remove section

### Resources
![image](https://user-images.githubusercontent.com/64538118/86008294-8993c180-b9e6-11ea-9758-e2cf49b3ba9e.png)

**Comment by denis-crsj** [comment]
Validate with Participant having both observed and non-observed phenotypes as well as with a Participant having only observed phenotypes and it works well. Moving the task to Done.

**Comment by vferretti** [comment]
Go to https://kf-qa.netlify.app/participant/PT_Z79XRW6V#clinical
weird table and choice of tabs
![image](https://user-images.githubusercontent.com/1181124/86006485-05403f00-b9e4-11ea-874c-bc5c5c9c0afd.png)

When there is no either observed or not observed hpo terms, remove corresponding tabs. When there is no both observed and not observed HPO, remove section

**Comment by denis-crsj** [comment]
@adipaul1981 I updated the description with Vincent's description of the defect. Moving the task back to In Progress.

**Comment by denis-crsj** [comment]
Tested. Moving to Done.
