### ISSUE TITLE
Be able to see where the selected options are coming from when returning into the Observed Phenotype Browser

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2516]
When we go back a second time into the Observed Phenotype Browser after having selected one or more options, there's no way to quickly know where the selected options are coming from.

We would need to have a visual indicator to help the user know in which branch the selected option(s) belong. We can achieve this by having the checkbox on the left of the branch stay blue. This way, the user can quickly identify all the different branches in which he selected an option.

If he clicks on the branch, the subsequent branch checkboxes are also blue until he gets to his selected option. This way, it is easier for the user to retrace his steps.

![image.png](https://images.zenhubusercontent.com/5ea980d6189dd52c91ddddfa/5096b3f9-2198-42eb-b267-2cffca6cc2a7)

![image.png](https://images.zenhubusercontent.com/5ea980d6189dd52c91ddddfa/f72909a1-0220-45b0-ad64-8b2caa29d00c)

![image.png](https://images.zenhubusercontent.com/5ea980d6189dd52c91ddddfa/49343bb9-277b-48f5-951e-3f140e4d7db3)

**Comment by vferretti** [comment]
select Abnormal lower limb bone morphology (HP:0040069). This term has two paths but only one is showed when we reopen the browser

**Comment by denis-crsj** [comment]
Tested.
