### ISSUE TITLE
Ontology browser: add counts of participants with the exact ontology term

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#2529]
Currently, the ontology browser provides for each term the number of participants with both the exact term AND all its descendants. 

Add a second column of counts for the number of participants with the exact term only. 

For the sake of simplicity, this ticket includes UX, backend and frontend tasks

**Comment by luclemo** [comment]
@adipaul1981 voici la [mise-à-jour de la maquette](https://www.figma.com/file/b7YRiKv8X4wPRS992hrj5f/KF---Ontology-Browser?node-id=34%3A929&viewport=4100%2C-1021%2C1). On pourra en parler quand tu veux.

**Comment by denis-crsj** [comment]
Tested successfully. Moving the task to Done.

![image](https://user-images.githubusercontent.com/64538118/85783372-417a5380-b6f5-11ea-8e18-af301b96ac83.png)
