### ISSUE TITLE
Ontology browser: add a link to open the browser from the queries

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#2534]
we should add a link called Browser in the red box below. Make solution generic enough to be able to have the same link for other ontologies such as Mondo.

![image](https://user-images.githubusercontent.com/1181124/82558227-343cd880-9b3b-11ea-9242-e99d8474267c.png)

**Comment by denis-crsj** [comment]
On hold pour le moment, Francis pourra reprendre la carte à son retour de congé.

**Comment by denis-crsj** [comment]
Testé avec succès dans Chrome et Firefox
