### ISSUE TITLE
Upload OMIM

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2536]
# Introduction
On veut pouvoir disposer des **informations OMIM** (_phénotypes et transmissions_) associées à un gène sur lequel on peut trouver des **variants**.

# Document explicatif
Les données a intégrer dans la BD des variants, ainsi que les sources de ces dernières sont expliquées sur le document suivant:

https://docs.google.com/document/d/1XiFd4COA8lTynvAl3PdxCQHquVGLr6ftl0ADueyHcdQ/edit#heading=h.v04f6z9b7jnj

**Comment by Emma-Drieux** [comment]
@vferretti dis moi s'il y a quelques chose a developper/modifier dans le doc:
https://docs.google.com/document/d/1XiFd4COA8lTynvAl3PdxCQHquVGLr6ftl0ADueyHcdQ/edit#heading=h.v04f6z9b7jnj
