### ISSUE TITLE
Participant Centric mapping modification for diagnosis - mondo

### ISSUE THREAD

**Issue by adipaul1981** [kids-first/kf-portal-ui#2539]
To correctly query by `age_at_event_days` for mondo diagnosis, we need to update the Elasticsearch mapping (and the ETL service). We need to add also a new field, is_tagged, to identify the mondo diagnosis that was tagged vs. ones that are parents of the one tagged.

Modify mapping as follows:

```
 {
    diagnoses: [
    {
       ...,
       is_tagged: <true|false>
       mondo:{
           name: <name>,
           parents:[
               <parent1>,
               <parent2>,
               ....
           ],
           is_tagged: <true|false>
       }
   },
   ....
   ]
}
```

**Comment by denis-crsj** [comment]
There no way really for me to test this but the is_tagged parameter is what's allowing the count column (first column) in the mondo browser and that was tested in another task.

Also, the task was review as it went through the Peer Review pipeline so I'll move the task to Done
