### ISSUE TITLE
Add a collapse on the filter

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#254]
When you expand a facet, you have to scroll all the way to the bottom to collapse the facet.  When you have a lot of values, this is very annoying to do. 

- [x] Add a "less" at the top after a facet has been expanded, beside the filter textbox
- [x] when the user scrolls the long facet list, fix the facet header/filter textbox to the top of the panel so it is always available for the user.

See screenshots and explanation below:

**Comment by kcullion** [comment]
As per discussion with Rosi and Phuong-My - this is a design proposal for KF that shows a "Load more" with a count of how many facet values there are. So the user loads a number at a time and prevents them from loading a huge number at a time.

![25 kf-file-repository-ux-tweaks](https://user-images.githubusercontent.com/18424138/38374631-24bc6b42-38c2-11e8-9516-d6cb0109c020.jpg)

**Comment by kcullion** [comment]
![screen shot 2018-04-05 at 4 08 05 pm](https://user-images.githubusercontent.com/18424138/39138677-81fba1bc-46ee-11e8-94b8-ef6af6626dcc.png)
![screen shot 2018-04-05 at 4 09 31 pm](https://user-images.githubusercontent.com/18424138/39138678-820798e6-46ee-11e8-8ffc-2c6a31a39ff9.png)
![screen shot 2018-04-23 at 12 04 28 pm](https://user-images.githubusercontent.com/18424138/39138679-8211f692-46ee-11e8-8508-1d65bea1a424.png)

**Comment by jgnieuwhof** [comment]
@rosibaj - yeah that makes a lot of sense, will investigate

**Comment by rosibaj** [comment]
thanks @jgnieuwhof!  Retested - this looks really fantastic!!
