### ISSUE TITLE
Ontology Sunburst: brainstorm on a second iteration design that fixes current issues

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#2540]
We need to think about the current issues and also about some enhancements

**Comment by denis-crsj** [comment]
This is not really a task but more something that could become one or more tasks. The objective would be to add these ideas/tasks in the Google Sheet instead and then create the tasks in Github only when we know what we want and what to do.

Closing the issue and transferring the details into the Google Sheet file : https://docs.google.com/spreadsheets/d/1U1JQZEBEMTP_07PngrmNh8rzbZICTX87Fe_2fEetAbI/edit#gid=0
