### ISSUE TITLE
Documentation des couleurs et de leurs utilisations dans le thème

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2541]
- Document available theme colors (text, button, etc)
- Add a .scss color theme file

**Comment by luclemo** [comment]
@francisl j'ai complété le travail pour le thème. Les docs mentionnaient plusieurs façon de faire le customization. Je ne sais pas si j'ai choisi la façon idéale mais j'ai modifié ces deux fichiers:

- `components/style/color/colors.less`
- `components/style/themes/index.less`

Comme `index.less` fait un import de `default.less` je n'ai ajouté que les chose qui diffèrent du thème par défaut. Peut-être que tu n'aime pas l'approche override? À toi de voir.

J'ai tout ça en local (versionné) donc j'attends de voir comment tu veux procéder. Je peux ajouter le repo sur git... ou je pourrais simplement de donner les fichiers as-is? 

Ça serait bien éventuellement de faire un set-up d'un live style-guide que je pourrais éventuellement modifier (avec vos reviews bien entendu) pour que l'on ait un source of truth pour les composantes? Il ce peux qu'on décide de faire des légers changements (ex: l'ajout d'une deuxième font pour le titres) ou des ajouts plus gros (ex: des composantes custom à partir de choses existants dans le portail). Bref, je suis 100% ouvert à toute proposition de stratégie pour le UI :)

**Comment by denis-crsj** [comment]
@francisl et @luclemo Y a-t-il une façon pour moi de tester cette carte ou on peut juste la bouger à DONE ?
