### ISSUE TITLE
Implement automated testing for the Reporting Service

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2550]
Currently, the service report has no pretests running before deployment.

It lowers our level of confidence since no test is run.

add a hook to run test automatically before a deploy

**Comment by evans-g-crsj** [comment]
- .circleci directory and config.yaml added

- project configured in circle-ci web interface

- github hooks added on master branch

![screenshotMasterBranchRule](https://user-images.githubusercontent.com/54366437/84051873-be7b9e00-a97d-11ea-8446-cc8de3ac5203.png)

**Comment by denis-crsj** [comment]
@evans-g-crsj I don't think there really is a way for me to test this. The task has been validated and has gone through the Peer review pipeline so I'll move to Done.
