### ISSUE TITLE
Ontology Browser: redundant display for terms on multiple paths

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#2556]
**Bug description**
the same term can be displayed multiple time on the right panel if it belongs to multiple path
**Steps To Reproduce**
1. Go to the ontology browser
2 search for Abnormal lower limb bone morphology (HP:0040069)
3 select twice this term from different path
4 you see the term has been added more than once on the right

**Expected behavior**
We should only see once the same search criteria

![image](https://user-images.githubusercontent.com/1181124/83665301-3b330480-a599-11ea-93af-578fd050f73c.png)

### Sub-Tasks
- [ ] Sub-task 1
- [ ] Sub-task 2
- [ ] Sub-task 3
- [ ] Sub-task 4

### Testing Strategy
See the steps to reproduce above as well as the spteps to reproduce. Anybody with access to the Bastion will be able to test.

**Comment by denis-crsj** [comment]
Tested using Abnormal lower limb bone morphology (HP:0040069). Once it has been added, it cannot be added again and the box is uncheckable. Moving to Done.
