### ISSUE TITLE
Style(File Repo, Family Manifest Modal): make modal readable 

### ISSUE THREAD

**Issue by evans-g-crsj** [kids-first/kf-portal-ui#2558]
The family manifest modal generates a preview of what the manifest file will contain.

To show the modal go to the file repo and click the button "File Manifest"

![screenshotWhereIsFileManifest.png](https://images.zenhubusercontent.com/5d6419eca4c8f41d47fc9940/b1e95ce7-1b36-423a-bf2f-5ed1b07ce9d1)

![screenshotFileManifest.png](https://images.zenhubusercontent.com/5d6419eca4c8f41d47fc9940/f89dec18-273b-4a72-9f32-5b5027cc763f)

The issue is that is very difficult to read the information. We need to improve the UI.

Note: the modal has an optional section that may show under certain circumstances. As soon as we know how to generate it a new screenshot will be added. That section goes under the participant section shown in the first screenshot. This section seems to have the same format as the one shown...

**Comment by denis-crsj** [comment]
Moving issue to Icebox

**Comment by denis-crsj** [comment]
Tested on Chrome and Firefox, all good !
