### ISSUE TITLE
ci(kf-api-portal-reports): linting

### ISSUE THREAD

**Issue by evans-g-crsj** [kids-first/kf-portal-ui#2563]
Add linting in tests workflow
- add same eslint configuration as in portal-ui
- make sure that we test for linting in circle-ci

### Sub-Tasks
- [ ] use same eslint configuration as in the portal
- [ ] add a new job in circle-ci and update the workflow

### Testing Strategy
dev can test it

**Comment by denis-crsj** [comment]
Moving to Icebox for now
