### ISSUE TITLE
Confirmation popup missing when deleting a virtual study from the Dashboard

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2566]
**Bug description**
When we delete a virtual study from the Dashboard, there is no validation. The virtual study is deleted without any warnings

**Steps To Reproduce**
1. Go to the Cohort Builder
2. Apply some filters and save the virtual study
3. Go to the Dashboard and delete it by clicking on the trash icon
4. The study is deleted without any warnings

**Expected behavior**
We should see a popup of some sort asking the user to confirm he really wants to delete the virtual study.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ea980d6189dd52c91ddddfa/43aeca14-11b1-4e8d-a366-5cc6d767ddb1)

**Desktop (please complete the following information):**
 - OS: mac OS Cataline 10.15.4
 - Browser: Chrome
 - Version: 81.0.4044.129

**Additional context**
Pop-up currently in place when deleting a virtual study from the Cohort Builder

![image](https://user-images.githubusercontent.com/64538118/84536131-31a54d00-acbb-11ea-8116-34fc81798c7b.png)

**Comment by denis-crsj** [comment]
Tâche à estimer avant d'être commencé svp.

**Comment by evans-g-crsj** [comment]
Please, when in QA, test the confirmation pop-up in the cohort builder since I ve updated the existing modal

![screenshot_delete_vs_cohort_builder](https://user-images.githubusercontent.com/54366437/86629655-bbce9180-bf99-11ea-8bc4-82dbff4b84c3.png)

**Comment by evans-g-crsj** [comment]
Review OK, waiting to merge in QA after next release

**Comment by denis-crsj** [comment]
Tested in Chrome and Firefox. No defect found.
