### ISSUE TITLE
refactor(cohort builder, save sets modal, file repository link): improve ui

### ISSUE THREAD

**Issue by evans-g-crsj** [kids-first/kf-portal-ui#2568]
- [x] Make the link to the file repository more intuitive
- [x] Make sure that the input is focused when opening the save sets modal

### Defects
- [x] The Cohort Results info are not aligned with the text inside the button.

### Resources
![Screen Shot 2020-06-23 at 2 58 52 PM](https://user-images.githubusercontent.com/64538118/85446717-d0a33200-b562-11ea-8311-3852e323430c.png)

**Comment by evans-g-crsj** [comment]
screenshots:

![screenshotSaveSetModalAutofocus](https://user-images.githubusercontent.com/54366437/84811654-2d3ea400-afdb-11ea-99cc-9b9205619415.png)

![screenshotFileRepoButtonLink](https://user-images.githubusercontent.com/54366437/84811656-2dd73a80-afdb-11ea-854f-1252cd200d83.png)

**Comment by denis-crsj** [comment]
@evans-g-crsj 1 defect found. I modified the the description and added the defect with a screenshot. Putting the task back to "In progress"

**Comment by evans-g-crsj** [comment]
@denis-crsj fix merged in qa

**Comment by denis-crsj** [comment]
All defects fixed. Tested in Chrome and Firefox. Moving the task to Done.
