### ISSUE TITLE
Overall design review

### ISSUE THREAD

**Issue by phuongmy** [kids-first/kf-portal-ui#257]
Starting a list here of design updates as per discussion with Kim and Rosi. List to be completed until next sprint planning. 
- [x] 1: Change `All filters` button design
- [x] 2: Filter textfield above table - Rename grey text to `Filter Table`
- [x] 3: Change filter icon in the filter textbox
- [x] 4: Change filter arrow to be to the left of label and add ability to have a search (mag glass) that opens up a search textbox (like GDC and ICGC)
- [x] 5: Font inconsistencies - headings are Montserrat and body copy/data is open sans and font-weight issues
- [x] 6: Always add the "x" icon when a user types into a searchbox or filterbox - eg filter table text field

FYI, other design changes will be handled in other tickets:
- [x] Fix gramatical error on file repository, see https://github.com/kids-first/kf-portal-ui/issues/263
- [x] `Show more` widget for the facet values, see https://github.com/overture-stack/arranger/issues/291
- [x] Facet fixes #290

**Comment by hlminh2000** [comment]
@jgnieuwhof what do you think we should do about the x button? some inputs are from arranger while others are in kf-portal... my thought is, we can use the input component in Arranger just as defaults but any component that uses an input would also provide an `InputComponent` prop which the portal can provide
