### ISSUE TITLE
Ontology Browser: Need better display when no phenotypes for returned participants

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#2586]
We should display a message in the ontology browser when there is no HPO term for participants returned by the active query. Currently we do get this window. 
![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/a6976d68-cf82-4adc-9c81-356b6829c7e9)

To reproduce, select the Kids First: Ewing Sarcoma - Genetic Risk study

Message should be: There is no observed HPO phenotypes for these participants

**Comment by denis-crsj** [comment]
@adipaul1981 The displayed message should be : There is no observed HPO phenotypes for these participants
