### ISSUE TITLE
 Cohort Builder (QA)- Download Participant-Only:  Improvement of the values ​​of the diagnostic category

### ISSUE THREAD

**Issue by EmmyDx** [kids-first/kf-portal-ui#2593]
# Description
Her is the applied filter:
![Filter](https://user-images.githubusercontent.com/12585875/86171305-8255dc00-baea-11ea-9987-0162f9071759.png)
1.
In the downloaded report, I have the following result (tab Participant):
![Diagnostic_category](https://user-images.githubusercontent.com/12585875/86171190-55092e00-baea-11ea-920a-d3a3dda13e6b.png)

The repetitions may be due to the fact that we take the value of the category of the diagnosis in the table of diagnoses and not the value in the table Participant

2.
Display of empty diagnosis values ​​(Diagnoses and histology diagnoses tabs)

![Onglet diagnosis](https://user-images.githubusercontent.com/12585875/86171925-8df5d280-baeb-11ea-9450-22b0ba7029ff.png)

![Onglet histological](https://user-images.githubusercontent.com/12585875/86171930-90f0c300-baeb-11ea-99ec-888eb11b087a.png)

# Proposed solution
1. The value of the diagnosis is that which appears in the table of the participant
> Note: the filter is applied to the values ​​of the diagnostic category of the diagnostic table
2. In the Diagnoses and Histological Diagnoses tabs, do not display empty values

**Comment by Emma-Drieux** [comment]
No more repetition for the Diagnostic Category column for the Participant_only and Participant and family members reports. The deletion of lines without diagnosis will be reported in another story
