### ISSUE TITLE
 Delete lines without diagnosis in the report

### ISSUE THREAD

**Issue by EmmyDx** [kids-first/kf-portal-ui#2594]
This story is taken from story # 2593

## Description
Her is the applied filter:
![Filter](https://user-images.githubusercontent.com/12585875/86171305-8255dc00-baea-11ea-9987-0162f9071759.png)

In the diagnoses and histological diagnoses tabs, we obtain several lines without diagnosis, as in the following screenshots

![Onglet diagnosis](https://user-images.githubusercontent.com/12585875/86171925-8df5d280-baeb-11ea-9450-22b0ba7029ff.png)

![Onglet histological](https://user-images.githubusercontent.com/12585875/86171930-90f0c300-baeb-11ea-99ec-888eb11b087a.png)

## Proposed solution
In the Diagnoses and Histological Diagnoses tabs, do not display empty values.
1. For the diagnostics tab, if all the columns from **E to H (included)** - _see the screenshot below_ - are empty, the row should be deleted
![colonne diagnoses](https://user-images.githubusercontent.com/12585875/86255891-add9d480-bb85-11ea-9ad5-de36052077fa.png)

2. We will do the same for the Histological diagnoses tab (for this case, it is the columns H to K which will be concerned)

**Note: this should be done for the participant-only report and that of the participant and family members**

**Comment by denis-crsj** [comment]
@EmmyDx Salut Emma, nous aurions besoin de plus de précisions en lien avec la démarche pour obtenir ce résultat svp.
