### ISSUE TITLE
 Values ​​of the y axis of the studies graph should be improved

### ISSUE THREAD

**Issue by EmmyDx** [kids-first/kf-portal-ui#2597]
In the Summary View of the Explore Data, the names of the studies are not well displayed (On the screenshot, we do not apply any filter, it may be a good parameter to be able to have all the names and have an idea of ​​the limit):
![studies graph](https://user-images.githubusercontent.com/12585875/86266381-23986d00-bb93-11ea-861b-a85da6a991f5.png)

**Comment by denis-crsj** [comment]
already fixed.
