### ISSUE TITLE
 Improve the sequencing data table on the participant page

### ISSUE THREAD

**Issue by EmmyDx** [kids-first/kf-portal-ui#2600]
Test performed on KF prod

For some participants, the sequencing data table is empty for some lines. 

![sequencing_data](https://user-images.githubusercontent.com/12585875/86269163-5b091880-bb97-11ea-8acc-2eb7479c7396.png)

These lines should not be displayed

**Comment by denis-crsj** [comment]
Transferred to the Icebox for now
