### ISSUE TITLE
Style(CohortBuilder, Cards): make card less compact

### ISSUE THREAD

**Issue by evans-g-crsj** [kids-first/kf-portal-ui#2609]
Cards are use to display data.

When there is too much data information becomes hard to read.

Make cards a little bit bigger to give more space.

**Comment by denis-crsj** [comment]
@evans-g-crsj Il n'y a pas beaucoup de détails dans la carte, je ne sais pas trop quoi regarder et à quoi comparer pour faire le QA. Est-ce possible d'ajouter un peu plus de précision en lien avec ce qui a été fait et qui doit être validé svp ? Ensuite je pourrai tester le tout !
