### ISSUE TITLE
Add Participants to an existing set

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2615]
### Feature

Instead of saving the selection as a new Participants set, users should be able to add the selected participants to one of their existing saved set.

A new option called "Add to existing Participants set" need to be added to the dropdown menu under the "Save as new Participants set" option. If the user has at least one set already, the option will be clickable but if the user does not have any saved set, the option will be greyed out.

Selecting this option will open a Modal box with a dropdown field listing all his sets and allowing him to select the one to which he wants to add the participants.

It is extremely possible that a user might add a set of Participants to one that already contain some of the IDs in question. If it’s the case, no errors nor validations need to be displayed to the user, the system will run that validation in the background and only add the IDs that were not already in the chosen set.

### Acceptance Criteria

**Scenario 1** User has no saved set
  - **Given:** The user is on the Cohort Builder
    - **And:** he just ran a query displaying some results
  - **When:** the user clicks on the "Save Participants set" button
  - **Then:** the user should see 2 options in the dropdown. The "Save as new Participants set" option should be clickable and the "Add to existing Participants set" option should be greyed out and unclickable.

**Scenario 2** User has 1 or more saved sets (No duplicates)
  - **Given:** The user is on the Cohort Builder
    - **And:** he just ran a query displaying some results
  - **When:** the user clicks on the "Save Participants set" button
  - **Then:** The user should see 2 options [Save as new Participants set / Add to existing Participants set]
  - **When:** the user clicks on the "Add to existing Participants set" option, a modal box open displaying a dropdown menu containing the user's list of Saved sets.
  - **Then:** The user selects a set which _does not contain duplicates_ and clicks "Confirm/Save".
  - **Then:** The user goes back to the dashboard and the updated number of items in the set should be the sum of the old set and the new selection

**Scenario 3** User has 1 or more saved sets (With duplicates)
  - **Given:** The user is on the Cohort Builder
    - **And:** he just ran a query displaying some results
  - **When:** the user clicks on the "Save Participants set" button
  - **Then:** The user should see 2 options [Save as new Participants set / Add to existing Participants set]
  - **When:** the user clicks on the "Add to existing Participants set" option, a modal box open displaying a dropdown menu containing the user's list of Saved sets.
  - **Then:** The user selects a set which _does contain some duplicates_ and clicks "Confirm/Save".
  - **Then:** The user goes back to the dashboard and the updated number of items in the set should be the sum of the old set and the new selection minus the duplicates that shouldn't have been added. (Existing set + new query - duplicates)
    - **And:** Downloading the data should show no duplicates in the file.

### Sub-Tasks
_List of what needs to be done  on the technical side._
- [ ] Sub-task 1
- [ ] Sub-task 2
- [ ] Sub-task ...

### Testing Strategy
Anyone with access to Bastion and the QA site can test

_(!!) What happens if the user was using the saved set in one of his notebooks ? Is it updated automatically for the user or do we show any kind of validations/warning messages?_

_(!!) What happens if the user had virtual studies using the set?_

### Defects
_List of defects/bugs found during QA._
- [ ] Defect 1
- [ ] Defect 2
- [ ] Defect ...

### Resources
![image.png](https://images.zenhubusercontent.com/5ea980d6189dd52c91ddddfa/00e7ec53-364b-4624-a975-e9d5f904f6c9)

**Comment by evans-g-crsj** [comment]
Note to Dev: change mutation names in arranger - make them start by "saveSetsMyMutation". (this is part of group discussion that we had)

**Comment by evans-g-crsj** [comment]
- [ ] back-end

- [ ] front-end

**Comment by evans-g-crsj** [comment]
Note for devs: sqon arithmetic is incorrect. For now, it's no problem but it could become an issue when building Venn's diagrams
