### ISSUE TITLE
Update links to support site in portal footer and header

### ISSUE THREAD

**Issue by chris-s-friedman** [kids-first/kf-portal-ui#2618]
**Bug description**
the links to `Support` in the portal link to documentation that is being deprecated. 

1. link to `Support` in the footer currently goes to https://kidsfirstdrc.org/support/getting-started. it should go to https://www.notion.so/d3b/Kids-First-DRC-Help-Center-c26b36ff66564417834f3f264475d10a 
2. Link to `Support` in the resources drop down (screenshot below) currently goes to https://kidsfirstdrc.org/support/getting-started. it should go to https://www.notion.so/d3b/Kids-First-DRC-Help-Center-c26b36ff66564417834f3f264475d10a 
3. Link to `Studies and Access` in the resources drop down (screenshot below) currently goes to https://kidsfirstdrc.org/support/studies-and-access/. it should go to https://www.notion.so/d3b/Studies-and-Access-a5d2f55a8b40461eac5bf32d9483e90f

![image](https://user-images.githubusercontent.com/17438916/87715788-de239480-c77b-11ea-8abd-c9ceeb029521.png)

**Comment by denis-crsj** [comment]
Tested all 3 locations and all links now point to Notion. Moving to Done.
