### ISSUE TITLE
Have users agree to terms and conditions on every sign in

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2621]
### Feature

We want users to agree to the Terms and conditions every time they sign in.

**Each sign in**
We click on one of the sign in method (Google, Facebook, or Orcid), we enter our credentials and then the box with the sign in options is replaced by a box displaying the terms and conditions. If we click on “Agree”, we are redirected to the portal dashboard. If we click on “Don’t agree”, we are redirected back to the page with the sign-in options.

### Acceptance Criteria

ToDo

### Sub-Tasks
_List of what needs to be done  on the technical side._
- [ ] Sub-task 1

### Testing Strategy
Anybody with a working account can test

### Defects
_List of defects/bugs found during QA._
- [ ] Defect ...

#### Documentation de chop

https://docs.google.com/document/d/1t3ELBFCxot6fhA87FLOD2O_5ew2kBDxPpx3j8f0kC40/edit

#### Maquettes

- [Prototype Figma](https://www.figma.com/proto/XbXIKmFZndykAqkBexNTay/KF-Terms-Opt-in?node-id=244%3A0&viewport=406%2C512%2C0.27073460817337036&scaling=min-zoom)
- [Composantes Ant (Figma)](https://www.figma.com/file/XbXIKmFZndykAqkBexNTay/KF---Terms-Opt-in?node-id=18%3A56&viewport=238%2C566%2C0.6291112899780273)

**Comment by luclemo** [comment]
@evans-g-crsj J'ai ajouté les liens vers les maquettes figma dans la section ressource. Le prototype va te montrer l'interaction. N'hésites pas si tu as des questions!

**Comment by HigginsD-CHOP** [comment]
Here is the most up-to-date version of the Terms & Conditions, changed today.
https://docs.google.com/document/d/1t3ELBFCxot6fhA87FLOD2O_5ew2kBDxPpx3j8f0kC40/edit

**Comment by evans-g-crsj** [comment]
make sure this is solved https://github.com/kids-first/kf-devops/issues/483 and tested before merging into prd

**Comment by denis-crsj** [comment]
It was decided we should deploy and if anything happens, we'll revert back to the previous version.
