### ISSUE TITLE
Refactor du Summary/table view

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2633]
## Maquettes 👇 

https://www.figma.com/file/xwFNKpa1zXoCg1xaJhAvKn/KF---Saved-Sets?node-id=18%3A56&viewport=1499%2C774%2C0.6173954606056213

### Defects
- [x] Espace blanc trop grand en haut des boutons "Columns" et "Export"
- [ ] Dans la barre "Query 1 ...", le texte et les petits icône ne semblent pas être de la bonne couleur
- [x] L'icône de la flêche à côté du nombre de fichier devrait être souligné également
- [x] Les bouton "Export" et "Download" ne devrait pas avoir de bordure - c'est le bouton style `ant-btn-link` small
- [x] L'icône du bouton "Column" doit être changé et déplacé à gauche du texte

![image](https://user-images.githubusercontent.com/64538118/93609492-ef666880-f999-11ea-94cf-0b25a09a8dc9.png)

![image](https://user-images.githubusercontent.com/1451515/93615573-926eb080-f9a1-11ea-9abb-f2b3c4d45516.png)

**Comment by denis-crsj** [comment]
Only the section regarding the tabs will be deployed and another story will be created for the portion with the buttons.

**Comment by denis-crsj** [comment]
Tested successfully on Chrome and Firefox

**Comment by francisl** [comment]
@luclemo about the second point. It's not from a font icon library, default antd or svg. they are not customizable.

@denis-crsj please create a new design ticket to provide the proper format, so we can theme the icons.

**Comment by luclemo** [comment]
@francisl Ok pas de soucis, si on les embed directement plutôt q'un img source ça devrait être plus flexible. J'ai les SVG si @denis-crsj veut les ajouter au nouveau ticket.

**Comment by luclemo** [comment]
>  L'icône de la flêche à côté du nombre de fichier devrait être souligné également

@francisl @denis-crsj Désolé j'avais pas vue ça passer. Si tu a déjas apporté la correction tant mieux, sinon tu peux laisser faire ça.

**Comment by luclemo** [comment]
@francisl voici les icônes en fichiers svg individuels et aussi un sprite suivant ce que tu préfère pour les intégrer:

[kf-icons.zip](https://app.zenhub.com/files/105170053/ee36fbe3-da32-4f4d-9745-cece07c561c5/download)
