### ISSUE TITLE
Front-end secure portal behind login

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#264]
https://github.com/overture-stack/ego/issues/89 secured the file browser, but we need to complete the front end work to secure the portal behind user login

- if a url is hit directly, and the user is not logged in, they should be redirected to the logged-in/sign-up page
- right now all pages should be behind sign-in

**Comment by hlminh2000** [comment]
flashing was fixed by https://github.com/kids-first/kf-portal-ui/pull/286
