### ISSUE TITLE
Add details regarding the selected HPO term on the right side of the Sunburst's card

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2640]
### Feature

We want to show some details about the selected HPO term on the right side of the graph/card. It should contain the following information and also look like the following screenshot:

- HPO Term and ID/Number
- Number of participants including descendants
- Number of participants with the exact term

![image](https://user-images.githubusercontent.com/64538118/97216149-c8baff00-179b-11eb-92a4-5c53ca96802d.png)

### Acceptance Criteria

1. The HPO term on the right represents the same HPO as the one selected in the Sunburst.
2. The values for the number of participants are accurate
4. Switching the term on the sunburst updates all values on the right (HPO term and number of participants)

### Sub-Tasks
_List of what needs to be done  on the technical side._
- [ ] Sub-task 1

### Testing Strategy
_What do we need to test? Who can test it? How do we test it? What do we need to test it?_

### Defects
_List of defects/bugs found during QA._
- [x] The number in the center of the Sunburst, on the right of it and the number of participants on top don't match.
- [x] Based on the designs, the spacing between the HPO term and it's ID should be a bit larger. Also, we need to remove the ":" and just put a space instead.

### Resources

Sunburst specs: https://www.notion.so/ferlab/KF-Ontology-Sunburst-212f8110b7794cbca44198a1ab7f993b

Figma designs: https://www.figma.com/file/0voQuoBD3Xvap4wYQ0VLYq/KF---Sunburst?node-id=151%3A0

**Comment by evans-g-crsj** [comment]
![image](https://user-images.githubusercontent.com/54366437/97459551-456fe980-1912-11eb-808d-6ab5fed6e360.png)

**Comment by denis-crsj** [comment]
@evans-g-crsj The different numbers on the page don't match and we'll need to figure out why before releasing it

**Comment by denis-crsj** [comment]
Only one small defect added to the description.

**Comment by denis-crsj** [comment]
all defects have been addressed, closing card
