### ISSUE TITLE
Remove 'provideLocalSqon'

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2653]

**Comment by evans-g-crsj** [comment]
QA: test that the advanced facet view modal works as expected

![screenshot_advanced_modal_facet_view](https://user-images.githubusercontent.com/54366437/90287134-429e4600-de45-11ea-97e7-8f6409d027dc.png)

**Comment by denis-crsj** [comment]
Tested in Chrome and Firefox and the Modal works as expected
