### ISSUE TITLE
Update download clinical behaviour: use same options as download manifest and harmonize content

### ISSUE THREAD

**Issue by phuongmy** [kids-first/kf-portal-ui#266]
Currently user can download manifest for either participants or (participants+family).
But he can download clinical data for either participants or family.
We should make the options consistent. 

That's why we should provide options:
- Download Clinical (Participant)
- Download Clinical (Participant and Family) --> this file should be updated to contain clinical data of participants AND family

Also we are adding a few columns in the TSV download.

See descriptions of the columns and rules in:
https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/383156225/Download+Clinical+and+Biospecimen+data#DownloadClinicalandBiospecimendata-a.Clinicaldataoftheparticipants

https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/383156225/Download+Clinical+and+Biospecimen+data#DownloadClinicalandBiospecimendata-b.Clinicaldataofthefamilymembers

**Comment by jgnieuwhof** [comment]
@phuongmy - I don't think I currently have access to atlassian, would it be possible to send me PDF versions of the requirements? sorry for the hassle

**Comment by jgnieuwhof** [comment]
@rosibaj - that's right, I just updated the proband values, try again now?

**Comment by rosibaj** [comment]
thanks @jgnieuwhof.  Looks great!
