### ISSUE TITLE
Remove Participants from an existing set

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2666]
### Feature

Instead of saving the selection as a new Participants set, users should be able to just remove the selected participants from one of their existing saved set.

A new option called "Remove from existing Participants set" need to be added to the dropdown menu under the "Add to existing Participants set" option. If the user has at least one set already, the option will be clickable but if the user does not have any saved set, the option will be greyed out.

Selecting this option will open a Modal box with a dropdown field listing all his sets and allowing him to select the one from which he wants to remove the participants.

It is extremely possible that a user might remove a set of Participants from one that doesn't contain some of the IDs in question. If it’s the case, no errors nor validations need to be displayed to the user, the system will run that validation in the background and only remove the IDs that are already in the chosen set.

### Acceptance Criteria

**Scenario 1** User has no saved set
  - **Given:** The user is on the Cohort Builder
    - **And:** he just ran a query displaying some results
  - **When:** the user clicks on the "Save Participants set" button
  - **Then:** the user should see 3 options in the dropdown. The "Save as new Participants set" option should be clickable, the "Add to existing Participants set" and "Remove from existing Participants set" options should be greyed out and unclickable.

**Scenario 2** User has 1 or more saved sets (No missing IDs)
  - **Given:** The user is on the Cohort Builder
    - **And:** he just ran a query displaying some results
  - **When:** the user clicks on the "Save Participants set" button
  - **Then:** The user should still see 3 options [Save as new Participants set / Add to existing Participants set / Remove from existing Participants set]
  - **When:** the user clicks on the "Remove from existing Participants set" option, a modal box open displaying a dropdown menu containing the user's list of Saved sets.
  - **Then:** The user selects a set which _does not have any missing IDs_ and clicks "Confirm/Save".
  - **Then:** The user goes back to the dashboard and the updated number of items in the set should be the substraction of the old set and the new selection

**Scenario 3** User has 1 or more saved sets (With missing IDs)
  - **Given:** The user is on the Cohort Builder
    - **And:** he just ran a query displaying some results
  - **When:** the user clicks on the "Save Participants set" button
  - **Then:** The user should see 3 options [Save as new Participants set / Add to existing Participants set Remove from existing Participants set]
  - **When:** the user clicks on the "Remove from existing Participants set" option, a modal box open displaying a dropdown menu containing the user's list of Saved sets.
  - **Then:** The user selects a set which _does not have missing IDs_ and clicks "Confirm/Save".
  - **Then:** The user goes back to the dashboard and the updated number of items in the set should be the substraction of the old set and the new selection plus the number of missing IDs that shouldn't have been removed. 
    - **And:** Downloading the data should show no duplicates in the file.

### Sub-Tasks
_List of what needs to be done  on the technical side._
- [ ] Sub-task ...

### Testing Strategy
Anyone with access to Bastion and the QA site can test

_(!!) What happens if the user had virtual studies using the set?_

### Defects
_List of defects/bugs found during QA._
- [ ] Defect ...

**Comment by evans-g-crsj** [comment]
- [ ] backend

- [ ] front-end
