### ISSUE TITLE
Freactal(remove provideState): Settings sections

### ISSUE THREAD

**Issue by evans-g-crsj** [kids-first/kf-portal-ui#2669]
remove modal effects from Settings.

notes for dev:

_I had to temporarily duplicate de CavaticaConnectModal because it's too complicated to remove in one pr since this modal is used at other places than the settings_

QA: test that these modal are ok

![screenshot_settings_modal.png](https://images.zenhubusercontent.com/5d6419eca4c8f41d47fc9940/973165e4-9b99-410d-8d26-fcaaf03cc5f8)

**Comment by denis-crsj** [comment]
@vferretti Vincent, would you be able to test this one please? I don't have Cavatica or NIH accounts so I can't test this one to see if the modals open correctly...
