### ISSUE TITLE
Enable BAs to change display values of boolean fields

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#267]
in regards to:  #186

- boolean fields are supported now but still show true false
- need the ability to define a display value for true/false values in boolean fields

**Comment by phuongmy** [comment]
Impact on the different components of the portal: facet, query, table, export TSV
<img width="1166" alt="screen shot 2018-04-06 at 8 29 01 am" src="https://user-images.githubusercontent.com/8812383/38421356-d90be732-3974-11e8-804e-e99f8298b0dc.png">

Example 1
Field `Access` with values set to True = Controlled, False = Open
- Facet: should display 3 boxes: Any, Controlled, Open
- Query: should indicate "Access is Controlled"
- File table: displays a lock (specific type of facet)
- Export TSV: should export Controlled, Open values 

Example 2
Field `Proband` with values set to: True = Is Proband, False = <empty string>
- Facet: see screenshot below and design provided by Kim, the facet should display 3 boxes: Any, Is Proband, -- 
- Query: should indicate "Proband is null"
- File table: should show Proband column with values "Is Proband" or "--"
- Export TSV should export "Is proband" and "--" values

**Comment by rosibaj** [comment]
Tested query, facet, and download values and all appear to be working correctly with the changed values!
