### ISSUE TITLE
Remove extra white space below graphics on Dashboard's cards

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2676]
In the Dashboard, the cards showing the different graphics have extra white space below them. We need to remove or minimize as much as possible that extra space.

### Defects
- [x] Card header not aligned and graphic size smaller than other graphics

### Screenshots
![image](https://user-images.githubusercontent.com/64538118/92242565-f8314780-ee8d-11ea-8b34-d57895aa9fb8.png)

**Comment by evans-g-crsj** [comment]
QA : make sure all graphs work in dashboard and cohort builder

![screenshot_explore_data_graphs](https://user-images.githubusercontent.com/54366437/91343885-26869700-e7ab-11ea-90e4-5c957e1388a8.png)

**Comment by denis-crsj** [comment]
@evans-g-crsj Tous les graphiques ont l'air parfait excepté juste 1 seul que son titre n'est pas aligné avec celui des autres cartes et qui en plus petit également. Je ne sais pas si c'est voulu ou non mais je le log quand même au cas ou. J'ai ajouté le defect ainsi que le screenshot dans la description plus haut.

Je re-bouge donc la carte en "In progress"

**Comment by evans-g-crsj** [comment]
Here is the fix for 'Card header not aligned and graphic size smaller than other graphics'

![screenshot_fix-qa-defects-most-participants-studies](https://user-images.githubusercontent.com/54366437/92272904-6ee33a80-eeb8-11ea-82fb-41ac2f01e4eb.png)
