### ISSUE TITLE
Remove freactal modal from uploadIds modal (File Repo)

### ISSUE THREAD

**Issue by evans-g-crsj** [kids-first/kf-portal-ui#2683]
subTask of : Remove "provideModalState" #2667

![screenshot_uploadmodalids_location.png](https://images.zenhubusercontent.com/5d6419eca4c8f41d47fc9940/8bb385cb-a8b7-4d16-83d8-3c756a523d47)

![screenshot_uploadmodalids.png](https://images.zenhubusercontent.com/5d6419eca4c8f41d47fc9940/1e7eb341-dcd9-4690-9c52-c151bf633e27)

**Comment by denis-crsj** [comment]
@evans-g-crsj The visual on my side (Button UI and position) is different than the one in your screenshot, is it normal ?

![image](https://user-images.githubusercontent.com/64538118/92243153-03d13e00-ee8f-11ea-88e9-de935f9e80a3.png)

**Comment by evans-g-crsj** [comment]
> @evans-g-crsj The visual on my side (Button UI and position) is different than the one in your screenshot, is it normal ?
> 
> ![image](https://user-images.githubusercontent.com/64538118/92243153-03d13e00-ee8f-11ea-88e9-de935f9e80a3.png)

My bad...the first screenshot is the modal in PRD at the moment of this dev. So what you ve seen is ok

**Comment by denis-crsj** [comment]
Tested successfully.
