### ISSUE TITLE
Update text on the Variant DB home page

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2687]
- [x] Update menu title --> Variant Workbench
- [x] Update Text (See Notion link below)
- [x] Move button
- [x] Rename the shut down cluster button

https://www.notion.so/Portal-Text-b73a9bf805394d38b0faff8f46646586

### Defects
- [ ] When we minimize the page vertically, the footer and the content get mixed up (See screenshot). Issue happening on Chrome and Firefox

![image](https://user-images.githubusercontent.com/64538118/93791878-c5fc4580-fc02-11ea-8556-91a01a98a689.png)

**Comment by evans-g-crsj** [comment]
Note: after discussion buttons are to be placed on top of the cards (must update notion link) 

result
![screenshot_variant_workbench](https://user-images.githubusercontent.com/54366437/93392951-a39fac00-f83f-11ea-88b7-aa76d3fc4683.png)

**Comment by denis-crsj** [comment]
@evans-g-crsj Je viens noter un defect (Voir dans la carte en haut) N'hésite pas si tu as des questions.

**Comment by denis-crsj** [comment]
Ticket will be deployed as is and another issue has been created to fix the issue
