### ISSUE TITLE
Refactor CSS

### ISSUE THREAD

**Issue by Fgerthoffert** [kids-first/kf-portal-ui#269]
- [ ] theme folder -> top level css instead of individual ones
- [ ] add styled system + export components (Text, Row, Col, Box)
- [ ] Bring beagle css out of arranger to kf
- [ ] Remove inline styles out of arranger into normal css
- [ ] Repeat for KF portal code 
- [ ] Then, refactor to a single css style sheet and remove repeating stuff
- [ ] Fix many small things - start adding classnames and replacing elements with styled-system ones
- [ ] browser compatibility 
- [ ] responsiveness

**Comment by hlminh2000** [comment]
Let's close this as style refactor is basically being done alongside all the fixes now, and the style approach we're taking is quite different now
