### ISSUE TITLE
remove sensitive logs from persona + clean vault variables

### ISSUE THREAD

**Issue by evans-g-crsj** [kids-first/kf-portal-ui#2714]
When there is errors related to Mongo, they are logged in cloud watch but with sensitive information. We have to make sure to remove any sensitive information from the logs.

We also need to remove vault logic: remove all variables and branching in the code that uses vault. For example: the useVault branching is not needed anymore (and constants used in that block)

export const retrieveSecrets = () =>
    useVault
        ? Promise.all(
        [vaultEmailSecretPath, vaultMailchimpSecretPath].map(async secretPath =>
            (await vaultClient())
                .read(secretPath)
                .then(
                    ({data}) =>
                        secretPath === vaultEmailSecretPath
                            ? {
                                user: data.email,
                                pass: data.password
                            }
                            : data
                )
                .catch(e => {
                    console.error(`failed to retrieve secret at ${secretPath}`);
                    return Promise.reject(e);
                })
        )
        ).then(([emailSecret, mailchimpSecret]) => ({
            emailSecret,
            mailchimpSecret
        }))
        : Promise.resolve({
            emailSecret: emailSecretFallback,
            mailchimpSecret: mailchimpSecretFallback
        });

**Comment by denis-crsj** [comment]
@evans-g-crsj Il faudrais mettre un estimé sur cette carte svp quand tu as quelques instants.

**Comment by denis-crsj** [comment]
Transferred to Icebox for now
