### ISSUE TITLE
Upload IDs - Should not fetch all 10,000+ IDs

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2716]
When using the "Upload IDs" menu to upload IDs in the Cohort Builder, even if we only specify 2 or 3 IDs, it looks like the system still fetches every IDs in the system. It shouldn't do that.

![image.png](https://images.zenhubusercontent.com/5ea980d6189dd52c91ddddfa/322a9c09-a078-4b19-8d8b-7407f5468c0c)

**Comment by evans-g-crsj** [comment]
This task must is aborted. Changing option other than "any of" ("all of" or 'not') leads to undesired behaviour. Suppose two ids x and y then when querying for ALL_OF(x, y) gives empty result meaning no term is displayed. On the other hand, NOT(x, y) gives a list of all participant ids minus x and y (the complement). 

Suggestion: make a feature that allow to uploads ids INTO a set.
