### ISSUE TITLE
Cohort Builder - Unwanted spinner in Table/summary view toolbar

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2730]
**Bug description**
An unwanted spinner is intermittently showing up just above the "Files" link in the Table/summary view toolbar.

**Steps To Reproduce - Issue is intermittent**
1. Go to the Cohort Builder
2. Click on the File Repo link

**Expected behavior**
There shouldn't be any spinner

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ea980d6189dd52c91ddddfa/a0d43b02-88a3-4ae5-8f2f-a39785eb5c78)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.5
 - Browser: Chrome
 - Version: 85.0.4183.102 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by francisl** [comment]
the spinner should be there when fetching data, the issue is more the layout
