### ISSUE TITLE
Remove freactal dependency for clear all queries modal

### ISSUE THREAD

**Issue by evans-g-crsj** [kids-first/kf-portal-ui#2780]
![image.png](https://images.zenhubusercontent.com/5d6419eca4c8f41d47fc9940/dac8114a-6220-458d-b6dd-8f30e7281101)

![image.png](https://images.zenhubusercontent.com/5d6419eca4c8f41d47fc9940/8be0d001-e92c-4ee4-99ea-1e91ffdd614d)

Note: please test the whole sqonBuilder since some needed cleaning was done

![image.png](https://images.zenhubusercontent.com/5d6419eca4c8f41d47fc9940/e852ae6a-f763-4092-8c54-1c526cf15a1f)

**Comment by denis-crsj** [comment]
Tested successfully.
