### ISSUE TITLE
MONDO plot showing an empty graph when there is no data

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2787]
**Bug description**
The MONDO plot just show an empty graph when all the Mongo diagnosis for a study are marked as "Not reported".

EX: https://kf-api-dataservice.kidsfirstdrc.org/diagnoses?study_id=SD_8Y99QZJJ&visible=true

**Expected behavior**
The MONDO plot should have similar behavior to the phenotype plot and show “no data” or something similar

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ea980d6189dd52c91ddddfa/e91c5aa9-baec-4b24-a55a-25f3cc96b04b)

**Additional context**
N/A

**Comment by evans-g-crsj** [comment]
![screenshot_no_data](https://user-images.githubusercontent.com/54366437/106053741-26bbf300-60b9-11eb-99c2-f7793b229d3a.png)

**Comment by denis-crsj** [comment]
We now see a "No Data" message and icon in the Mondo Plot but I just saw that the "No Data" visual is not the same for the "Observed Phenotype" plot when there is no data for this one as well.

@luclemo Which visual should we use, the circle or the empty box icon?

![image](https://user-images.githubusercontent.com/64538118/106497734-6b1a0b00-648c-11eb-9f6e-1de663180242.png)

**Comment by denis-crsj** [comment]
Ok super, merci @luclemo ! Donc en gros il faudrait ajuster pour avoir le même visuel partout lorsqu'une requête ne retourne pas de données. Je remet la carte en "In progress"

**Comment by luclemo** [comment]
Oui il faut 'avoir partout.
J'ai créé 2 versions du components en 2 tailles différentes pour convenir aux différents usages à travers le portail.
![image](https://user-images.githubusercontent.com/1451515/106645946-0f6a8300-655b-11eb-9a8b-1510c1e0f8a2.png)
