### ISSUE TITLE
Remove the participant.diagnosis_category field and adjust queries accordingly in the cohort builder

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#2818]
Currently we have 2 fields for diagnosis categories. 
```
"participant_id":"PT_2EH6ZE0H",
 "diagnosis_category": null,
"diagnoses":[
    {    "diagnosis_category":"Cancer",
         "mondo_diagnosis": "Leukemia"
    }
]
```
This creates inconsistencies in the cohort builder. Example:  https://portal.kidsfirstdrc.org/explore?id=61s

First step: Fix the query in the cohort builder
Second step: Remove the diagnosis_category field at the participant level at the ETL step

**Comment by evans-g-crsj** [comment]
Minimally,

- [ ] mapping must be changed (remove diagnosis_category)

- [ ] The problem seems to be with participants having mondo diagnosis. That must be fixed + (remove filtering in portal UI)

**Comment by denis-crsj** [comment]
Validé avec Adrian
