### ISSUE TITLE
Switch Hotjar for usersnap

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2819]
Hotjar is currently integrated with the portal and it does not seems to have a very good feedback mechanism so we'll need to switch it back to usersnap, the solution that was in place before Hotjar

https://help.usersnap.com/docs/track-getting-started
https://help.hotjar.com/hc/en-us/categories/115001808227

**Comment by evans-g-crsj** [comment]
TODO: when in place, remove hotjar env var from netlify

**Comment by adipaul1981** [comment]
looks good

**Comment by denis-crsj** [comment]
Replacement has been completed. The only thing left to do will be to move the Feedback button on the right side of the screen but I think it has to be done in the usersnap account settings
