### ISSUE TITLE
Lock beta.kids-first.io with a user white list 

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#282]
the beta portal (beta.kids-first.io) is publicly accessible to anyone who wants to register right now. 

- Create a "whitelist" of users that have to be approved to gain access to beta.kids-first.io 
- needs to be done ASAP 
- When we deploy to alpha testing(defined user list) in production (URL TBD)  this will be maintained
- When we open to beta (public users) in production environment(URL TBD) , this restriction should be removed 

Discussed Implementation:

Portal & middleware will look for a person with "Approved" status in Ego.  If they are not approved, they will be redirected to a page.  If Approved, then they will proceed with the login wizard. 

make sure "approved" is in JWT

**Comment by andricDu** [comment]
Talked to Rahul, we shall look at the ego deployment.
