### ISSUE TITLE
Deploy Ego admin page in Amplify

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2823]
After the migration, we lost the admin interface for Ego. We would need to redeploy it on Netlify.

**See Alex or Jeremy for any questions**

**Comment by evans-g-crsj** [comment]
see AWS amplify

**Comment by evans-g-crsj** [comment]
see devop tickets: https://github.com/kids-first/devops-requests/issues/19

**Comment by denis-crsj** [comment]
transferred to Icebox for now
