### ISSUE TITLE
Cohort builder - Remove the age_at_diagnosis column and add the PedcBio one

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#2830]
- Remove Age_at_diagnosis column in the cohort builder table
- Add a column called PedcBio before the Files one. This column will display the PedcBioPortal ID with a hyperlink to it. See page https://portal.kidsfirstdrc.org/participant/PT_F822DBA0#summary for the link to add

**Comment by denis-crsj** [comment]
The Age_at_diagnosis column has been removed and the new field has been added. The link is also working properly. Moving card to DONE
