### ISSUE TITLE
Move "Members Interests" graph to the members section

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2846]
This chart is wrong since members have multiple interests. Make it a bar chart and show the top 10 interests. The chart should be dynamic, that is adjusted with the current query

**Comment by vferretti** [comment]
This chart is wrong since members have multiple interest. Make it a bar chart and show the top 10 interests

**Comment by denis-crsj** [comment]
Icebox for now, will revisit after april
