### ISSUE TITLE
Kf portal crashes on large Age of Diagnosis range

### ISSUE THREAD

**Issue by adipaul1981** [kids-first/kf-portal-ui#2849]
- create a Range filter with large age at Diagnosis (ex 4 years to 12 years)
![image.png](https://images.zenhubusercontent.com/5db1b4ee9f4bf300014d8774/a5c990b5-d124-4b2c-9130-893fec781e01)

- Click on  Demographics --> and field
![image.png](https://images.zenhubusercontent.com/5db1b4ee9f4bf300014d8774/751fec03-bff9-460f-a202-4ee7c621b961)

- crash

**Comment by adipaul1981** [comment]
The issue seems resolved. Cannot reproduce anymore.

**Comment by denis-crsj** [comment]
Unable to reproduce as well, issue seems fixed.
