### ISSUE TITLE
Cohort Builder: Suggest better default titles for saved sets

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#2851]
Currently, default titles are in format Saved_set_n. Implement same default title rules as for the File Repo saved queries.

Don't provide any default title for combined queries, i.e. queries that refers to another one (e.g #Q1 U #Q2)

**Comment by denis-crsj** [comment]
De mon côté tout semble beau.

**Comment by adipaul1981** [comment]
ca me semble ok aussi.
