### ISSUE TITLE
Participant Entity page: Replace section Available Data Files

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#2854]
Go to the page https://portal.kidsfirstdrc.org/participant/PT_F822DBA0#summary
and look at the section Available Data Files. The display is very bad and we want to improve it. We will do like in the GDC portal (see screenshot below)
Create 2 tables side by side  like in GDC
- First table: File counts by data type
 Columns: Data Type, Files,  (n=xx)
 where xx is the total number of files for this participant

- Second table: File counts by experimental strategy
 Columns: Experimental Strategy, Source Files, (n=yy), Harmonized Files, (n=ww)
 where yy is the total number of source files and ww is the total number of harmonized files for this participant

- Add like in GDC the small proportion bar icon. 

![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/960cb80b-fc27-41ea-9fc0-ddbb60c165f3)

Here is the[ link to GDC particpant page](https://portal.gdc.cancer.gov/cases/30bc72d5-07b5-48d2-b025-bba9bcf2f09f?filters=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22genes.is_cancer_gene_census%22%2C%22value%22%3A%5B%22true%22%5D%7D%7D%5D%7D)

**Comment by denis-crsj** [comment]
Icebox for now. Will revisit after April
