### ISSUE TITLE
Summary View - Study widget should be filtered as well when clicking on a study

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2857]
At the moment, when you click on a study in the Study widget, it filters every other widgets but not itself. We need to modify so that it also gets filtered.

![image.png](https://images.zenhubusercontent.com/5ea980d6189dd52c91ddddfa/fdc8b55e-ff59-47e3-99fd-632b6be42015)

**Comment by vferretti** [comment]
It's a general problem. A facette are not filtered when one of its values  is selected. This is the right behavior. However, for the graphs, we need to filter them even if one of its values is part of the query

**Comment by denis-crsj** [comment]
The graph is now filtered when selecting a study
