### ISSUE TITLE
Search by PHS aka the dbgap accession number

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2860]
This is the ID that is used when you apply for access on dbgap. This is also the id that the NIH puts on their managed KF page to indicate a study is released. So they think there are people coming to the portal with the PHS and want to search on that.

This value is stored as the external_id in Study, we need to be able to search by this ID in the file repo

**Comment by adipaul1981** [comment]
I would require same precision on this task plz:

1. Do we need to add a new filter in the File Filters? eg:
![image](https://user-images.githubusercontent.com/29788342/102261199-5636e780-3edf-11eb-8937-667028d766af.png)

2.  If yes, it will be a list by all external_ids and they count (ordered from highest count to least)? (like the File Format for ex)
![image](https://user-images.githubusercontent.com/29788342/102261465-b463ca80-3edf-11eb-8f1a-0c94b4ecb698.png)

**Comment by adipaul1981** [comment]
Actually the code was already existing in the portal for the filter by `study.external_id`. I've just fixed the issue with the mapping to display it properly in the portal. Here is the result:

![image](https://user-images.githubusercontent.com/29788342/102408788-1bef4800-3fbc-11eb-92aa-b7b7de995d81.png)

**Comment by denis-crsj** [comment]
La recherche fonctionne bien.
