### ISSUE TITLE
FIX: make sure portal does not break when logging out

### ISSUE THREAD

**Issue by evans-g-crsj** [kids-first/kf-portal-ui#2866]
from slack (portal channel):

![image.png](https://images.zenhubusercontent.com/5d6419eca4c8f41d47fc9940/4f9831a5-bdb8-4b3b-afb7-f9e490d9a225)

zoom in:

![image.png](https://images.zenhubusercontent.com/5d6419eca4c8f41d47fc9940/2a1ef919-5b2e-4593-b48c-c0b362ac8936)

**Comment by denis-crsj** [comment]
Login and logout multiple times and was not able to reproduce the issue. Looks like the issue is resolved.
