### ISSUE TITLE
Fix missing phenotype fields in the case of same phenotype

### ISSUE THREAD

**Issue by adipaul1981** [kids-first/kf-portal-ui#2867]
fields are missing:
![image.png](https://images.zenhubusercontent.com/5db1b4ee9f4bf300014d8774/64c0c4c2-7312-4094-8322-a76ef5f8bb6a)

![image.png](https://images.zenhubusercontent.com/5db1b4ee9f4bf300014d8774/30ddc744-f0c3-4675-9b4d-9a08128dbee8)

This is just a fix for the immediate bug. Ideally, a discussion should take place if we want to replace the `phenotype` field, with the `(non)observed_phenotype`, and what that would imply.

**Comment by denis-crsj** [comment]
Validé avec Adrian
