### ISSUE TITLE
Handle Expired Tokens

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#288]
Right now, a users token can expire, causing the file repository data to not load (due to an expired token).  The site is partially functional, but looks like it is crashing.  

The behaviour that should be happening is that if the token is expired, redirect the user to the login screen

**Comment by hlminh2000** [comment]
- [ ] Server-side needs to respond with error to client when token expired (https://github.com/overture-stack/ego-token-middleware/pull/3)

- [ ] Client-side needs to re-direct user to log-in screen when receives 401
