### ISSUE TITLE
Date Range Facet UI is cut off/unusable 

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#290]
![Screen Shot 2018-04-13 at 4.18.49 PM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/a220ef9d-1f63-449f-90ef-c0d8f5138633)

The right side of the Date facet is cut off on the right.  Then, when you click, the facet should expand out, but it is trapped in the right panel. 

![Screen Shot 2018-04-13 at 4.21.35 PM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/33d5067b-05ec-4d9a-a044-b291c1e16e95)

Also, for the boolean facet, the border color for selection is #00afed and Any should be capitalized 

![screen shot 2018-04-13 at 4 27 30 pm](https://user-images.githubusercontent.com/15824252/38756453-980fe12a-3f37-11e8-9238-edd1f1d1a0c8.png)

**Comment by rosibaj** [comment]
@jgnieuwhof Was there some sort issue with the text input box?  Users should be able to type a date in as well.  Alternately, if this calendar has a year widget, that could help as well.

**Comment by jgnieuwhof** [comment]
@rosibaj - this is a hole in the `react-dates` airbnb date picker design. there's a PR that's actively being reviewed here - https://github.com/airbnb/react-dates/pull/1106 (issue here - https://github.com/airbnb/react-dates/issues/25).

what do you think? I could put a comment/+1 in the issue & PR to try and help get this merged quicker if this would be sufficient for our needs.

**Comment by rosibaj** [comment]
@jgnieuwhof hmm we definitely need a way to select the year and airbnb may not implement in time.  I would comment/+1 for sure - In the meantime, can we return to the original date input design to allow users to do it that way at least?
