### ISSUE TITLE
Variant Warehouse: Improve error messages and Spark cluster session management 

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#2905]
- I was initially disconnected from the two data repositories (KF and NCI) 
- I get an error message when I try to launch a Spark cluster 
TO DO: improve message error to indicate users need to connect first to the data repos (DR) and add the link to the settings page.
- Connect to the 2 DR in the user's setting page
- you can now launch the cluster
- disconnect to the 2 DR
- close your cluster
- launch again your cluster. -> it works even if I am disconnected from the two DR  (weird)
- close your cluster
- log out from the KF portal and log in again -> I am still disconnected from the DR
- Launch your cluster -> it still works (weird)

---

While the cluster starts, we ping every 30 seconds to check if the cluster finished loading. If the cluster shuts off after an hour of inactivity, the button should change back to initial state.

- We should continue to ping to make sure the cluster is still up.

### Tasks
- [x] Improve error message to explain to user that the fences are disconnected and add a link that redirect to the Settings page to allow the user to reconnect his fences
- [x] Modify the code to continue pinging even after the cluster is up because when it shuts down, we want to switch back the button to it's original state "Start cluster"

**Comment by luclemo** [comment]
@celinepelletier 
![image](https://user-images.githubusercontent.com/1451515/116292063-48358500-a763-11eb-83e6-6584b334bfd3.png)
