### ISSUE TITLE
[variant-wb-automation] Add Clinvar automation task to the Airflow DAG

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2909]
This will launch the Spark job and then launch the import process. We will start from Christophe's already existing DAG.

- [x] Need CHOP to install an instance of Airflow (Jeremy will speak to Alex).
- [ ] implement and upload a dag to automate clinvar update on a weekly basis

**Comment by botekchristophe** [comment]
the role used by airflow to run the jobs is missing permission to access s3 bucket kf-strides-variant-prd.
Ask Devops to fix this

**Comment by alubneuski** [comment]
@botekchristophe does it need read/write or just read permissions to that bucket?
