### ISSUE TITLE
The Biospecimen export on the Cohort Builder times out for large cohorts

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2925]
**Bug description**
If you try to download the Biospecimen data for a too large cohort, the request times out and display an error message

**Steps To Reproduce**
1. Go to the Cohort Builder
2. Click on "Study" and select the CBTTC Pediatric Brain Tumor Atlas study
3. Click on "Download" and then click on "Biospecimen Data"
4. Wait for a while and then notice the error message in the upper right corner

**Expected behavior**
The request should not time out and the file should be downloaded normally

**Screenshots**
![image](https://user-images.githubusercontent.com/64538118/106194159-77e0eb00-617c-11eb-83af-550c7914344f.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by evans-g-crsj** [comment]
After investigation, the problem may be from the devops'side _https://github.com/kids-first/kf-devops/issues/580_ ....waiting for that part of the puzzle to be solved before continuing on.

**Comment by evans-g-crsj** [comment]
boosted instance computing power

**Comment by denis-crsj** [comment]
Was able to downlaod the CBTTC study biospecimen report. closing issue
