### ISSUE TITLE
Gen3 : use RAS IDP for login 

### ISSUE THREAD

**Issue by jecos** [kids-first/kf-portal-ui#2965]
RAS is already integrated in gen3, but by default, when user login in gen 3, NIH is still used (default one)
We should add an environment variable for each fence to specify IDP to use
```
GEN3_IDP : ras
DCF_IDP : ras
```

If we want to use NIH instead of RAS, we should set this env var to `fence`

Then we should use this env var when we build gen3 redirect URL and set `idp` request parameter with the value set in the env var: 
https://github.com/kids-first/kf-portal-ui/blob/61006080c859f0c485bcd004edbdb4fedc881f5f/src/services/fence.js#L54

Here the list of supported fences in gen3 :
https://gen3staging.kidsfirstdrc.org/user/login

Here the full api documentation :
 https://petstore.swagger.io/?url=https://raw.githubusercontent.com/uc-cdis/fence/master/openapis/swagger.yaml#/oauth2/authorize

**Comment by denis-crsj** [comment]
Spoke with Eric and Bailey, they will try to test on their side and see if it works
