### ISSUE TITLE
Implement Virtual grouping for top fields

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#299]
- [ ] Data Type, File Format, File Size should all be nested under a "File Properties" category.  
We can introduce a "virtual group" for all top level fields under the file index 

expected:

![screen shot 2018-04-03 at 1 13 55 pm](https://user-images.githubusercontent.com/15824252/38264486-1e4c0f60-3741-11e8-97e4-d784cf6a7f3a.png)

now:
<img width="337" alt="screen shot 2018-04-03 at 1 13 50 pm" src="https://user-images.githubusercontent.com/15824252/38264414-e6f5b99e-3740-11e8-9d34-2c4e2fcca0a3.png">

**Comment by jgnieuwhof** [comment]
addressed in https://github.com/overture-stack/arranger/pull/359
