### ISSUE TITLE
Cohort builder - Summary View - Studies bar chart: Replace study names by study codes in Y axis

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#3005]

**Comment by denis-crsj** [comment]
The Y axis is now correctly using the Study Codes but we can see a code called `_missing_` in the results. That should probably be removed.

![image](https://user-images.githubusercontent.com/64538118/117136082-e1712680-ad75-11eb-945f-fc203133d1e6.png)

**Comment by adipaul1981** [comment]
Its a issue with the data. For one study, its missing the study code here. Its not an issue with this task. There should be a code for every study. I'm running shortly the ETL again in QA (for other reasons) it should correct the issue. If not, it has to be investigated why it still missing. 

Also the names showed on hover, are not the `short_name`. It should be. That also should be corrected with the re-run of the ETL. This short name should also be displayed in the study page table.
