### ISSUE TITLE
Download state management 

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#302]
- click the Clinical (Participant) download button 
- if your token is valid, the file downloads, however, the button on the spinner spins forever 
- If you download a Participant manifest, the same behaviour occurs - it downloads, but the spinner spins forever. 
-

**Comment by jgnieuwhof** [comment]
fix here - https://github.com/overture-stack/arranger/pull/343

**Comment by rosibaj** [comment]
All tested - Fix looks to be working well!  Thanks @jgnieuwhof
