### ISSUE TITLE
Summary Data is Wrong

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#304]
Query: https://beta.portal.kids-first.io/search/file?sqon=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22%3E%3D%22%2C%22content%22%3A%7B%22field%22%3A%22participants.diagnoses.age_at_event_days%22%2C%22value%22%3A28%7D%7D%2C%7B%22op%22%3A%22%3C%3D%22%2C%22content%22%3A%7B%22field%22%3A%22participants.diagnoses.age_at_event_days%22%2C%22value%22%3A9426%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22participants.diagnoses.diagnosis_category%22%2C%22value%22%3A%5B%22Cancer%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22participants.samples.aliquots.analyte_type%22%2C%22value%22%3A%5B%22RNA%22%5D%7D%7D%5D%7D . 

![screen shot 2018-04-20 at 1 51 55 pm](https://user-images.githubusercontent.com/15824252/39066130-0ba7a1d0-44a2-11e8-97de-87b3fd323733.png)

The summary says that there is *1 family*, but if you check the data, there are no family members or families in this data set.  The summary should say 0 families

**Comment by jgnieuwhof** [comment]
fix in https://github.com/overture-stack/arranger/pull/346 and https://github.com/kids-first/kf-portal-ui/pull/319

**Comment by rosibaj** [comment]
@jgnieuwhof Tested - looks like when there are NO families it works fine: 
https://beta.portal.kids-first.io/search/file?sqon=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22participants.study.external_id%22%2C%22value%22%3A%5B%22KF7316%22%5D%7D%7D%5D%7D


but when i have a query, the numbers are not fine - the #files, # participants, and # families is always the same :

 https://beta.portal.kids-first.io/search/file?sqon=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22participants.samples.anatomical_site%22%2C%22value%22%3A%5B%22C76.3%3A%20Pelvis%2C%20NOS%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22participants.study.external_id%22%2C%22value%22%3A%5B%22phs001194%22%5D%7D%7D%5D%7D

**Comment by rosibaj** [comment]
Retested - I think there was an issue with some caching as it appears to be adjusting correctly now.
