### ISSUE TITLE
Add semver visuals

### ISSUE THREAD

**Issue by bdolly** [kids-first/kf-portal-ui#306]
Add semantic version numbering to portal in order to allow easy version tracking and issue resolution. This will also help in user testing so we can report on what specific version of the code base that the issue was experienced.

**Comment by jgnieuwhof** [comment]
I think this ticket depends on what our production (post-beta) release strategy will be. Right now we're doing CI / CD right off of master, but I assume at some point we're going to want to switch to a flow where (master|develop) branch deploys to a (staging|qa) environment and production releases are planned & controlled.

@andricDu - is there currently a plan in place for production releases once we're out of alpha / beta?

**Comment by andricDu** [comment]
Good question @jgnieuwhof , something we should discuss sooner rather than later.

Currently no agreed on plans regarding this.

**Comment by hlminh2000** [comment]
It's reading from `package.json` now, got it showing in the footer as below and included in usersnap data.

Note for CI @andricDu: As long as the value in `package.json` is only modified with `npm version` command, git tag will be up to date. https://docs.npmjs.com/cli/version

![screen shot 2018-06-14 at 4 52 31 pm](https://user-images.githubusercontent.com/11821106/41437769-60f2df2a-6ff3-11e8-8ed5-b69de1e71676.png)
