### ISSUE TITLE
Use operator AND when adding a term to an active query from the sunburst

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#3070]
Cohort builder.
Create a query with an Observed phenotype A
Use the sunburst to select and add another phenotype B to the active query

As a result, the active query is now Observed phenotype = A OR B.  (any of)

This should be A **AND** B  (all of)

![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/f6175b02-17f0-4231-a4fc-a8fae9f174ef)

**Comment by denis-crsj** [comment]
tested successfully
