### ISSUE TITLE
discrepancies with Clinvar values

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#3106]
serach for vairiant 1-45343310-G-A
in the result table, you can see than clinvar = Benign, Likely_benign
but in the entity page, clinical association tab, it is only Benign

**Comment by botekchristophe** [comment]
I believe this is a front-end bug because in the data I have 'Benign, Likely_benign'
<img width="1688" alt="Screen Shot 2021-04-20 at 1 37 54 PM" src="https://user-images.githubusercontent.com/4457114/115440529-d34fd180-a1dd-11eb-9cbb-3517a34f91ea.png">

**Comment by botekchristophe** [comment]
same in elasticsearch
<img width="1079" alt="Screen Shot 2021-04-20 at 1 41 33 PM" src="https://user-images.githubusercontent.com/4457114/115440824-2aee3d00-a1de-11eb-8099-51627e73bb10.png">

**Comment by botekchristophe** [comment]
The 'interpretation' section in Clinvar tab is wrong
<img width="846" alt="Screen Shot 2021-04-20 at 1 43 55 PM" src="https://user-images.githubusercontent.com/4457114/115441099-7acd0400-a1de-11eb-8c94-1bea10825cc6.png">

**Comment by vferretti** [comment]
un autre exemple est 

rs120074160
