### ISSUE TITLE
Change columns for allele frequencies

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#3109]
We have to change some columns in the result table and in the entity page, KF cohorts table.
- [ ] Replace these columns 
![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/4ae24592-aeaf-42b4-9501-f03aa406496e)

by Participants , ALT Alleles, Homozygotes 
where Participants is of the form X / N (écriture scientifique) 
where X = participants, N = total_participants and Y = frequency_participant

- [ ] do the same for the KF cohort table
![image](https://user-images.githubusercontent.com/1181124/114736251-efea9600-9d13-11eb-8887-3170a8059e8c.png)

- [x] Replace the current Frequencies below by frequency_participant

![image](https://user-images.githubusercontent.com/1181124/114734547-5078d380-9d12-11eb-82f6-7cd65fe658c0.png)

**Comment by botekchristophe** [comment]
the information per studies are available as:
X: studies[k]. participant_number
N: participant_total_number

for the variant:
X: participant_number
N: participant_total_number
