### ISSUE TITLE
Display impact long names

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#3111]
Currently, we use D, T, etc. for the impact calls

![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/31b23fc9-cd6f-48d1-8eb9-efa2944544a2)

Find the corresponding names for each score (eg. D means Deleterious)  and display them

Please, double check why there is no call for polyphen. This is maybe not normal

**Comment by denis-crsj** [comment]
Would need to provide mapping.

**Comment by botekchristophe** [comment]
I checked the scores and predictions. the prediction is not shown when the data is missing in Elasticsearch which is normal. I looked at few exemple and there was no discrepancies.

**Comment by botekchristophe** [comment]
Based on documentation (https://vatlab.github.io/vat-docs/applications/annotation/variants/dbnsfp/)

SIFT_pred
- D -> damaging
- T -> tolerated
Polyphen2_HVAR_pred
- P -> possibly damaging
- D -> probably damaging
- B -> benign
FATHMM_pred
- D -> damaging
- T -> tolerated
LRT_pred
- D -> deleterious
- N -> neutral
- U -> unknown
