### ISSUE TITLE
Table data : fix markup for links in table cells

### ISSUE THREAD

**Issue by luclemo** [kids-first/kf-portal-ui#3122]
Remove the button embedded inside the link. This will also fix the alignment issue.

![Pasted_Image_2021-04-15__3_28_PM.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/8fcbd339-b395-4d6a-83da-750d3e3af57f)

![image.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/1cc4021f-4f0d-4ce0-8f10-3b4736fafa53)

**Comment by evans-g-crsj** [comment]
solved. However, this ticket was not tagged in the pr that solved it.
