### ISSUE TITLE
Variant entity page : update display for empty tables (change request)

### ISSUE THREAD

**Issue by luclemo** [kids-first/kf-portal-ui#3128]
- [x] Change display for empty cards (see screenshot and [link to mockup](https://www.figma.com/file/xelYw9knAeZJomJ2lh4xfa/KF-Variant-Page?node-id=1089%3A24853))
- [x] When an entire tab has no data available, we will display the tab anyway (prior rule was to disable tab + tooltip)

![Pasted_Image_2021-04-16__4_03_PM.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/bc52f94d-49fa-415e-9c8e-b7d7ac549ed7)

**Comment by evans-g-crsj** [comment]
After discussing with @luclemo we have decided to change the display a little bit.

![image](https://user-images.githubusercontent.com/54366437/117050146-05cff300-ace3-11eb-8331-de50e0907224.png)

Main reason:

- avoid customization (antd doesn't support a card with a header only and an empty body)

For QA, I've only found empty data for the external cohorts table and the clinvar table. Please provide examples for other cases should they exist.

**Comment by evans-g-crsj** [comment]
**Note:** I've found a case in the search page that leads to an empty table. Search for `JKAMP` in QA and you'll get

![image](https://user-images.githubusercontent.com/54366437/117060811-6107e280-acef-11eb-9f52-c7eb781d8987.png)

Since it's a different scenario than the one in this ticket and I'm not sure what to display , I'll leave this case unsolved for now.

**Comment by botekchristophe** [comment]
for JKAMP it's ok it's only in QA, because the chromosome 14 is not available. the data is there in prod

**Comment by botekchristophe** [comment]
![Screen Shot 2021-05-06 at 10 00 53 AM](https://user-images.githubusercontent.com/4457114/117311297-12bf2480-ae52-11eb-84ce-af74289900d5.png)
The tab looks inconsistent, I'll reopen this bug
I believe the two tab should look the same.

**Comment by botekchristophe** [comment]
When the data is loading, we can see that the default page 'no data' is the old one.
to repeat the problem click on Summary then on Frequencies and look at 'Kids First Studies'. while it's loading it shows the old 'no data' icon.
<img width="1675" alt="Screen Shot 2021-05-06 at 4 05 32 PM" src="https://user-images.githubusercontent.com/4457114/117359050-e40e7180-ae84-11eb-9ff2-c63fcf63a947.png">
