### ISSUE TITLE
Show current table  page information on Top

### ISSUE THREAD

**Issue by francisl** [kids-first/kf-portal-ui#3130]
showing 1 - 10 of 28 above the table

**Comment by luclemo** [comment]
Looks perfect except for the colour. Should be the basic body color:  `body-1` (`#383F72`)

**QA:**
![image.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/e8ac7c59-53f4-458e-b84c-e9d1c4643a68)

**Mockup:**
![image.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/545e4c07-0ec7-43d6-b963-d381bf5ba7dc)

https://www.figma.com/file/xelYw9knAeZJomJ2lh4xfa/KF-Variant-Page?node-id=1117%3A44

**Comment by denis-crsj** [comment]
Il semble que la couleur bien que spécifié à quelque part dans le code, ne soit pas appliquée correctement. Quand j'inspecte l'élément, je vois 2 couleurs différentes pour le texte qui ne sont pas les bonnes.

![image](https://user-images.githubusercontent.com/64538118/119504802-52cf4400-bd3a-11eb-9a2c-410ae5cb76e3.png)

![image](https://user-images.githubusercontent.com/64538118/119504650-2fa49480-bd3a-11eb-8e01-980090271a0f.png)

![image](https://user-images.githubusercontent.com/64538118/119504701-392dfc80-bd3a-11eb-810a-6d7aad5021a1.png)

**Comment by denis-crsj** [comment]
@francisl Voir mon commentaire juste avant. Je remet donc la carte dans la colonne "In Progress"
