### ISSUE TITLE
hgvsg field shouldn't be null

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#3136]

**Comment by botekchristophe** [comment]
[before_split_multi_allellic.csv](https://github.com/kids-first/kf-portal-ui/files/6358909/before_split_multi_allellic.csv)
<img width="1682" alt="after_split" src="https://user-images.githubusercontent.com/4457114/115728648-aa048200-a352-11eb-8c58-53bf534a5332.png">
