### ISSUE TITLE
Add CI/CD pipeline to kf-dag-portal-etl

### ISSUE THREAD

**Issue by botekchristophe** [kids-first/kf-portal-ui#3161]
the pipeline should include

- [x] Pylint
- [x] Copying the dags folder to s3://kf-strides-232196027141-service-dag-bucket/dags
- [x] Copying the requirements.txt file to s3://kf-strides-232196027141-service-dag-bucket/requirements.txt

**Comment by celinepelletier** [comment]
CI (aka pylint) -> Circle-ci
CD (aka aws cp) -> Jenkins

**Comment by celinepelletier** [comment]
CI : https://app.circleci.com/pipelines/github/kids-first/kf-dag-portal-etl
<img width="1918" alt="Capture d’écran, le 2021-05-11 à 10 04 29" src="https://user-images.githubusercontent.com/82821620/117829027-5ba31e80-b240-11eb-9cec-cbdbe2ed3aa2.png">

CD : https://aws-infra-jenkins-service.kf-strides.org/job/kids-first-kf-dag-portal-etl/
Apply only for master branch (do nothing for others)
<img width="917" alt="Capture d’écran, le 2021-05-11 à 09 56 40" src="https://user-images.githubusercontent.com/82821620/117829138-79708380-b240-11eb-8557-0ce47bf84e09.png">

Upload requirements.txt in S3
<img width="1595" alt="Capture d’écran, le 2021-05-11 à 09 58 14" src="https://user-images.githubusercontent.com/82821620/117829202-89886300-b240-11eb-9685-77c6d3070831.png">


Upload dags/** in S3
<img width="1599" alt="Capture d’écran, le 2021-05-11 à 09 58 33" src="https://user-images.githubusercontent.com/82821620/117829255-94db8e80-b240-11eb-9ed4-5267665ea18f.png">
