### ISSUE TITLE
Implement a simple DAG that demonstrate how to use airflow slack operators

### ISSUE THREAD

**Issue by botekchristophe** [kids-first/kf-portal-ui#3162]

**Comment by celinepelletier** [comment]
Notifications sent to #airflow-kf slack channel

<img width="1114" alt="Capture d’écran, le 2021-05-04 à 15 47 04" src="https://user-images.githubusercontent.com/82821620/117061300-028f3400-acf0-11eb-8ce6-dfacab49b713.png">
