### ISSUE TITLE
Variant Search: We can't select and copy the text from the Variant column which is very annoying 

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#3167]
![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/1803712c-cbb3-4e1e-b43a-3d9b32908d92)

**Comment by luclemo** [comment]
@vferretti This is because it's coded as a button rather than a link. I think @evans-g-crsj was working on fixing all of those across all the tables.

**Comment by evans-g-crsj** [comment]
Francis' previous fixes regarding the links fix that issue as well.
