### ISSUE TITLE
Responsive theme for smaller screens

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#32]
Design mockups: responsive theme (tablet priority

**Comment by kcullion** [comment]
Did mockup of how the mobile navigation would look/behave:

![05 kidsfirst-portal-dashboard-mobile](https://user-images.githubusercontent.com/18424138/40196675-3b1cc4f2-59df-11e8-9592-996a4c8da46c.jpg)
![06 kidsfirst-portal-mobile-menuopen](https://user-images.githubusercontent.com/18424138/40196676-3b2b2b50-59df-11e8-830a-58eda3544d2c.jpg)

**Comment by bdolly** [comment]
would the file repo also have a mobile design? Also curious what the use cases for mobile would be.
