### ISSUE TITLE
Add ability to subscribe to KF when signing up

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#321]
The AOC wants to give people the option to sign up for the KF mailing list when they sign up with KF, as well as the option to subscribe for the NIH program list.   

Design:
https://projects.invisionapp.com/d/main/default/#/console/13157333/275376887/preview

- [x] There should be 2 opt-ins - one for KF and one for NIH.
- [x] KF Opt-in (first box) 
> The KF team uses MailChimp as their subscription service. Here are the development docs to send an email to a list. https://developer.mailchimp.com/documentation/mailchimp/guides/manage-subscribers-with-the-mailchimp-api/
The KF List id is: 741ebc6736

- [x] NIH Opt-in (second box) 
>The NIH team uses manual management.  If a user signs up and has this box selected, and email should be sent to KidsFirst@od.nih.gov 
The content of this email should say:
>>Full User Name: <First Name Last Name>
User Email: <email address signing up with>
Date Opted IN: <current date>
Source = Kids First DRP Registration

**Comment by kcullion** [comment]
@rosibaj just to add..I asked Bailey and she said this is the same mailchimp newsletter signup that will be on the website. Just an FYI

**Comment by rosibaj** [comment]
@kcullion Yes, that is what I was expecting!  Once designs are done, we can connect with their MailChimp Admin to get the right info  - just storing the MailChimp info with the ticket so it's easier to implement later!

**Comment by hlminh2000** [comment]
@rosibaj some additional resources we need for this feature to work in prod:
1) username and API an key for the kf team's mailchimp
2) access

**Comment by hlminh2000** [comment]
:/ looks like I clicked close by accident before finished typing... yeah the aws email access, I'll work with Rahul on that ;)

**Comment by hlminh2000** [comment]
This is al in now so we can close this ticket
