### ISSUE TITLE
Variant page : Orphanet link always redirect to the same disease

### ISSUE THREAD

**Issue by jecos** [kids-first/kf-portal-ui#3226]
**Bug description**
Open any variant page with orphanet disease, and navigate to Clinical Associations tabs : 
[Example](https://portal.kidsfirstdrc.org/variant/d4b0f542f86c1c156da89fff9ff2f972f4705c7e?hgvsg=chr1:g.45331556C%3ET#view=clinical)

Then click on orphanet link, the disease is not the good one 

NB : Orphanet is not working today, when it will be back we could give more informations

**Comment by evans-g-crsj** [comment]
https://kidsfirst-team.slack.com/archives/GP759PD6F/p1620845416170200

example of correct link: https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=19549
