### ISSUE TITLE
build: decrease vulnerabilities from dependencies as much as possible

### ISSUE THREAD

**Issue by evans-g-crsj** [kids-first/kf-portal-ui#3244]
from npm audit : `found 676 vulnerabilities (288 low, 168 moderate, 220 high) in 3392 scanned packages`

**Comment by celinepelletier** [comment]
TODO : 
<img width="1290" alt="Capture d’écran, le 2021-05-12 à 10 25 35" src="https://user-images.githubusercontent.com/82821620/117991935-7fcc3180-b30c-11eb-8ed1-de0fe4b3f8cd.png">

**Comment by celinepelletier** [comment]
<img width="304" alt="Capture d’écran, le 2021-05-18 à 09 52 54" src="https://user-images.githubusercontent.com/82821620/118663662-db8c3400-b7be-11eb-85a4-e3ecfdfb74f8.png">

**Comment by celinepelletier** [comment]
Also fix babel-polyfill deprecated warning message
