### ISSUE TITLE
User Profile Banners + tags

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#325]
The user profile banners need to be updated with the purchased istock image (see pngs in the comment). Please also add the background gradient as specified, so it's consistent with what has been done on the dashboard.

**Research user:**
Use the transparent dna image that fades into a blue gradient: 
background-image: linear-gradient(rgb(38, 109, 177) 33%, rgb(17, 134, 176) 66%, rgb(18, 151, 215));
background-position-x: right;

Research tag colour: #00afed;
![screen shot 2018-05-01 at 12 21 43 pm](https://user-images.githubusercontent.com/18424138/39481691-46abc9c8-4d3a-11e8-9ecc-29cfc2fc318d.png)

**Community user:**
Use the transparent block image that fades into a pink gradient: 
background-image: linear-gradient(rgb(143, 52, 127) 33%, rgb(169, 64, 139) 66%, rgb(205, 81, 98));
background-position-x: right;

Community tag colour: #e83a9c;
![screen shot 2018-05-01 at 12 23 20 pm](https://user-images.githubusercontent.com/18424138/39481775-8ce5fc74-4d3a-11e8-869b-885c22a79cbd.png)

**Health user:**
Use the transparent stethoscope image that fades into a green gradient: 
background-image: linear-gradient(rgb(10, 93, 108) 33%, rgb(25, 136, 149) 66%, rgb(28, 163, 158));
background-position-x: right;

Health tag colour: #1f9bb6;
![screen shot 2018-05-01 at 12 25 38 pm](https://user-images.githubusercontent.com/18424138/39481842-cba49204-4d3a-11e8-8e5d-0abcb0a88f3c.png)

**Comment by kcullion** [comment]
![user-banner-community](https://user-images.githubusercontent.com/18424138/39482019-76e25fb6-4d3b-11e8-9e7d-6585a12cf63e.png)
![user-banner-health](https://user-images.githubusercontent.com/18424138/39482020-76ec2604-4d3b-11e8-8b13-b3062a22fed8.png)
![user-banner-research](https://user-images.githubusercontent.com/18424138/39482022-776e55a2-4d3b-11e8-89e3-4d7f36c5e14d.png)

**Comment by rosibaj** [comment]
@jgnieuwhof @kcullion The icons for Community is not right. It should have a circle around them like Research does.  Kim, can you make sure Jordan has the right image for that?

**Comment by jgnieuwhof** [comment]
@rosibaj - icon should be updated now :)

**Comment by rosibaj** [comment]
tested - looks great!  thanks @jgnieuwhof
