### ISSUE TITLE
Graphics : remove underline on field labels from Studies and Mondo graphs

### ISSUE THREAD

**Issue by luclemo** [kids-first/kf-portal-ui#3255]
Currently the fields for the studies and mondo graphics are displayed with an underline. This is inconsistent with the other graphics. Additionally the underline is an affordance associated with links so the user may get confused.

**Task:** Remove underline from the fields in both graphics.

![Pasted_Image_2021-05-13__3_04_PM.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/3aefd8d6-0c87-4ec4-b886-d0def5b856ac)

**Comment by celinepelletier** [comment]
Fix applies for
Most Frequent Diagnoses (Mondo) (Explore data)
Studies (Explore data)
Most Frequent Diagnoses (Dashboard)
Studies - Participants (Dashboard)
