### ISSUE TITLE
Fix various issues in study page

### ISSUE THREAD

**Issue by adipaul1981** [kids-first/kf-portal-ui#3310]
### Feature

Fix/enhance the issues specified bellow: 

-  for search bar add a suggestion drop-down similar to this:
![image](https://user-images.githubusercontent.com/29788342/119831320-2a2a8400-becb-11eb-95b2-b6011ef35829.png)
- in drow-down: 1st tile is the `short_name` (bold) and 2dn line is the `study_code`
- on click of a study, table is filtered to that study only.
- change suggestion message to _e.g. KF-DSD, Neuroblastoma_
- change info message to _Search by study code or name_
- Change title to _Search Studies_
- Fix pagination issue
- 50 studies per page as default

### Resources

https://www.notion.so/ferlab/Study-list-Page-dc32283665dd432790e67e46f2d5e596

**Comment by luclemo** [comment]
Ant component: Multiselect with responsive count (https://ant.design/components/select/#components-select-demo-responsive)

**Comment by luclemo** [comment]
@adipaul1981 Mockup details: https://www.figma.com/file/IelL4AHNbrBxDA94zSOxJt/KF-Studies?node-id=1109%3A30955
