### ISSUE TITLE
Refactor: remove lib react-grid-system

### ISSUE THREAD

**Issue by evans-g-crsj** [kids-first/kf-portal-ui#3323]
there seems to be only one component that uses this lib: src/uikit/SummaryTable/index.js

If this is dead code, then remove it and flush the lib (after making sure it s not use elsewhere, of course)

![image.png](https://images.zenhubusercontent.com/5d6419eca4c8f41d47fc9940/d8d7bc95-47fd-4682-af2b-3f5c8c8baa26)

**Comment by celinepelletier** [comment]
Closed by https://github.com/kids-first/kf-portal-ui/pull/3345/files#submit-review
