### ISSUE TITLE
Implement new download manifest modal design 

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#333]
Design: 

- the data should remain/behave the same (click on download button)
https://projects.invisionapp.com/share/MQFHWABDK9Y#/294604046_29a-KF-File-Repository-Manifest1 

The designs have been uploaded to zeplin:
https://zpl.io/29DRw1e
https://zpl.io/VQo455P
https://zpl.io/anm4yEn

- [x] one download button
- [x] if no family design 1
- [x] if family found, design 2 with tabular rows

**Comment by rosibaj** [comment]
@hlminh2000 Functionality looks great here!  Counts appear to be adding up well.  There are some UI issues that need to be resolved: 

1) The Copy button should say COPY ID with an ICON and should be a more square box
![screen shot 2018-05-14 at 12 51 37 pm](https://user-images.githubusercontent.com/15824252/40011349-94cbf57a-5775-11e8-8442-f9dffaa25c28.png)

2. Add the check icon to the participant row.  it should always there. Also, the file size icon is wrong - it should be the three stacked disks database icon
![screen shot 2018-05-14 at 12 54 49 pm](https://user-images.githubusercontent.com/15824252/40011507-04ed1da2-5776-11e8-99ff-912f5902dd54.png)

3.  When it is participant only, the row should be white
![screen shot 2018-05-14 at 12 50 54 pm](https://user-images.githubusercontent.com/15824252/40011324-77c1c6ee-5775-11e8-919e-4b546c1e0fb1.png)

4. When it is participant + family
- participant row should be the selcted blue color always
- add a select all checkbox to the top row.  When clicked, all data types should be selected. 
- the family data type table should be alternating white/grey
![screen shot 2018-05-14 at 12 55 50 pm](https://user-images.githubusercontent.com/15824252/40011557-2fbbb6f6-5776-11e8-8356-972606af7c70.png)
- when a row is selected, it should check off & turn the selected blue color
![screen shot 2018-05-14 at 12 53 56 pm](https://user-images.githubusercontent.com/15824252/40011461-e2fd0cde-5775-11e8-808a-d73d33e4bfce.png)

**Comment by hlminh2000** [comment]
thanks for the review @rosibaj! Added this PR to address your points: https://github.com/kids-first/kf-portal-ui/pull/371

**Comment by rosibaj** [comment]
@hlminh2000 Looks much, much better!!  A couple small things still:
1) When the family manifest loads, there is a weird bump as it calculates whether or not to add family... Can we instead calculate before the modal loads and then load the correct size modal?

2) When you click Generate, there is a flash before it switches to copy.  Can you use the loader instead to prevent the weird flash?

3) Add a bit more space between Download button and Generate manifest button (like screenshot above)

**Comment by rosibaj** [comment]
@hlminh2000 yup that works great as a solution!

**Comment by hlminh2000** [comment]
@rosibaj all these points should be addressed in live beta portal now :)

**Comment by rosibaj** [comment]
Thanks @hlminh2000! Looks great!
