### ISSUE TITLE
Small bug fixes

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#356]
- [x] Reduce the default # of facet values showing to 5
- [x] Change the value "Missing" to "No Data".  Make sure that No Data always shows as the last facet
- [x] Reduce the pagination values below table to only show 5 pages
- [x] For internal review, the Cavatica button should be disabled.  1) Grey out the button.  2) Add this text above the button: 
> Link to Cavatica will not be available for internal review.  
- [x] Tags can be removed when in edit mode.  Make tags removable only when the Edit button has been clicked
- [x] Replace the list of "interests" with 
* Ewing Sarcoma
* DNA repair
* bone tumor
* tumor genomics
* structural birth defect
* cleft palette

- [x] When you add your API key to Gen3, when you click connect, nothing happens.  The API endpoint needs to be updated to `https://data.kidsfirstdrc.org/` 
- [x] on chrome vincents /dashboard page never loads (even in incognito).  These are the console errors
![image 1](https://user-images.githubusercontent.com/15824252/39828878-933776ec-538a-11e8-88f9-cd7f227d1587.png)
![image](https://user-images.githubusercontent.com/15824252/39828879-934698b6-538a-11e8-88b1-f9e6e2783d7b.png)

- [x] fix dropdown states on buttons.  If you click the clinical/biospecimen repot button, the dropdown appears.  if you do not click on the dropdown, it never closes.  If a user clicks the button, but clicks away, the dropdown should disappear. 

- [x] File size facet is having issues readjusting during query exploration 
![screen shot 2018-05-09 at 1 13 56 pm](https://user-images.githubusercontent.com/15824252/39828963-e5b1213e-538a-11e8-894e-ea0ec5ce7e80.png)
![screen shot 2018-05-09 at 1 25 26 pm](https://user-images.githubusercontent.com/15824252/39829440-759b364e-538c-11e8-950d-38d18ce750fe.png)

**Comment by jgnieuwhof** [comment]
@rosibaj - checked issues are addressed in https://github.com/kids-first/kf-portal-ui/pull/357

**Comment by jgnieuwhof** [comment]
fix for range agg not updating w/ sqon is here: https://github.com/overture-stack/arranger/pull/370

**Comment by rosibaj** [comment]
Checked em' all!  Looks great @jgnieuwhof
