### ISSUE TITLE
Update denial message on whitelising login

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#360]
The text when a non-approved ego user tryies to login to the portal is this: You have not been authorized to access the portal, please contact the administrators to gain access

Please switch the text to: 

> The Kids First DRP is currently in the internal review phase and is not accessible for beta testing.  Please contact a Kids First administrator if you have registered for internal review and are not able to log in.

- [x] the text "contact a Kids First administrator" should link to email support@kidsfirstdrc.org
- [x] the text should be styled in the same error manner as the KF portal errors 
![Screen Shot 2018-05-09 at 5.02.22 PM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/5e163da0-1099-45d9-9671-a324a97fe177)

While you are there:
-  [x] Update Researcher text to:
>  I'm a biomedical researcher or data scientist interested in data analysis, cross-disease research, and real-time collaboration. 
-  [x] Update Community text to:
>  I'm part of a patient family or foundation interested in learning more about current research and connecting with researchers in specific disease area.
-  [x] Update Health text to:
> I'm a physician-scientist interested in finding the latest research to target patients' needs based on genetic characteristics.

**Comment by jgnieuwhof** [comment]
addressed in https://github.com/kids-first/kf-portal-ui/pull/357

**Comment by rosibaj** [comment]
this looks amazing @jgnieuwhof !  Thanks for the prompt changes.
