### ISSUE TITLE
Fix No Data bucket counts

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#364]
- if the only bucket is 'No data" do not include it on afv when [x] only show fields with data is checked
- for example, in this screenshot the first field should not be showing if there is just No Data

![Screen Shot 2018-05-10 at 12.59.48 PM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/c7974452-c027-4834-a54e-963648d548de)

**Comment by jgnieuwhof** [comment]
@rosibaj - this should be ready for testing now

**Comment by rosibaj** [comment]
@jgnieuwhof if i unselect the checkbox for "show only etc..." the page crashes now.

**Comment by jgnieuwhof** [comment]
😬 yup will fix

**Comment by jgnieuwhof** [comment]
@rosibaj - it was a bork'd config in arranger admin. we should guard against it, but for now the issue is resolved w/out code change
