### ISSUE TITLE
Update Portal Footer

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#372]
- New Footer Design
https://projects.invisionapp.com/d/main/default/#/console/13157333/275376887/preview
- Links:
 --> Website: kidsfirstdrc.org
 --> Contact Us: kidsfirstdrc.org/contact/
 --> Policies: kidsfirstdrc.org/policies/

- Social Media links
--> https://www.facebook.com/kidsfirstDRC/?ref=bookmarks
--> https://twitter.com/kidsfirstDRC
-->https://github.com/kids-first

**Comment by jgnieuwhof** [comment]
@rosibaj - 2 questions/comments:
- we don't currently have mechanisms for the versioning, is it ok to leave that portion as is for now?
- are the social media links in scope for this ticket? if so could use the accounts they should point to

**Comment by rosibaj** [comment]
looks great! Thank you @jgnieuwhof
