### ISSUE TITLE
AFV Floats on Back navigation

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#373]
- open AFV
- press back button on browser
- page behind changes but AFV stayes

![Screen Shot 2018-05-14 at 9.09.56 PM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/0c879fec-1668-4106-9432-fcd5a37f9be4)

**Comment by rosibaj** [comment]
@hlminh2000 The last action before clicking back is not being registered properly 

1. If i go Dashboard --> file repo --> AFV, then click back it goes to dashboard
-- When you click back, it should land on file repo
2. If i go Dashboard --> file repo --> click a facet--> AFV, then click back it goes to file repo with no facets selected
 -- it should go back to file repo with facet selected
2. If i go Dashboard --> file repo --> click 2 facets--> AFV, then click back it goes to file repo with 1facets selected
 -- it should go back to file repo with both previously selected facets selected

**Comment by hlminh2000** [comment]
@rosibaj I think we can move these points mentioned to a different issue :) the problem regarding afv being visible in dashboard page is actually a problem with any modal (not specific to afv), and that has been resolved, so these points are touching on a different issue now.

**Comment by rosibaj** [comment]
#396
