### ISSUE TITLE
Action Panel Design Review

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#375]
-  [x] Please make the following css and copy changes:
![screen shot 2018-05-15 at 11 32 59 am](https://user-images.githubusercontent.com/18424138/40067465-32d1574c-5834-11e8-8be3-176c7340f380.png)

- [x] Implement Slide in/out
https://projects.invisionapp.com/share/MQFHWABDK9Y#/screens/297295040

**Comment by rosibaj** [comment]
@hlminh2000 LOVE the slide - it looks fantastic!  ! small thing - on the Clinical download button, when you click the text the button gets larger goes out of frame.  Instead, can we keep the button the exact same size, and just not show any overflow text that does not fit in the same space?

**Comment by hlminh2000** [comment]
button issue addressed by https://github.com/kids-first/kf-portal-ui/pull/445 (pending review)
