### ISSUE TITLE
Download Clinical Participant returns exactly 1000, 2000 rows

### ISSUE THREAD

**Issue by phuongmy** [kids-first/kf-portal-ui#376]
Test on the beta portal as of May 15.

1. Go to File Repo, you can see there are 2,186 participants
2. Click on "Download Clinical (Participants)"
> There are exactly 2,000 participant rows in the TSV file. There should be clinical data for 2,186 participant rows.

3. Add a filter to the query, for example "Study is Genetic Contribution to Ewing...", you can see there are 1,051 participants
4. Click on "Download Clinical (Participants)"
> There are exactly 1,000 participant rows in the TSV file. There should be clinical data for 1,051 participant rows.

Note: Unless there's no clinical data at all, when there's at least 1 participant with clinical data then all of the participants should be displayed in the TSV file (for the participants without clinical data it would display "--" in the clinical columns).

See screenshots below.

<img width="1434" alt="1-query_without_filter-2000_rows" src="https://user-images.githubusercontent.com/8812383/40068727-4a35bf24-5837-11e8-9db3-343fd84de761.png">
<img width="1440" alt="2-query_with_filter-1000_rows" src="https://user-images.githubusercontent.com/8812383/40068729-4a4ff736-5837-11e8-9c9a-eef7be1ae4a3.png">

**Comment by rosibaj** [comment]
Tested- row are returning the intended values.  thanks @jgnieuwhof!!

**Comment by jgnieuwhof** [comment]
@rosibaj - I don't think the fix is deployed yet!

**Comment by jgnieuwhof** [comment]
hmmm.... maybe all of the queries you tested happened to have values for `diagnoses.age_at_event_days` ?
