### ISSUE TITLE
Numbers should be separated by comma to indicate 1,000

### ISSUE THREAD

**Issue by phuongmy** [kids-first/kf-portal-ui#377]
Missing styling on the numbers, they should be separated by a comma like 1,000.
Observed on:
- summary section in File Repo and All Filters pop-up
- boolean facet
-  Upload Ids report
- Download Manifest pop-up

See screenshots below.

<img width="1438" alt="1-repo" src="https://user-images.githubusercontent.com/8812383/40069580-c404a250-5839-11e8-8d2a-b96cb5b32f55.png">
<img width="1132" alt="2-as" src="https://user-images.githubusercontent.com/8812383/40069581-c4224210-5839-11e8-93ad-79702c5023ef.png">
<img width="1133" alt="3-upload_ids" src="https://user-images.githubusercontent.com/8812383/40069583-c43fc1dc-5839-11e8-9aac-3d03fcf71a7a.png">
<img width="1020" alt="4-download_manifest" src="https://user-images.githubusercontent.com/8812383/40069584-c45ff25e-5839-11e8-9e43-597b04437db0.png">

**Comment by rosibaj** [comment]
Tested - looks great @jgnieuwhof!  Numbers are showing up beautifully separated now!
