### ISSUE TITLE
Using Upload Ids facet + another standard facet triggers an error message on the facet panel

### ISSUE THREAD

**Issue by phuongmy** [kids-first/kf-portal-ui#379]
1. Go to File Repository and select gender is Male
2. Click on Upload Ids then in the pop-up select File entity
3. Upload for example 2 file ids that were displayed in the previous screen, i.e. match to query gender is male: `GF_6VDP32HR` and `GF_7ECY5MVS`
4. Click on Upload
> In File Repo page, it shows an error message in the facet panel. Although the File table seems to filter correctly and is showing the matching files.

Note: same issue happen when you first upload file Ids then narrow down your search by selecting another standard filter.

See screenshot below.

<img width="1408" alt="screen shot 2018-05-15 at 12 47 48 pm" src="https://user-images.githubusercontent.com/8812383/40072189-f65eada2-5840-11e8-8010-b0e95c11c81d.png">

**Comment by jgnieuwhof** [comment]
@phuongmy - this is due to an underlying elasticsearch error: https://github.com/elastic/elasticsearch/issues/27782. I've asked in that ticket if we can expect the fix in ES 6.2, or if we'll need to wait for 6.3 & migrate.

@alex-wilmer - do you have any thoughts on this? should we implement a stopgap arranger level solution until arranger is up to 6.3?

**Comment by jgnieuwhof** [comment]
got a response on that PR, we've gotta wait for 6.3. So we should probably start thinking about a stopgap sol'n?

**Comment by hlminh2000** [comment]
Notes on a potential stopgap solution after discussing with @jgnieuwhof, if we decide to go that route: resolve the set into a list of ids first and place that back in the sqon before running the final ES query. If we get 6.3 early enough then this will not be necessary. 

We could also consider putting up a "feature coming" kind of message and disable set + query for now?

**Comment by phuongmy** [comment]
Oups sorry @jgnieuwhof , I did not notice I received a notification for that ticket. ^^'
When do you think 6.3 would be implemented?
It's a good idea to put up "feature coming" kinda message if let's say 6.3 comes in September?? :p
cc @hlminh2000 @rosibaj

**Comment by rosibaj** [comment]
@phuongmy We talked about this here - looks like 6.3 could potentially not be ready in time.  Instead, @jgnieuwhof will adjust the arranger SQON with a function.

**Comment by jgnieuwhof** [comment]
yup, plan is to manually resolve set lookups in arranger server rather than using elasticsearch's terms lookup, until 6.3 when we can once again use the elasticsearch terms functionality

**Comment by hlminh2000** [comment]
Stopgap solution is in place :)

![screen shot 2018-05-18 at 5 02 48 pm](https://user-images.githubusercontent.com/11821106/40257762-64968a28-5abd-11e8-9859-93c78673a1d3.png)

**Comment by rosibaj** [comment]
@hlminh2000 Yay!  There are no errors anymore!  But I have some bad news that it is still not filtering correctly. 

For example, if i put a filter of GF_6VDP32HR, you can see that there is facet data returned based on the the file.  
![screen shot 2018-05-22 at 10 22 50 am](https://user-images.githubusercontent.com/15824252/40368584-282b9872-5daa-11e8-9910-fef995b13807.png)

If I upload this same file as an upload id  & the filter is Saved Manifest, the the facets do not respond correctly - they have no data.  As this is essentially the same query, the facets should be responding the exact same way as just the filter on that file id. 
![screen shot 2018-05-22 at 10 23 06 am](https://user-images.githubusercontent.com/15824252/40368578-26c8c9a0-5daa-11e8-9fb6-b32f0a4b69f4.png)

**Comment by hlminh2000** [comment]
issue identified and addressed in https://github.com/overture-stack/arranger/pull/398 (pending review). Elasticsearch has delay of up to 1s until indexed data is available. 

The fix for the original issue requires resolution of the indexed sets immediately after it is indexed so there was a race condition. We're just making the set saving functionality wait until elasticsearch has made the indexed sets available before completing.

**Comment by hlminh2000** [comment]
@rosibaj this problem should be fixed. The race condition doesn't always happen so it's probably good to test a few times. I've done myself but good to get some extra validation :)
