### ISSUE TITLE
Can't scroll to click on buttons (during registration or upload Ids)

### ISSUE THREAD

**Issue by phuongmy** [kids-first/kf-portal-ui#380]
I'm on Chrome 100% zoom level on Mac laptop.

1. In File Repository, click on "Upload Ids"
2. Select File entity type and enter 10 actual file Ids, e.g. 
GF_00621P88
GF_00AJKP4Y
GF_00ER61HS
GF_00VMMB4N
GF_00YES27B
GF_01018JDE
GF_012ABNRB
GF_016PFEFX
GF_0188Y8C2
GF_01948QG1

> The summary report on matching files is taking up the whole space and you cannot see the "Upload" or "Cancel" buttons at the bottom anymore. You cannot see the "x" button at the top either. You cannot scroll up or down to the buttons. You can't click outside of the pop-up to close it.
At this point you are blocked and the only thing you can do is to zoom out on the browser to be able to click on the actionable buttons. 

Is it part of responsiveness ticket? We should make sure that the user is at least able to scroll to the buttons.

See screenshot of my laptop below.
<img width="1437" alt="responsiveness" src="https://user-images.githubusercontent.com/8812383/40077595-21c8b2ee-5850-11e8-98f8-2151fd9650ee.png">

**Comment by rosibaj** [comment]
@hlminh2000 i see for the upload modal you fixed the height so the buttons were available, but this is an issue on registration as well:  
![screen shot 2018-05-18 at 4 05 37 pm](https://user-images.githubusercontent.com/15824252/40255496-572f1402-5ab5-11e8-8921-fd8159b19204.png)

For example here, I cannot scroll to click next to continue registration.  Can we enable page scrolling in situations like this as a stopgap before we get Kim to do complete responsive designs?

**Comment by hlminh2000** [comment]
yes, definitely! I missed the comment made by @phuongmy regarding this page. I think making the content below the progress bar scrollable would be a fair solution for now :) Will tackle this!

**Comment by hlminh2000** [comment]
@rosibaj the signup screen should be updated now

**Comment by rosibaj** [comment]
Tested - scroll on signup works now. Thanks @hlminh2000!
