### ISSUE TITLE
Update Cavatica links - should point to staging environment

### ISSUE THREAD

**Issue by phuongmy** [kids-first/kf-portal-ui#385]
There is now a staging environment for Cavatica.

Please update the links on the data portal to point to that environment.

Links are:
1- Main page: https://kids-first-staging-vayu.sbgenomics.com
2- Registration page: https://accounts-kids-first-staging-vayu.sbgenomics.com/auth/register
3- Developer dashboard - auth token: https://kids-first-staging-vayu.sbgenomics.com/developer#token

Also when the user copies his token and clicks on Connect, it should connect to the staging environment.
Discussion with @joneubank:  `we need to update the environment variable for our portal to point to the correct place`

See attached screenshots
<img width="1206" alt="screen shot 2018-05-16 at 2 29 28 pm" src="https://user-images.githubusercontent.com/8812383/40136436-e9c9d2e4-5915-11e8-92a3-d096d10505c9.png">
<img width="1159" alt="screen shot 2018-05-16 at 12 05 46 pm" src="https://user-images.githubusercontent.com/8812383/40136445-ee3e4b48-5915-11e8-819e-7fa7870c0900.png">

**Comment by phuongmy** [comment]
This will address partly https://github.com/kids-first/user-feedback/issues/9.
We are pointing to staging environment until Cavatica Prod is available.

**Comment by jgnieuwhof** [comment]
@rosibaj - currently our Cavatica urls are as follows:
API - https://g9xs4f0xy8.execute-api.us-east-1.amazonaws.com/prod/cavatica
WEB - https://kids-first-vayu.sbgenomics.com

Do we need an updated API url in addition to the web ones specified in the ticket? Or does the API stay the same?

**Comment by rosibaj** [comment]
@jgnieuwhof i think so -   Can you ask @joneubank to confirm the API url if you have any issues?  He was the first to set it up.

**Comment by rosibaj** [comment]
@joneubank sorry for the delay, but just got confirmation that that should be the right one
