### ISSUE TITLE
Do not display shared queries in "Dashboard - My saved queries"

### ISSUE THREAD

**Issue by phuongmy** [kids-first/kf-portal-ui#393]
Currently when a user shares a query, it does show that query in “My saved queries” in the dashboard. However that section should only show queries "saved" by the user.

https://github.com/kids-first/kf-portal-riff/issues/1 will provide backend support for a flag that can distinguish shared vs saved queries. Make sure on the UI "My saved queries" section in the dashboard only shows saved queries.

Example of screenshot below.
1. Go to File Repo and select Tissue Type is Saliva
2. Click on Share - copy short URL
3. You can reproduce  step 2 x 4 additional times
> The query is displayed in My Saved queries 5 times.
<img width="1042" alt="screen shot 2018-05-18 at 7 33 03 am" src="https://user-images.githubusercontent.com/8812383/40242578-fdd7e24a-5a8b-11e8-9137-9c0328ef9281.png">

**Comment by hlminh2000** [comment]
@joneubank might be looking at https://github.com/kids-first/kf-portal-riff/issues/1 soon so we will address this issue following that.

**Comment by rosibaj** [comment]
thanks @hlminh2000!! Tested and shared queries are no longer being saved in the saved queries section.
