### ISSUE TITLE
Add KF Beta Tags on UI

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#394]
- [ ] Add UI warning on landing page
Login: https://invis.io/MQFHWABDK9Y#/297864190_01-KF-Login-Beta-Message
- [x] Warning on wizard
Join: https://invis.io/MQFHWABDK9Y#/297864191_02-KF-Join-Beta-Message=
- [x] Tag on logo 
Portal logo - beta tag: https://invis.io/MQFHWABDK9Y#/297864193_03-KidsFirst-Portal-Beta-Tag

**Comment by jgnieuwhof** [comment]
addressed item 3 in https://github.com/kids-first/kf-portal-ui/pull/478

**Comment by jgnieuwhof** [comment]
addressed item 2 in https://github.com/kids-first/kf-portal-ui/pull/479
