### ISSUE TITLE
firefox - column checkboxes appear disabled

### ISSUE THREAD

**Issue by andricDu** [kids-first/kf-portal-ui#410]
They do work when you click on them, just their appearance is confusing. 
![image](https://user-images.githubusercontent.com/6350043/40495314-ec71c0bc-5f44-11e8-8974-56897dd3bb2f.png)

**Comment by jgnieuwhof** [comment]
@andricDu - I've been unable to reproduce this on FF mac, and FF win10 via browserstack. Might this be a ubuntu-specific issue?

**Comment by andricDu** [comment]
It is still present on my Linux machine so yea it might be a ubuntu issue.
