### ISSUE TITLE
SVGs are not loading correctly in Edge

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#429]
**Sender**: rosi.bajari@gmail.com
**Comment**: SVGs are not loading correctly in Edge

<a href='https://usersnappublic.s3.amazonaws.com/2018-05-28/16-36/a7e1ed6c-76bf-4bf9-8129-7499e17d6288.png'>![usersnap- - Icon issue in edge](https://usersnappublic.s3.amazonaws.com/2018-05-28/16-36/1ff67cf4-d555-493b-8db1-7d34b0534723.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-05-28/16-36/a7e1ed6c-76bf-4bf9-8129-7499e17d6288.png'>Download original image</a>

**Browser**: Edge 16 (Windows 10)
**Referer**: [https://beta.portal.kids-first.io/dashboard](https://beta.portal.kids-first.io/dashboard)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 904
**Additional Information**:
```
{
    "portalVersion": "0.0.0.0", 
    "dataVersion": "unreleased", 
    "gaClientId": "1689962660.1527518096", 
    "sqonHistory": [], 
    "arrangerProjectId": "may16", 
    "state": {
        "percentageFilled": 0.9375, 
        "loggedInUserToken_exist": true, 
        "loggedInUser": {
            "googleScholarId": "", 
            "_id": "5aa6809141303f0025a46594", 
            "acceptedTerms": true, 
            "roles": [
                "community"
            ], 
            "egoId": "12048"
        }
    }
}
```

**Comment by jgnieuwhof** [comment]
@rosibaj - I'm not entirely sure what the circles correspond to in the image, so I took a quick click-through the app on edge but didn't notice anything w.r.t. svg's. Would you be able to provide a little more info on which svg's are affected?

**Comment by rosibaj** [comment]
Thanks, @jgnieuwhof. It looks like some of the other changes might have resolved this.  I will close this ticket.
