### ISSUE TITLE
Too many scrollbars

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#431]
**Sender**: rosi.bajari@gmail.com
**Comment**: Remove some of the scrollbars

<a href='https://usersnappublic.s3.amazonaws.com/2018-05-29/00-16/7198f2ed-af13-4362-957a-3987ec2c3e42.png'>![usersnap- - so, so, so many scrollbars](https://usersnappublic.s3.amazonaws.com/2018-05-29/00-16/d8351584-9b8b-47a5-ba5e-c3f52a43ca43.jpg)
**Browser**: Firefox 60 (Windows 10)
**Referer**: [https://beta.portal.kids-first.io/search/file](https://beta.portal.kids-first.io/search/file)
**Screen size**: 1280 x 720 **Browser size**: 1280 x 607
**Additional Information**:
```
{
    "portalVersion": "0.0.0.0", 
    "dataVersion": "unreleased", 
    "gaClientId": "519118593.1527517664", 
    "sqonHistory": [], 
    "arrangerProjectId": "may16", 
    "state": {
        "percentageFilled": 1, 
        "loggedInUserToken_exist": true, 
        "loggedInUser": {
            "googleScholarId": "hello", 
            "_id": "5aa6809141303f0025a46594", 
            "acceptedTerms": true, 
            "roles": [
                "research"
            ], 
            "egoId": "12048"
        }
    }
}
```

**Comment by hlminh2000** [comment]
but it gives users so much freedom to scroll! more flexibility! :P
