### ISSUE TITLE
Fix Download File

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#434]
When i try and download a file, this 400 error is occurring:

![Screen Shot 2018-05-29 at 10.40.29 AM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/6effaefa-725f-4860-9926-56007f2b8ae0)

```
{
  "errors": [
    {
      "message": "Cannot query field \"uuid\" on type \"fileNode\". Did you mean \"id\"?",
      "locations": [
        {
          "line": 1,
          "column": 79
        }
      ]
    }
  ]
}
```

I have access to this dataset so it should be downloadable - it should be querying on File ID.

**Comment by hlminh2000** [comment]
Let's move this back to backlog as we're blocked by a data model update here it seems
