### ISSUE TITLE
Update Terms and conditions in the consent form displayed during registration

### ISSUE THREAD

**Issue by Fgerthoffert** [kids-first/kf-portal-ui#480]
In https://github.com/kids-first/kf-portal-ui/blob/master/src/components/forms/ConsentForm.js#L63 update terms and conditions to match the website: https://kidsfirstdrc.org/policies/ (only Terms & Conditions)

**Comment by allisonheath** [comment]
And since it's just the T&C on the portal if you make the last part:

> If you have any questions about these terms, conditions or the practices of this site or any of the other Kids First DRC Services, please contact us at support@kidsfirstdrc.org. For a full list of Kids first DRC policies see https://kidsfirstdrc.org/policies/.
