### ISSUE TITLE
Select all files - push to cavatica

### ISSUE THREAD

**Issue by allisonheath** [kids-first/kf-portal-ui#483]
Right now it's a bit unintuitive that if you have *no* files selected that's how you push *all* the files to a Cavatica project. But if you select the checkbox in the title row, it just select the ones displayed on the page, so you'll only push 20 of the files. Took me a few tries to figure out the behavior, not sure how to best address - but maybe if it was consistent with cavatica project where they have the little drop down to select all that would help?

![screen shot 2018-06-16 at 10 56 24 pm](https://user-images.githubusercontent.com/2213854/41504296-8d993dbe-71b8-11e8-9b00-8ca5c1d55d72.png)

**Comment by rosibaj** [comment]
@kcullion maybe we can talk about this Friday - @allisonheath noticed the same cavatica thing we were talking about

**Comment by rosibaj** [comment]
- the select all checkbox should Select All files
- state should be maintained across pages (like GDC cart)

**Comment by bdolly** [comment]
I noticed this and thought if might be helpful if we had a filter for "Studies I can Download" that selected all current studies the user has access to. Say there are 10 studies total but I only have access to 4, there's currently no way to tell this in the File Repo without have to go back to your Gen3 connection details and then back to the Repo. Gen3 currently only gives you Study IDs and not Study short names, so to make the connection between ID and short name you have to select the Study ID column and make the cognitive connection between them.

**Comment by rosibaj** [comment]
@bdolly we have 2 changes planned as well:  1) on the user dashboard, to show the short name with id and then be able to link right to the repo from there.  2) on the last column, show the users access to the files that they see in the table.  I think these should start to help

**Comment by kcullion** [comment]
@rosibaj I think #1 you mean on the user profile - setting section.

But maybe we add the "Authorized Studies" button on the dashboard too - where the GEN3 connection shows up in the grey box
![screen shot 2018-07-05 at 12 31 27 pm](https://user-images.githubusercontent.com/18424138/42335747-5db714f4-804f-11e8-876e-ee840d6eaa0c.png)

**Comment by abgeorge7** [comment]
Hi, is there a timeline for this feature? We are hoping to be able to select all rows in a table, instead of all the rows visible on a page of the table. thanks!

**Comment by rosibaj** [comment]
@abgeorge7 Hi Abby! We are just looking into design now and don't have an exact date.  If you are wanting this soon, this is an open-source project, so feel free to put a pull request up to the Arranger repo (https://github.com/overture-stack/arranger)  yourself and one of our team members (@hlminh2000, @lepsalex, @andricDu) will help with review.

**Comment by kcullion** [comment]
Closed this ticket as it will now be addressed in: https://github.com/kids-first/kf-portal-ui/issues/1043
