### ISSUE TITLE
Signup form - remove scrollbar from form

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#484]
The sign-up form has a scrollbar that appears when the screen is small, and sometime the form appears hidden on the page because it's within a scrolling area.  Please remove this height from the form and allow the user see the entire form, i.e. to scroll the whole page.

![screen shot 2018-06-18 at 9 24 02 am](https://user-images.githubusercontent.com/18424138/41539002-a8749246-72da-11e8-98c7-8e5e39922991.png)

![screen shot 2018-06-18 at 9 25 07 am](https://user-images.githubusercontent.com/18424138/41539005-abbeb788-72da-11e8-861e-b53cee439acd.png)

**Comment by kcullion** [comment]
Note @rosibaj: this was also reported in: https://usersnap.com/a/#/your-team-oy1k/p/portal-testing-7a044ebb/71

**Comment by rosibaj** [comment]
@hlminh2000 i tested this on production, but it still looks like it is functioning with the content scroll

**Comment by rosibaj** [comment]
@hlminh2000 when you revisit this, can you look at the for buttons as well? the cancel/back routes appear to not be working now.
