### ISSUE TITLE
User menu dropdown - Style fix 

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#487]
For the user menu please:

- [x] Left justify the menu items
- [x] Move the menu over approximately right:25px (to put some space between the menu and the browser edge)
- [x] if you click somewhere else the menu should disappear (like the Share and Save query dropdown behaviour)

So should look more like: 
![screen shot 2018-06-19 at 10 34 03 am](https://user-images.githubusercontent.com/18424138/41604419-34edc8dc-73ad-11e8-8c1d-90fdd008954c.png)

**Comment by ciaranschutte** [comment]
https://github.com/paypal/downshift/issues/490#issuecomment-400745565

**Comment by hlminh2000** [comment]
@rosibaj we made a mistake of having this merged this into `next` without going through your QA. Pretty small PR and I've tested any it all looks good so let's move this to prod to clear up the pipe if you could help take a quick glance on QA. We'll make sure things going into `next` are clear cleared for QA in feature branches moving forward ;) 
QA is still useful for staging back-end changes too so it's worth keeping next up to date with master.

**Comment by rosibaj** [comment]
@hlminh2000 @ciaranschutte 
- When I click on the page, the user dropdown stays open on the page iIam navigated to and does not close until I click away. 
- After clicking on an option, the page should be navigated to and the dropdown should close.

**Comment by hlminh2000** [comment]
@ciaranschutte are we able to patch this up quickly? :)

**Comment by ciaranschutte** [comment]
@hlminh2000 looking into this now

**Comment by hlminh2000** [comment]
Let's move this forward and have the patch in a new PR :)
