### ISSUE TITLE
Facet Counts not correct in some cases

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#488]
If you select this facet, there is one diagnosis listed, Schwanoma, with count (1) and Other with count (13).  
https://portal.kidsfirstdrc.org/search/file?sqon=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22participants.diagnoses.mondo_id_diagnosis%22%2C%22value%22%3A%5B%22MONDO%3A0021637%22%5D%7D%7D%5D%7D . 
![Screen Shot 2018-06-19 at 10.01.06 AM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/785dfd1d-fe47-4c9e-adfe-96cbb4e5b783)

If you click either of these facet values, no files appear.  It looks like the facet count is incorrect and should not be counting that diagnosis. 
![Screen Shot 2018-06-19 at 10.01.15 AM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/a90f3733-f675-49f3-9522-1e35132376c9)

**Comment by hlminh2000** [comment]
@rosibaj this is fixed now on both the beta and the prod portal

**Comment by rosibaj** [comment]
thanks @hlminh2000 will test now!

**Comment by rosibaj** [comment]
Thanks for the dfix @hlminh2000!!  Tested and it looks like it is correct now - Can be verified with query above and https://portal.kidsfirstdrc.org/search/file?sqon=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22kf_id%22%2C%22value%22%3A%5B%22GF_MF94095R%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22participants.diagnoses.mondo_id_diagnosis%22%2C%22value%22%3A%5B%22MONDO%3A0002070%22%5D%7D%7D%5D%7D
