### ISSUE TITLE
Adjust Gen3 login (front-end)

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#494]
Implement new GEN3 connection mockups:
- [x] 1. When the user clicks on "connect" for GEN3 in the settings section, the 
(https://invis.io/MQFHWABDK9Y#/278537349_26-KF-Researcher-Settings-Connected)

They get a modal with the NIH login screen within it:
https://invis.io/MQFHWABDK9Y#/304086490_25a-KF-Researcher-ConnectGEN3
(Zeplin: https://zpl.io/a74Ep4M)

- [ ] 2. When they login, they go back to the settings page with "Connected" information within the table and the ability to remove the connection.  Also they should receive a success alert (#232 design) that says `Controlled dataset access sucessfully connected through Gen3`:

https://invis.io/MQFHWABDK9Y#/304086714_26a-KF-Researcher-Settings-GEN3connected
(Zeplin: https://zpl.io/a8KNDwE)

3. They get a new button inside the table to "view authorized studies" within the system. This opens the following modal:
https://invis.io/MQFHWABDK9Y#/304086900_26c-KF-Researcher-Settings-Authorized-Studies-Modal

Each study displays the study name, id and a link to the dataset within the file repository.
(Zeplin: https://zpl.io/V0y0zgo)

**Comment by rosibaj** [comment]
@hlminh2000 There looks to be a small bug.  If you click connect, then close the NIH page, the portal connect continually spins.  Can you make it so that:
- it redirects the whole page
- This redirect returns to the profile page
![screen shot 2018-07-16 at 12 53 53 pm](https://user-images.githubusercontent.com/15824252/42772100-5c74f54c-88f7-11e8-927a-e6bee1651a25.png)


https://github.com/kids-first/user-feedback/issues/43

**Comment by rosibaj** [comment]
@hlminh2000 I have identified a different bug during testing:

Sometimes the connection to Gen3 disappears 😱 .  It appears to happen after you have been in the portal for an amount of time (Allison verified that it happened to her today as well)

**Comment by rosibaj** [comment]
@hlminh2000 One more thing - The View Studies modal appears not to be appearing as well

**Comment by kcullion** [comment]
@rosibaj, @hlminh2000 I noticed on the portal.kidsfirstdrc.org settings page that if I click the "Connect" button for GEN3 and it directs me to the new page to log in to NIH. But if I change my mind and close that NIH window and go back to the settings page, I just get a spinner where the connect button was (I have to know to refresh the page).

![screen shot 2018-07-23 at 3 04 10 pm](https://user-images.githubusercontent.com/18424138/43097469-2b5e76f2-8e8a-11e8-8ecc-b2aeaf534c17.png)

**Comment by rosibaj** [comment]
Adjust ticket to #568 #569
