### ISSUE TITLE
User Settings + Profile - UI improvements

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#495]
Please make the following improvements to the USER SETTINGS section:

- [x] Hide the left subnav until we have more sections to display
- [x] Re-style "Connected to Facebook" button so it looks less like an actionable button and more like the "connected" style (see mock) - also the cursor changes to a "pointer" - this also suggests that it's clickable.
- [x] Revise the copy for GEN3 and Cavatica in the table (copy can be found in zeplin: https://zpl.io/bAA0jGo):
- [x] Fix the teal buttons in the table so they are closer to the design (larger) and have the external icon in them.

![24 kf-researcher-settings-with-updates](https://user-images.githubusercontent.com/18424138/43097169-30670ba6-8e89-11e8-8937-1ef90a898ee5.jpg)

Please make the following improvements to the USER PROFILE section:
- [x] When the user has filled out a section of their profile, the instructions should disappear from their non-edit view

![screen shot 2018-07-09 at 3 23 37 pm](https://user-images.githubusercontent.com/18424138/42471551-15b13c08-838c-11e8-8915-e81ca73bf828.png)

- [x] Add the cancel button to the top of the bio/story section to keep it consistent with the other edit box

![screen shot 2018-07-09 at 3 25 19 pm](https://user-images.githubusercontent.com/18424138/42471616-64e0a89a-838c-11e8-8725-6e4fba879374.png)

**Comment by ciaranschutte** [comment]
https://github.com/kids-first/kf-portal-ui/pull/587
(Still figuring out how to properly link this)
@rosibaj  Merged into 'next' branch

**Comment by rosibaj** [comment]
@ciaranschutte Looks much better!  Just a couple comments:

1. Can you use the same google G icon that we have on login for consistency

 (with the 4 colors)
![screen shot 2018-08-01 at 10 54 26 am](https://user-images.githubusercontent.com/15824252/43529446-4e6bb254-9579-11e8-8d31-064c4230ed0f.png)

2. The teal connect buttons look a little funny when not connected.  They should have a maximum width: 160px.



![screen shot 2018-08-01 at 11 06 58 am](https://user-images.githubusercontent.com/15824252/43530218-06b28378-957b-11e8-8b31-197aecc3dece.png)

**Comment by kcullion** [comment]
@ciaranschutte I have a couple more requests as outlined in the following screenshot
(also let me know if you need any svg icons or other assets)

![screen shot 2018-08-02 at 10 02 41 am](https://user-images.githubusercontent.com/18424138/43588840-5e24515c-963b-11e8-9da7-97559fd73915.png)

**Comment by ciaranschutte** [comment]
@kcullion Do we have a color Google icon like the one on the login screen?
There isn't a version in the prebuilt icon packs we're using.

**Comment by ciaranschutte** [comment]
@rosibaj fixes deploying to QA
