### ISSUE TITLE
Refactor File Repository UI with new table changes

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#511]
- [x] Move the "Copy Files to Cavatica" button to the top of the actions list, and re-style it so it's purple (stands out more)
- [x] Remove Access column 
- [x] Change final download column - For this column, the users permission to download the file is indicated by the icons. 
> 1.  If the user HAS permission to download the file, show the download icon. 
> 2. If the user clicks the download button, the file is downloaded
> 3. If the user DOES NOT have permission to download the file, show lock icon. When the user mouses over the icon, a tooltip displays with the text `You do not have access to download this file`

Zeplin mockup: https://zpl.io/VQY74Kx

**Comment by hlminh2000** [comment]
The PRs attached to this only covers stuff from the code. Removing the Access column will need to be done through the admin UI so I will do that separately.

**Comment by rosibaj** [comment]
@hlminh2000 Can you make the lock icon the correct purple color (same as the download icon)?  Right now it is grey

**Comment by hlminh2000** [comment]
updated! thanks for the review :)

**Comment by rosibaj** [comment]
@hlminh2000 This looks good now!  I will just review after deploy before closing.

**Comment by rosibaj** [comment]
@hlminh2000 @kcullion and I noticed something weird. 

1) When you select a file via the checkmark, ALL of the rows reload and the permission is recalculated.  Why is this reloading at this point

2) It looks like the spinner is larger than the lock/download icons, so the table rows get slightly bigger then get smaller again in a "bump" motion when you take actions.  Can we make these the same size so it does not shift like that?

**Comment by hlminh2000** [comment]
@rosibaj great catch!!! addressed both issues in this PR: #610

**Comment by hlminh2000** [comment]
access column is taken out in the latest batch of metadata. This can be closed now

**Comment by rosibaj** [comment]
looks great! thanks @hlminh2000
