### ISSUE TITLE
Footer should not be fixed at bottom of page

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#512]
The footer is taking up too much space on the portal. It should not be fixed at the bottom of each page, but should be at the bottom of the scroll. 

Example: https://dcc.icgc.org/search

**Comment by rosibaj** [comment]
@hlminh2000 it looks like this is having some issues still.  If the bio on the settings page is made long then the footer gets locked in the middle of the page:

![screen shot 2018-08-01 at 2 59 57 pm](https://user-images.githubusercontent.com/15824252/43542646-9581db42-959b-11e8-82a8-2dc265779f53.png)

**Comment by rosibaj** [comment]
@hlminh2000 there is also a spacing issue on the #settings page.  You should be able to see the bottom of the table. 

![screen shot 2018-08-01 at 3 01 17 pm](https://user-images.githubusercontent.com/15824252/43542717-c99920b6-959b-11e8-988c-5a7e4ed7af9f.png)

**Comment by ciaranschutte** [comment]
@hlminh2000 @rosibaj I'll investigate these ^

**Comment by rosibaj** [comment]
@ciaranschutte @hlminh2000 Footer looks great now after testing!

**Comment by hlminh2000** [comment]
merged to prod, this can probably be closed now
