### ISSUE TITLE
Cavatica: Add billing group option when creating a new project

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#517]
When a user has more than one billing group in their Cavatica account, add the option for them to select which billing group to associate when they create a new Cavatica project on the portal.

Design Proposal:

1. Add a column in the table for the billing group:
ZEPLIN: https://zpl.io/2jlqMvx

2. When the user clicks "create a project" button, the form is to have an extra dropdown field for "Select billing group". It is populated with their billing groups from Cavatica (if they only have one billing group, do not display the dropdown).
ZEPLIN: https://zpl.io/2jlqMvx

3. When the request is submitted, the project is created with:
     - Project Name
     - Selected billing group

4. When the user saves their new project + billing group, it is added to the top of the table, and is auto-selected:
ZEPLIN: https://zpl.io/VKN7ykq

**API documentation:** 
Billing: 
http://docs.cavatica.org/v1.0/docs/billing

**Comment by allisonheath** [comment]
Just bumping as this has come up again now that we have several more user with pilot funds in a separate billing group from their default personal one.

**Comment by rosibaj** [comment]
@kcullion Yup, we should still implement for consistency! Ive assigned Minh and Paule
