### ISSUE TITLE
Update Cavatica Error Reporting Methods

### ISSUE THREAD

**Issue by bdolly** [kids-first/kf-portal-ui#528]
### Error 1: User has not connected their ERA Account to Cavatica

**Steps to Reproduce**
1. Create new Cavatica account using just email/password at https://pgc-accounts.sbgenomics.com/auth/login 
2. Successfully Connect Cavatica to portal (Dashboard > Settings > Cavatica) using Auth Token
3. Select Files in File Repo and copy to Cavatica 
4. User will get the message that files copy "successfully" 
5. If you follow success modal to project in Cavatica,  **No files actually copied to project in Cavatica**

This is problematic because it does not inform the user of the need to connect Cavatica to Kids First via their eRA Commons account and allows them to complete to the Copy to Cavatica workflow without any actual results. 

Cavaticas API should respind with a `200` success message, the contents of which include a per/file update.  If a user has not connected their ERA, or has tried to push a file they do not have access to they will see an error like this: 

```
       "5b97ade2e4b0934a467dbe74":{  
          "status":"FAILED",
          "error":{  
             "status":403,
             "code":5001,
             "message":"Insufficient privileges to access the requested file.",
             "more_info":"http://docs.cavatica.org/docs/api-status-codes/#5001"
          }
       },
```

**EXPECTED BEHAVIOUR:**
- [ ]  update copy in the "How to Connect to Cavatica" modal to inform users of the need to connect their Cavatica account via eRA Commons / NIH login
- [ ]  update Copy to Cavatica success modal to inform the user of how many files have actually successfully been copied to their Cavatica project by parsing the `200` response

### Error 2: There is a mismatch in Cavatica File IDs between the portal and Cavatica.

Both the portal and Cavatica have to index KF files for user access; if the portal and Cavatica are out of sync, then the file_ids that are sent to Cavatica will not result in any files being added.  The user should be made aware of the  

We need to parse the response to Cavatica when this scenario happens.

**Comment by rosibaj** [comment]
@bdolly there should be a warning if you try and push filed to cavatica and have not yet connected your Gen3.  Did you try this scenario and that did not work?
