### ISSUE TITLE
Reports Download Stalling for `Clinical (Participant)` and `Clinical (Participant and Family)`

### ISSUE THREAD

**Issue by bdolly** [kids-first/kf-portal-ui#533]
Noticed that reports download in the File Repo just spins for clinical data. The call `https://arranger.kids-first.io/june_13/download` fails after about a minute with the status of `
net::ERR_SPDY_PROTOCOL_ERROR` and no file is downloaded

**Comment by hlminh2000** [comment]
This is a combination of a few problems, but the biggest issue of the download not starting is addressed here: https://github.com/kids-first/kf-arranger/pull/63
The spinner will keep spinning, but that'll take some big change in the back end to fix... or we'll just apply a timeout instead :P We can keep that in a separate issue.

**Comment by rosibaj** [comment]
@hlminh2000 created a ticket for the spinnner issue https://github.com/kids-first/kf-portal-ui/issues/575

Closing as this is resolved
