### ISSUE TITLE
Update Terms & Conditions

### ISSUE THREAD

**Issue by baileyckelly** [kids-first/kf-portal-ui#538]
https://github.com/kids-first/kf-portal-ui/blob/375dfc30e48c05d5206e3c898d131b915c709c38/src/components/forms/ConsentForm.js#L58-L164

Hi - we have a new approved Terms & Conditions. I believe it's just the closing paragraph that changed.

Terms and Conditions
Last Updated 7/13/18

As a user of the Services you agree that you are 13 years of age or older and furthermore agree to the Terms and Conditions of Services defined herein and where applicable the terms defined by the NIH Genomic Data User Code of Conduct. These terms include, but are not limited to: 

1.	You will request controlled-access datasets solely in connection with the research project described in an approved Data Access Request for each dataset;
2.	You will not distribute controlled-access datasets to any entity or individual beyond those specified in an approved Data Access Request;
3.	You will adhere to computer security practices in compliance with NIH Security Best Practices for Controlled-Access Data such that only authorized individuals possess access to data files;
4.	You acknowledge Intellectual Property Policies should they exist as specified in a dataset’s associated Data Use Certification; and,
5.	You will report any inadvertent data release in accordance with the terms in the Data Use Certification, breach of data security, or other data management incidents contrary to the terms of data access.

DRC terms and conditions may be changed at any time via a public posting of revisions to the Services. As a user, you agree to review the Terms & Conditions and Privacy Policies each time you use the Services so that you are aware of any modifications made to these policies. By accessing or using the Services, you agree with and to be bound by all of the terms and conditions and policies as posted on the Services at the time of your access or use, including the Privacy Policies then in effect.

For documents and/or data available from the Services, the DRC does not warrant or assume any legal liability or responsibility for the accuracy, completeness, or usefulness of any information, apparatus, product, or process. No specific medical advice is provided by any Services, and the Kids First urges users to of Services to consult with a qualified physician for diagnosis and for answers to personal questions.

If you have any questions about these terms, conditions or the practices of this site or any of the other Services, please contact us at support@kidsfirstdrc.org. The full list of Kids first DRC policies are located at https://kidsfirstdrc.org/policies/.

**Comment by baileyckelly** [comment]
I think the opening paragraph has some changes too, now on second glance. Probably best to just replace the whole thing with the new content. :)

**Comment by rosibaj** [comment]
@hlminh2000 Can you update the date above this to `7/13/18`
