### ISSUE TITLE
Download manifest (Participant and Family)

### ISSUE THREAD

**Issue by cy** [kids-first/kf-portal-ui#54]

**Comment by phuongmy** [comment]
Specifications: https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/290422965/Download+Files+Manifests#DownloadFiles/Manifests-3.DownloadParticipantandFamilyManifest

The user should be able to download manifest for all the files resulting from the query (or selected by the user in file table) + files of family members as selected in the pop-up by the user.

Reminder: a manifest is 2 files:
- 1 that contains the list of files uuid
- 1 that describes more metadata about those files
