### ISSUE TITLE
Download clinical data (Participant)

### ISSUE THREAD

**Issue by cy** [kids-first/kf-portal-ui#55]

**Comment by phuongmy** [comment]
Specifications: https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/383156225/Download+Clinical+and+Biospecimen+data

Design: https://projects.invisionapp.com/d/main#/console/13157333/280439821/preview

There are 2 options for downloading clinical data:
- for the participants
- for the family members of the participants
