### ISSUE TITLE
Design Review: New Profile Fields

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#556]
**Basic info form**

- [x] No need for First name, Last name and Organization textfields to have the label repeated within the field

![screen shot 2018-07-19 at 9 29 29 am](https://user-images.githubusercontent.com/18424138/42948184-f57b7530-8b3c-11e8-8139-b9ee1a7f5c77.png)

- [x] Put a colon (:) after Institutional Email Address and City
- [x] Search location - add a search icon and an example (address)
![screen shot 2018-07-19 at 10 19 45 am](https://user-images.githubusercontent.com/18424138/42948351-497b3bfc-8b3d-11e8-9572-bba424901ac7.png)

- [x]  The example phone number should have 3 more digits. EG +1-555-555-5555
- [x] For the Title fields - there is no way of going back to Select none - there should be another option that resets the field to blank if the user changes their mind
- [x] When the user saves their info, it should display on the profile in the following areas
![profile-fields](https://user-images.githubusercontent.com/18424138/42948659-f9de9688-8b3d-11e8-85bd-d888d782c24f.jpg)

- [x] Change “Organization” to “Institution/Organization”

**Research Interests:**
- [x] Change “Kids First Disease Area” to “Kids First Disease Areas”
- [x] For consistency, change “Select An Option” to “Select an option” (not capitalized)
- [x] For the disease areas: PNOC/CBTTC - should probably just be "Pediatric Brain Tumors"
- [x]  For the Search for interests search box, please use the same magnifying glass as the one used in the file repository search fields (grey)
![screen shot 2018-07-19 at 10 29 18 am](https://user-images.githubusercontent.com/18424138/42949464-d044338a-8b3f-11e8-9b01-e385d67b7eac.png)

**Find me on**
- [x] Please make the input fields span the entire box (see mockup)
- [x] To be consistent with the other forms, add colons to each field label
- [x] Google Scholar Id URL should be “Google Scholar URL”
- [x] when the user edits and they have their url within the textfield, please implement the "x" icon in the textfield for them to quickly clear the textfield if they want to. Like:
![screen shot 2018-07-24 at 11 50 20 am](https://user-images.githubusercontent.com/18424138/43150439-f00bc204-8f37-11e8-85ed-3837af35b4c1.png)

- [x] ORCHID should not have an "H" - please change to ORCID iD (lowercase "i" is also how they refer to it)
- [x] Please make the “e.g.” consistent - so add a period in between e and g for website url and google scholar url examples.
![screen shot 2018-07-19 at 10 38 36 am](https://user-images.githubusercontent.com/18424138/42949514-e7a72726-8b3f-11e8-9fc4-f718cf108927.png)

- [x]  Since we are giving the KF examples, can you change twitter and GitHub rom Simon to @kidsfirstDRC and kidsfirst
![screen shot 2018-07-19 at 10 36 54 am](https://user-images.githubusercontent.com/18424138/42949526-ee7b0540-8b3f-11e8-840f-24d46084bb48.png)

- [x] Can you make it so the icons look like their are lined up with the text fields.

**Profile**
- [x] When the user enters their story and/or bio and saves, the italicized interactions can be removed from the interface.

**Comment by ciaranschutte** [comment]
@rosibaj (Point 6) Doesn't look like there's a "Contact Information" section built yet. Created ticket for it #649

**Comment by ciaranschutte** [comment]
@kcullion Should input fields text be italicized?

**Comment by ciaranschutte** [comment]
@rosibaj https://5b775225b312744d2d53e276--kf-qa-portal.netlify.com/

**Comment by kcullion** [comment]
@ciaranschutte no let's not make them italicized. How can I review this netlify link?

**Comment by ciaranschutte** [comment]
@kcullion Ok great.

**Comment by rosibaj** [comment]
@ciaranschutte this looks really great!! - agree with splitting out the other sections/bug into a ticket 
Feedback: 
- in the title selection, make this Select and Option consistent with the lowercase 
<img width="402" alt="screen shot 2018-08-21 at 1 39 27 pm" src="https://user-images.githubusercontent.com/15824252/44418906-af78f100-a547-11e8-974b-45ebf48204a6.png">
