### ISSUE TITLE
User Profile - Researcher

### ISSUE THREAD

**Issue by cy** [kids-first/kf-portal-ui#56]

**Comment by phuongmy** [comment]
Scope of the researcher profile page (ability to view and update):
- Basic info at the top (name, role, etc.)
- About me
- Settings and Privacy - Account integrations (but Connect buttons won't do anything)
- Settings and Privacy - Privacy

Design: https://projects.invisionapp.com/d/main#/console/13157333/276423110/preview
Wiki: https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/385744922/Log+in+KF+account+User+Profile

Note in "Research interests" section: after the users enters the website and google scholar ID then from the user profile view, clicking on the buttons open in a new tab:
- the website
- the link of all citations listed in google scholar based on ID >> https://scholar.google.fr/citations?user=<google_scolar-ID>, e.g https://scholar.google.fr/citations?user=QnfVYHIAAAAJ

**Comment by phuongmy** [comment]
Research Interest section - add a research interest by creating a new research interest or selecting an existing one:
https://invis.io/MQFHWABDK9Y#/280722992_20d-KF-Researcher-Profile-Edit-Interests-Autofill
