### ISSUE TITLE
Add beta note/message to dashboard

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#562]
- [ ] Add the BETA message note to the dashboard

ZEPLIN mockup: https://zpl.io/b6M5qKK

**Comment by hlminh2000** [comment]
could we have this split in two issues? I've done the beta message in https://github.com/kids-first/kf-portal-ui/pull/564 as that seems more urgent

**Comment by rosibaj** [comment]
@hlminh2000 yes we sure can! will do now

**Comment by kcullion** [comment]
@rosibaj @hlminh2000 

Here's some styling tweaks:

- [ ] Make flask icon a bit larger and position it as follows (height:40px; top:15px; right:15px; )

- [ ] Body copy throughout the portal is meant to be Open Sans (just headings are Monsterrat). Can you make the body copy open sans regular, font-size:15px; line-height:30px; Hoping to have this fixed throughout the portal style one day :)

- [ ] Increase the padding inside the box to 30px and change the border to :1px solid #e0e1e6

- [ ] Can you change the margin-bottom for the heading ("The Portal is currently in BETA Phase") from 20px to 10px.

**Comment by hlminh2000** [comment]
updated :)

**Comment by rosibaj** [comment]
@hlminh2000 can you change "We are actively working on features" -> "We are actively working on improvements"? and then deploy this today?
