### ISSUE TITLE
Fix setting button icons on dashboard page

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#567]
The settings wheel and edit button are unreasonably small.

![Screen Shot 2018-07-24 at 10.55.50 AM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/3e22ad41-6c39-4a37-8141-20d43bbefdaf)

**Comment by ciaranschutte** [comment]
Going to fix this with #596

**Comment by ciaranschutte** [comment]
@rosibaj https://5b8e020b3813f0660c9d4373--kf-qa-portal.netlify.com/
