### ISSUE TITLE
Success Message on Gen 3 connect

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#569]
After users login to Gen3, they go back to the settings page with "Connected" information within the table and the ability to remove the connection.  
- [x] they should receive a success alert (#232 design) that says `Controlled dataset access sucessfully connected through Gen3`:

https://invis.io/MQFHWABDK9Y#/304086714_26a-KF-Researcher-Settings-GEN3connected
(Zeplin: https://zpl.io/a8KNDwE)

**Comment by hlminh2000** [comment]
@rosibaj QA portal updated with this message and a restyling of the prompt messages (the toasts, error message in modal, beta message in dashboard which @kcullion has agreed should follow the rest of the message styles :)

**Comment by rosibaj** [comment]
@hlminh2000 Checked out all the error messages!  It looks great from my end.

**Comment by hlminh2000** [comment]
cool! will bring to prod :)

**Comment by hlminh2000** [comment]
we can probably close this now :)

**Comment by rosibaj** [comment]
@hlminh2000 Checked on prod!  Looks good!.
