### ISSUE TITLE
Dashboard placeholder page

### ISSUE THREAD

**Issue by cy** [kids-first/kf-portal-ui#57]

**Comment by phuongmy** [comment]
Specification for the homepage in progress.

For now we can just show the login section with the ability to log in with gmail (+FB is available) and the "New to Kids First? Join now".
The rest is "coming soon"!

**Comment by phuongmy** [comment]
After discussion with Vincent, Rosi, Kim, the homepage will be shared with the website, see first draft here: https://projects.invisionapp.com/share/UJF2TO7AX#/screens/281260401.

I'm removing this ticket from data portal scope. We'll just show a log in page, see https://github.com/kids-first/kf-portal-ui/issues/74
