### ISSUE TITLE
Add 4th User profile page

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#580]
User Profile: https://zpl.io/V0yWqKK
![screen shot 2018-08-02 at 3 14 47 pm](https://user-images.githubusercontent.com/18424138/43605610-def37472-9666-11e8-9888-59f740758b9c.png)

Assets for new icons + community banner images are posted on: https://github.com/kids-first/kf-portal-ui/issues/582

Gradient values for banner: https://zpl.io/a74RBRq
Dark blue: 1e3a90. R: 30. G: 58. B: 144
Medium blue: 404c9a. R: 64. G: 76. B: 154
Light blue: 7a85cb. R: 122. G: 133. B: 203

Dashboard profile sidebar: https://zpl.io/a74RBRq

![screen shot 2018-08-02 at 3 07 12 pm](https://user-images.githubusercontent.com/18424138/43605255-cb7c5e0a-9665-11e8-8c11-a1f3d1969535.png)

**Comment by ciaranschutte** [comment]
@rosibaj QA link: https://5b6afb62c6aed63744841c1c--kf-qa-portal.netlify.com/ 
(same as #582)
* NB: need your ego token from the QA environment
