### ISSUE TITLE
Add 4th User role to registration wizard

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#581]
- [ ] Add to possible Roles in Persona
- [ ] Add 4ths user choice to the 2nd wizard page
- [ ] Content for all user types needs to be updated

Mockup: https://zpl.io/bAGJMKq

![00 kf-join-wizard-new](https://user-images.githubusercontent.com/18424138/43543127-0354ba4e-959d-11e8-8bd3-957a129cfa55.jpg)

**Comment by kcullion** [comment]
FYI @bdolly these are the new user rolls that will need to be worked in to the analytics after it's built (new labels for all as well)

**Comment by rosibaj** [comment]
resolved as part of #580
