### ISSUE TITLE
Update Profile Icons across the portal

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#582]
User labels and icons need to be updated.

NEW ASSETS: 
[KF-new-user-assets.zip](https://github.com/kids-first/kf-portal-ui/files/2253699/KF-new-user-assets.zip)

4 User Types: Researcher, Healthcare Professional, Patient/Family Member, Community Member

1. On the wizard page (see https://github.com/kids-first/kf-portal-ui/issues/581)

2. On the Dashboard
3. On the Profile Banner

![profile-new-icons](https://user-images.githubusercontent.com/18424138/43544765-f43a7f1c-95a1-11e8-8207-c5b247a9dff2.jpg)

4. On the User Profile when you can edit basic information (you can toggle the profile types):
The new type needs to be added here, and the labels changed.

![screen shot 2018-08-01 at 3 47 00 pm](https://user-images.githubusercontent.com/18424138/43544859-3be661c8-95a2-11e8-9389-42e82d047928.png)
![screen shot 2018-08-01 at 3 47 03 pm](https://user-images.githubusercontent.com/18424138/43544860-3bf3feaa-95a2-11e8-9d7a-2b6ae11deb30.png)
![screen shot 2018-08-01 at 3 47 06 pm](https://user-images.githubusercontent.com/18424138/43544861-3bffdf0e-95a2-11e8-90e5-f7b44169a48f.png)

**Comment by ciaranschutte** [comment]
Add new user role to Persona:
https://github.com/kids-first/kf-persona/pull/12

**Comment by ciaranschutte** [comment]
@rosibaj QA link: https://5b6afb62c6aed63744841c1c--kf-qa-portal.netlify.com/ 
(same as #580)
* NB: need your ego token from the QA environment

**Comment by rosibaj** [comment]
@ciaranschutte A couple issues on your branch
- wizard is broken
- #settings page and logout do not work
