### ISSUE TITLE
Copy File IDs to Cavatica

### ISSUE THREAD

**Issue by joneubank** [kids-first/kf-portal-ui#59]

**Comment by phuongmy** [comment]
Specifications: 
1- Connect to Cavatica (design) https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/385744922/Log+in+KF+account+User+Profile#Login,KFaccount,UserProfile-b.Analyzedata:Cavatica
2- Copy Files to Cavatica: https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/246939898/Link+to+Cavatica
See section  3.2 Copy files to my Cavatica project

Main scenario:
As a user, I would like to connect to my Cavatica account from the data portal. In the File Repository, I would like to look for files of interest, including controlled files. Then I should be able to select 1 of my Cavatica projects and copy the files of interest to selected Cavatica project.

In scope of the ticket: support the different access error messages described in the wiki.
Out of scope of the ticket: create a Cavatica project from the data portal (user will copy files to an existing project).

**Comment by phuongmy** [comment]
Feature complete except for the user error messages, which will be handled in:
https://github.com/kids-first/kf-portal-ui/issues/225
https://github.com/kids-first/kf-portal-ui/issues/226
Closing this ticket.
