### ISSUE TITLE
Update Authorized Study modal with consents below studies in the #settings page

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#593]
A user may come in with multiple consent codes for a single study (like so) 
> phs001100.c1
>phs001100.c2
>phs001100.c3

Right now the authorized studies modal only shows study level access.  We would like to show a list of the specific consent codes a user has access to below the study.  Update the authorized studies content modal to the new design with consent codes:

Mockup within setting section (consistent with the dashboard widget): https://zpl.io/V0y0zgo
"studies and data access" opens in a new window: https://kidsfirstdrc.org/support/studies-and-access/

![screen shot 2018-10-16 at 3 08 20 pm](https://user-images.githubusercontent.com/18424138/47040861-5dbea280-d155-11e8-90b9-1d35dcf6b4fe.png)

**Comment by rosibaj** [comment]
@kcullion I guess it is better to be consistent?

**Comment by rosibaj** [comment]
@kcullion Can you attach the mockups here?

**Comment by hlminh2000** [comment]
I think this ticket is complete? :)

**Comment by kcullion** [comment]
@hlminh2000 this was actually making the authorized studies available from the gen3 integration on . the settings page. Maybe we don't need this now that they are on the dashboard thought? @rosibaj thoughts? 
https://zpl.io/V0y0zgo

**Comment by hlminh2000** [comment]
oh I see! if we still want to show this in the settings page it should be pretty straight forward to take the same component and render it on the modal too :)

**Comment by rosibaj** [comment]
@kcullion i think its good to be consistent (and also i think it will be important when more than one integration is connected)
