### ISSUE TITLE
User Profile: Buttons for Editing Profile Widgets

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#594]
Add the "Cancel | Save" buttons at the bottom of the widgets too:
Zeplin links: https://zpl.io/25qLvd8
https://zpl.io/brN4QN7

![screen shot 2018-07-31 at 4 48 31 pm](https://user-images.githubusercontent.com/18424138/43486332-93f97da8-94e1-11e8-93db-263a4de924fa.png)

![screen shot 2018-07-31 at 4 48 15 pm](https://user-images.githubusercontent.com/18424138/43486339-98937a08-94e1-11e8-864d-08105eabf573.png)

**Comment by ciaranschutte** [comment]
@rosibaj https://5b748461e39e7c7d7a9fb3cb--kf-qa-portal.netlify.com/

**Comment by rosibaj** [comment]
@ciaranschutte looks good - only feedback is that cancel/save buttons are too big but that will be fixed in https://github.com/kids-first/kf-portal-ui/issues/596 i think

**Comment by rosibaj** [comment]
one more feedback - this looks like the last letter is getting cut off for some reason?
<img width="774" alt="screen shot 2018-08-16 at 12 52 52 pm" src="https://user-images.githubusercontent.com/15824252/44419595-ab4dd300-a549-11e8-8bed-99040075d6b5.png">

**Comment by rosibaj** [comment]
https://github.com/kids-first/user-feedback/issues/66

**Comment by ciaranschutte** [comment]
@rosibaj Fixed typo in https://github.com/kids-first/kf-portal-ui/pull/655

**Comment by ciaranschutte** [comment]
@rosibaj regarding last letter. I think that's just font. ![Screen Shot 2018-08-22 at 2.11.38 PM.png](https://images.zenhubusercontent.com/5b58924328d06e60f1c19ac1/5c949207-ed4f-48ea-a71f-17d173b350b1)
This is it with a tonne of margin (to push out any element that may be cutting it off) around it and it looks the same.

**Comment by kcullion** [comment]
@ciaranschutte please add the save/close button at the bottom of the Research Interest box too

**Comment by rosibaj** [comment]
@kcullion I think that is in another ticket actually

**Comment by kcullion** [comment]
@rosibaj sorry - @ciaranschutte please ignore
