### ISSUE TITLE
Overall style consistency: White Buttons

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#596]
There should be only 1 style of white button throughout the portal. Please fix all white buttons so they have the following style

**White Action buttons:**
Style:
![screen shot 2018-08-01 at 1 30 24 pm](https://user-images.githubusercontent.com/18424138/43538138-27e307ac-958f-11e8-8340-9caff26c985b.png)

### **Instances of white buttons**
- [x] Dashboard - Profile buttons
![screen shot 2018-08-01 at 11 21 43 am](https://user-images.githubusercontent.com/18424138/43531149-2e8d088a-957d-11e8-806f-58d3929cf184.png)
- [x] Profile edit/cancel

![screen shot 2018-08-01 at 11 56 53 am](https://user-images.githubusercontent.com/18424138/43533219-4b80033e-9582-11e8-9265-48ba85e3314f.png)

![screen shot 2018-08-01 at 11 58 29 am](https://user-images.githubusercontent.com/18424138/43533188-3ebb2890-9582-11e8-8c8e-8025f0bcc874.png)

- [x] User Settings page:
![screen shot 2018-08-01 at 12 12 55 pm](https://user-images.githubusercontent.com/18424138/43533993-3ffcfdb2-9584-11e8-9d03-80b104d9bf70.png)

- [x] ALL Modal Cancel buttons (I know this isn't the white button in my mockup, but since we are using white cancel buttons in the profile widgets, please change this to the white button style)

![screen shot 2018-08-01 at 12 00 22 pm](https://user-images.githubusercontent.com/18424138/43533492-e9a5357a-9582-11e8-8abd-d10c55ddcf41.png)
![screen shot 2018-08-01 at 12 19 57 pm](https://user-images.githubusercontent.com/18424138/43534402-415cde42-9585-11e8-84ec-b839b3b245dc.png)
(All filters cancel) 
![screen shot 2018-08-01 at 1 28 43 pm](https://user-images.githubusercontent.com/18424138/43538019-e616b72e-958e-11e8-9a95-aa7f51a75902.png)

- [x] Change avatar button - also try to make the label fit on one line  (may mean wider modal, which is fine)
![screen shot 2018-08-01 at 12 13 54 pm](https://user-images.githubusercontent.com/18424138/43534100-801c6fea-9584-11e8-88fe-fee3f74a4647.png)

- [x] File Repository
![screen shot 2018-08-01 at 12 16 21 pm](https://user-images.githubusercontent.com/18424138/43534183-c145c232-9584-11e8-9593-826a031ddd6b.png)

![screen shot 2018-08-01 at 12 17 49 pm](https://user-images.githubusercontent.com/18424138/43534286-f03b101a-9584-11e8-93d8-8060f817208f.png)

- [x] Cavatica modal (create a project and cancel buttons)
![screen shot 2018-08-01 at 12 19 15 pm](https://user-images.githubusercontent.com/18424138/43534344-1fdfff9c-9585-11e8-9764-ef49c2ffbf78.png)

- [x] Upload IDS modal (cancel button)
![screen shot 2018-08-01 at 2 07 22 pm](https://user-images.githubusercontent.com/18424138/43539901-3b6dfb74-9594-11e8-968d-7918cb8d61d9.png)

**Comment by ciaranschutte** [comment]
@kcullion  Are the icon sizes right in the first screen descriptive image?
They look a little small as mentioned in #567
Smaller than Zeplin also.
