### ISSUE TITLE
Overall style consistency: Teal Buttons

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#599]
There should be only 1 style of teal button throughout the portal (with slight variation - small and large). Please fix all teal buttons so they have the following style:

Style:
![teal-buttons](https://user-images.githubusercontent.com/18424138/43539602-56aca620-9593-11e8-934d-2910ab9be7ef.png)

### **Instances of small teal buttons**
- [x] Profile - Save buttons
![screen shot 2018-08-01 at 1 54 45 pm](https://user-images.githubusercontent.com/18424138/43539278-7754e226-9592-11e8-8a36-185456e687e3.png)

- [x] Modal save buttons 
Profile edit basic info: 
![screen shot 2018-08-01 at 1 53 57 pm](https://user-images.githubusercontent.com/18424138/43539300-823b3bf4-9592-11e8-8e7e-18f5abb65455.png)

- [x] Profile - connect to Cavatica modal
![screen shot 2018-08-01 at 2 13 11 pm](https://user-images.githubusercontent.com/18424138/43540193-092c025e-9595-11e8-8ffa-dd67db60da12.png)

- [x] File Repository - all filters button
![screen shot 2018-08-01 at 2 01 58 pm](https://user-images.githubusercontent.com/18424138/43539692-8db78f0e-9593-11e8-87ae-88a18c25646c.png)

And view results button (in all filters modal):
![screen shot 2018-08-01 at 2 02 11 pm](https://user-images.githubusercontent.com/18424138/43539719-a5b2c948-9593-11e8-8bf8-5b51e402a5c4.png)

- [x] File Repository - Download button (also has download icon)
![screen shot 2018-08-01 at 2 02 03 pm](https://user-images.githubusercontent.com/18424138/43539704-9897c0d8-9593-11e8-96d8-56dc69d7ae12.png)

And download manifest modal button:
![screen shot 2018-08-01 at 2 03 48 pm](https://user-images.githubusercontent.com/18424138/43539750-c3f12648-9593-11e8-93a6-82e5a78a87ea.png)

- [x] File Repository - Copy files to cavatica modal:
![screen shot 2018-08-01 at 2 04 52 pm](https://user-images.githubusercontent.com/18424138/43539803-ecd6ea34-9593-11e8-9796-fd64a77b8195.png)

- [ ] File Repository - Upload IDs modal:
![screen shot 2018-08-01 at 2 11 17 pm](https://user-images.githubusercontent.com/18424138/43540109-cf17ddfe-9594-11e8-9176-8c93f19caaa9.png)

### **Instances of large teal buttons**
- [x] Dashboard: Settings button
![screen shot 2018-08-01 at 2 14 51 pm](https://user-images.githubusercontent.com/18424138/43540264-4606383e-9595-11e8-93f5-86b607e9db1d.png)

(REMOVE, this has been redesigned with the demo queries) Dashboard: File Repository button (when this note is implemented in empty saved query box)
![screen shot 2018-08-01 at 2 15 19 pm](https://user-images.githubusercontent.com/18424138/43540303-5c6dc6d2-9595-11e8-977d-8f54df13c8ed.png)

- [x] User Profile: integration table connect button:
![screen shot 2018-08-01 at 2 17 35 pm](https://user-images.githubusercontent.com/18424138/43540428-b5e15eea-9595-11e8-9c5c-32bd99114530.png)

**Comment by rosibaj** [comment]
Related to: https://github.com/kids-first/kf-portal-ui/issues/659

**Comment by ciaranschutte** [comment]
file repo button #675
