### ISSUE TITLE
Connect to Gen3 and Download Files

### ISSUE THREAD

**Issue by joneubank** [kids-first/kf-portal-ui#60]

**Comment by phuongmy** [comment]
Design mock-ups:
- Connect to GEN3: https://projects.invisionapp.com/d/main#/console/13157333/276667049/preview
- Download file in File table: https://projects.invisionapp.com/d/main#/console/13157333/275099469/preview

Wiki specifications:
https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/385744922/Log+in+KF+account+User+Profile#Login,KFaccount,UserProfile-5.3SettingsandPrivacy
