### ISSUE TITLE
Overall style consistency: Purple Buttons

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#601]
The purple buttons are meant to emphasize very important features so there aren't many.  Please fix the 2 buttons so they have the following style:

Style:
![screen shot 2018-08-01 at 2 36 47 pm](https://user-images.githubusercontent.com/18424138/43541405-624eca3a-9598-11e8-9383-ed0c0318ec5e.png)

### **Instance of small purple buttons**
- [ ] Profile - Authorized Studies (when connect to GEN3)
![screen shot 2018-08-01 at 2 38 56 pm](https://user-images.githubusercontent.com/18424138/43541531-a24ea5e2-9598-11e8-92ee-0ccd2239f1de.png)

### **Instance of large purple button**
- [ ] File Repository - COPY FILES TO CAVATICA
PLEASE ALSO CHANGE THE LABEL TO JUST "COPY FILES TO CAVATICA"

![screen shot 2018-08-01 at 2 40 22 pm](https://user-images.githubusercontent.com/18424138/43541622-d9686036-9598-11e8-890a-5dc11b78848e.png)

**Comment by rosibaj** [comment]
Closing as this has been addressed
