### ISSUE TITLE
Align compl-o-meter

### ISSUE THREAD

**Issue by ciaranschutte** [kids-first/kf-portal-ui#608]
![image.png](https://images.zenhubusercontent.com/5b58924328d06e60f1c19ac1/c5dd96a6-2385-4bf2-ab62-18f43a9e3ba0)

**Comment by ciaranschutte** [comment]
@rosibaj https://5b7428bc3813f01043ac0939--kf-qa-portal.netlify.com/

**Comment by rosibaj** [comment]
@ciaranschutte tested - this looks good to go to QA!
