### ISSUE TITLE
Profile widgets: Add save and cancel to bottom

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#611]
For the "Research Interests" and "Find me on" widgets, please add the cancel and save buttons at the bottom of the edit view too.

<img width="465" alt="screen shot 2018-08-03 at 9 27 26 am" src="https://user-images.githubusercontent.com/18424138/43645353-9aeeb914-96ff-11e8-9d0b-f5697683c907.png">

Zeplin: Research interests: https://zpl.io/25qLvd8
Find me on: https://zpl.io/brN4QN7

**Comment by ciaranschutte** [comment]
@rosibaj https://5b87d9483813f076d0b702e1--kf-portal.netlify.com/

**Comment by ciaranschutte** [comment]
@rosibaj https://5b87dc603813f05255b702a0--kf-portal.netlify.com/

**Comment by ciaranschutte** [comment]
@rosibaj updated link https://5b87f156e39e7c46e35df51e--kf-qa-portal.netlify.com/

**Comment by rosibaj** [comment]
@ciaranschutte Cache clear worked :) This looks great - we can get this in for demo late  if you merge this morning maybe!
