### ISSUE TITLE
Header: Adding an "All apps" menu dropdown

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#613]
The Kids First item in the header will open a dropdown with links to the following.  
1. The Data Resource Portal (this will be always active when on the portal)
2. Website - will link to: https://kidsfirstdrc.org/ (OPEN IN A NEW WINDOW)
3. Support - will link to: https://kidsfirstdrc.org/support/getting-started/ (OPEN IN A NEW WINDOW) 
4. Contact - will link to: https://kidsfirstdrc.org/contact

It looks like this:
![screen shot 2018-08-23 at 3 19 53 pm](https://user-images.githubusercontent.com/18424138/44547110-04536d80-a6e8-11e8-826d-582efa18a574.png)

Mockups can be found here:
Off state: https://zpl.io/VxYolPw
On state: https://zpl.io/V0yWqKK

Icons can be downloaded here:
[KF-all-apps-icons.zip](https://github.com/kids-first/kf-portal-ui/files/2291179/KF-all-apps-icons.zip)

**Comment by ciaranschutte** [comment]
@rosibaj https://5b86ea64c96592716fc9dfe2--kf-qa-portal.netlify.com/

**Comment by rosibaj** [comment]
@ciaranschutte i think the colors are off.  

- [ ] Can you change all headings to #90278e 
EX:

![screen shot 2018-08-29 at 3 50 22 pm](https://user-images.githubusercontent.com/15824252/44811792-85f14280-aba3-11e8-93d4-59d9a15afab8.png)

![screen shot 2018-08-29 at 3 51 08 pm](https://user-images.githubusercontent.com/15824252/44811769-7bcf4400-aba3-11e8-9503-aa6adb491486.png)

- [ ] When they user mouses over the menu or user profile it should be icon` v` and words and icon highlighed to #c03299

- [ ] When they user clicks the menu or user profile it should be icon `^` and words and icons highlight to #c03299

**Comment by ciaranschutte** [comment]
https://5b87d9483813f076d0b702e1--kf-portal.netlify.com/
@rosibaj should be good now :)

**Comment by ciaranschutte** [comment]
@rosibaj https://5b87d9483813f076d0b702e1--kf-portal.netlify.com/

**Comment by rosibaj** [comment]
@ciaranschutte When i login on this link I see this now:
![screen shot 2018-08-30 at 9 01 32 am](https://user-images.githubusercontent.com/15824252/44853245-6efa3100-ac33-11e8-9fc8-da52011a768e.png)

**Comment by ciaranschutte** [comment]
@rosibaj https://5b87d9493813f076d0b702ea--kf-qa-portal.netlify.com/
(correct link)

**Comment by rosibaj** [comment]
@ciaranschutte This looks great now!!!! Same comment - if we can deploy this morning you can demo this afternoon ;)
