### ISSUE TITLE
Footer link updates

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#614]
The footer links need to be updated to the following (with a new order):

1. kidsfirstdrc.org   - will link to: https://kidsfirstdrc.org/ (OPEN IN A NEW WINDOW)
2. About the Portal  - will link to: https://kidsfirstdrc.org/portal (OPEN IN A NEW WINDOW) 
3. Policies    - will link to: https://kidsfirstdrc.org/policies
4. Support - will link to https://kidsfirstdrc.org/support/getting-started/ (OPEN IN A NEW WINDOW) Note this section isn't live yet
5. Contact - will link to https://kidsfirstdrc.org/contact (OPEN IN A NEW WINDOW) 

It looks like this:
<img width="518" alt="screen shot 2018-08-03 at 12 03 38 pm" src="https://user-images.githubusercontent.com/18424138/43653298-9ff9869e-9715-11e8-96a5-f35f5712b124.png">

Mockup can be found here:
Off state: https://zpl.io/VxYolPw

**Comment by ciaranschutte** [comment]
@rosibaj https://5b8d9d0bb31274675bc458c5--kf-qa-portal.netlify.com/

**Comment by rosibaj** [comment]
@ciaranschutte This looks great - good to deploy!
