### ISSUE TITLE
Profile Wizard UI Design

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#62]
Make sure profile wizard is compliant with design specifications

**Overall (applies to all wizard screens)**
- [x] The right font is not being used
- [x] Top numbers steps should be 1,2,3 (not 0,1,2)
- [x] The page fade from the top should be more pronounced
- [x] Add  cursor: pointer; to Signup/Login button. When on the profile wizard, the top right button should just be "Log in" - this wizard is the sign up process
- [x] Add more padding inside the wizard container (35px)
- [x] Please use the box border colour value and shadow values from Zeplin. Wizard should have a shadowed edge
- [x] The container is too wide. On desktop, the wizard should have fixed width (defined in Zepplin). (And change for when responsiveness is implemented)
- [x] The step numbers span the width of the container and are a bit larger, with a 1px grey (#d4d6dd) border underneath
- [x] Headlines - please use the font (Montserrat) and sizes from Zeplin (main headline and instruction headline)
- [x] Please use #343434 for the body copy style.
- [x] Bottom cancel button should not be bolded (steps 2, 3)
- [x] Save button should be rounded and match the text styles in zeplin (steps 2, 3)
- [x] When profile or login is complete, user should be re-directed to user profile (when built) 
- [x] The Dashboard and File Repository navigation items should not be present until the user finishes this wizard.

**Page 1**
- [x] In step one of the wizard, the "Basic Info" and "Consent" text should be greyed out 

**Page 2**
- [x] The grey is too dark on the Email field
- [x] Patient role should say Patient/Caregiver
- [x] Text on role boxes is too large - please match zeplin values. Try to make the descriptions span two lines so that the icon isn't so large too. - icon size 35px, font size 12px, title montserrat, body open sans
- [x] Non-selected role boxes should have a white background and grey border.  Only the roles that is selected by the radio button should have a blue background with blue border. 
- [x] There should be a back button to return to the name/openid page
- [x] Use the form field labels from the mockups to make it friendlier? ("My first name is,... I am a...")
- [x] When I landed on this screen 'Patient" was selected by default. Can we make them all deselected by default?
- [x] Can you make the entire radio button box selectable - so the user can click on anywhere within this box to turn that radio button on.
- [x] Can you increase the space between the radio buttons and the grey border on top of the buttons
- [x] All role text and imagers were revised by KF - can you implement the updated text from Zeplin (https://invis.io/MQFHWABDK9Y#/275376887_11-KF-Signup-V1-Step2)

**Page 3**
- [x] Terms and conditions box should have rounded edges and be a lighter grey
- [x] finish button should be rounded and blue with white text
- [x] Agreement checkbox should be unselected by default

Nice to haves
- [ ] The progress bar at the top is one color.  It should be a fade from light to dark blue.

**Comment by cy** [comment]
It's super hard to get things lined up exactly like the design, seems like zeplin and browser renders font sizes differently? :/ Below is screenshots from zeplin vs browser for the same css style
```
	font-family: Montserrat;
	font-size: 14px;
	line-height: 2.0;
	color: #343434;
```
Zeplin
![screen shot 2018-03-05 at 11 58 20 am](https://user-images.githubusercontent.com/1314446/36988352-ae572a9a-206c-11e8-90b6-5436be536b55.png)
Browser
![screen shot 2018-03-05 at 11 58 27 am](https://user-images.githubusercontent.com/1314446/36988357-b072fb10-206c-11e8-971b-91500e69fc5f.png)

Zeplin: looks bolder, Browser: is longer
