### ISSUE TITLE
Improve navigation dropdown behaviour

### ISSUE THREAD

**Issue by hlminh2000** [kids-first/kf-portal-ui#623]
From @rosibaj: 
- When I click on the an option in the dropdown, the user dropdown stays open on the page I am navigated to and does not close until I click away.
- After clicking on an option, the page should be navigated to and the dropdown should close.

**Comment by ciaranschutte** [comment]
@rosibaj https://5b71d83b3813f041d2750e90--kf-qa-portal.netlify.com/
Functionality in this ticket is fixed.
Need to investiage why 'Settings' is broke on these deploy links.

**Comment by rosibaj** [comment]
@ciaranschutte tested - this looks great!
