### ISSUE TITLE
Actions Panel: remove scrolling

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#636]
The actions panel is scrollable currently - but it doesn't need to be. Please remove scroll

![screen shot 2018-08-09 at 2 51 37 pm](https://user-images.githubusercontent.com/18424138/43919442-e17471f6-9be3-11e8-9ed3-faa7790aff58.png)

**Comment by rosibaj** [comment]
closed as this was fixed with other changes!
