### ISSUE TITLE
Hide Manifest Id on Upload

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#637]
Hide the manifest id box from the UI

![Screen Shot 2018-08-09 at 5.19.01 PM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/6874dc41-a346-4fe6-af45-92feb08eb1ba)

**Comment by hlminh2000** [comment]
@rosibaj preview link: https://5b7c4f513813f04367010b7c--kf-qa-portal.netlify.com/

**Comment by rosibaj** [comment]
@hlminh2000 looks great!  Can deploy to QA

**Comment by hlminh2000** [comment]
what about prod? are we are we looking for CHOP's sign off?

**Comment by rosibaj** [comment]
@hlminh2000 good point - we are not on this one! go ahead
