### ISSUE TITLE
Split file repository facets into two tabs: File, Participant

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#638]
**Mockup:**
![screen shot 2018-08-17 at 11 34 18 am](https://user-images.githubusercontent.com/18424138/44279455-6d863d00-a21f-11e8-9afd-df2df2b7020e.png)

Zeplin:Participant tab: https://zpl.io/2vWlMNQ 
Files tab: https://zpl.io/VxlkmRW

**Technical considerations:** 
- This can be done front-end in the KF code
- We would not be able to select facets in arranger - the code would determine the facet organization
- This would be kids-first specific and arranger would not be involved

**Comment by kcullion** [comment]
Mockups of tabs: 
1. Participants on: https://invis.io/8JMV1FYY675#/314176273_06a-KF-File-Repository-New-Actions-Panel
2. Files on: https://invis.io/8JMV1FYY675#/314620185_02-KF-File-Repository-Actions-Tab-Files
