### ISSUE TITLE
File repo table not updating

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#641]
1. go to last page of table 
2. click a facet.  The summary numbers update, but the table does not.

https://usersnap.com/a/#/your-team-oy1k/p/portal-testing-7a044ebb/130

**Comment by rosibaj** [comment]
https://github.com/kids-first/user-feedback/issues/60

**Comment by hlminh2000** [comment]
suspect from `@arranger/component`: `modules/components/src/DataTable/Table/Table.js`

**Comment by rosibaj** [comment]
@ciaranschutte huh - it looks like some other change addressed this bug as i can no longer reproduce either! we can close.
