### ISSUE TITLE
4th user type - design review

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#646]
Related to: https://github.com/kids-first/kf-portal-ui/issues/583

Please fix the following: 

- [x] On the join wizard, reorder the user list to: Researcher, Healthcare Professional, Patient or Family Member, Community Member
![screen shot 2018-08-16 at 10 10 00 am](https://user-images.githubusercontent.com/18424138/44213806-8cf86980-a13c-11e8-99c5-758ea0bb8eb0.png)

- [x] Fix the descriptions for the user profiles. You can copy and paste them from: https://zpl.io/bAGJMKq

- [x] Reorder the user list in the edit profile option to: Researcher, Healthcare Professional, Patient or Family Member, Community Member
![screen shot 2018-08-16 at 9 19 05 am](https://user-images.githubusercontent.com/18424138/44213991-1019bf80-a13d-11e8-935b-f645d246bc24.png)

- [x] [won't do] To keep consistent with the website, please use this darker blue icon for the community member item in the join wizard (i.e. whenever it's on a white background). 

[KF-community-icon.zip](https://github.com/kids-first/kf-portal-ui/files/2293973/KF-community-icon.zip)

**Comment by hlminh2000** [comment]
Regarding the icon color, the icon color is programatically set to match up with the role's primary color, so if we're going forward with this, would be good to modify the gradient so the pill stands out. Thanks @rosibaj for picking up on the color collision, we're leaving it as is for now because of this problem.

**Comment by kcullion** [comment]
@hlminh2000  and @ciaranschutte just ignore the request to update the icon colour to the darker blue. Please just leave it at #5b6bbb

**Comment by hlminh2000** [comment]
This is all merged, so I'm closing :)
