### ISSUE TITLE
Create Contact Information section

### ISSUE THREAD

**Issue by ciaranschutte** [kids-first/kf-portal-ui#649]
![image.png](https://images.zenhubusercontent.com/5b58924328d06e60f1c19ac1/1f46f67d-30aa-401c-b169-ce3b26793991)

**Comment by ciaranschutte** [comment]
@rosibaj https://5b7ec9c5c6aed62d081d26ca--kf-qa-portal.netlify.com/

**Comment by rosibaj** [comment]
Looks good so far @ciaranschutte.  One thing:

- If a person does not have one of the fields filled out, we should not show that icon on the bottom with no information.  For example, here do not show the phone with blank fields. 

![screen shot 2018-08-23 at 1 12 02 pm](https://user-images.githubusercontent.com/15824252/44540875-496ea400-a6d6-11e8-8b89-277b3438ac7e.png)
