### ISSUE TITLE
Download manifest (Participant)

### ISSUE THREAD

**Issue by Fgerthoffert** [kids-first/kf-portal-ui#65]

**Comment by phuongmy** [comment]
Specifications: https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/290422965/Download+Files+Manifests#DownloadFiles/Manifests-2.DownloadParticipantManifest

The user should be able to download the manifest for all the files resulting from the query or files selected in the table.
The scope of this ticket is the "Download Manifest (Participant)" option.
(The other option is to download a manifest for Participants' files + family's files >> issue #54)

Reminder: a manifest is 2 files:
- 1 that contains the list of files uuid
- 1 that describes more metadata about those files
