### ISSUE TITLE
Actions panel - button updates

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#650]
- [x]  Remove the subtitles below the "Download" title ("File Manifest" and "Reports") 
- [x] Split actions into 3 buttons ("Manifest" "Biospecimens" and "Clinical"). Clinical will have two options "Participant" and "Participant and Family".
- [x] Update label of the Cavatica button to "Copy files to Cavatica"

Mockup: https://invis.io/8JMV1FYY675#/314176274_06b-KF-File-Repository-New-Actions-Clinical
zeplin:https://zpl.io/2vWlMNQ

![screen shot 2018-08-17 at 1 16 32 pm](https://user-images.githubusercontent.com/18424138/44279885-1da87580-a221-11e8-9664-603c84e8596c.png)

All downloads will function as they do now.

**Comment by hlminh2000** [comment]
@rosibaj @kcullion  preview link for this one: https://5b898e263813f045cd40d49d--kf-qa-portal.netlify.com/

**Comment by kcullion** [comment]
Thanks @hlminh2000!
@rosibaj just to keep consistent with other headings and buttons, do you agree with these changes:

![screen shot 2018-08-31 at 4 16 31 pm](https://user-images.githubusercontent.com/18424138/44934034-68ee7800-ad39-11e8-9a8e-75c0c0d47898.png)

**Comment by rosibaj** [comment]
@kcullion yeah this looks like a good change

**Comment by hlminh2000** [comment]
@kcullion @rosibaj, it's updated :)

**Comment by kcullion** [comment]
@hlminh2000 is it updated on the same link above?

**Comment by hlminh2000** [comment]
@kcullion: https://5b8eb59802ed836b3548cbca--kf-qa-portal.netlify.com/

**Comment by rosibaj** [comment]
@hlminh2000 fucntion looks great, but the display is looking odd as is.  can we stack the buttons and have them all the same width ( i think the width of the biospecimen as it is longest)

**Comment by hlminh2000** [comment]
sure, not a big change. @kcullion would that work for you?

**Comment by kcullion** [comment]
@hlminh2000 Yep! Rosi and I talked about it :)

**Comment by hlminh2000** [comment]
@rosibaj @kcullion, updated :) : https://5b8ec5943813f07ea100bb48--kf-qa-portal.netlify.com/

**Comment by rosibaj** [comment]
looks good to me!

**Comment by kcullion** [comment]
@hlminh2000 works for me too. Thanks!

**Comment by hlminh2000** [comment]
sweet! got Ciaran to glance through the code too, so merging now :)
