### ISSUE TITLE
Facet Panel - Select All

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#654]
- [ ] When a facet has the "# more" link at the bottom (so more than 5 values)
include a select all link - where the user can select all of the values at once.

![screen shot 2018-08-17 at 1 52 21 pm](https://user-images.githubusercontent.com/18424138/44281138-ca382680-a224-11e8-9991-2621d8640e46.png)

See ICGC
Shown in zeplin mockup: https://zpl.io/bev8YdN

**Comment by rosibaj** [comment]
https://github.com/kids-first/user-feedback/issues/63
https://github.com/kids-first/user-feedback/issues/62

**Comment by jecos** [comment]
Done
