### ISSUE TITLE
Edit Profile places autocomplete broken

### ISSUE THREAD

**Issue by ciaranschutte** [kids-first/kf-portal-ui#656]

**Comment by ciaranschutte** [comment]
@rosibaj found this

**Comment by ciaranschutte** [comment]
looks like auto complete functionality on prod is working, I'm assuming this is just an api key issue.
fixing the broken child prop error

**Comment by rosibaj** [comment]
@ciaranschutte this issue has appeared on Prod now - i think something from QA messed this up!

**Comment by hlminh2000** [comment]
This is now fixed on prod :)

**Comment by rosibaj** [comment]
@hlminh2000 looks good
