### ISSUE TITLE
Gen 3 connection issues

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#672]
see for details: https://github.com/kids-first/user-feedback/issues/67

Additional details from Bailey: 
> The only error I get is Proccess_Interrupted
> Then after the 3rd or 4th time I try, it works and will work everytime after that.
> if i log out & log back in - its the same cycle. Process interrupted for 3 or 4 tries
> and then works

I see this error:
![Screen Shot 2018-08-23 at 10.03.05 AM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/6aecf2b5-39a8-4aa2-9d72-a2bb6d319adc)

![Screen Shot 2018-08-23 at 11.11.12 AM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/c4724ce2-0b34-4be1-aed2-d2842d10807c)

**Comment by rosibaj** [comment]
@hlminh2000 Are there any PRs to connect to this issue?

**Comment by hlminh2000** [comment]
had them connected to the wrong issue, reconnected to this now. There are some PRs in the lambda as well but I can't seem to connect those

**Comment by hlminh2000** [comment]
[correction]: realized I can connect them through zenhub, so went ahead and did it :P

**Comment by rosibaj** [comment]
@hlminh2000 tested on prod! this is working now thank you!!
