### ISSUE TITLE
Dashboard - Demo queries box

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#675]
When a user hasn't saved queries yet, show this version of the query box:

![screen shot 2018-08-23 at 4 03 48 pm](https://user-images.githubusercontent.com/18424138/44549136-2bad3900-a6ee-11e8-80ed-465f47bee92b.png)

Zeplin mockup: https://zpl.io/V1lzkYB

@rosibaj to specify the example queries
1. All Harmonized Data
https://p-qa.kfdrc.org/s/1b
2. Name: `Female probands with cleft palate (HP:0000175) and parents with harmonized aligned reads`
https://p-qa.kfdrc.org/s/z 
3. Data from oral samples of probands with full trio data
https://p-qa.kfdrc.org/s/18

**Comment by rosibaj** [comment]
@ciaranschutte demo queries, names, and order are completed now

**Comment by bdolly** [comment]
would like to add analytics into this before merge so we can track if people are using it

**Comment by ciaranschutte** [comment]
![image.png](https://images.zenhubusercontent.com/5b58924328d06e60f1c19ac1/030ad8eb-f6f3-4dc9-a9c9-92e8a4d78f19)

**Comment by ciaranschutte** [comment]
https://github.com/kids-first/kf-portal-ui/tree/feature/default-queries

**Comment by rosibaj** [comment]
@hlminh2000 The queries have the incorrect names and order. Can you name and order the demo queries like so:

**All Harmonized Data** (currently the third query) 
**Female probands with cleft palate (HP:0000175) and parents with harmonized aligned reads** (currently the 2nd query)
**Data from oral samples of probands with full trio data** (currently the 1st query)

Also, the link shoudl be the brand purple, not blue.

**Comment by hlminh2000** [comment]
updated @rosibaj :)

**Comment by rosibaj** [comment]
@hlminh2000 whats the new link?

**Comment by hlminh2000** [comment]
@rosibaj https://5b91551d1f12b774a0dca64b--kf-qa-portal.netlify.com/
