### ISSUE TITLE
Finish share query

### ISSUE THREAD

**Issue by Fgerthoffert** [kids-first/kf-portal-ui#68]

**Comment by phuongmy** [comment]
Test on http://deploy-preview-73--kf-portal.netlify.com/s/r14gIG5DG
1- After you click on Share, it opens the dropdown of share options but then if you click outside of the dropdown, it does not close it. Clicking outside the dropdown should close it.
2- Click on Share, it opens the dropdown. Scroll down on the page (e.g. to see the files at the bottom of the table) >> the dropdown sticks to the screen, same location. Should it rather stay with the Share button?
3- “Copy short URL” option is written on 2 rows in the dropdown. It should be written on 1 row.
4- You can copy short URL only once, then it’s marked copied and you cannot copy it anymore (even though you update the query or let’s imagine you copied something else to your clipboard afterwards, it's not possible to copy the short URL again unless you refresh the page). Example in ICGC, the message "copied!" is displayed only for a few seconds then it comes back to original state so user can copy again.

**Comment by phuongmy** [comment]
5- Overlay between Show column and Share features.
<img width="1434" alt="screen shot 2018-02-21 at 8 21 33 am" src="https://user-images.githubusercontent.com/8812383/36482215-802bb63a-16e0-11e8-8632-7d830723932a.png">

**Comment by alex-wilmer** [comment]
bumping to 5 to figure out serverside rendering for dynamic opengraph tags
