### ISSUE TITLE
Short URL connecting to local

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#681]
Query:
https://portal.kidsfirstdrc.org/search/file?sqon=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22participants.study.short_name%22%2C%22value%22%3A%5B%22Ewing%20Sarcoma%3A%20Genetic%20Risk%22%2C%22Orofacial%20Cleft%3A%20European%20Ancestry%22%5D%7D%7D%5D%7D

Copied text: https://portal.kidsfirstdrc.org/search/file?sqon=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22participants.study.short_name%22%2C%22value%22%3A%5B%22Ewing%20Sarcoma%3A%20Genetic%20Risk%22%2C%22Orofacial%20Cleft%3A%20European%20Ancestry%22%5D%7D%7D%5D%7D

Result Url that gets sent:
https://local.portal.kidsfirstdrc.org:3000/search/file?sqon=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22participants.study.short_name%22%2C%22value%22%3A%5B%22Congenital%20Diaphragmatic%20Hernia%22%5D%7D%7D%5D%7D

**Comment by rosibaj** [comment]
https://github.com/kids-first/user-feedback/issues/69

**Comment by hlminh2000** [comment]
@rosibaj this one is on QA now :)

**Comment by rosibaj** [comment]
@hlminh2000 this looks great on QA - good to move from my view :)

**Comment by hlminh2000** [comment]
This is up on prod, confirmed to be working so closing :)
