### ISSUE TITLE
Align facet text

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#688]
<img width="322" alt="screen shot 2018-08-28 at 10 04 36 am" src="https://user-images.githubusercontent.com/15824252/44739421-bb276300-aac5-11e8-8108-25c7b10d9c87.png">

**Comment by nyanofthemoon** [comment]
@hlminh2000 I made the CSS modifications in the `kf-portal-ui` (since we had some CSS overriding in there already); adding to the arranger components next.
