### ISSUE TITLE
Bug: profile phone number

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#698]
When I put the dashes in to my profile phone number, the output on my profile has extra dashes.

![screen shot 2018-08-30 at 1 33 27 pm](https://user-images.githubusercontent.com/18424138/44869568-ec399c00-ac5b-11e8-82df-06ff6c76c478.png)

**Comment by ciaranschutte** [comment]
@rosibaj https://5b8d75684ed62f6156febc51--kf-qa-portal.netlify.com/
