### ISSUE TITLE
Firefox bug: Community Member icon not working

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#699]
- [ ] In firefox, the community member icon is not working on the edit profile form, dashboard or profile banner

![Screen Shot 2018-08-30 at 1.54.43 PM.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/e898b5c1-8b4d-490d-87e2-0dff618a03c1)

It's also not showing on the user profile banner and dashboard:
<img width="393" alt="screen shot 2018-08-30 at 2 45 09 pm" src="https://user-images.githubusercontent.com/18424138/44872420-7cc7aa80-ac63-11e8-8c49-d2efc28ce169.png">

<img width="202" alt="screen shot 2018-08-30 at 2 46 51 pm" src="https://user-images.githubusercontent.com/18424138/44872462-979a1f00-ac63-11e8-9bc0-78b01746e1fa.png">

- [ ] In the "Find me on" edit form, the website url icon is not showing up.
![screen shot 2018-08-30 at 3 06 09 pm](https://user-images.githubusercontent.com/18424138/44873531-81da2900-ac66-11e8-9be9-488d40e349b3.png)

**Comment by rosibaj** [comment]
Closing this issue as the member icons is now working correctly 
<img width="1575" alt="screen shot 2018-12-19 at 1 13 37 pm" src="https://user-images.githubusercontent.com/15824252/50239342-ec3ae480-038f-11e9-8abc-34c4885579d5.png">
