### ISSUE TITLE
Firefox bug: Modal overflow

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#701]
The modal content scroll area isn't working in firefox.  So when I edit my profile on a smaller screen (laptop) I see the following.

This prevents people from pressing the bottom buttons to cancel or save too. (The "All Filters" modal scroll is working - that could provide insight for this one)

![Screen Shot 2018-08-30 at 2.50.22 PM.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/0ba39af7-fa43-4e3e-8e7f-ea01f28ce83f)

**Comment by ciaranschutte** [comment]
@rosibaj  https://5b8ddce21f12b771f54bf4fb--kf-qa-portal.netlify.com/

**Comment by rosibaj** [comment]
@ciaranschutte tested, and is working great now! thank you!!
