### ISSUE TITLE
Firefox bug: delete query isn't working from dashboard

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#703]
When I click on the garbage can icon from the dashboard to delete a query, sometimes the query disappears from the dashboard and sometime the query fades out but never gets deleted from the list. But if I refresh or navigate away from the dashboard then go back, the queries are not deleted

![Screen Shot 2018-08-30 at 3.10.36 PM.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/8913912e-ead8-4f13-bb7a-56210b1bd684)

**Comment by hlminh2000** [comment]
To avoid conflicts, this has been bundled into #735
