### ISSUE TITLE
Make downloaded file names consistent

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#706]
When a user downloads a file they should be descriptive and consistent.

## Acceptance criteria
In thie file repository:
- When they export the file table, rename 
  - from "file-table.tsv" 
  - to "kidsfirst-file-repository-[version number].tsv" (ex.`kidsfirst-file-repository-1.10.0.tsv`)

In the cohort builder: (participant table)
- For participant_clinical reports, rename 
  - from: participant_clinical_20180830.tsv 
  - to "kidsfirst-participant-clinical-[version number].tsv"
- For  participant-and-family_clinical reports, rename 
  - from: participant-and-family_clinical_20180830 
  - to "kidsfirst-participant-family-clinical-[version number].tsv"
- For participants_biospecimen reports, rename 
  - from: participants_biospecimen_20180830 
  - to "kidsfirst-participant-biospecimen-[version number].tsv"

## Screenshots
![screen shot 2018-08-30 at 3 55 57 pm](https://user-images.githubusercontent.com/18424138/44875873-60c90680-ac6d-11e8-9721-d38d70b15a49.png)

![screen shot 2018-08-30 at 4 01 09 pm](https://user-images.githubusercontent.com/18424138/44876139-2a3fbb80-ac6e-11e8-9d82-3d498058b524.png)

## Technical details
- Aparently, the endpoint to retrieve the version number of the data release already exists: http://kf-release-coord.kids-first.io/releases?state=published&limit=1
it gives the latest release with the version number and other info. See also #1737 that will require the same version number retrieval.
- Store the info in Redux.

**Comment by allisonheath** [comment]
Wonder now that we have the data versioning ironed out if that should be included in the name as well?

**Comment by rosibaj** [comment]
@kcullion yes, that would be a good replacement instead of addition

**Comment by kcullion** [comment]
thanks @rosibaj. What do the version numbers look like? Can you update my descriptions, removing the dates?

**Comment by rosibaj** [comment]
@kcullion yup and done!

**Comment by kcullion** [comment]
Thanks!

**Comment by aalex** [comment]
Question: where is that version number taken from?

**Comment by aalex** [comment]
We need the release number from the ETL, so we need a new RESTful endpoint for that.

**Comment by aalex** [comment]
Aparently, the endpoint already exists: http://kf-release-coord.kids-first.io/releases?state=published&limit=1
