### ISSUE TITLE
Cannot download files in Firefox

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#707]
Example file `GF_TSGCD0XK` 

https://portal.kidsfirstdrc.org/search/file?sqon=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22filter%22%2C%22content%22%3A%7B%22fields%22%3A%5B%22kf_id%22%2C%22participants.kf_id%22%2C%22participants.study.short_name%22%2C%22participants.family_id%22%2C%22data_type%22%2C%22file_format%22%5D%2C%22value%22%3A%22GF_TSGCD0XK%22%7D%7D%5D%7D

I successfully downloaded this file in Chrome (see download in bottom left corner) 
![Screen Shot 2018-08-30 at 3.58.15 PM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/5dda486d-c12f-4d23-b9c6-2956ed634319)

If i try and donwload a file i do not have access to, i correctly get the notice that I do not have permission to download the file.   When i try and download a file i have permission to in firefox, nothing happens.  It does look like the s3 url is retrived, but does not redirect to download:

<img width="1542" alt="screen shot 2018-08-30 at 4 04 05 pm" src="https://user-images.githubusercontent.com/15824252/44876203-578c6980-ac6e-11e8-9e51-3a08514ff061.png">

**Comment by rosibaj** [comment]
@hlminh2000 worked perfectly!!! Lets move to prod when possible!

**Comment by hlminh2000** [comment]
This is merged so I'm closing now :)
