### ISSUE TITLE
Improve Gen3 connection interactivity

### ISSUE THREAD

**Issue by hlminh2000** [kids-first/kf-portal-ui#710]
Gen3 connection is expected to be a low-frequency feature, so lambda will likely be asleep everytime traffic hits. As such, the auth redirect window might be open for a while with nothing to show, so users are likely to close it before the token submission to lambda is complete.

Recommendation: the auth window will take the code, write to local storage for the main window to pick up and do the posting while keeping the spinner in place.

**Comment by jecos** [comment]
First, we need to check if it's a cold start issue by adding some logs in key management. If the answer is yes, we should move to a classical long running application in fargate.

**Comment by denis-crsj** [comment]
Closing issue for now. Transferring details into the Google Sheet : https://docs.google.com/spreadsheets/d/1U1JQZEBEMTP_07PngrmNh8rzbZICTX87Fe_2fEetAbI/edit#gid=0
