### ISSUE TITLE
Dashboard: Add share feature to file repo queries (demo and saved)

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#725]
Add Share/Delete actions to demo queries. 
zeplin: https://zpl.io/V1lzkYB

![Screen Shot 2018-09-04 at 10.25.22 AM.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/cef469e9-c6d9-4ba1-a9c5-9ed7f8883006)

When the user starts saving queries, they replace the blue note above the example queries.
Zeplin: https://zpl.io/2GOdAl4

![Screen Shot 2018-09-04 at 10.28.18 AM.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/2f2daa89-738b-4e33-bdf2-05e8f6a77fad)

**Comment by jecos** [comment]
Missing share button
