### ISSUE TITLE
Upload id box spinning forever

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#742]
![Screen Shot 2018-09-06 at 2.44.10 PM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/8f57ca9c-cbeb-4136-8e22-ec9001414fde)

**Comment by rosibaj** [comment]
https://github.com/kids-first/feedback/issues/1

**Comment by hlminh2000** [comment]
uhm seems I still have some issues with it... hangon

**Comment by rosibaj** [comment]
@hlminh2000 I double checked on prod - this is working now!  Thank you for the fast work!!!
