### ISSUE TITLE
Inconsistent `No Data` categorization on facets

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#752]
Some facets respond to the `No Data` label and some do not.

For example, if you search at `availability`, you can see that it says `no data` with a count in the facet, but when I search Diagnosis it is an empty facets with no text in them:

Also, when a field has data, the `No Data` tag does not always appear
(https://p.kfdrc.org/s/7k)

<img width="314" alt="screen shot 2018-09-08 at 4 15 10 pm" src="https://user-images.githubusercontent.com/15824252/45258254-839c9e80-b382-11e8-8905-c13f5beafc82.png">

**Analysis:**
This happens when there is nested data and the parent data has no structure so the nested object is never create.  Elasticsearch cannot perform aggregation counts on _missing_ on fields that do not exist. 

**Solution:**
The ETL will create empty blocks of designated nested data objects. 
Specs: https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/748027905/ETL+Calculations#ETLCalculations-NoDataFacetValue

**Comment by andricDu** [comment]
I'm leaning towards fixing this with an ETL task. I have a very similar example I can go over in ICGC.

**Comment by rosibaj** [comment]
@joneubank I updated the specs and this ticket, and have assigned this ticket to you.   I will move back to Ready for Implementation as well so you can pick it up after you finish anything current!
