### ISSUE TITLE
Affected Status/Participant.Diagnosis Category are not showing up correctly

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#753]
- Both fields are present in the released indices : Release `re_we2pyzdp`
- Fields alternately appear/don't appear in places.  For example: 
     > I can see `affected_status` in afv, but not arranger admin
     > I can see `diagnosis_category` in arranger admin, but not the afv

**Comment by hlminh2000** [comment]
I think we can close this now?
