### ISSUE TITLE
Advanced Facet View filter slider does not work for decimals 

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#757]
![Screen Shot 2018-09-08 at 5.17.11 PM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/93762a32-6d3b-4b13-8e0b-c05a797e4b05)

**Comment by hlminh2000** [comment]
@rosibaj here's a QA preview link: :) https://5ba2cfd373f2cf7e1c522b07--kf-qa-portal.netlify.com/

Needed back-end support as well so I re-deployed QA arranger too.
Also added the dropdown for the type, it was too risky to leave it as an input as we can accidentally corrupt the data :P

**Comment by rosibaj** [comment]
@hlminh2000 This looks great - we can deploy forward

**Comment by rosibaj** [comment]
Check on prod - this is working now!
