### ISSUE TITLE
Facets are not filtering themself

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#766]
**Query**: https://portal.kidsfirstdrc.org/search/file?sqon=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22participants.diagnoses.diagnosis_category%22%2C%22value%22%3A%5B%22Structural%20Birth%20Defect%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22participants.diagnoses.source_text_diagnosis%22%2C%22value%22%3A%5B%22Medulloblastoma%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22participants.phenotype.hpo.source_text_phenotype%22%2C%22value%22%3A%5B%22Hydrocephalus%22%5D%7D%7D%5D%7D

**Dataservice**: http://kf-api-dataservice.kids-first.io/diagnoses?participant_id=PT_QZN7FZER

**Steps to reproduce:**
1. go to query
2. Click a Diagnosis (Source Text)
3. Click a Diagnosis Category one by one until you get 0 results 

**Issue**:  The `Diagnosis Category` field is not filtering itself when the Diagnosis (Source Text) is being selected ( or vice-versa).  This means that impossible combinations are being allowed in the facet selection.

**Comment by andricDu** [comment]
```
{"data":{"file":{"extended":[{"field":"participants.biospecimens.source_text_tissue_type","type":"keyword","displayName":"Tissue Type (Source Text)","active":false,"isArray":false,"primaryKey":false,"quickSearchEnabled":false,"unit":null,"displayValues":{}},{"field":"participants.study.external_id","type":"id","displayName":"Study External ID","active":false,"isArray":false,"primaryKey":false,"quickSearchEnabled":false,"unit":null,"displayValues":{}},{"field":"participants.diagnoses.diagnosis_category","type":"keyword","displayName":"Diagnosis Category","active":false,"isArray":false,"primaryKey":false,"quickSearchEnabled":false,"unit":null,"displayValues":{}},{"field":"participants.diagnoses.source_text_diagnosis","type":"keyword","displayName":"Diagnosis (Source Text)","active":false,"isArray":false,"primaryKey":false,"quickSearchEnabled":false,"unit":null,"displayValues":{}},{"field":"participants.gender","type":"keyword","displayName":"Gender","active":false,"isArray":false,"primaryKey":false,"quickSearchEnabled":false,"unit":null,"displayValues":{}},{"field":"participants.is_proband","type":"boolean","displayName":"Proband","active":false,"isArray":false,"primaryKey":false,"quickSearchEnabled":false,"unit":null,"displayValues":{"true":"Yes","false":"No"}},{"field":"participants.family.family_compositions.composition","type":"keyword","displayName":"Family Composition","active":false,"isArray":false,"primaryKey":false,"quickSearchEnabled":false,"unit":null,"displayValues":{}},{"field":"participants.study.short_name","type":"keyword","displayName":"Study Name","active":false,"isArray":false,"primaryKey":false,"quickSearchEnabled":false,"unit":null,"displayValues":{}},{"field":"participants.race","type":"keyword","displayName":"Race","active":false,"isArray":false,"primaryKey":false,"quickSearchEnabled":false,"unit":null,"displayValues":{}}],"aggregations":{"participants__study__short_name":{"buckets":[]},"participants__diagnoses__diagnosis_category":{"buckets":[{"doc_count":1,"key_as_string":null,"key":"Cancer"},{"doc_count":1,"key_as_string":null,"key":"Other"}]},"participants__diagnoses__source_text_diagnosis":{"buckets":[{"doc_count":1,"key_as_string":null,"key":"Ependymoma"},{"doc_count":1,"key_as_string":null,"key":"Other medical conditions NOS"}]},"participants__family__family_compositions__composition":{"buckets":[]},"participants__is_proband":{"buckets":[]},"participants__gender":{"buckets":[]},"participants__race":{"buckets":[]},"participants__biospecimens__source_text_tissue_type":{"buckets":[]},"participants__study__external_id":{"buckets":[]}}}}}

```

**Comment by rosibaj** [comment]
For reference: this issue was addressed here as well: https://github.com/kids-first/kf-portal-ui/issues/488

**Comment by hlminh2000** [comment]
I am very confused how this got resolved, but just re-deploying arranger fixed this problem... I also added a few things to the `/status` endpoint of kf-arranger so we can tell which version of arranger core it is running, and also a few logs in the core so we have some queries to try running against ES if we see this happening again.

**Comment by rosibaj** [comment]
Closing as this does not appear to be happening on prod anymore
