### ISSUE TITLE
User Login Issues

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#776]
When a user has Third-Party Cookies disabled in Chrome they are not able to login with Google Sign-In.

**Steps to reproduce:** 
1. Go to Chrome settings and disable third-party cookies
2. Attempt to log in to the production portal 
3. The Login with Google button will be blocked

<img width="627" alt="screen shot 2018-09-12 at 10 36 42 am" src="https://user-images.githubusercontent.com/15824252/45435731-1ee18c80-b67f-11e8-975d-2310b195038f.png">

There are 2 options:
1. Request users who have disabled third-party data in a toaster
2.  Implement server-side OAuth 2.0 flows

*Google Developer documentation:* https://developers.google.com/identity/sign-in/web/troubleshooting 

**We want to move forward with:** 
Before implementing a technical solution, we will warn users that they are disabled. 

**1. When user can't login with Google (3rd party cookies are disabled)**
Mockup in Zeplin: https://zpl.io/VqwNJ9N

![screen shot 2018-09-13 at 2 49 04 pm](https://user-images.githubusercontent.com/18424138/45509012-5a09bb80-b764-11e8-8a29-2601d6e8781f.png)

**2. When user can't login with Facebook (ad blocker issue)**
Zeplin: https://zpl.io/aNoeJ09
![screen shot 2018-09-13 at 3 11 44 pm](https://user-images.githubusercontent.com/18424138/45510146-5b88b300-b767-11e8-87b1-d9738e80ce5b.png)

**3. Other login issues when reason is unknown**
Contact us  - opens in a new window: https://kidsfirstdrc.org/contact/
Zeplin: https://zpl.io/VQEkXEx

![screen shot 2018-09-13 at 2 58 59 pm](https://user-images.githubusercontent.com/18424138/45509470-a73a5d00-b765-11e8-91b0-555887a6982f.png)

**Comment by rosibaj** [comment]
Decided in planning:   Not with pursuing technically, but we can implement a design to alert users.

**Comment by kcullion** [comment]
@rosibaj @bdolly I think we can change the tooltip for the locks to read: "File is locked. Click the lock to request access." and then the lock can be programmed to link to the correct "Applying for Access" link from the website study page: https://kidsfirstdrc.org/support/studies-and-access/.

Mockup:
![04 kf-file-repository-lock-hover](https://user-images.githubusercontent.com/18424138/45493345-7e51a200-b73c-11e8-9158-811e87d5253e.jpg)

This is consistent with what I've been doing on the file entity page.  If the user has access to the file, they get the download button on the entity page:
![screen shot 2018-09-13 at 10 06 05 am](https://user-images.githubusercontent.com/18424138/45493401-a5a86f00-b73c-11e8-85fb-6ead698e3229.png)

And if they don't have access to the file, they get the locked message with a link to apply for access:
![screen shot 2018-09-13 at 10 06 40 am](https://user-images.githubusercontent.com/18424138/45493428-b8bb3f00-b73c-11e8-98e7-d16240a8d780.png)

**Comment by kcullion** [comment]
@rosibaj mockup is posted above

**Comment by ciaranschutte** [comment]
third party cookies can be blocked by going to chrome://settings/content/cookies and disabling them

adblocking can be checked by installing https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en and enabling the 'Annoyances' filter lists in settings

**Comment by rosibaj** [comment]
@ciaranschutte 
<img width="726" alt="screen shot 2018-09-24 at 1 37 00 pm" src="https://user-images.githubusercontent.com/15824252/45968438-f6eb1500-bffe-11e8-9370-45df4b54e0e5.png">

**Comment by ciaranschutte** [comment]
^ covered by this
![screen shot 2018-09-24 at 1 39 32 pm](https://user-images.githubusercontent.com/1486054/45968576-66610480-bfff-11e8-8b3f-5a4d94574250.png)
