### ISSUE TITLE
Connect to Cavatica is not pushing files

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#778]
*Steps to Reproduce*
1. Select Files
2. Click Copy to Cavatica Button
3. Check the project in Cavatica.  The files will not be there

The Response looks like this:
```
{"href":"https://cavatica-api.sbgenomics.com/v2/action/files/resolve_origin_ids","items":[]}
```
The endpoint tht returns Cavatica ids from KFIds is returning an empty array.

**Comment by hlminh2000** [comment]
Issue identified as being `kf_id` being used to identify files to Cavatica instead of `latest_did`. We also encountered the requirement that users' Cavatica accounts have to be connected with gen3 indirectly through eRA account.

**Comment by rosibaj** [comment]
Tested on Production - the file successfullt transfer to Cavatica.  We will address the Gen3 connection issue in another ticket!  thanks @hlminh2000 !!
