### ISSUE TITLE
Unit tests for the ETL

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#779]
As a developer, I need unit tests for the code I am working on, so that I can find errors more easily.

## Acceptance criteria
- Add unit tests.

## Discussion
Original title: Input/output test fixtures

- Add tests to the ETL so that when i t runs we can debug better

**Comment by joneubank** [comment]
Create test to run ETL end-to-end and verify output
- Run based on input data that matches expected format of dataservice content
- Input data can have a small dataset (1 file, 1 participant to start)
- Output into embedded ES
- Validate ES index mapping is exact match (no extra fields, no missing fields)
- Validate output content (number of files, participant mapping, familly mappings - need to enumerate entire list of criteria)
