### ISSUE TITLE
Refine Beta website header

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#78]
All pages:
- [x] Use correct branding images and spacing as per spec

Join Kids First page (http://beta.portal.kids-first.io/join)
- [x] Logo, no page links
- [x] same space and sizing in zepplin link below
(before starting this ticket, check for updated header/wizard specs)

All other pages (logged in) :
- [x] Dashboard link, File Repo link, and user profile link should be visible when logged in

- Do not implement search or language dropdown or my network
Spec link: https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5a69ff3de0f4923ee24d2304

**Comment by cy** [comment]
can't find the link pr button https://github.com/kids-first/kf-portal-ui/pull/114
