### ISSUE TITLE
ETL Deploy Spark Cluster

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#780]
- Change to ElasticMapReduce 
- Update the URL in the ETL
- Update terraform scripts for DevOps

**Comment by andricDu** [comment]
For devops:
- Use bootstrap actions for EMR cluster to do deployment of KPETS
  - Implies uploading of scripts to S3

For development:
- Switch from docker running of ETL+Spark to using spark-submit to submit ETL jar for execution on  the cluster

**Comment by andricDu** [comment]
[awsemr.pdf](https://github.com/kids-first/kf-portal-ui/files/2466138/awsemr.pdf)

**Comment by rosibaj** [comment]
@andricDu Can e we close this ticket?
