### ISSUE TITLE
Create an alert in non-chrome/firefox browsers

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#784]
For users in non-chrome/firefox create an altert that the best experience is in CHROME or FIREFOX

*Mockups:*
Zeplin: https://zpl.io/aBNLJZK

Links: open in a new window to download these browsers:
https://www.google.com/chrome/
https://www.mozilla.org/en-US/firefox/new/

![screen shot 2018-09-13 at 3 05 59 pm](https://user-images.githubusercontent.com/18424138/45509806-89b9c300-b766-11e8-8f24-7fbb22a2ecd9.png)

**Comment by denis-crsj** [comment]
Closing issue. Details transferred to the Google Sheet file : https://docs.google.com/spreadsheets/d/1U1JQZEBEMTP_07PngrmNh8rzbZICTX87Fe_2fEetAbI/edit#gid=0
