### ISSUE TITLE
Spelling issues

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#792]
- [x] change this to `Resources`
![Screen Shot 2018-09-24 at 8.20.13 AM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/ac92bf11-9c1a-45d9-bf44-31457de155a8)

- [x] change this to `ORCHID ID` (all capitol).  Its in 2 spots: When nothing is filled in, and on the field label

![Screen Shot 2018-09-24 at 8.21.55 AM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/f8d25bfc-dd68-4d86-8ef0-ce2ec6a73489)

![Screen Shot 2018-09-24 at 8.21.25 AM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/c3f7c921-14ed-41b4-b18e-c64d471ee715)

**Comment by ciaranschutte** [comment]
@rosibaj https://5ba8e94db312745e19400969--kf-qa-portal.netlify.com

**Comment by allisonheath** [comment]
There's no `H` In ORCID... @rosibaj

**Comment by rosibaj** [comment]
@allisonheath My cold is coming to haunnnnnt me.  @ciaranschutte As Allison has so thankfully pointed out, I made a spelling mistake ontop of the original spelling mistake.  Im so sorry!!!! Do you mind adjusting the second text to ```ORCID ID``` (no H)

**Comment by ciaranschutte** [comment]
@rosibaj no probs at all. feel better!
