### ISSUE TITLE
Adjust Clinical Download 

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#795]
**The Clinical Download is not to spec:**

https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/383156225/Download+Clinical+and+Biospecimen+data

The current columns are:
![Screen Shot 2018-09-24 at 9.57.53 AM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/8c0b40bc-e2a0-462f-a3da-3ac027438e04)

**The columns should be:** 
Participant ID |Participant External ID| Father ID | Mother ID | Family ID| Family External ID| Is Proband | Other relationships | Study Name  | Study External ID |Gender | Race | Ethnicity | Observed Phenotypes | Non observed Phenotypes | Diagnosis |Diagnosis External ID|<other diagnosis data>

**FIELDS:** 
<participant.kf_id> |<participant.external_id> | <participant.father_id> | <participant.mother_KF_id>| <participant.family_id> |<participant.family.external_id> | <participant.is_proband> | <list of relationships with other participants except father and mother>|<participant.study.name> |<study.external_id> |<participant.gender> | <participant.race> | <participant.ethnicity> | <participant.hpo_phenotypes_observed> | <participant.hpo_phenotypes_not_observed> | <participant.diagnoses.diagnosis>|| <participant.diagnoses.external_id>|  <follow with ALL DIAGNOSIS FIELDS>
 --> these should include these fields in this order:
- source_text_diagnosis

- age_at_event_days
- diagnosis_category
- icd_id_diagnosis
- mondo_id_diagnosis
- ncit_id_diagnosis
- source_text_tumor_location
- spatial_descriptor
- uberon_id_tumor_location

**NOTE:**
If a participant has N diagnoses:
repeat all previous information. e.g.: if the participant has 2 diagnoses, this participant will be displayed on 2 rows: 1 row for diagnosis 1, the other row for diagnosis 2 >> studies, parents, demographic, phenotype information is repeated.
Order of the rows: "Age at event days" >> from the highest number to lowest (meaning starting from most recent diagnosis)

**Comment by ciaranschutte** [comment]
@rosibaj https://5bacbb97c6aed6029ad54fcc--kf-qa-portal.netlify.com/

**Comment by rosibaj** [comment]
@ciaranschutte Sorry for the very long delay in review 😬 Feel free to harrass me more!!! Where are the headers on the TSV coming from?  They seemto be adding some stuff to the display name: 

>Kf Id 
>External Id 
> Family Father Id
> Family Mother Id 
> family.family_id    ------> Should be Family Id
> Is Proband 
> Study Name 
> Study External Id 
> Gender 
> Race  
> Ethnicity 
> Phenotype Hpo Hpo Phenotype Observed   ------> Should be Hpo Phenotype Observed
> Phenotype Hpo Hpo Phenotype Not Observed   ------> Should be Hpo Phenotype Not Observed
> Diagnoses Diagnosis 
> Diagnoses External Id 
> Diagnoses Age At Event Days 
> Diagnosis Category 
> Diagnoses Mondo Id Diagnosis  ------> Should be Mondo Id Diagnosis 
> Diagnoses Ncit Id Diagnosis ------> Should be Ncit Id Diagnosis
> Diagnoses Source Text Diagnosis ------> Should be Source Text Diagnosis
> Diagnoses Source Text Tumor Location  ------> Should be Source Text Tumor Location
> Diagnoses Uberon Id Tumor Location------> Should be Uberon Id Tumor Location

**Comment by ciaranschutte** [comment]
@rosibaj 
So first thing, I just want to make sure I'm using the right fields, they don't match up exactly with what's in the ticket but they're the only ones that make sense from the columns coming back I think.
``` 'kf_id',
            'external_id',
            'family.father_id',
            'family.mother_id',
            'family.family_id',
            'family.external_id',
            'is_proband',
            'study.name',
            'study.external_id',
            'gender',
            'race',
            'ethnicity',
            'phenotype.hpo.hpo_phenotype_observed',
            'phenotype.hpo.hpo_phenotype_not_observed',
            'diagnoses.diagnosis',
            'diagnoses.external_id',
            'diagnoses.age_at_event_days',
            'diagnoses.diagnosis_category',
            'diagnoses.idc_id_diagnosis',
            'diagnoses.mondo_id_diagnosis',
            'diagnoses.ncit_id_diagnosis',
            'diagnoses.source_text_diagnosis',
            'diagnoses.source_text_tumor_location',
            'diagnoses.spatial_scriptor',
            'diagnoses.uberon_id_tumor_location',```

**Comment by rosibaj** [comment]
@ciaranschutte I see - the shape has changes since these original specs. The fields you have listed *are* correct.  There are couple adjustments (noted below) but that is the correct set.    The issue I was highlighted what that the column headings (or field names at the top of the excel) were inconsistent in display.  Is that coming from Arranger and it needs to be fixed there? 

``` 'kf_id',
            'external_id',
            'family.father_id',
            'family.mother_id',
            'family.family_id',
            'family.external_id',
            'is_proband',
            'study.name',
            'study.external_id',
            'gender',
            'race',
            'ethnicity',
            'phenotype.hpo_phenotype_observed',    ///this will be updated this morning (.hpo.) removed
            'phenotype.hpo.hpo_phenotype_not_observed',   ///this will be updated this morning (.hpo.) removed
            'diagnoses.diagnosis',
            'diagnoses.external_id',
            'diagnoses.age_at_event_days',
            'diagnoses.diagnosis_category',
            'diagnoses.idc_id_diagnosis',   /// there is a tyoe here: "icd_id_diagnosis": {
            'diagnoses.mondo_id_diagnosis',
            'diagnoses.ncit_id_diagnosis',
            'diagnoses.source_text_diagnosis',
            'diagnoses.source_text_tumor_location',
            'diagnoses.spatial_scriptor',
            'diagnoses.uberon_id_tumor_location',```

**Comment by ciaranschutte** [comment]
@rosibaj  Great thank you! yup working on that now... just making sure step 1 is 100% correct before changing headers

**Comment by jecos** [comment]
Related to #2031
