### ISSUE TITLE
Add Project Description to Cavatica Create Project  

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#801]
When a create project request is submitted to Cavatica, the project is created with no description.  We would like this to be fixed!  It would be nice for a user to come into a cavatica with some context of the data that they sent over.

The template description is found in a markdown file that needs be be submitted with the API request on create project.  (**Ask Rosi for Markdown file for description as it cannot be imported to this github ticket**)

4. When the user saves their new project + billing group, it is added to the top of the table, and is auto-selected:
https://invis.io/MQFHWABDK9Y#/285364389_16e-KF-Cavatica-Connected-Create-Project3
ZEPLIN: https://zpl.io/VKN7ykq

**API documentation:** 
Creating/adding a description to a project:
http://docs.cavatica.org/docs/create-a-new-project

**Comment by hlminh2000** [comment]
@rosibaj here's the prod preview link: https://5bb37c2267610c536e38eb7e--prod-kidsfirst-portal.netlify.com/

**Comment by rosibaj** [comment]
@hlminh2000 2 things:

1) It looks like the portal contact link has changed in the last line: (https://kidsfirstdrc.org/contact/g) --> (https://kidsfirstdrc.org/contact/).

2)There is a *slight* amount of formatting that I forgot about :p.  Are we able to format one of the links in the markdown? Where it says: -   Start [Analyzing your Kids-First Data](https://cavatica.sbgenomics.com/u/<username>/<project-name>/files/), can we input the <<Cavatica_username>> and the <<newly_created_project_name>> ?

For example, my generated link would look like this: 
https://cavatica.sbgenomics.com/u/rosita_bajari/test-project-description/files/

**Comment by hlminh2000** [comment]
@rosibaj updated prod preview link addressing the above points :) : https://5bb4e77ce39e7c2f5bde5a4c--prod-kidsfirst-portal.netlify.com/

**Comment by rosibaj** [comment]
@hlminh2000 this looks great!!!! This is good to go!

**Comment by rosibaj** [comment]
@mattions Description is not populating on prod as discussed!

**Comment by mattions** [comment]
@rosibaj fantastic! I've just tested and it works!

(I guess you wanted to write _now_  not _not :) )
