### ISSUE TITLE
Update text of Cavatica button

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#802]
Update the button text to:

- ```Analyze Files in Cavatica```

![screen shot 2018-12-04 at 2 45 19 pm](https://user-images.githubusercontent.com/18424138/49468579-45711880-f7d3-11e8-8407-d3ad690352a4.png)

**Comment by mattions** [comment]
I've read the discussion on slack on this. Let me make clear my point of view.

We want to make sure that people do understand two things:

1) The files are not replicated on Cavatica. I mean ultimately these files are on a S3 bucket where we all point to
2) They won't have to pay storage cost of this files on Cavatica, 'cause it's already cover by the DRC

Now, about the messaging:

- **Copy** do convey the message that files duplicated
- **Link** is the one that nails exactly what we are doing, however it gets complicated from the people point of view to understand

Maybe, we could live copy, and have below a little explanation saying the file do get linked, and there is no duplication. Maybe there is a better word for that.

What do you guys think?

**Comment by rosibaj** [comment]
@mattions Thanks for the feedback.  @kcullion @christinayung What do you think about adding a (?) about tooltip for the Cavatica button that addresses Michelles point about no duplication and no cost to user?

**Comment by christinayung** [comment]
Tool tip explaining there's no duplication of data is good.  I'll leave "no cost" out as this goes into a longer explanation of costs of storage vs compute.

**Comment by kcullion** [comment]
@rosibaj @christinayung @mattions 

What do you think of this revision for the actions panel?
![screen shot 2018-10-01 at 1 58 15 pm](https://user-images.githubusercontent.com/18424138/46306380-24493d00-c582-11e8-8610-27a660bd3c1c.png)

**Comment by kcullion** [comment]
Preference from Vincent - include a "?" with action description.
Rosi and I discussed, we changed the button label to "Analyze files in Cavatica"

**Comment by rosibaj** [comment]
Closing as new designs will not include the action panel - any button updates will be included there
