### ISSUE TITLE
Filter table: Should be able to filter %key term%

### ISSUE THREAD

**Issue by Fgerthoffert** [kids-first/kf-portal-ui#808]
Feedback from Vincent, the table filter only works on exact matches:
- It should work on partial matches as well
- It should be case insensitive
This is an arranger ticket

This is only to update current behavior, need further discussion on overall search behavior.

**Result of discussion with dev team and PO's Christina/Vincent:**

**Analysis**: ES requires analyzers on fields in order to do multimatch (case insensitive / partial match).  This means that for the table search to be general, the index must have this defined.  This is not a generic process, as the index generator would need to make sure this is labelled and thus should not be part of Arranger. Also, in order to be across the pagination of the table, the search must be serverside, which means it must be part of the query.

**Possible Solution(s):**
**1.** Leave the current server-side implementation with exact match.  
         - The cons to this approach are that boolean fields are not searchable this way, and partial matches are not possible, and users confuse it as a "google" search.
**2.** Allow client-side UI search
         - The cons to this approach are that it can only search the first page of records, 
**3.** Remove the table search 
         - The cons to this approach are that there is not a free text search, but that no users are confused.  We can pursue ideas/designs on how to provide free text search in another manner. 

Decision: Solution (3): Remove the table search was chosen.

**Comment by hlminh2000** [comment]
After some investigation, this feature would require an update to our index mapping in Elasticsearch. Further, implementation is arguably very data dependent, so we may want to consider having this away from arranger core. I don't want to make these decisions in silo so I think this is worth a discussion.

@Fgerthoffert would be great if you could help adjust this ticket accordingly :)

**Comment by rosibaj** [comment]
@hlminh2000 I have updated the ticket with the discussion/decision above.  There are 2 options; hide on KF or strip out of arranger; If this issue is revisited, hiding is a quick way to backtrack :), however we might want to do it right.  Thoughts?

**Comment by rosibaj** [comment]
Closing as this was removed from portal
