### ISSUE TITLE
Only HPO related fields should be under HPO

### ISSUE THREAD

**Issue by Fgerthoffert** [kids-first/kf-portal-ui#810]
Only HPO related fields should be under HPO. Move up all the other fields outside of HPO and under Phenotype.
Replace Hpo with HPO and correct the typo in Hpo Phenotype Observed

![Screen Shot 2018-09-28 at 1.12.09 PM.png](https://images.zenhubusercontent.com/58f9764651aa2c30577c0706/489e6128-0c73-4d25-8483-edab7b922143)

**Comment by rosibaj** [comment]
Issue moved to [kids-first/kf-es-model #41](https://github.com/kids-first/kf-es-model/issues/41) via [**ZenHub**](https://www.zenhub.com/)
