### ISSUE TITLE
Optimize the space used by the footer

### ISSUE THREAD

**Issue by Fgerthoffert** [kids-first/kf-portal-ui#812]
- [x] Reduce height of the footer (~50-60px)
- [x] Put the copy on one line to allow for shorter height

See mockup: https://zpl.io/bev8YdN

![screen shot 2018-10-01 at 2 19 53 pm](https://user-images.githubusercontent.com/18424138/46307513-1e089000-c585-11e8-9780-9aed15087bdc.png)

**Comment by harryc9** [comment]
Hi! I would like to try this one out. Is it taken?

**Comment by ciaranschutte** [comment]
zenhub connect not working: https://github.com/kids-first/kf-portal-ui/pull/829
