### ISSUE TITLE
Improve scrolling behavior - so footer is hidden on first load

### ISSUE THREAD

**Issue by Fgerthoffert** [kids-first/kf-portal-ui#813]
Vincent and Christina agreed: 

Let's make the scrolling be similar to HCMI except the table isn't scrollable. 

So the user would scroll the facets and the page separately and on the right side they would scroll past the table to the footer. Goal: see as much of the data on the screen at once (and have to scroll to the footer).

**Comment by rosibaj** [comment]
@kcullion sure this is already in the sprint.  @hlminh2000 you can grab this whenever you need your next ticket!

**Comment by ciaranschutte** [comment]
@rosibaj  https://5bc0a1743813f0510999ecec--kf-qa-portal.netlify.com/

**Comment by kcullion** [comment]
@rosibaj @ciaranschutte talked to Ciaran about this and explained that the table shouldn't be scrollable (should show all 20 rows and the user scrolls it with the page). Also the right actions panel shouldn't be scrollable (part of another ticket but I'll try to find it)

**Comment by ciaranschutte** [comment]
@kcullion @rosibaj https://5bc49448dd28ef733e485e20--kf-qa-portal.netlify.com/ updated link :)

**Comment by rosibaj** [comment]
@ciaranschutte @kcullion sounds good.  @ciaranschutte can you go ahead and put in qa when you apply kims suggestion?

**Comment by ciaranschutte** [comment]
@rosibaj yup I will put it into QA and post the link in this thread

**Comment by rosibaj** [comment]
@ciaranschutte i meant the QA QA...(https://kf-qa-portal.netlify.com/) not a netlify link.  Is that what you meant?

**Comment by ciaranschutte** [comment]
@rosibaj ohhh the QA QA! Not what I meant. I understand. Will do.

**Comment by rosibaj** [comment]
https://github.com/kids-first/user-feedback/issues/98
