### ISSUE TITLE
Make the facets panel width user-resizable

### ISSUE THREAD

**Issue by Fgerthoffert** [kids-first/kf-portal-ui#814]
Add the ability to change the size, or collapse the left facet panel. 

As examples:
- HCMI has the abiltiy to expand (https://hcmi.netlify.com/) 
- GDC has the ability to collapse (https://portal.gdc.cancer.gov/exploration) 

Mockup:
Zeplin: https://zpl.io/bev8YdN
Similar to HCMI, the crosshair icon will show up when the user hovers over the edges of the panels (both facet and action panels).
The title area of the facet panel will change slightly to match the collapsible style of the action panel.

![screen shot 2018-12-04 at 11 14 54 am](https://user-images.githubusercontent.com/18424138/49455854-e18c2700-f7b5-11e8-9dea-b630a60c2c38.png)

**Comment by rosibaj** [comment]
QA - facet can collapse, but still not able to adjust the size of the panel (larger or smaller)

**Comment by rosibaj** [comment]
@nyanofthemoon Vincent wants to go ahead and deploy with JUST the collapse - this looks fine in preview - can you merge to deploy?

**Comment by nyanofthemoon** [comment]
@rosi I merged this into the `vr` branch (preview). Do I need to merge this somewhere else as well? I'll ask in standup this morning.

**Comment by nyanofthemoon** [comment]
@rosibaj @hlminh2000 PR to merge from `vr` to `next` https://github.com/kids-first/kf-portal-ui/pull/1063

**Comment by rosibaj** [comment]
tested on prod - working as expected.  Nice work @nyanofthemoon !
