### ISSUE TITLE
File Repository: Improve per-column facet-like filtering in the results table

### ISSUE THREAD

**Issue by Fgerthoffert** [kids-first/kf-portal-ui#815]
As a user, I want to be able to filter results by using per-column criterias.

## Acceptance criterias
Consistent with the table filters in the cohort builder (https://github.com/kids-first/kf-portal-ui/issues/1203)
- [ ] All columns will get a grey filter icon that will open filtering options
- [ ] Filter option dropdown also consists of a sorting option (Ascending/Descending)
- [ ] All column filters are added to the query scone when applied by the user.
- [ ] The columns that are also in the facet panel will also get filtered.
- [ ] When a column filter is applied, the filter icon turns teal for that column

## Mockups
- [ ] For variables that are checkboxes:
Zeplin: https://zpl.io/blZvkov
![screen shot 2019-02-13 at 3 09 39 pm](https://user-images.githubusercontent.com/18424138/52740845-f9480e80-2fa1-11e9-9478-e41e989cb793.png)

- [ ] For Boolean variables:
Zeplin: https://zpl.io/VxL8lD3
![screen shot 2019-02-13 at 4 00 25 pm](https://user-images.githubusercontent.com/18424138/52743690-98700480-2fa8-11e9-98f8-23e10fe336df.png)

- [ ] For continuous variables:
Zeplin: https://zpl.io/2ZkGnnG
![screen shot 2019-02-13 at 4 01 58 pm](https://user-images.githubusercontent.com/18424138/52743750-bfc6d180-2fa8-11e9-9ec6-9b7325f2b05b.png)

- [ ] For continuous variables (dropdown open):
![screen shot 2019-02-13 at 4 03 03 pm](https://user-images.githubusercontent.com/18424138/52743795-db31dc80-2fa8-11e9-8e75-1ff09cef7f0b.png)

- [ ] Continuous variable applied to the scone (change the format so it's more readable)
Zeplin:https://zpl.io/bWgYWv7
![screen shot 2018-12-19 at 12 05 55 pm](https://user-images.githubusercontent.com/18424138/50235701-8007b300-0386-11e9-949e-d8c49bcc26fe.png)

**Comment by rosibaj** [comment]
@kcullion Can you please update this with the new slider mockup with the 2 boxes?
