### ISSUE TITLE
Facets: When clicking on the magnifier, automatically place the cursor in the text box

### ISSUE THREAD

**Issue by Fgerthoffert** [kids-first/kf-portal-ui#816]

**Comment by ciaranschutte** [comment]
In review. Adds 'autofocus' attribute only.

**Comment by ciaranschutte** [comment]
@rosibaj https://master--kf-qa-portal.netlify.com/search/file

Merged already but just in case you want to verify :)

**Comment by rosibaj** [comment]
@ciaranschutte thanks for the heads up - this looks great!
