### ISSUE TITLE
Search by HPO terms and not just by ID for Observed phenotypes

### ISSUE THREAD

**Issue by Fgerthoffert** [kids-first/kf-portal-ui#817]
- Need to be able to search by HPO terms and not just by ID for Observed phenotypes. 
- Just enabling this would increase a lot the value of the data harmonization effort. 
- 

Mockups:
1. Addition of Phenotype observed and not observed facets to the panel
Zeplin: https://zpl.io/bev8YdN
![screen shot 2018-10-01 at 3 55 58 pm](https://user-images.githubusercontent.com/18424138/46312367-ddb00e80-c592-11e8-8ab9-1b5d9fc1b52e.png)

2. Search dropdown for phenotype facets:
Zeplin: https://zpl.io/am4X5KK
<img width="301" alt="screen shot 2018-10-05 at 5 10 19 pm" src="https://user-images.githubusercontent.com/18424138/46560410-aa86bb80-c8c1-11e8-9edf-4635dfaefa4d.png">

**Comment by vferretti** [comment]
Concatenate term and ID into a single field and facet. e.g cleft (HP939393)

**Comment by joneubank** [comment]
The `hpoObservedText` field will now have an array of strings with the format `s"${text} (${hpo_id})"`

Example: `Dactylphobia (HP:00001234)`
