### ISSUE TITLE
Save query and view my saved queries in my user dashboard

### ISSUE THREAD

**Issue by phuongmy** [kids-first/kf-portal-ui#82]
Provide UI to:
- save a query from File Repo (with suggested name corresponding to selected filters + toaster)
- view my saved queries in my user dashboard and related actions: view counts, rename, re-run query, delete

Note: notification system is out of scope.

Specifications and design available on this link:
https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/444956841/Share+and+save+query#Shareandsavequery-3.2Savequery

**Comment by cy** [comment]
dashboard stuff around saved query https://github.com/kids-first/kf-portal-ui/pull/122

**Comment by cy** [comment]
missing `rename`
