### ISSUE TITLE
Add # Files to Facet UI

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#820]
- Users are confused by the number; They do not understand if it means the number of files or the number of participants
- To make it more clear, we will add the **# Files** to the facet column header 

Mockup:
Zeplin: https://zpl.io/bev8YdN

![screen shot 2018-10-01 at 2 15 40 pm](https://user-images.githubusercontent.com/18424138/46307314-8f940e80-c584-11e8-98ed-6fcef8ed3ef3.png)

**Comment by hlminh2000** [comment]
This is part of the 'TermAggs' component in @arranger/components

**Comment by rosibaj** [comment]
@nyanofthemoon Can you put this in VR branch or QA for testing!

**Comment by rosibaj** [comment]
@nyanofthemoon @hlminh2000 I checked this out and it looks great!!!!  Let's do the dev thing and get it deployed :)
