### ISSUE TITLE
Direct users to controlled access application

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#821]
- [x] Remove 2nd tooltip (icon-controlled-access) from popping up after extended hover
<img width="436" alt="screen shot 2018-09-30 at 11 42 02 pm" src="https://user-images.githubusercontent.com/15824252/46268765-7484b880-c50a-11e8-94eb-9ee944cd0393.png">

- [x] When users hover over the lock, change the tooltip and pointer to be clickable.  When the user clicks on the lock, it should direct them to the url ```https://kidsfirstdrc.org/support/studies-and-access/#applying-for-data-access```

- [x] Change the text to "File is locked. Click the lock to apply for access." Mockup in zeplin: https://zpl.io/bev8YdN

- [x] hover state for the lock: #CC3399

![screen shot 2018-10-01 at 2 08 44 pm](https://user-images.githubusercontent.com/18424138/46306903-86567200-c583-11e8-98e2-762ecc75e86b.png)

`src/components/FileRepo/customTableColumns.js` in `kf-portal-ui` should have everything needed for this

**Comment by rosibaj** [comment]
kids-first/user-feedback#81

**Comment by rosibaj** [comment]
@baileyckelly Can you confirm that the url links in the website are using study short name, per bullet point 2 in this ticket?

**Comment by baileyckelly** [comment]
Hi there - They are not currently using the study short name. They're currently using the investigators last name but I can change them to whatever we want. I was actually thinking of KF id for teh study - the SD # ... While unlikely, it is possible (and easy) to change short names. Can't ever change the SD #. Thoughts?

**Comment by rosibaj** [comment]
@baileyckelly The SD# works for me! Would that change be possible?

**Comment by nyanofthemoon** [comment]
@rosibaj A lot of noise for my newbie brain! Could you validate what was done for this already and what still needs to be done? It appears like a ticket that could potentially be out of date and I just wanted to be certain. :)

**Comment by rosibaj** [comment]
@nyanofthemoon I edited the top description this morning - the ticket description is the most up-to-date and accurate info!  If you want a walkthrough of the ticket, we can slack/bluejeans call if that helps!

**Comment by nyanofthemoon** [comment]
@rosibaj Thank you! On it.

**Comment by nyanofthemoon** [comment]
@rosibaj For `Remove 2nd tooltip (icon-controlled-access) from popping up after extended hover`, this issue also exists for any other Tooltip using one of our SVG icons. I will fix this one as part of the ticket, but please note that it may exist in other parts of the UI.

**Comment by nyanofthemoon** [comment]
@rosibaj For `When users hover over the lock, change the tooltip and pointer to be clickable.  When the user clicks on the lock, it should direct them to the url`,:

- is there a specific style to the link you would like to have (other than a regular link)?
- should it open in a new window or within the same window?

Please confirm. :)

**Comment by rosibaj** [comment]
@nyanofthemoon new window please ; Re the style, im not sure what you mean?

**Comment by rosibaj** [comment]
@nyanofthemoon is this available for test in a netlify link or environment?

**Comment by rosibaj** [comment]
@nyanofthemoon Can you update the font color to the blue to match the spec? 
![screen shot 2019-01-04 at 5 14 59 pm](https://user-images.githubusercontent.com/15824252/50713792-4ac8b980-1044-11e9-845d-fff99653d406.png)

**Comment by kcullion** [comment]
@nyanofthemoon the font info: 
 font-family: OpenSans;
 font-size: 12px;
color:#2B388F;
