### ISSUE TITLE
In all search textfields, add a small 'x' to clear content

### ISSUE THREAD

**Issue by Fgerthoffert** [kids-first/kf-portal-ui#823]
Please use a consistent icon for this.  Let's go with the one used in the file repo:
![screen shot 2018-10-01 at 2 29 21 pm](https://user-images.githubusercontent.com/18424138/46307984-6f654f00-c586-11e8-9ee5-a080e986e112.png)

- [x] Add the "x" functionality to all facet panel filter boxes:
![screen shot 2018-10-01 at 2 30 43 pm](https://user-images.githubusercontent.com/18424138/46308048-9b80d000-c586-11e8-89b0-3d8dce28e1b1.png)

- [x] Add the "x" functionality for the cavatica modal:
![screen shot 2018-10-01 at 2 37 56 pm](https://user-images.githubusercontent.com/18424138/46308442-a9832080-c587-11e8-9f56-f9e311af0c90.png)

- [x] Add the "x" functionality for the Research Interest search box:
![screen shot 2018-10-01 at 2 40 09 pm](https://user-images.githubusercontent.com/18424138/46308566-fa931480-c587-11e8-85bf-9c88f29f7b11.png)

- [x] Add the "x" functionality for the search location box in the profile basic info:
![screen shot 2018-10-01 at 2 45 09 pm](https://user-images.githubusercontent.com/18424138/46308815-9c1a6600-c588-11e8-8545-1fe5c7bef828.png)

- [x] modify the icon to the one in the file repo for all of the fields in "find me on"
![screen shot 2018-10-01 at 2 42 10 pm](https://user-images.githubusercontent.com/18424138/46308707-5b225180-c588-11e8-97c1-85157fe3de22.png)

**Comment by hlminh2000** [comment]
The `FilterInput` component from `/src/uikit/Input.js` should have this behaviour built-in, make sure components defined directly in the portal ui is using this first. 

As for arranger components, many accept an `InputComponent` prop, which expects any input that implements the same interface as the default react-DOM input, so `FilterInput` would work. If the component of interest does not accept such, Arranger should be updated.

**Comment by rosibaj** [comment]
@hlminh2000  i think that @lepsalex was working on this too - just want to make sure you guys connected and there was not double work!

**Comment by hlminh2000** [comment]
This is reviewed and deployed :)
