### ISSUE TITLE
Release # in footer not working

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#839]
The Prod release coordinator endpoint is not available on public ips. 

Portal on prod:
![Screen Shot 2018-10-10 at 2.00.28 PM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/b9579150-c891-4cd8-903a-819374014d01)

Portal on prod on OICR VPN:
<img width="478" alt="screen shot 2018-10-10 at 2 37 56 pm" src="https://user-images.githubusercontent.com/15824252/46758168-2d30c180-cc9a-11e8-9f7e-000b51641b86.png">

This ticket is blocked until the CHOP team makes the endpoint with the release number public or until the portal application can access the endpoint.  @dankolbman will be able to provide information about when that endpoint can/will be ready.

**Comment by aalex** [comment]
@dankolbman Is the endpoint to get the data release version number now active and publicly reachable?

**Comment by dankolbman** [comment]
@aalex the coordinator api is still whitelisted to specific ips for the moment.

**Comment by allisonheath** [comment]
@dankolbman do we have any associated tickets towards making it publicly accessible?

**Comment by dankolbman** [comment]
@allisonheath we don't. We have not yet scoped this out.

**Comment by aalex** [comment]
It seems like this is a duplicate of 
![image](https://user-images.githubusercontent.com/293677/57879033-7d9c6e80-77e9-11e9-9626-1331c16dff68.png) - there might be some new info there that makes this not blocked anymore.

**Comment by jecos** [comment]
Need to add authentication on release coordinator.
Blocked by https://github.com/kids-first/kf-api-release-coordinator/issues/172

**Comment by dankolbman** [comment]
The coordinator is now public for querying information about published releases including the latest version using both APIs:
[GraphQL API](https://kf-release-coord.kidsfirstdrc.org/graphql#query=query%20publicReleases%20%7B%0A%20%20allReleases(state%3A%22published%22%2C%20orderBy%3A%20%22-created_at%22)%20%7B%20%20%20%0A%20%20%20%20edges%20%7Bnode%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20kfId%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20version%0A%20%20%20%20%20%20state%0A%20%20%20%20%20%20description%0A%20%20%20%20%20%20studies%7B%0A%20%20%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%7D%0A%20%20%7D%0A%7D&operationName=publicReleases)
[REST API](https://kf-release-coord.kidsfirstdrc.org/releases?state=published)
