### ISSUE TITLE
Text search

### ISSUE THREAD

**Issue by hlminh2000** [kids-first/kf-portal-ui#858]
continuation of #811

Functional specifications:
- User can type exact matches or partial matches
- As a user types, fields should autocomplete results 

**Mockups:**
1. Participant and Biospecimen searches: https://zpl.io/blPv4qG
2. Participant search dropdown - uses brand icons instead of the circle+PA/BI: https://zpl.io/2ZzyYWG
3. File facet - search by file ID dropdown: https://zpl.io/VODgNBr
4. Upload ID modal;separate the text area and the upload options so they look more like two choices. Also, the results tabs should be hidden until the user actually enters any ids.: https://zpl.io/a8NzAQg

**Back-end:**
- Will need support from elasticsearch (analyzers)
- Decide whether this belongs in Arranger

**Comment by jecos** [comment]
Duplicate #1137
