### ISSUE TITLE
Update Login UI 

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#885]
- See the new design with vertical listing of all providers
Zeplin: https://zpl.io/blZM5QG
- Add LinkedIn as the first support provider for now; Even though there are other providers listed, those are not yet ready to be implemented

**Comment by kcullion** [comment]
@rosibaj do you mean vertical?

**Comment by rosibaj** [comment]
@kcullion yes, yes i do 🤦‍♂️

**Comment by kcullion** [comment]
After meeting with Vincent and Christina, the horizontal buttons were approved
