### ISSUE TITLE
Upload Id Enhancements 

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#888]
UI:
**File Repository:**

- [ ] fix text on query when facet is applied 
- [ ] fix text on query when the user uploads ids:
![screen shot 2018-10-18 at 1 34 35 pm](https://user-images.githubusercontent.com/18424138/47172882-9d62c700-d2da-11e8-8229-49654a139e2e.png)
- [x] Search dropdown: update the symbol for each entity type to be the icons for participant, biospecimen and file:
![screen shot 2018-10-18 at 1 39 51 pm](https://user-images.githubusercontent.com/18424138/47173156-56c19c80-d2db-11e8-979c-2812703b0010.png)

**Upload IDS modals**
- [x] fix text on upload modal title (specific for each entity type) eg. "Upload a List of Participant Identifiers"
- [x] fix text on upload modal - specific examples in the text area field for each entity type - so for Participants: "eg.  e.g. PT_XV43P6BV, PT_XV9MDYKR, PT_A35NHA2M, 4-73m, 6-32f"
- [x] Split the text area and upload buttons so they look like two options
![screen shot 2018-10-18 at 1 47 31 pm](https://user-images.githubusercontent.com/18424138/47173567-61306600-d2dc-11e8-8e39-1f61b7441eee.png)

- [x] hide the table until the user pastes in the text area or uploads a file - then show the table

**Comment by rosibaj** [comment]
https://github.com/kids-first/user-feedback/issues/95

**Comment by hlminh2000** [comment]
@rosibaj here's the QA preview link for the work except for the first 2 points, which would take some digging into Arranger so I want to look at them separately if possible
https://5bce1ed71f12b720cbcb1a90--kf-qa-portal.netlify.com/search/file

**Comment by rosibaj** [comment]
@hlminh2000 The other two points can be addressed separately. Made this ticket: https://github.com/kids-first/kf-portal-ui/issues/902 

Re: the UI facets- A couple of things: 
- [ ] File search is not working (it DOES work on prod) 
![screen shot 2018-10-23 at 12 35 48 pm](https://user-images.githubusercontent.com/15824252/47376431-96fc9280-d6c0-11e8-82d6-80367178b513.png)

- [ ] f i click away from the facet, the dropdown stays as i click other things. The dropdown should disappear.

![screen shot 2018-10-23 at 12 36 22 pm](https://user-images.githubusercontent.com/15824252/47376430-96fc9280-d6c0-11e8-8a2d-a01ff57acc1d.png)
