### ISSUE TITLE
OpenID Connect Button Styling

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#90]
[ ] Login OpenID buttons should be rounded, floating next to each other, with a #d4d6dd border.

Note:  Alex L had success stying the Gmail button for the Jupyter hub.  For difficulties, perhaps he could assist!

**Comment by Jephuff** [comment]
Have we confirmed we are allowed with google and facebooks terms of service? (and orchid/linkedin for future)

**Comment by rosibaj** [comment]
Good point @Jephuff  - I took a look at the documentation.  Orchid is pretty open, but LinkedIN, Google, Facebook all seem to have some preferences.  @kcullion Can you weigh in on this?

**Comment by kcullion** [comment]
Let's just use the standard buttons for linkedIN, Google and Facebook - well I think we have to abide by the brand guidelines :) Then we can match orchid to those

**Comment by rosibaj** [comment]
Design will be adjusted to reflect the standard styling for sign in connectors.  Closing this issue as it is not longer valid.
