### ISSUE TITLE
Update text on upload ids

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#902]
UI:
**File Repository:**

- [ ] fix text on query when facet is applied 
- [ ] fix text on query when the user uploads ids (changed to uploaded list instead of saved manifest):
![screen shot 2018-10-18 at 1 34 35 pm](https://user-images.githubusercontent.com/18424138/47172882-9d62c700-d2da-11e8-8229-49654a139e2e.png)

**Comment by nyanofthemoon** [comment]
https://github.com/kids-first/kf-portal-ui/pull/1029
