### ISSUE TITLE
Deactivate KF account

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#907]
@phuongmy commented on [Wed Feb 28 2018](https://github.com/kids-first/kf-internal-tracker/issues/62)

A user should be able to deactivate his KF account. 

See option in User profile - Accounts & Settings: https://invis.io/MQFHWABDK9Y#/276667049_24-KF-Researcher-Settings

*Specifications to be completed*
What is the impact? 
User is not searchable anymore? Can he still log in? How can he reactivate his account?
Can he change his open ID when reactivating?
What if he tries to go through the sign-up process after he had deactivated his account?
...

---

@allisonheath commented on [Wed Oct 24 2018](https://github.com/kids-first/kf-internal-tracker/issues/62#issuecomment-432884897)

@rosibaj we had talked about way back when! but closing as this is likely stale now?

---

@rosibaj commented on [Thu Oct 25 2018](https://github.com/kids-first/kf-internal-tracker/issues/62#issuecomment-433053841)

@allisonheath this is probably stale - do we still want to offer these options eventually though?

---

@allisonheath commented on [Thu Oct 25 2018](https://github.com/kids-first/kf-internal-tracker/issues/62#issuecomment-433058494)

I think so, if we could move it to the right place and close this one out that’d be great.

**Comment by aalex** [comment]
This backlog item is very similar to #1395. To keep things simpler, that other one has been prioritized, so we can close this one.
