### ISSUE TITLE
Update Studies chart following comments from the demo

### ISSUE THREAD

**Issue by Fgerthoffert** [kids-first/kf-portal-ui#916]
[ x ] - update interval
[ x ] - label axes
[ x ] - move legend to compensate for axes
[ x ] - onHover
[ x ] - onClick?
[ x ] - order by

Zeplin: https://zpl.io/blP74GD
![screen shot 2018-11-02 at 3 35 35 pm](https://user-images.githubusercontent.com/18424138/47936714-f6268800-deb4-11e8-96c6-9bf42aa7e7a2.png)

hover state: user can hover over each study graph row, it will highlight and show the hand cursor to indicate it's clickable - this will link to the file repo filtered on the study
Zeplin: https://zpl.io/VQ9nERm
![screen shot 2018-11-02 at 4 08 06 pm](https://user-images.githubusercontent.com/18424138/47938159-88308f80-deb9-11e8-869e-d08be47af920.png)

**Comment by ciaranschutte** [comment]
[ ] - update interval
[ ] - label axes
[ ] - move legend to compensate for axes

**Comment by ciaranschutte** [comment]
updating interval using library default for now. may need to change after demo feedback

**Comment by ciaranschutte** [comment]
Pending build issues
