### ISSUE TITLE
Global search: Index to support global search

### ISSUE THREAD

**Issue by Fgerthoffert** [kids-first/kf-portal-ui#917]
Developers need to search in an index in order to make a general search possible.

## Acceptance criteria
- A general search includes files, participants and users.

## Technical details
- Charlie has done a quick-search index containing the contents of the PDF files, and more fields can be added to it.
- For the users, Persona currently has MongoDB in its backend. (we would like to move towards PostgreSQL instead, ideally) - we might want to query Persona to search for users, or re-index it everyday.

**Comment by aalex** [comment]
We will probably need to index the users.
