### ISSUE TITLE
Top 10 Diagnosis Card

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#920]
- sort descending on graph
- show only the top 10 matching results

zeplin: https://zpl.io/blP74GD

![screen shot 2018-11-02 at 3 23 33 pm](https://user-images.githubusercontent.com/18424138/47936410-ebb7be80-deb3-11e8-8c52-ee853d001371.png)

**Comment by allisonheath** [comment]
Could we do this on MONDO field versus the diagnosis source text?

**Comment by rosibaj** [comment]
@allisonheath this us a mockup only - it would reference this field as per our previous discussions: https://github.com/kids-first/kf-portal-etl/issues/41 

Is this in line with your expectations?

**Comment by allisonheath** [comment]
Perfect thanks - just couldn't tell that looking at the ticket 👍

**Comment by ciaranschutte** [comment]
Pending build issues + live data
