### ISSUE TITLE
Cannot download biospecimens for a specific query

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#933]
For this query: https://p.kfdrc.org/s/139, when you download the biospecimen report it downloads blank.  It works with no query, and with other queries just fine. 

**Download Biospecimen results:** You get an empty file

**Expected Results:** Some biospecimens should download
- For example, the first file in this query `GF_8D6RCT3Z`  *has* a biospecimen with values attached in the index, but these are not in the downloaded file
```GET file_centric_sd_bhjxbdqk_re_9f2p3vrt/file_centric/GF_8D6RCT3Z ```
```http://kf-api-dataservice.kids-first.io/biospecimens/BS_QE7WAAKC ```

```        "biospecimens": [
          {
            "ncit_id_tissue_type": "NCIT:C8509",
            "genomic_files": [],
            "source_text_tumor_descriptor": "Progressive",
            "concentration_mg_per_ml": 0.031,
            "kf_id": "BS_QE7WAAKC",
            "analyte_type": "DNA",
            "ncit_id_anatomical_site": "NCIT:C12438",
            "source_text_tissue_type": "Tumor",
            "source_text_anatomical_site": "Central Nervous System",
            "consent_type": "GRU",
            "uberon_id_anatomical_site": "UBERON:0001017",
            "age_at_event_days": 5657,
            "dbgap_consent_code": "SD_BHJXBDQK.c1",
            "external_sample_id": "7316-2237-T-431398.WGS",
            "composition": "Solid Tissue",
            "external_aliquot_id": "732160"
          }```

**Comment by hlminh2000** [comment]
@joneubank looks like the problem is coming from the `files.sequencing_experiments.experiment_strategy` not being typed properly in the `participant_centric` index's mapping

**Comment by rosibaj** [comment]
ETl should be deployed nad run today; fix can be verified on production after that!
