### ISSUE TITLE
Add `Method of Sample Procurement` to biospecimen report download

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#934]
We need to update the columns that are exported in the Biospecimen Report download.  What would be awesome is if this worked on a * system, so that if new fields get added the report updates automatically!

All fields on the biospecimen entity should be exported.  Currently these fields are included:
```
Kf Id	 
External Sample Id	 
External Aliquot Id	 
Age At Event Days	 
Composition	 
Analyte Type	 
Concentration Mg Per Ml	 
Shipment Date	 
Shipment Origin	
```

**These fields need to be added:**
```
Tumor Descriptor
Method of Sample Procurement
Consent Type
dbGap Consent Code
ncit_id_anatomical_site
ncit_id_tissue_type
Sequencing_center_id
Shipment_date
Shipment_origin
Source_text_anatomical_site
Source_text_tissue_type
source_text_tumor_descriptor
spatial_descriptor
uberon_id_anatomical_site
Volume ul
```

**NOTE: this should use the Display name from Arranger from the field

**Comment by baileyckelly** [comment]
Per conversations tonight with @allisonheath - We're thinking we should just add all biospecimen fields to the download.

**Comment by rosibaj** [comment]
thanks for confirming @baileyckelly

**Comment by jecos** [comment]
Issue moved to [kids-first/kf-api-portal-reports #14](https://github.com/kids-first/kf-api-portal-reports/issues/14) via [**ZenHub**](https://www.zenhub.com/)
