### ISSUE TITLE
Implement File Entity page

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#960]
File Entity page, user has access to file
Zeplin: https://zpl.io/a7JgR8R

File Entity page, user does not have access to this file - they see this message instead of the download button:
Zeplin: https://zpl.io/brlAnBX
![screen shot 2018-11-22 at 2 39 27 pm](https://user-images.githubusercontent.com/18424138/48920027-6e54ed80-ee64-11e8-86ec-b9572e291592.png)

Link:      Consent Code Glossary » the idea was to link to a help doc or pdf for the user to download a list of the consent codes and their explanations.
@rosibaj should we ask AOC if they have that?

With "Analyze file in Cavatica" button

**Comment by ciaranschutte** [comment]
Just to keep a note there, I'm working on the table sections
