### ISSUE TITLE
Participant Entity page: Summary

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#961]
As a user, I want to be able to view the summary of a participant with the most important data.

## Acceptance criteria
- A page whose URL contain the participant ID should show the participant's info.
- The different sections should provide the info specified in the wireframe.
- Clicking on a number of files should lead to the file repository, with the appropriate filter applied.
- Clicking on the study name can lead to the generic studies page.
- For each specimen, a tab changes the values in the "Specimen" table.
- Make the columns sortable.

## List of sections
- Summary
- Specimen
- Available Data

## Wireframe
![image](https://user-images.githubusercontent.com/293677/59121442-11afb080-8926-11e9-9fe6-2efdc349c3e3.png)

## Technical details
- See the (up to date) Balsamiq wireframe: https://drive.google.com/drive/folders/1leQDF5dQi3Zv41FNkasbX0Tc9Wcwyvh-
- Zeplin - (deprecated) That is for some CSS to be copy-pasted. Note that the design specs has changed since this Zeplin has been made. Participant Summary Tab: https://zpl.io/2vNjqxJ
- Link for the generic studies page: https://kidsfirstdrc.org/support/studies-and-access/

**Comment by aalex** [comment]
See ICGC for a comparison: https://dcc.icgc.org/donors/DO232224/specimen

**Comment by aalex** [comment]
The number of files per biospecimen won't be implemented yet, since the ES query to retrieve those info seem to be a bit complicated, or perhaps impossible. We will move that to another backlog item.

**Comment by aalex** [comment]
In QA: we will need to check that the "File Properties" table still looks ok, since it has been modified in the commit that is in a PR now.

**Comment by aalex** [comment]
(QA) Great job! There will probably be a few cosmetic changes to make, but we can wait until the participant page feature is complete, and merge this one, meanwhile, as it it not easily publicly available, yet. LGTM
