### ISSUE TITLE
Entity Page Template

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#993]
- [x] Routing
- [x] Header
- [x] Tabs
- [x] API Integration

**Comment by joneubank** [comment]
Links to all the Zeplin template pages for easy reference:
File: https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5bf703950fae8e7eadc08fd0
Participant / Summary: https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5bf7073a74e6157e7828f47f
Participant / Clinical: https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5bf70c41d0bcdb4d8f9caeae
Participant / Family: https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5bf7123f4390473eaa6c3453
